### ISSUE TITLE
hello,how to set WebSocket.binaryType?

### ISSUE THREAD

**Issue by zhengweiyang** [TooTallNate/Java-WebSocket#1002]

**Comment by zhengweiyang** [comment]
WebSocket.binaryType

**Comment by PhilipRoman** [comment]
You should add more information. Currently your question is unclear.

`binaryType` is specific to client side JavaScript websockets. There is no need to set it when using this library. All binary messages will be received as ByteBuffers.

**Comment by zhengweiyang** [comment]
The server only supports connection by binary.I don't know how to connect. It is fail to connect when using this library.

**Comment by PhilipRoman** [comment]
Please post your code or give us a link to your project.

**Comment by PhilipRoman** [comment]
No response - closing issue!
