### ISSUE TITLE
How to specify Sec-WebSocket-Protocol

### ISSUE THREAD

**Issue by man-csl** [TooTallNate/Java-WebSocket#1004]
**Describe what you would like to know or do**
I am trying to connect a OCPP compliant client to a basic websocket server created with this library. The server is a copy paste of the example provided.

**Describe the solution you'd considered**
I expect the client to get connected properly, but instead I get the error: HTTP/1.1 404 WebSocket Upgrade Failure.

**Additional context**
After some debugging I found out that the issue is here:
private HandshakeState containsRequestedProtocol(String requestedProtocol)
This returns HandshakeState.NOT_MATCHED because requestedProtocol is set to 'ocpp1.6' because the client is OCPP 1.6 compliant client. OCPP specification states that ocpp1.6 is registered with IANA.

After looking through the code I can see that when creating a server we can pass in a list of drafts which may include 'ocpp1.6' as a acceptable Sec-WebSocket-Protocol. However it is not very clear how this can be done. Appreciate some info in this regard.

**Comment by marci4** [comment]
Hello @man-csl,

check out this example https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SecWebSocketProtocolClientExample.java

Best regards,
Marcel

**Comment by pezi** [comment]
Hi!
Same problem like my issue:
https://github.com/TooTallNate/Java-WebSocket/issues/1003

My solution with seperations of the the protocols - combination is also possible

```java
private static ArrayList<Draft> occp15Draft = new ArrayList<Draft>();
private static ArrayList<Draft> occp16Draft = new ArrayList<Draft>();
...
ArrayList<IProtocol> protocols = new ArrayList<IProtocol>();
protocols.add(new Protocol("ocpp1.5"));
occp15Draft.add(new Draft_6455(Collections.<IExtension>emptyList(), protocols));
protocols = new ArrayList<IProtocol>();
protocols.add(new Protocol("ocpp1.6"));
occp16Draft.add(new Draft_6455(Collections.<IExtension>emptyList(), protocols));
```
Use following constructor for including drafts

```java
public WebSocketServer( InetSocketAddress address , List<Draft> drafts ) 
```

If you use google gson, you need perhaps additional code for the XMLGregorianCalendar.class
I use the SOAP OCPP WSDL class files, generated by wsimport, also for JSON - perhaps, if you use the JSON schema files, this trick is not necessary  

```java
GsonBuilder gson_builder = new GsonBuilder();
gson_builder.registerTypeAdapter(XMLGregorianCalendar.class, new XMLGregorianCalendarConverter.Serializer());
gson_builder.registerTypeAdapter(XMLGregorianCalendar.class, new XMLGregorianCalendarConverter.Deserializer());
gson = gson_builder.create();
```

```java
public class XMLGregorianCalendarConverter {
    public static class Serializer implements JsonSerializer {
        public Serializer() {
            super();
        }
        public JsonElement serialize(Object t, Type type,
                JsonSerializationContext jsonSerializationContext) {
            XMLGregorianCalendar xgcal = (XMLGregorianCalendar) t;
            return new JsonPrimitive(xgcal.toXMLFormat());
        }
    }
    public static class Deserializer implements JsonDeserializer {
        public Object deserialize(JsonElement jsonElement, Type type,
                JsonDeserializationContext jsonDeserializationContext) {
            try {
                return DatatypeFactory.newInstance().newXMLGregorianCalendar(
                        jsonElement.getAsString());
            } catch (Exception e) {
                return null;
            }
        }
    }
}
```

**Comment by pezi** [comment]
Perhaps it would be a good idea to add the most important sub-protocols from the IANA to the code
https://www.iana.org/assignments/websocket/websocket.xml

**Comment by marci4** [comment]
> 
> 
> Perhaps it would be a good idea to add the most important sub-protocols from the IANA to the code
> [iana.org/assignments/websocket/websocket.xml](https://www.iana.org/assignments/websocket/websocket.xml)

I would like to improve the documentation and not simple include some incomplete list.

Best regards,
Marcel

**Comment by man-csl** [comment]
In my case also, giving the list of extensions worked properly. I missed the example @marci4 mentioned because I was only looking for server examples. It would have been useful if this can at-least be mentioned in the main documentation.
