### ISSUE TITLE
It is currently not possible to accept ws and wss connections at the same time via the same websocket server instance.

### ISSUE THREAD

**Issue by jaimegarzon** [TooTallNate/Java-WebSocket#1007]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to accept ws and wss connections at the same time via the same websocket server instance.

**Describe the solution you'd like**
Being able to receive ws and wss connections at the same time

**Describe alternatives you've considered**
I have tried to modify the WebSocketServerFactory but I could not get the solution

**Additional context**
Please help me fix this. when i use WSS with DefaultSSLWebSocketServerFactory work fine, but when i use WS throw "Connection closed because ofjavax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?"

**Comment by marci4** [comment]
Hello @jaimegarzon,
this is currently not supported, and we have no plans to implement a workaround to get this to work.

If you really wanna WS, please use a separate port. I would recommend to only use WSS whenever it is possible.

Best regards,
Marcel
