### ISSUE TITLE
Missing carriage return character (\r) in error message.

### ISSUE THREAD

**Issue by pawankgupta-se** [TooTallNate/Java-WebSocket#1017]
Hi,
I noticed that there in error message Content-Type content you have missed  **\r** at one place. Which is causing issue on some platform/library (used by client). Class `WebSocketImpl`

```
private ByteBuffer generateHttpResponseDueToError( int errorCode ) {
		String errorCodeDescription;
		switch(errorCode) {
			case 404:
				errorCodeDescription = "404 WebSocket Upgrade Failure";
				break;
			case 500:
			default:
				errorCodeDescription = "500 Internal Server Error";
		}
		return ByteBuffer.wrap( Charsetfunctions.asciiBytes( "HTTP/1.1 " + errorCodeDescription + "\r\nContent-Type: text/html\nServer: TooTallNate Java-WebSocket\r\nContent-Length: " + ( 48 + errorCodeDescription.length() ) + "\r\n\r\n<html><head></head><body><h1>" + errorCodeDescription + "</h1></body></html>" ) );
	}
```

**Comment by marci4** [comment]
Hey,

just out of curiosity, which lib has a problem with that?

Any PR is welcome!

Best regards,
Marcel

**Comment by pawankgupta-se** [comment]
Hey, 
We are using "websocket-sharp" https://github.com/sta/websocket-sharp for windows client.

Also I was trying to push the change for PR but its failing due to lack of permission. Please do the needful will be glad to contribute.

Thanks
Pawan
