### ISSUE TITLE
cant not recevie message size more than 21M

### ISSUE THREAD

**Issue by fanyong920** [TooTallNate/Java-WebSocket#1020]
my project
[https://github.com/fanyong920/jvppeteer](url)
run test package:
PagesTracingExample
it will stop receive massega. stop in class 
com.ruiyun.jvppeteer.util.Helper#readProtocolStream
line 180

**Comment by marci4** [comment]
Hello @fanyong920,

please use the bug report template https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md

Cannot reproduce the issue.

Best regards,
Marcel

**Comment by marci4** [comment]
As for now it looks like you block the reading thread!

Closing this issue.

Best regards,
Marcel

**Comment by fanyong920** [comment]
thanks.I understand l
