### ISSUE TITLE
The byte array obtained from the wav file cannot be sent.无法发送wav文件获取到的字节数组。

### ISSUE THREAD

**Issue by mudcastles** [TooTallNate/Java-WebSocket#1023]
中文：
我将本地的wav文件用FileInputStream读取到byte array中，然后使用WebSocket发送数据，测试过程中发现一旦调用send方法就会断开连接，服务端也无法收到数据。测试发送txt文件没有问题。

以下是我的代码：

```kotlin
val file = File(Environment.getExternalStorageDirectory().path, "ceshitest.txt")
val input = FileInputStream(file)
val byteArray = ByteArray(input.available())
input.read(byteArray)
webSocketClient.sendData(byteArray)
```

```
fun sendData(bytes: ByteArray) {
    if (webSocketClient != null && webSocketClient!!.isOpen) {
        webSocketClient!!.send(bytes)
    }
}
```

English:
I read the local wav file into the byte array using FileInputStream, and then use WebSocket to send data. During the test, I found that once the send method is called, the connection will be disconnected, and the server cannot receive the data. There is no problem in sending txt files.

The following is my code:

```kotlin
val file = File(Environment.getExternalStorageDirectory().path, "ceshitest.txt")
val input = FileInputStream(file)
val byteArray = ByteArray(input.available())
input.read(byteArray)
webSocketClient.sendData(byteArray)
```
```
fun sendData(bytes: ByteArray) {
    if (webSocketClient != null && webSocketClient!!.isOpen) {
        webSocketClient!!.send(bytes)
    }
}
```

**Comment by marci4** [comment]
Please check for the correct project.
We do not have an API called `sendData`

**Comment by mudcastles** [comment]
> Please check for the correct project.
> We do not have an API called `sendData`

I encapsulated the api, the sendData method actually called the send method.

**Comment by marci4** [comment]
Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
Marcel

**Comment by mudcastles** [comment]
> Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!
> 
> Without a full bug report this will be closed.
> 
> Best regards,
> Marcel

After testing, the byte array will appear when it is large, but not when it is small. Is there a length limit for WebSocket? How to modify this limit?

**Comment by PhilipRoman** [comment]
I've done some tests and all versions of this library can definitely process messages of at least 256 megabytes.

**Comment by marci4** [comment]
Closing this issue as no additional infos were provided.
Best regards,
Marcel
