### ISSUE TITLE
Crash on Android due to missing method `setEndpointIdentificationAlgorithm` on 1.5.1

### ISSUE THREAD

**Issue by wuyinlei** [TooTallNate/Java-WebSocket#1024]
Websocket library 1.5.1
The same code was not crashing on 1.4.1

java.lang.NoSuchMethodError

No virtual method setEndpointIdentificationAlgorithm(Ljava/lang/String;)V in class Ljavax/net/ssl/SSLParameters; or its super classes (declaration of 'javax.net.ssl.SSLParameters' appears in /system/framework/core-libart.jar)

OPPO A59M  Android5.1
Huawei DIG TL10 Android6.0

**Comment by marci4** [comment]
Hello @wuyinlei,
check out https://github.com/TooTallNate/Java-WebSocket/wiki/No-such-method-error-setEndpointIdentificationAlgorithm

Best regards,
Marcel

**Comment by wuyinlei** [comment]
thank you
