### ISSUE TITLE
Force client to use the valid schema

### ISSUE THREAD

**Issue by yindex** [TooTallNate/Java-WebSocket#1026]
**Is your feature request related to a problem? Please describe.**

Yes.

When I use the invalid schema(https, http) with explicit port in uri
```
//dev config, host=domain:port

String url = String.format("http://%s/%s", host, "websocket");

ws = new WebSocketClient(new URI(url)) 
```

MayBe, I can't find the potential the problem, because it can run without exception.

But, it will failed when we omit the port in uri. and It will throw an exception:"unkown schema http"

```
// prod config, host=domain

String url = String.format("http://%s/%s", host, "websocket");

ws = new WebSocketClient(new URI(url)) `

```
 
I'm alway frustrated when run failed only with different config in prod environment.

I think we should allow user to find the potential problem during development. 

**Describe the solution you'd like**

always check the schema and throw exception on invalid schema,  regardless whether the port is explicit set(no matter uri.getPort() == -1).

**Comment by marci4** [comment]
@yindex thx for creating the issue.
