### ISSUE TITLE
NO_CERTIFICATE_SET after using SSL self signed certificate

### ISSUE THREAD

**Issue by joaomgcd** [TooTallNate/Java-WebSocket#1027]
**Describe what you would like to know or do**
I would like to use my own SSL self signed certificate on an Android WebSocket server

**Describe the solution you'd considered**
I have created a self signed certificate and then did this:
`val sslContext = SelfSignedCertificate(context, "192.168.87.35").sslContext

val factory = DefaultSSLWebSocketServerFactory(sslContext)

setWebSocketFactory(factory)`

**Additional context**
When I create a WebSocket via JavaScript:
`new WebSocket("wss://192.168.87.35:9879")`
on the server I always get an exception in this line of [WebSocketServer.java ](https://github.com/TooTallNate/Java-WebSocket/blob/433935a7b07896176fe03c2dc4db6f0b19bddcc3/src/main/java/org/java_websocket/server/WebSocketServer.java#L456) with the following message:

> javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7b75703848: Failure in SSL library, usually a protocol error
error:100000ae:SSL routines:OPENSSL_internal:NO_CERTIFICATE_SET (external/boringssl/src/ssl/tls13_server.cc:689 0x7b6b16ce6b:0x00000000)

Am I doing something wrong? Seems like the connection is not trying to use the certificate I set in the sslContext?

Thanks in advance for any help!

**Comment by PhilipRoman** [comment]
What version of Java-WebSocket are you using?

**Comment by joaomgcd** [comment]
Hi. Thanks for responding and sorry for not including that right away.
I'm using version 1.5.1. Please let me know if there's any more info I need to add. Thank you.

**Comment by marci4** [comment]
Please provide a full example project with exact steps to repeat!

Best regards,
Marcel

**Comment by joaomgcd** [comment]
Ok, here you go.

[HttpsSocketServer.zip](https://github.com/TooTallNate/Java-WebSocket/files/4752558/HttpsSocketServer.zip)

To reproduce:

- Build the app and install on your Android device
- Keep the app open
- Add a break point on the line [mentioned above](https://github.com/TooTallNate/Java-WebSocket/blob/433935a7b07896176fe03c2dc4db6f0b19bddcc3/src/main/java/org/java_websocket/server/WebSocketServer.java#L456)
- In a web browser on the same network use a command like `new WebSocket("wss://192.168.87.35:32456")` (changing it to your local IP address)
- Check that Android Studio stopped at the line with the mentioned exception

Hope this helps!

**Comment by marci4** [comment]
Hello @joaomgcd,
I am not sure your SelfSignedCertificate.kt does not provide a valid certificate with private key.
To be honest, I am not into kotlin and I have no clue what you are trying to do there.
Take a look at how to generate a bks file for android and then load it in your android app.

Best regards,
Marcel

**Comment by marci4** [comment]
@joaomgcd I updated an example application https://github.com/marci4/AndroidJavaWebsocketExample to 1.5.1

Maybe this helps you spot the issue.

Best regards,
Marcel

**Comment by marci4** [comment]
@joaomgcd is this issue solved for you?

**Comment by marci4** [comment]
Closing this issue as it should be solved
