### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by valeciawolf34** [TooTallNate/Java-WebSocket#1029]
**Describe the bug**

**To Reproduce**
1. .
2. ..
3. ...
4. ....

**Example application to reproduce the issue**
A link to a github project/gist to reproduce the issue.

**Expected behavior**

**Debug log**
The the debug log (set the log level to `TRACE`) to help explain your problem.

**Environment(please complete the following information):**
 - Version used:
 - Java version:
 - Operating System and version:
 - Endpoint Name and version:
 - Link to your project:

**Additional context**

**Comment by PhilipRoman** [comment]
Please add more information about your problem.
