### ISSUE TITLE
1.5.1-AndroidRuntime: FATAL EXCEPTION:

### ISSUE THREAD

**Issue by sangsais** [TooTallNate/Java-WebSocket#1030]
**Debug log**
T05-25 19:37:05.344 13908-14303/? E/AndroidRuntime: FATAL EXCEPTION: WebSocketConnectReadThread-1134
    Process: cn.sharesmile.lian, PID: 13908
    java.lang.NoSuchMethodError: No virtual method setEndpointIdentificationAlgorithm(Ljava/lang/String;)V in class Ljavax/net/ssl/SSLParameters; or its super classes (declaration of 'javax.net.ssl.SSLParameters' appears in /system/framework/core-libart.jar)
        at org.java_websocket.client.WebSocketClient.onSetSSLParameters(WebSocketClient.java:528)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:475)
        at java.lang.Thread.run(Thread.java:818)

**Environment(please complete the following information):**
 - Version used: 1.5.1
 - Java version: JavaVersion.VERSION_1_8
 - Operating System and version: android 6.0
 - Endpoint Name and version: xiaomi Redmi Note 4

**Additional context**
When I use the old version 1.3.4 there is no problem

**Comment by marci4** [comment]
Please check out https://github.com/TooTallNate/Java-WebSocket/wiki/No-such-method-error-setEndpointIdentificationAlgorithm

Best regards,
Marcel
