### ISSUE TITLE
want to capture the web-socket data using selenium webdriver 

### ISSUE THREAD

**Issue by mahendra1999** [TooTallNate/Java-WebSocket#1031]
i Have an requirement to test the websocket date with UI. We have an URL of Web socket and connected message ie.,  ["{\"msg\":\"connect\",\"version\":\"1\",\"support\":[\"1\",\"pre2\",\"pre1\"]}"] after that we have client id message to get the data ie., ["{\"msg\":\"method\",\"method\":\"marketingTargetSegmentationTechnologyCountByServiceTier\",\"params\":[{\"clientId\":\"ZTDCFxpo9sRQd5hhg\",\"orgId\":\"12837743\",\"region\":null,\"location\":null,\"period\":\"last-28d\"}],\"id\":\"26\"}"]  
Based on this how to write java web socket connection to get the data

**Comment by marci4** [comment]
We do not provide application support.

Best regards,
Marcel
