### ISSUE TITLE
Are WebSocketClient methods (onMessage etc.) concurrent?

### ISSUE THREAD

**Issue by piorrro33** [TooTallNate/Java-WebSocket#1032]
I'd like to know if the WSClient methods are concurrent. Concretely, can onMessage be run twice in two different threads, or is there only one thread listening for messages/callbacks?

I have a LinkedList used as a Queue implementation in my client and I fear that there may be concurrent calls to it.

**Comment by marci4** [comment]
Hey,

No there cannot be two messages at the same time.
OnMessage is waiting for the response.

Best regards,
Marcel
