### ISSUE TITLE
WebSocket closed!code=1002,reason:Unknown opcode 12,remote:false

### ISSUE THREAD

**Issue by Wheats** [TooTallNate/Java-WebSocket#1035]
server : nettry websocket

WebSocket closed!code=1002,reason:Unknown opcode 12,remote:false;

**Comment by marci4** [comment]
Hello @Wheats

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4

**Comment by marci4** [comment]
Closing this question as no additional info was provided!

Best regards,
Marcel
