### ISSUE TITLE
Clients disconnecting even with setConnectionLostTimeout set to 0

### ISSUE THREAD

**Issue by harispdev** [TooTallNate/Java-WebSocket#1036]
Even though I've set **setConnectionLostTimeout** to 0 on both client and server side (before calling .connect() and .start() methods respectively), my Android clients keep disconnecting at random intervals ranging from 3-6 minutes when left idle. 
WiFi is enabled during the sleep on all devices.

Any thoughts?

**Comment by PhilipRoman** [comment]
What are the arguments to `onClose()`? Specifically, what is the close code and reason, and is the closing caused by server or client side?

**Comment by harispdev** [comment]
Server closes the connection. Code: 1006 Reason: Connection reset

**Comment by marci4** [comment]
Hello,
Could you please provide a small example application and some steps to repeat?

Thx a lot 
Best regards
Marcel

**Comment by harispdev** [comment]
Hello,
I'm using exact copy of 
https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/ExampleClient.java (on Android)
and
https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/ChatServer.java (On Java backend running on Wildfly)

Steps to reproduce:
1. Run the server
2. Run the android app
3. Server logs an active connection
4. Let phone go to sleep and wait for 3-6 minutes
5. Server disconnects the client with error code 1006 and reason Connection reset

Thanks for the help.

**Comment by marci4** [comment]
Both servers have setConnectionLostTimeout set to 0?

Could be that android is optimizing the application and therefore freezing the application?

**Comment by harispdev** [comment]
Yes, both client and the server have setConnectionLostTimeout set to 0. 
Shouldn't be the case, it's implemented as a service, and if you try to ping clients under 3 minutes it wakes the phone and delivers the message.

**Comment by marci4** [comment]
Could you please provide an android studio project?

Thx a lot

**Comment by harispdev** [comment]
Of course, here you go:
https://pastebin.com/jKu2XyWy

Thank you for your time.

**Comment by marci4** [comment]
Please provide a full project..

**Comment by harispdev** [comment]
[WebSocketsTest.zip](https://github.com/TooTallNate/Java-WebSocket/files/4732103/WebSocketsTest.zip)

**Comment by harispdev** [comment]
Found the issue, by default Android chooses to optimize battery life by freezing low priority apps while they run in the background no matter what you specify in manifest. To fix this in the Settings -> Apps -> Configure apps -> Special access -> Battery optimization your app needs to be set to 'No optimization'
