### ISSUE TITLE
Is there a way to implement synchronous messages?

### ISSUE THREAD

**Issue by gharia** [TooTallNate/Java-WebSocket#1037]
**Describe what you would like to know or do**
I am looking for a way to wait for the response for a particular set of synchronous messages. Like wait for the response or pass a consumer function which can be invoked on the response of a message sent. Is it supported out of the box?

**Update:**
I have been trying to create a Java WS client for Janus gateway, which has a WS server and some of the requests are synchronous https://janus.conf.meetecho.com/docs/audiobridge#bridgeapi, for e.g  `create` (create a session) is synchronous.
Following is my client 

```
public class JanusClient extends WebSocketClient {

--------
--------
@Override
	public void onMessage(String message) {
		// TODO Auto-generated method stub

	}
	
	public SessionResponse createSession() {
		JsonObject createSessionReq = new JsonObject();
		createSessionReq.addProperty("transaction", Generators.timeBasedGenerator().generate().toString());
		createSessionReq.addProperty("janus","create");
		String respose = this.send(createSessionReq.toString());
		// At this point I am looking for an opion to wait for response from Janus server and than return the recived SessionResponse  to caller
	}

}
```

So for the synchronous requests only, I would like to wait for a response and not for asynchronous.

**Describe the solution you'd considered**
A clear and concise description of any solutions you've considered.

**Additional context**
Add any other context or links about the question here.

**Comment by PhilipRoman** [comment]
Hello!
Please explain your problem in more detail, a code example of what you're looking for would help.
If I understood correctly, you're looking for something like this:
```java
socket.send("...");
var response = socket.awaitNextMessage();
```
If that's the case; you will need to use a [blocking queue](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ArrayBlockingQueue.html). In the server/client subclass you should put all incoming messages into the queue and, in another thread, use `var x = queue.take()` to wait for the next response.

If you're writing a server and need to support a large amount of clients, there is a more efficient, but harder to write way to do this.

Again, you should add more details about what you need.

**Comment by gharia** [comment]
Apology for being unclear. Updated the details. I am looking for something similar to what you said. The only difference is, the Janus server does not ave each and every request synchronous. It has few asynchronous ones and for them, I don't see a point to wait for a response.

**Comment by PhilipRoman** [comment]
Here is a quick example of how this can be achieved.
```java
import java.util.concurrent.*;

import java.net.*;

import org.java_websocket.server.*;
import org.java_websocket.client.*;
import org.java_websocket.*;
import org.java_websocket.handshake.*;

public class Main extends WebSocketServer {
	public static void main(String[] args) throws Throwable {
		Main main = new Main();
		main.start();
		Thread.sleep(100); // just to make sure that server has started
		Client client = new Client(URI.create("ws://localhost:"+main.getPort()));
		new Thread(client).start();
		Thread.sleep(1000);
		client.runExample();
	}

	public void onError(WebSocket socket, Exception e) {
		e.printStackTrace();
	}

	public void onMessage(WebSocket socket, String msg) {
		socket.send("result: 4");
	}

	public void onClose(WebSocket socket, int code, String msg, boolean remote) {}

	public void onOpen(WebSocket socket, ClientHandshake handshake) {}

	public void onStart() {}
}

class Client extends WebSocketClient {
	volatile CompletableFuture<String> awaitedResponse;
	volatile String expectedType;

	public Client(URI uri) {
		super(uri);
	}

	public void onOpen(ServerHandshake handshake) {
	}

	public void onError(Exception e) {
		e.printStackTrace();
	}

	public void onClose(int code, String msg, boolean remote) {
	}

	public void onMessage(String msg) {
		// check if the message is of expected type, and not some async message that got inbetween
		if(awaitedResponse != null && msg.startsWith(expectedType)) {
			awaitedResponse.complete(msg);
			awaitedResponse = null;
			expectedType = null;
		} else {
			// handle asynchronous message
			System.out.println("Async message " + msg);
		}
	}

	/* The reason why query is sent from this method is that in theory,
	 * the response could arrive before we've set up the handle
	 * (in practice, that only happens on localhost) */
	String awaitResponse(String query, String type) throws InterruptedException {
		awaitedResponse = new CompletableFuture<>();
		expectedType = type;
		send(query);
		try {
			return awaitedResponse.get();
		} catch(ExecutionException e) {
			throw new RuntimeException(e.getCause());
		}
	}

	public void runExample() throws InterruptedException {
		String response1 = awaitResponse("What is 2+2?", "result");
		System.out.println("Got response: '" + response1 + "'");

		String response2 = awaitResponse("What is 1+3?", "result");
		System.out.println("Got response: '" + response2 + "'");
	}
}
```

**Comment by PhilipRoman** [comment]
If your issue has been solved, feel free to close it.

**Comment by gharia** [comment]
Thanks @PhilipRoman for the help. Sorry I was off to another stuff.  Your solution of waiting for the response looks good and yeah blocking queue should also work fine. However, I am trying another approach of using `java.util.function.Consumer` function.Basically maintain the HashMap of each request's consumer for which response is awaited. And accept when I receive a response. 

```
public class JanusClient extends WebSocketClient {
        private Map<String, Consumer<?>> awaitResponse = new HashMap();
--------
--------
       @Override
	public void onMessage(String message) {
		// Extract transaction, which is the unique id we sent along with the request
                // Check if awaitResponse contains the consumer for this response
               // if yes, then extract and accept it

	}
	
	public SessionResponse createSession(Consumer<String> onResponse) {
                String transaction = Generators.timeBasedGenerator().generate().toString();
                awaitResponse.put(transaction, onResponse);
		JsonObject createSessionReq = new JsonObject();            
		createSessionReq.addProperty("transaction", transaction);
		createSessionReq.addProperty("janus","create");
		this.send(createSessionReq.toString());
	}

}
```

Closing this ticket. Thanks.
