### ISSUE TITLE
TLSv1.2 protocol doesn't support on devices running Android API level bellow 20.

### ISSUE THREAD

**Issue by pawankgupta-se** [TooTallNate/Java-WebSocket#1039]
I am using this library as WebSocketServer. I my app using TLSv1.2 and its working fine on devices running on Android API level 20+. But when I tried testing on device running on API level 17 I got issue stating `UNSUPPORTED_PROTOCOL`. I went through document and found that I can use custom protocol and cipher if I use `CustomSSLWebSocketServerFactory` but then I got different error 
```
06-16 04:39:08.605 9634-9751/com.crestron.airmedia.receiver.m360 E/WebSocketReceiver: <0063>  Protocol TLSv1.2 is not supported.
06-16 04:39:08.605 9634-9751/com.crestron.airmedia.receiver.m360 E/k.b.v.e: [WebSocketSelector-99] e::handleFatal Interrupt during stopjava.lang.IllegalArgumentException: Protocol TLSv1.2 is not supported.
        at org.apache.harmony.xnet.provider.jsse.SSLParametersImpl.setEnabledProtocols(SSLParametersImpl.java:266)
        at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.setEnabledProtocols(SSLEngineImpl.java:251)
        at k.b.v.a.a()
        at k.b.v.e.doAccept()
        at k.b.v.e.run()
        at java.lang.Thread.run(Thread.java:856)
```

**To Reproduce**

Trying using `CustomSSLWebSocketServerFactory`
with protocols 
`{"TLSv1.2"}`

on devices running on API level 17

**Comment by PhilipRoman** [comment]
I don't think this issue is related to this library. The Android documentation says that TLSv1.2 is supported in level 17, but not enabled by default, so I have no idea why it's not working.

**Comment by pawankgupta-se** [comment]
@PhilipRoman Because if you look at SSLEngine documentation it says SSLv1.2 is supported from API level 20. https://developer.android.com/reference/javax/net/ssl/SSLEngine.

**Comment by PhilipRoman** [comment]
You're right. Well, I don't think there is any way to fix it, unless you use a custom SSL library, like BouncyCastle.

**Comment by pawankgupta-se** [comment]
@PhilipRoman Well I was looking at this library BouncyCastle but I think I need to modify your WebSocket Library code to use it. If you can give any insight how I can both library can work together or if you have any example code it will be great help. Also I was thinking about using SSLSocket instead of SSLEngine for api level below 20 (Is that make sense) because SSLSocket supports TLSv1.2 bellow 20+

**Comment by PhilipRoman** [comment]
Check out this answer on stackoverflow: https://stackoverflow.com/a/33495988/5318121. It seems to provide a simple way to migrate to bouncycastle.

**Comment by pawankgupta-se** [comment]
Thanks a lot I will go through it.

**Comment by pawankgupta-se** [comment]
Resolved issue using [Conscrypt](https://github.com/google/conscrypt).
