### ISSUE TITLE
InvalidDataException: Continuous frame sequence not completed

### ISSUE THREAD

**Issue by Mohammed2Hussein** [TooTallNate/Java-WebSocket#1044]
D/WebSocketConnection: onError() -> org.java_websocket.exceptions.InvalidDataException: Continuous frame sequence not completed.
D/WebSocketConnection: onClose() -> Reason: Continuous frame sequence not completed. - Code: 1002

I got this error when try to connect with server at first time, when do reconnect this error not happened again.
Sometimes this error not happened after try to connect several times.

**Comment by marci4** [comment]
Hello,
Please provide a full example and some steps to repeat for both the server and the client.

Best regards,
Marcle

**Comment by Mohammed2Hussein** [comment]
Client:
fun startWebSocketConnection(username: String?, password: String?) {
        // HTTP header using credentials
        val credentials: String = username + ':' + password
        val encoded = String(Base64.encode(credentials.toByteArray(), Base64.NO_WRAP))
        val httpHeaders: HashMap<String, String> = HashMap()
        httpHeaders.put("Authorization", "Basic " + encoded)
        // Start WebSocket
        webSocket = WebSocketConnection(
                URI("wss://<IP>:<Port>"),
                httpHeaders
        )
        // Set WebSocket Protocol
        var sslContext: SSLContext = NaiveSSLContext.getInstance("TLS")
        val factory = sslContext.socketFactory
        webSocket?.setConnectionLostTimeout(0)
        webSocket!!.setSocketFactory(factory)
        webSocket!!.connect()
    }
------------------
Server:
another lib written with C#

**Comment by marci4** [comment]
Please provide a full example project for both client and server

**Comment by marci4** [comment]
Closing this issue as no example application was provided.

Best regards,
Marcel
