### ISSUE TITLE
A question with AutobahnClientTest .

### ISSUE THREAD

**Issue by dota17** [TooTallNate/Java-WebSocket#1045]
**Describe what you would like to know or do**
The result of autobahnClient was not expected.

Run the org.java_websocket.example.AutobahnClientTest and the org.java_websocket.example.AutobahnServerTest .

Enter the command in the client side:
**r 1 5**
we can get the message:
>//////////////////////Exec: case=1&agent=tootallnate/websocket

But from `Type 'r <first casenumber> <last casenumber>' to run a testcase. Example: r 1 295`, **i think there will be some more cases to run, but it didn't.**

For example, if we enter the command `r 1  5`, the expect result maybe:
>//////////////////////Exec: case=1&agent=tootallnate/websocket
>//////////////////////Exec: case=2&agent=tootallnate/websocket
>//////////////////////Exec: case=3&agent=tootallnate/websocket
>//////////////////////Exec: case=4&agent=tootallnate/websocket
>//////////////////////Exec: case=5&agent=tootallnate/websocket
>

On the another hand, if we type `ex`, the program will exit.
But after the first command is entered, it doesn't work with any following commands or the first task keeps a long time and is not finished anymore.
![autobahnclient_20200706150815](https://user-images.githubusercontent.com/50514813/86565558-9db56100-bf9a-11ea-9b58-6eccb0182d20.png)

**Comment by PhilipRoman** [comment]
Please clarify your issue

**Comment by marci4** [comment]
Works for me with the current master.

**Comment by marci4** [comment]
@dota17  if this issue is solved for you, please close it

**Comment by dota17** [comment]
> @dota17 if this issue is solved for you, please close it

Excuse me, how's the repair going? 

I can't see any changes with pr or commit.

**Comment by marci4** [comment]
Nothing is broken? No steps to repeat were provided which showed unexpected behaviour....

**Comment by dota17** [comment]
![autobahnclient_20200706145618](https://user-images.githubusercontent.com/50514813/86564554-ff74cb80-bf98-11ea-8950-fd6cb7907320.png)

**Comment by marci4** [comment]
Is your Autobahntestsuite running???

**Comment by dota17** [comment]
> Is your Autobahntestsuite running???
> 
> Right port and configuration??

Is this https://github.com/TooTallNate/Java-WebSocket/wiki/Testing-using-the-Autobahn-Test-Suite ?
I'm sorry that I can't open the site of http://autobahn.ws/ .

**Comment by marci4** [comment]
https://github.com/crossbario/autobahn-testsuite should be the link

**Comment by dota17** [comment]
> https://github.com/crossbario/autobahn-testsuite should be the link

I had installed the autobahn-testsuite and run the server in the ubuntu as follow:
![autobahnserver_20200708171238](https://user-images.githubusercontent.com/50514813/86900865-77302b00-c13e-11ea-966d-588e6e097973.png)

And I had a new question with that how can I run the AutobahnClient in the ubuntu?
![autobahnclient_20200708171551](https://user-images.githubusercontent.com/50514813/86901104-b8c0d600-c13e-11ea-9d4f-495c5d7c4ca4.png)

**Comment by marci4** [comment]
Please check Google on how do compile java files and run them on Linux

**Comment by PhilipRoman** [comment]
@dota17 The error in your last screenshot happens because the class name is actually `org.java_websocket.example.Autobahn`. To run it, go to the `target` directory and run
```sh
java -cp 'test-classes:classes' org.java_websocket.example.AutobahnClientTest
```

**Comment by dota17** [comment]
@PhilipRoman 
It works. Thank you very much.

I would run and test to check whether the problems which I commented above are existed.

**Comment by dota17** [comment]
![autobahnclient_20200710113932](https://user-images.githubusercontent.com/50514813/87113991-128de100-c2a2-11ea-8df3-fa1225b12496.png)
It's OK now. I closed this.
