### ISSUE TITLE
Impossible to write in the console.

### ISSUE THREAD

**Issue by notaryzw3b** [TooTallNate/Java-WebSocket#1047]
**Describe the bug**
When I launch the server, i can't write in my command line.

**To Reproduce**
1 - Only launch server.

**Expected behavior**
I want to write in my command line bc its needed for properly stop my emulator.

**Environment(please complete the following information):**
 - Version used: 1.5.1
 - Java version: 1.8.0_251 (java 8)
 - Operating System and version: Windows 8.1
 - Link to your project: if its needed i can send in discord pm.

**Additional context**
The websocket is added in Arcturus Morningstar Emulator (Habbo Server).

**Comment by PhilipRoman** [comment]
I don't use Discord, so you should either post the link here or (if it's a private project) email it to me: dev.philipjohn@gmail.com and I can try to reproduce your issue.

**Comment by marci4** [comment]
Thx for taking a look at this. Ping me if you need any support!

**Comment by notaryzw3b** [comment]
> I don't use Discord, so you should either post the link here or (if it's a private project) email it to me: [dev.philipjohn@gmail.com](mailto:dev.philipjohn@gmail.com) and I can try to reproduce your issue.

I sent you the project :)

**Comment by PhilipRoman** [comment]
In `src/main/java/com/eu/habbo/websockets/WebsocketServer.java`, line 67, you call `server.run()`. This is a blocking method which returns only when the server is closed. It is likely that all your problems can be fixed simply by replacing `server.run()` with `server.start()`, which will run the server in a separate thread.
