### ISSUE TITLE
Is there anyway to identify a session?

### ISSUE THREAD

**Issue by pawankgupta-se** [TooTallNate/Java-WebSocket#1052]
**Describe what you would like to know or do**
Hi I have requirement to identify each client connected to the server.

**Describe the solution you'd considered**
I was doing it using WebSocket object (conn) ```	public abstract void onOpen( WebSocket conn, ClientHandshake handshake );``` I get here. I used to generate a `channelId` by concatenating `conn?.remoteSocketAddress?.hostName`  and  `conn?.localSocketAddress?.hostName` and used to identify the client using `channelId`. but I realised that when client disconnects `conn?.remoteSocketAddress` becomes `null`. so I cannot Identify which client exactly has been disconnected

**Additional context**
I need to identify client for the resource cleanup purpose after connection closes.

**Comment by PhilipRoman** [comment]
It sounds like you could use the setAttachment/getAttachment methods in WebSocket to identify each socket

See https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.1/org/java_websocket/WebSocket.html#getAttachment-- for more info

**Comment by pawankgupta-se** [comment]
@PhilipRoman Thanks for your quick response buddy. It worked for me, thanks.

**Comment by joedavid91** [comment]
For those like me who were wondering how attachments work, an example of how to set and get attachments can be found in the examples folder [here](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/ChatServerAttachmentExample.java)
