### ISSUE TITLE
How to debugg the client using Fiddler or sth else

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [TooTallNate/Java-WebSocket#1058]
**Describe what you would like to know or do**
I'd like to debug my websocket client using Fiddler

**Describe the solution you'd considered**
I've tried `proxy` like [this](https://github.com/TooTallNate/Java-WebSocket/blob/65300d44507e5a4ed942b92dd27873cb8b95c936/src/main/example/ProxyClientExample.java), but it reports cert error.
```
ExampleClient c = new ExampleClient(new URI("wss://a-site-to-test.com:12345"));
c.setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 8888)));
c.connect();
```

I googled that and copied a factory to trust all certs. The client works, but the https stream didn't goto Fiddler
```
ExampleClient c = new ExampleClient(new URI("wss://a-site-to-test.com:12345"));
c.setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 8888)));
c.setSocketFactory(TrustAllCertSSLUtil.getFactory());
c.connect();
```

**Additional context**
**TrustAllCertSSLUtil.java**
```
public class TrustAllCertSSLUtil implements TrustManager, X509TrustManager {

	private TrustAllCertSSLUtil() {
	}

	private static SSLSocketFactory sslFactory = null;

	public static SSLSocketFactory getFactory() throws Exception {
		if (sslFactory == null) {
			TrustManager[] trustAllCerts = new TrustManager[1];
			TrustManager tm = new TrustAllCertSSLUtil();
			trustAllCerts[0] = tm;
			SSLContext sc = SSLContext.getInstance("SSL");
			sc.init(null, trustAllCerts, null);
			sslFactory = sc.getSocketFactory();
		}
		return sslFactory;
	}

	public java.security.cert.X509Certificate[] getAcceptedIssuers() {
		return null;
	}

	public boolean isServerTrusted(java.security.cert.X509Certificate[] certs) {
		return true;
	}

	public boolean isClientTrusted(java.security.cert.X509Certificate[] certs) {
		return true;
	}

	public void checkServerTrusted(java.security.cert.X509Certificate[] certs, String authType)
			throws java.security.cert.CertificateException {
		return;
	}

	public void checkClientTrusted(java.security.cert.X509Certificate[] certs, String authType)
			throws java.security.cert.CertificateException {
		return;
	}
}
```

**Comment by dota17** [comment]
Can you change SSL to TLS ?
`SSLContext sc = SSLContext.getInstance("**SSL**");`

Follow the example:
https://github.com/TooTallNate/Java-WebSocket/wiki/Using-the-WebSocket-through-a-http-proxy
![TLS](https://user-images.githubusercontent.com/50514813/89390809-daab7980-d739-11ea-9715-308b60af9959.PNG)

The same issue as follow:
https://blog.csdn.net/qq_21090257/article/details/54910677

**Comment by nICEnnnnnnnLee** [comment]
There's nothing to do with that.    
If **socketFactory** exists, the config **proxy** will not work.
https://github.com/TooTallNate/Java-WebSocket/blob/0c163f6b9c0ca35a4d50c21766da908ce9e61f93/src/main/java/org/java_websocket/client/WebSocketClient.java#L447-L471

**Comment by nICEnnnnnnnLee** [comment]
BTW, the method given in the wiki is Deprecated.  
<https://github.com/TooTallNate/Java-WebSocket/wiki/Using-the-WebSocket-through-a-http-proxy>
https://github.com/TooTallNate/Java-WebSocket/blob/0c163f6b9c0ca35a4d50c21766da908ce9e61f93/src/main/java/org/java_websocket/client/WebSocketClient.java#L812-L813

**Comment by marci4** [comment]
> 
> 
> BTW, the method given in the wiki is Deprecated.
> [TooTallNate/Java-WebSocket/wiki/Using-the-WebSocket-through-a-http-proxy](https://github.com/TooTallNate/Java-WebSocket/wiki/Using-the-WebSocket-through-a-http-proxy)
> 
> https://github.com/TooTallNate/Java-WebSocket/blob/0c163f6b9c0ca35a4d50c21766da908ce9e61f93/src/main/java/org/java_websocket/client/WebSocketClient.java#L812-L813

https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/ProxyClientExample.java is up to date

**Comment by marci4** [comment]
My fiddle behaves unexpected. I do not need the socketfactory, but the connection will be reset by fiddle (since it cannot validate the certificate of the other side?)

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> My fiddle behaves unexpected. I do not need the socketfactory, but the connection will be reset by fiddle (since it cannot validate the certificate of the other side?)

@marci4 , it seems you're talking about debugging sever using specific cert. But in my case, the server's cert is qualified.  
My concern is how to let the client accept the cert signed by Fiddler itself.
```
mitm proxy

           cert singed by Fiddler                    cert given by server
client  <--------------------------->  Fiddler  <----------------------------->  Server

```

**Comment by dota17** [comment]
> There's nothing to do with that.
> If **socketFactory** exists, the config **proxy** will not work.
> https://github.com/TooTallNate/Java-WebSocket/blob/0c163f6b9c0ca35a4d50c21766da908ce9e61f93/src/main/java/org/java_websocket/client/WebSocketClient.java#L447-L471

Can you check your Internet Settings as follow ?
![SSL_20200806092425](https://user-images.githubusercontent.com/50514813/89480022-e1340280-d7c6-11ea-93ea-4c3b8ac20ec0.png)

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> Can you check your Internet Settings as follow ?
> ![SSL_20200806092425](https://user-images.githubusercontent.com/50514813/89480022-e1340280-d7c6-11ea-93ea-4c3b8ac20ec0.png)

The same with you.  

Well, I agree with your opinion to change "SSL" to “TLS” or "TLSv1.2".  
The fiddler still receives nothing from the client, what should I do next?

**Comment by nICEnnnnnnnLee** [comment]
```
ExampleClient c = new ExampleClient(new URI("wss://a-site-to-test.com:12345"));
c.setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 8888)));
c.connect();
```
It works if I change `null` to `trustAllCerts` and delete the judment `if (socket instanceof SSLSocket) ` follows in **WebSocketClient.java**.


https://github.com/TooTallNate/Java-WebSocket/blob/0c163f6b9c0ca35a4d50c21766da908ce9e61f93/src/main/java/org/java_websocket/client/WebSocketClient.java#L465-L478

```
// if the socket is set by others we don't apply any TLS wrapper
if (isNewSocket && "wss".equals(uri.getScheme())) {
	SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
	// sslContext.init(null, null, null);
	TrustManager[] trustAllCerts = new TrustManager[] { 
			new X509TrustManager() {
				@Override
				public void checkClientTrusted(X509Certificate[] arg0, String arg1)
						throws CertificateException {
					
				}
				@Override
				public void checkServerTrusted(X509Certificate[] arg0, String arg1)
						throws CertificateException {
					
				}

				@Override
				public X509Certificate[] getAcceptedIssuers() {
					return new java.security.cert.X509Certificate[] {};
				}
			} 
	};
	sslContext.init(null, trustAllCerts, null);
	SSLSocketFactory factory = sslContext.getSocketFactory();
	socket = factory.createSocket(socket, uri.getHost(), getPort(), true);
}

//if (socket instanceof SSLSocket) {
//	SSLSocket sslSocket = (SSLSocket) socket;
//	SSLParameters sslParameters = sslSocket.getSSLParameters();
//	onSetSSLParameters(sslParameters);
//	sslSocket.setSSLParameters(sslParameters);
//}
```

**Comment by dota17** [comment]
> ```
> ExampleClient c = new ExampleClient(new URI("wss://a-site-to-test.com:12345"));
> c.setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 8888)));
> c.connect();
> ```
> 
> It works if I change `null` to `trustAllCerts` and delete the judment `if (socket instanceof SSLSocket) ` follows in **WebSocketClient.java**.
> 
> https://github.com/TooTallNate/Java-WebSocket/blob/0c163f6b9c0ca35a4d50c21766da908ce9e61f93/src/main/java/org/java_websocket/client/WebSocketClient.java#L465-L478
> 
> ```
> // if the socket is set by others we don't apply any TLS wrapper
> if (isNewSocket && "wss".equals(uri.getScheme())) {
> 	SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
> 	// sslContext.init(null, null, null);
> 	TrustManager[] trustAllCerts = new TrustManager[] { 
> 			new X509TrustManager() {
> 				@Override
> 				public void checkClientTrusted(X509Certificate[] arg0, String arg1)
> 						throws CertificateException {
> 					
> 				}
> 				@Override
> 				public void checkServerTrusted(X509Certificate[] arg0, String arg1)
> 						throws CertificateException {
> 					
> 				}
> 
> 				@Override
> 				public X509Certificate[] getAcceptedIssuers() {
> 					return new java.security.cert.X509Certificate[] {};
> 				}
> 			} 
> 	};
> 	sslContext.init(null, trustAllCerts, null);
> 	SSLSocketFactory factory = sslContext.getSocketFactory();
> 	socket = factory.createSocket(socket, uri.getHost(), getPort(), true);
> }
> 
> //if (socket instanceof SSLSocket) {
> //	SSLSocket sslSocket = (SSLSocket) socket;
> //	SSLParameters sslParameters = sslSocket.getSSLParameters();
> //	onSetSSLParameters(sslParameters);
> //	sslSocket.setSSLParameters(sslParameters);
> //}
> ```

So ?  Welcome PR.

**Comment by marci4** [comment]
No we cannot do this. This breaks everything for normal users

**Comment by marci4** [comment]
Are we talking about Fiddler Everythere or Fiddler Classic?

**Comment by nICEnnnnnnnLee** [comment]
I'm using Fiddler Classic.  
Will it differ if I use Fiddler Everythere, or Fiddler Classic, or Charles, or sth else?

**Comment by nICEnnnnnnnLee** [comment]
I've made a commit https://github.com/nICEnnnnnnnLee/Java-WebSocket/commit/8d355a70ed42c6a4296cbe3f9698f360af1cad9a
But I'm not sure whether it will break something, especially 
https://github.com/nICEnnnnnnnLee/Java-WebSocket/blob/8d355a70ed42c6a4296cbe3f9698f360af1cad9a/src/main/java/org/java_websocket/client/WebSocketClient.java#L485-L491

**Comment by marci4** [comment]
The only real option is that you can provide a socket factory when trying to use a proxy.
So someone is able to disable all security if he needs to

**Comment by marci4** [comment]
Attached example code shows how I was able to connect to Fiddler Classic
'''java
  public static void main(String[] args) throws URISyntaxException, NoSuchAlgorithmException, KeyManagementException {
    ExampleClient c = new ExampleClient(new URI("wss://echo.websocket.org"));
    c.setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 8888)));
    SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
    // Trust all certificates 
    // Do NOT USE this in PRODUCTION
    TrustManager[] trustAllCerts = new TrustManager[] {
            new X509TrustManager() {
              public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                return new X509Certificate[0];
              }
              public void checkClientTrusted(
                      java.security.cert.X509Certificate[] certs, String authType) {
              }
              public void checkServerTrusted(
                      java.security.cert.X509Certificate[] certs, String authType) {
              }
            }
    };
    sslContext.init(null, trustAllCerts, null);
    c.setSocketFactory(sslContext.getSocketFactory());
    c.connect();
  }
'''
