### ISSUE TITLE
Where is Base64#decode?

### ISSUE THREAD

**Issue by BomBardyGamer** [TooTallNate/Java-WebSocket#1063]
The format doesn't really fit for what I'm asking

So I've been starting to use this library, and I'm using an older example of where this library is used, and I saw that it was using Base64#decode to decode a message encoded in `Base64`, and I tried writing in the method, and IntelliJ told me that it didn't exist. So I thought that was strange, and so I dug through the `Base64` class in `org.java_websocket.utils`, and true enough, it wasn't there. This confused me even more, so I then went and dug through the code on GitHub, and again, found that it didn't exist, whether in the `master` branch or in the `1.5.1` branch. I checked the commits to see if this had been removed, I also checked the release notes, and I couldn't find any information about this being deprecated or being removed.

I'm really not sure if it's just there and I'm just being stupid or I've done something wrong, but I'm really confused. Please let me know either way, and also let me know if you need any information about how I'm depending on the library, etc.

**Comment by BomBardyGamer** [comment]
And I should also mention that I looked for replacement decoding methods in that class (e.g. `Base64#encode` was replaced by `Base64#encodeBytes` I believe, or something like that), but the only method containing `decode` was `decode3To4`, which is private (and is probably not meant to be used as a utility method)

**Comment by dota17** [comment]
I think the code of https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/util/Base64.java is just a part of the origin [Base64.java](http://iharder.net/base64)

**Comment by BomBardyGamer** [comment]
So I should use Java's built-in `Base64` utility class then instead of the one wrapped in Java-WS?

**Comment by dota17** [comment]
> So I should use Java's built-in `Base64` utility class then instead of the one wrapped in Java-WS? (it said something along the lines of "this is now in Java" on that site) or is there a different solution?

Yes, but please note that the origin Base64.java just moved into JDK8 and after.
