### ISSUE TITLE
alert (level: fatal description internal error) in Client Hello

### ISSUE THREAD

**Issue by abhi484** [TooTallNate/Java-WebSocket#1067]
Hello All, 

I am seeing an alert with Internal Error when accessing https://erwebdev.dnb.com/memberpages/erwebservice.asmx through  app when the site is going through a CDN. As of now, the site has been taken off the CDN. Please find the screenshot of the error below: 

![image](https://user-images.githubusercontent.com/67599173/93104143-19ced200-f6cb-11ea-8700-a57faddc98a4.png)

When accessed through a browser, it works fine. Please find the snippet below: 

![image](https://user-images.githubusercontent.com/67599173/93104301-4be03400-f6cb-11ea-8b03-c2f41bff47f5.png)

SessionID is not found when I check the app traffic however I see the same in browser trace.

**Comment by marci4** [comment]
Please provide an example application and steps to repeat..

**Comment by marci4** [comment]
If you example application and steps to repeat are provided, this issue will be closed...
