### ISSUE TITLE
Android onMessage resend the same message every minute

### ISSUE THREAD

**Issue by GPRGLAMBERT** [TooTallNate/Java-WebSocket#1068]
I develop an Android client which communicates with my own server written in C, and find a strange behavior on the client side.

When the com is established and the client received the first message , the client receive the same message every minutes on the onmessage callback. I checked with wireshark and confirm that nothing comes from the server.
The Android application locks the screen in the manifest to avoid onPause callback.

Any idea of the cause of this surprising behavior ?

Thanks   

Gerard
[Android-websocket.tar.gz](https://github.com/TooTallNate/Java-WebSocket/files/5231265/Android-websocket.tar.gz)

**Comment by marci4** [comment]
Hey,

I am not able to reproduce this issue.

Pushed the code to https://github.com/marci4/Java-WebSocket_Issue_1068.
Tested in emulator with Pixel 3a and API Level 29.
Not using the openvpn activity (disabled via code).

Best regards,
Marcel

**Comment by GPRGLAMBERT** [comment]
Thanks for your investigations.
I am sorry for the waste of time. After more analyses , I found that
the wireshark analysis was wrong and the problem came from the server
side.
In fact I did'nt know that the PING message ,send every minute by   the
client,  trigers the LWS_CALLBACK_SERVER_WRITEABLE founction which
resend the same message.
Regards
Gerard
