### ISSUE TITLE
Javscript Client using SSL

### ISSUE THREAD

**Issue by sadzas** [TooTallNate/Java-WebSocket#1069]
Hi,

I'm looking for a way to stablish a SSL connection between Javascript client and my Java server.

Right now, everything is working fine without any secure line. 

My javascript client is very simple:
`socket = new WebSocket("ws://IPSERVER:6382");`

My Java server:
`socket = new Main(port);`
`socket.start();`

And that's it. Works like a charm.

So, I want to secure the connection. I believed that using HTTPS with selft-certificate plus "wss" would do the trick but I was wrong. If I do that, I can see (tcpdump) from server side the client trying to contact but it is not working.

In fact I'm not sure how to configure server side. The examples shows how to do it but for java clients, not for javascript.

Before asking here I tried a lot on Google. A LOT.

Thanks in advance.
(sorry for my english)

**Comment by CyberNipsu** [comment]
Hi,

Code-wise, it does not need much. Assuming you have "everything else" setup properly. 

What does your client error messages say? 
Is your client connection refused or is it connected by the server at all?  
Does your Java server have certificates setup properly?

Websocket goes through HTTP or HTTPS first before upgrading the connection, usually this is simpy handled by configuring the host properly for default HTTP/S ports (80, 443). The host then upgrades and reroutes Websocket connections to proper ports. 
 
If you set the server PORT directly in the client, you still need to handle the protocol upgrade somehow on the server side. Maybe theres a misaligned configuration? 

My own setup uses server with Apache2 (hosting https) and all connections connect with:
 `socket = new WebSocket("wss://IPSERVER");` 

I leave the port number off from client setup and instead reroute the websocket-connections from port 443 (default wss the client connects and asks for upgrade) to my Java server port within Apache2 configs (using Rewrite).

**Comment by marci4** [comment]
A special thing for webbrowser is that you have to trust the self signed certificate first.

If your wss url is wss://<SERVER>:<PORT>, open the website first with https://<SERVER>:<PORT>.
The browser reports the certificate as not trustworthy, so you manually have to tell the browser to trust the certificate anyway.

Best regards,
Marcel

**Comment by CyberNipsu** [comment]
> A special thing for webbrowser is that you have to trust the self signed certificate first.
> 
> If your wss url is wss://:, open the website first with https://:.
> The browser reports the certificate as not trustworthy, so you manually have to tell the browser to trust the certificate anyway.
> 
> Best regards,
> Marcel

Also if you are developing both the server and client on the same network, you might not be able to get a proper route to `wss://[SERVER WEB ADDRESS]` since your route most likely will go directly, through LAN IP. 

If client connects to the server under local network the address is not trusted in the certificate. Then you need to change the wss address to `wss://[SERVER LOCAL ADDRESS]` and manually make sure your browser will trust this "fake address" as described above ( `https://[SERVER LOCAL ADDRESS]` ).

**Comment by sadzas** [comment]
1) **Assuming you have "everything else" setup properly.**
mmmmm no... In fact, I'm not sure about that.

2) **Does your Java server have certificates setup properly?**
That's a thing. If I follow the examples, I should use:
`keytool -genkey -keyalg RSA -validity 3650 -keystore "keystore.jks" -storepass "storepassword" -keypass "keypa............`
So I have the keystore in the server but **I'm not sure how to use it on my client side**. The examples are only for java clients. I developed my client in JS.

Server side:

`socket = new Main(6283);`
`String STORETYPE = "JKS";`
`String KEYSTORE = Paths.get("/usr", "local", "keys", "keystore.jks").toString();`
`String STOREPASSWORD = "PASS";`
`String KEYPASSWORD = "PASS";`
        
`KeyStore ks = KeyStore.getInstance(STORETYPE);`
`File kf = new File(KEYSTORE);`
`ks.load(new FileInputStream(kf), STOREPASSWORD.toCharArray());`
`KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509");`
`kmf.init(ks, KEYPASSWORD.toCharArray());`
`TrustManagerFactory tmf = TrustManagerFactory.getInstance("SunX509");`
`tmf.init(ks);`      
`SSLContext sslContext = null;`
`sslContext = SSLContext.getInstance("TLS");`
`sslContext.init(kmf.getKeyManagers(), tmf.getTrustManagers(), null);`
`socket.setWebSocketFactory(new DefaultSSLWebSocketServerFactory(sslContext));`

`socket.setConnectionLostTimeout(10);`
`socket.start();`

Client side:

`host = "wss://server.local:6283";`
`socket = new WebSocket(host);`

3) **If you set the server PORT directly in the client, you still need to handle the protocol upgrade somehow on the server side. Maybe theres a misaligned configuration?**

My Apache:

`<IfModule mod_ssl.c>`
`   <VirtualHost *:443>`
`        ServerName blabla.blabla`
`        DocumentRoot /var/www/html/web`
`        SSLEngine on`
`        SSLCertificateFile /usr/local/etc/apachessl/server.crt`
`        SSLCertificateKeyFile /usr/local/etc/apachessl/server.key`
`    </VirtualHost>`
 
`   <VirtualHost *:6283>`
`        ServerName blabla.blabla`
`        DocumentRoot /var/www/html/web`
`        SSLEngine on`
`        SSLCertificateFile /usr/local/etc/apachessl/server.crt`
`        SSLCertificateKeyFile /usr/local/etc/apachessl/server.key`
`    </VirtualHost>`
`</IfModule>`

4) **What does your client error messages say?**

Chrome:
`main-agente.php:66 WebSocket connection to 'wss://server.local:6283/' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID`

Firefox:
`Firefox can't establish a connection to the server at server.local`

5) **If your wss url is wss://:, open the website first with https://:.
The browser reports the certificate as not trustworthy, so you manually have to tell the browser to trust the certificate anyway.**

Yes, that was one of the first things that I did.

6) **Also if you are developing both the server and client on the same network, you might not be able to get a proper route to wss://[SERVER WEB ADDRESS] since your route most likely will go directly, through LAN IP.**

Both server and client are on the same network and everything is ok with that. Server side has a FQDN and I use that for "wss".

7) Did you search on Google what client says?
Yes guys, I really did it. This error is a very common I think but none of the answers helped.

Thank you guys, really.

**Comment by CyberNipsu** [comment]
On client side (javascript+browser) the browser itself handles SSL connection issues (I do wish the browser error messages to be more specific, though). Your client side code is ok. 

However, your Apache is hosting on port 6283 (and I assume your Java server is doing the same) so I see a port conflict there.

Here's my rather identical setup: 

- Server machine hosts the webpage that contains javascript-client (default https, port 80 rerouted to 443). It also hosts several other services, multiple websocket servers etc. The client code of course could be hosted anywhere. When I host the client on the same domain as the websocket-server the SSL is is "automatically" trusted.  

- If I happen to connect the server machine from the same network, I need to modify javascript to use local address as well as manually confirm my browser that the "new address" is trusted. 

- My client connects to default wss port (443) and Apache rewrites wss-connections towards my websocket server (and hosts pages for https connections as usual).

The important part of my config (websocket on port 44444): 

```
<VirtualHost *:443>
      RewriteEngine on

#Cleaning the domain address
      RewriteCond %{HTTP_HOST} ^www.myserver.com$
      RewriteCond %{SERVER_PORT} ^443
      RewriteRule ^(.*)$ https://myserver.com$1 [R=301]

#Upgrading to websocket 
      RewriteCond %{HTTP:Upgrade} websocket [NC]
      RewriteCond %{HTTP:Connection} upgrade [NC]
      RewriteRule .* "wss://myserver.com:44444" [P,L]
</VirtualHost>
```

**Comment by sadzas** [comment]
I'm not sure about port issue.

My server side is just the java app. No Apache or anything else. Just the app running and publishing on port 6283.
My client side is a PHP web (Apache service) and javascript.

I think that as Chrome says it is a CERT issue.
`WebSocket connection to 'wss://server:6283/' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID`

If I check the port with tcpdump (server side).
`user@server:~$ sudo tcpdump -i any 'port 6283'`
`17:41:26.720524 IP javaServer.45930 > javaServer.6283: Flags [S], seq 2917480464, win 43690, options [mss 65495,sackOK,TS val 2540002133 ecr 0,nop,wscale 7], length 0`
`17:41:26.720534 IP javaServer.6283 > javaServer.45930: Flags [S.], seq 2870204795, ack 2917480465, win 16384, options [mss 65495,sackOK,TS val 2540002134 ecr 2540002133,nop,wscale 0], length 0`

Have you seen source and destination same host (server host)? why? And why port 45930?
