### ISSUE TITLE
setSocket marked as deprecated

### ISSUE THREAD

**Issue by rashaverak** [TooTallNate/Java-WebSocket#1073]
**Describe the bug**
setSocket marked as deprecated, should use setSocketFactory instead.

in your code socket = socketFactory.createSocket(); is called

Java 14  javax.net.SocketFactory.createSocket() just returns Exception

public Socket createSocket() throws IOException {
        //
        // bug 6771432:
        // The Exception is used by HttpsClient to signal that
        // unconnected sockets have not been implemented.
        //
        UnsupportedOperationException uop = new
                UnsupportedOperationException();
        SocketException se =  new SocketException(
                "Unconnected sockets not implemented");
        se.initCause(uop);
        throw se;
    }

**Expected behavior**
No deprecate something that cannot be replaced.

**Comment by marci4** [comment]
Hey 
I cannot find anything in the documentation for this.
Can you share some links?

Thx 

Best regards
Marcel

**Comment by PhilipRoman** [comment]
`javax.net.SocketFactory` is an abstract class. If you want to use a custom factory, you will need to override the `createSocket()` method.

**Comment by rashaverak** [comment]
You are right, I am sorry, too tired, this is one of the non abstract methods, public available to override though.
