### ISSUE TITLE
How to open WebSocket with available port?

### ISSUE THREAD

**Issue by tnsatt** [TooTallNate/Java-WebSocket#1074]
I use this code but getPort still return 0. Thank you

> int port=0;
> socket = new WebServer(port);
> socket.start();
> System.out.println(socket.getPort());

**Comment by PhilipRoman** [comment]
The server runs in its own thread and has not started yet when you call `getPort()`.  You should use the `onStart()` callback to know when the server has started.

**Comment by tnsatt** [comment]
```
public void onStart() {
	System.out.println("WebSocket Running On Port: "+port);
	setConnectionLostTimeout(100);
}
```
That not work, bro. I have this code but it still return port 0.
**WebSocket Running On Port: 0**

**Comment by PhilipRoman** [comment]
Well, you are printing the port variable, which you haven't changed. To get the port, use method `getPort()`

**Comment by tnsatt** [comment]
I wrong. Thank you so much
