### ISSUE TITLE
Can't connect to socket server also no error

### ISSUE THREAD

**Issue by nrohpos** [TooTallNate/Java-WebSocket#1076]
i had try connect to socket server(2) one is local, both got the same result <httpstatus = 101 switching protocol > .
uri that i used (ws://ip/), (wss://ip/) 
i had try by the following method that i reach #882 look like mine. but  i had try the 
for the code in that class had mentions in #882  >{ SecWebSocketProtocolClientExample.java } but it doesnt work , also got error code 426 (Invalid status code received: 426 Status line: HTTP/1.1 426 No Sec-WebSocket-Protocols requested supported).
is there any solution for that ?
thanks you ,

**Comment by marci4** [comment]
Hello @nrohpos 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4

**Comment by nrohpos** [comment]
Hello @marci4 , here the something details that i can descript>

uri = new URI(ws://ip:8080/); or uri = new URI(wss://ip/) is have same pb.
 socketClient = new WebSocketClient(uri);
the following hand shake that i got onOpen(.... handshake), 
httpstatus ->101
httpmessages -> Switching Protocols
Connection -> Upgrade
Sec-WebSocket-Accept -> 4A2ArW2Ar+C3HNO2g7SjSo+vzOU=
Upgrade -> websocket
...
after that i had call method send(socket.send()) in onOpen for send message to websocket (server),
but it like i mention before my kind of issues might be like #882 .
nothing response back from websocket(server)  but on IOS does have something,  they use [Starscream](https://github.com/daltoniam/Starscream) i just the same flow as them(if connect send the message back).

Thanks you .

**Comment by marci4** [comment]
Hello,

what is the error code?
Could you provide the handshakes?

Best regards,
Marcel

**Comment by nrohpos** [comment]
this what i got for handshake when debug :
httpstatus ->101
httpmessages -> Switching Protocols
Connection -> Upgrade
Sec-WebSocket-Accept -> AJg8vTP/DmscQINybJYOVXjT120=
Upgrade -> websocket
X-Powered-By -> Ratchet/0.4.1 
that's it .
there is no error code or error for that   ,
Thanks you.

**Comment by nrohpos** [comment]
it's like "The app is notified by the onOpen() callback: the http code and description are 101 and 'Switching protocols'.
The server is still sleeping waiting for a connection. It is not using any protected protocol.
If I send a string nothing happens." , i cant get nothing for that

**Comment by marci4** [comment]
Please provide an example application...

**Comment by nrohpos** [comment]
Dear , @marci4 
ex for my application :
my application willing to connect to websocket(server) and api (using laravel).
connect to socket for listen if there any new data or not , it new data call to api for that .
so the process itself , it the connection open or success (socket) ,  i have send some information back to socket !
it kinda crazy for use this 2 types together but save a lot !
Note : the connection(socket) itself if call back on "onOpen" with handshake the i provide above , 
Thanks you.
code for connection test : 
 try {
                    String url = "ws://192.168.0.13:8080/NNN/"; //local
                    uri = new URI(url);
                } catch (URISyntaxException e) {
                    e.printStackTrace();
                }
                assert uri != null;
//              Draft_6455 draft = new Draft_6455(Collections.<IExtension>emptyList(), Collections.<IProtocol>singletonList(new Protocol("ocpp2.0")));
                socketClient = new WebSocketClient(uri) {
                    @Override
                    public void onOpen(ServerHandshake handshake) {
                        Log.d(TAG, "onOpen: " + handshake);
                        if (handshake.hasFieldValue("Sec-WebSocket-Accept")) {// doesnt need
                            String webSocketKey = handshake.getFieldValue("Sec-WebSocket-Accept");
                            //send register data to websocket(server)
                             registerData();
                        }
                    }

                    @Override
                    public void onMessage(String message) {
                       //handle message here
                        Log.d(TAG, "onMessage: " + message);
                    }

                    @Override
                    public void onClose(int code, String reason, boolean remote) {
                        Log.d(TAG, "onClose: " + reason);
                     
                    }

                    @Override
                    public void onError(Exception ex) {
                        Log.d(TAG, "onError: " + ex);
                    }

                    @Override
                    public void onMessage(ByteBuffer bytes) {
                       //handle message here
                        Log.d(TAG, "onMessage: " + bytes);


                    }

                };

                socketClient.setConnectionLostTimeout(0);
                socketClient.connect();

**Comment by marci4** [comment]
Could it be that your server does not implement the Sec-WebSocket-Protocol `ocpp2.0` ?

Best regards,
Marcel

**Comment by nrohpos** [comment]
I'm not sure , I'm about to check with them .
if that the case i will close this for sure.
Thanks you .

**Comment by marci4** [comment]
Any update?

**Comment by nrohpos** [comment]
they're looking for the pbs too.
since i had try the another libraries (more than 3 of those) got the same result (onOpen/handShake)
but call .send doesn't do anything with the server(like it sleep).
i'm about to close this ticket. 
Thanks you for you time @marci4  .
