### ISSUE TITLE
Host HTTP endpoints on the same port as WS

### ISSUE THREAD

**Issue by SerVB** [TooTallNate/Java-WebSocket#1077]
**Describe what you would like to know or do**
I want to handle HTTP requests (only GET for now) on the same WS port.

**Describe the solution you'd considered**
I don't want to deploy another web server (like `com.sun.net.httpserver.HttpServer`) and redirect WS calls to the WS port, because two ports will be taken.

I've dived into sources and it seems managed to write a custom `Draft` implementation that handles GET requests. There are snippets that make the server return `<h1>Requested path: ${path}</h1>` for HTTP GET requests to `path`, and WS continues to work too (written in Kotlin, library version 1.4.0):

```kt
val ClientHandshake.isHttp: Boolean get() = this.getFieldValue("Upgrade").isNullOrBlank()

class HttpDraft : Draft() {

  private companion object {

    private const val PATH_FIELD = "X-My-Path"
  }

  override fun acceptHandshakeAsServer(handshakedata: ClientHandshake): HandshakeState {
    return when (handshakedata.isHttp) {
      true -> HandshakeState.MATCHED
      false -> HandshakeState.NOT_MATCHED
    }
  }

  override fun postProcessHandshakeResponseAsServer(request: ClientHandshake, response: ServerHandshakeBuilder): HandshakeBuilder {
    response.put(PATH_FIELD, request.resourceDescriptor)
    return response
  }

  override fun createHandshake(handshakedata: Handshakedata, withcontent: Boolean): List<ByteBuffer> {
    val content = "<h1>Requested path: ${handshakedata.getFieldValue(PATH_FIELD)}</h1>".toByteArray()

    val header = Charsetfunctions.asciiBytes(
      "HTTP/1.0 200 OK\r\n" +
      "Mime-Version: 1.0\r\n" +
      "Content-Type: text/html\r\n" +
      "Content-Length: ${content.size}\r\n" +
      "Connection: close\r\n" +
      "\r\n"
    )

    val bytebuffer = ByteBuffer.allocate(content.size + header.size)
    bytebuffer.put(header)
    bytebuffer.put(content)
    bytebuffer.flip()
    return listOf(bytebuffer)
  }

  override fun getCloseHandshakeType(): CloseHandshakeType {
    return CloseHandshakeType.NONE
  }

  override fun copyInstance(): Draft {
    return this
  }

  override fun reset() {
    // nop
  }

  override fun translateFrame(buffer: ByteBuffer): List<Framedata> {
    throw Exception("This draft doesn't work with frames")
  }

  override fun processFrame(webSocketImpl: WebSocketImpl, frame: Framedata) {
    throw Exception("This draft doesn't work with frames")
  }

  override fun createBinaryFrame(framedata: Framedata): ByteBuffer {
    throw Exception("This draft doesn't work with frames")
  }

  override fun createFrames(binary: ByteBuffer, mask: Boolean): List<Framedata> {
    throw Exception("This draft doesn't work with frames")
  }

  override fun createFrames(text: String, mask: Boolean): List<Framedata> {
    throw Exception("This draft doesn't work with frames")
  }

  override fun postProcessHandshakeRequestAsClient(request: ClientHandshakeBuilder): ClientHandshakeBuilder {
    throw Exception("This draft can't be used on a client")
  }

  override fun acceptHandshakeAsClient(request: ClientHandshake, response: ServerHandshake): HandshakeState {
    throw Exception("This draft can't be used on a client")
  }
}
```

To use it, you now have to create the server like `WebSocketServer(InetSocketAddress(port), listOf(HttpDraft(), Draft_6455()))` and start `onOpen` with
```kt
when (handshake.isHttp) {
  conn.close()
}
```

It works pretty well, I think I'll extract this logic to a subclass of `WebSocketServer` and make an abstract method to handle GET requests, it will make everything look adequate.

**Additional context**
Not sure what's the right way. Are there others? Maybe I can embed WebSocketServer inside another Web Server, without dedicating a real port for WebSocketServer?

**Comment by SerVB** [comment]
I've managed to introduce the following interface:

https://github.com/JetBrains/projector-client/blob/de987ed4ad243ecc84dc0e450f0cfaeb5ef536a5/projector-server-core/src/main/kotlin/org/jetbrains/projector/server/core/util/HttpWsServer.kt#L172-L178

Seems to be working.

Any chance that similar functionality will be available in this repo?

**Comment by marci4** [comment]
Sorry I am not sure what functionality you are asking for.

Best regards,
Marcel

**Comment by SerVB** [comment]
@marci4 , of course I'm talking about a feature of supporting handling HTTP requests 😉

**Comment by marci4** [comment]
No, we do not have any plans to support http requests. Sorry.

I wanna keep this library focusing on one thing and one thing only.

**Comment by SerVB** [comment]
Oh, OK... Thanks for the answer anyway
