### ISSUE TITLE
How to enable debug logging in this library, if it is being used by some other applicatiion

### ISSUE THREAD

**Issue by ashevade1** [TooTallNate/Java-WebSocket#1078]
I am using. third party java library which has a a websocket server implementation using this Java-Webcoket library
When deployed in a loud environment, seeing issues with the websocket connections.
 The suspect is some of the HTTP headers such as the "Upgrade" are being stripped off and not reaching the server, causing  this issue

Is it possible to enable logging from this library, in my java application which uses this ?

  we have a POM dependency on this , so not sure how to force this  to emit debug logging
Thanks for any help

Best Regards
Ani

**Comment by SerVB** [comment]
Hey, haven't tried it but it seems like SLF4J implementation should be added to classpath (for example: <https://github.com/TooTallNate/Java-WebSocket/wiki/SimpleLogger-example>) and log level should be set (like this: <https://stackoverflow.com/a/46052596/6639500>).

**Comment by marci4** [comment]
Please close this issue if your question is answered.

Best regards,
Marcel

**Comment by ashevade1** [comment]
Thanks a lot for those suggestions. It worked for me,

**Comment by ashevade1** [comment]
I  appreciate the help. I implemented what was suggested by servB and closing the issue.
