### ISSUE TITLE
How to enforce HSTS ?

### ISSUE THREAD

**Issue by pawankgupta-se** [TooTallNate/Java-WebSocket#1079]
Port 8887 is showing HTTP is detected. This port and is not enforcing HTTP Strict Transport Security (HSTS).

**Comment by marci4** [comment]
Hey,
You can add the http headers by overriding the method onWebsocketHandshakeReceivedAsServer:

E.g.
```java
  @Override
  public ServerHandshakeBuilder onWebsocketHandshakeReceivedAsServer(WebSocket conn, Draft draft,
      ClientHandshake request) throws InvalidDataException {
    ServerHandshakeBuilder builder = super
        .onWebsocketHandshakeReceivedAsServer(conn, draft, request);
    builder.put("Strict-Transport-Security", "max-age=100");
    return builder;
  }
```

Best regards,
Marcel

**Comment by pawankgupta-se** [comment]
@marci4 Thanks I will try that. I was having this solution but was not sure how to use and this will fix the issue or not.

**Comment by marci4** [comment]
@pawankgupta-se  is this question answered? If so please close the issue.

Best regards,
Marcel
