### ISSUE TITLE
Pathparameter

### ISSUE THREAD

**Issue by dOhx** [TooTallNate/Java-WebSocket#1081]
Gives no pathparameters?

**Comment by PhilipRoman** [comment]
I'm not sure what exactly you're asking here. If you want to access the endpoint path, use the `handshake` parameter in `onOpen`. See the documentation for more info: https://javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.1/org/java_websocket/handshake/ClientHandshake.html#getResourceDescriptor--

**Comment by PhilipRoman** [comment]
No further details and a solution has been provided. Closing issue.
