### ISSUE TITLE
ws or wss

### ISSUE THREAD

**Issue by zhuiyi1820** [TooTallNate/Java-WebSocket#1084]
helle,
I happen a bug, I setting ws://ip+port no problem，but wss error . This problem happen in simulator , phone is no problem.

**Comment by marci4** [comment]
Hello @zhoulifu 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4
