### ISSUE TITLE
use websocket+proxy, how to set user and password certification of prosy?which api here?

### ISSUE THREAD

**Issue by Gloria5zy** [TooTallNate/Java-WebSocket#1085]
**Describe what you would like to know or do**
A clear and concise description of what the problem is.
I wanna to know in this project, how to use proxy with user and password certification in a websocket connection?
Snippet code below
 public WebSocket(String url) throws URISyntaxException {
        super(new URI(url));
        super.setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(host, port)));
    }
Is there any api available  here ? thanks~~
**Describe the solution you'd considered**
A clear and concise description of any solutions you've considered.

**Additional context**
Add any other context or links about the question here.

**Comment by marci4** [comment]
Please check google for your question.

There are a few answers available, e.g. https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html or https://nashuasilverknights.com/lib/share/ups/RSS_developers_kit/RSS_reference_guide/WebHelp/Java/java_proxy_authentication.htm

Best regards,
Marcel
