### ISSUE TITLE
Is there any performance benmark for this implementation?

### ISSUE THREAD

**Issue by SouthernYard** [TooTallNate/Java-WebSocket#1087]
Hi team,
**Describe what you would like to know or do**
I am implementing the WebSocket client recently. Do you have any performance tests for this WebSocket implementation? Or do you have any performance comparison with, like Netty/Node.js/Jetty, etc? Or are there any metrics when using the current WebSocket client/server?
- GC
- Memory
- CPU
...

**Describe the solution you'd considered**
NO
**Additional context**
NO

Look forward to your reply.

Thanks,
Shawn

**Comment by marci4** [comment]
No, there are no performance benchmarks.
And right now, we do not have any plans to create some.

Best regards,
Marcel
