### ISSUE TITLE
How to stop resumption & renegotiation?

### ISSUE THREAD

**Issue by pawankgupta-se** [TooTallNate/Java-WebSocket#1089]
I read somewhere we can do like this but how to set this with web socket lib?

You can cause s_server to refuse to resume sessions like this:

`openssl s_server -port 443 -cert leaf1.crt -key leaf1.key -no_ticket -no_cache`

You can cause s_server to refuse renegotiation requests like this (only from OpenSSL 1.1.1 and above):

`openssl s_server -port 443 -cert leaf1.crt -key leaf1.key -no_renegotiation`

**Comment by marci4** [comment]
Hey 
I think you are looking for this.
https://support.datastax.com/hc/en-us/articles/360010967098-FAQ-How-to-disable-client-initiated-TLS-renegotiation

It is a Java feature not a lib feature.

Best regards,
Marcel
