### ISSUE TITLE
Are topic subscription implemented?

### ISSUE THREAD

**Issue by baldodavi** [TooTallNate/Java-WebSocket#1091]
In there an implementation of topic subscription in order to send "private" messages to users?
If no is there a way you can suggest to send messages to single user?

**Comment by PhilipRoman** [comment]
You can send messages to single users using [`WebSocket.send`](https://javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.1/org/java_websocket/WebSocket.html#send-java.lang.String-).

If that's not what you're looking for, you should clarify your question.

**Comment by baldodavi** [comment]
Thanks, going to investigate.
