### ISSUE TITLE
Any plans to support ws: and wss: in the same server instance?

### ISSUE THREAD

**Issue by jpaulm** [TooTallNate/Java-WebSocket#1092]
This is probably a dumb question, but I thought I would ask...  Apologies in advance!

After wrestling with the Java-WebSocket server logic for a while, I found this: "It is currently not possible to accept ws and wss connections at the same time via the same websocket server instance."

In my app - https://github.com/jpaulm/javafbp-websockets - I therefore have a parameter which specifies whether I am supporting ws: or wss: client requests.  I have put this in a parameter file, so the user can control which option s/he uses for a given run, so at least it's not hard-coded.  This parameter is used to control whether or not the sslContext.init command is issued.   It would be nice not to need this parameter, so I was just wondering if there are any plans to change this...   Or perhaps I have totally misunderstood!

Thanks!

**Comment by marci4** [comment]
Hey @jpaulm,

there are a few reason why I do not want to support both ws and wss.

1. Everything moving towards wss anyway. Every modern browser will require wss sooner or later anyway.
2. You would have to bind to two different ports to make this happen.
3. wss will always require some setup (certificate management etc).

Best regards,
Marcel

**Comment by jpaulm** [comment]
Many thanks, @marci4 !  Makes sense!  So I should probably drop the ws: option altogether - that also simplifies my code!  I have to try to understand certificate management anyway!  :-)

All the best, 

Paul
