### ISSUE TITLE
PerMessageDeflate report "RSV1 bit must be set for DataFrames." with npm WebSocket(ws) server

### ISSUE THREAD

**Issue by hpop1994** [TooTallNate/Java-WebSocket#1093]
Start a websocket server using npm WebSockets with configuration below, com.taobao.android.muise_sdk.jws.extensions.permessage_deflate.PerMessageDeflateExtension#isFrameValid will raise an Exception: "RSV1 bit must be set for DataFrames."

https://github.com/websockets/ws#websocket-compression
```javascripte
const WebSocket = require('ws');

const wss = new WebSocket.Server({
  port: 8080,
  perMessageDeflate: {
    zlibDeflateOptions: {
      // See zlib defaults.
      chunkSize: 1024,
      memLevel: 7,
      level: 3
    },
    zlibInflateOptions: {
      chunkSize: 10 * 1024
    },
    // Other options settable:
    clientNoContextTakeover: true, // Defaults to negotiated value.
    serverNoContextTakeover: true, // Defaults to negotiated value.
    serverMaxWindowBits: 10, // Defaults to negotiated value.
    // Below options specified as default values.
    concurrencyLimit: 10, // Limits zlib concurrency for perf.
    threshold: 1024 // Size (in bytes) below which messages
    // should not be compressed.
  }
});
```

Due to `threshold: 1024` , message length under 1024 is not compressed(rsv1:false when "Sec-WebSocket-Extensions" is returned in header), whereas PerMessageDeflateExtenstion assume all msg should be compressed and assert rsv1 to be true.

**Comment by marci4** [comment]
Please provide an example application for the client implementation using Java (not Android)!

Best regards,
Marcel

**Comment by marci4** [comment]
Last warning. Please provide an example otherwise I will close this issue.

**Comment by snowinszu** [comment]
I have the same issue when using https://github.com/uNetworking/uWebSockets.js and set compression on.

**Comment by marci4** [comment]
@snowinszu please create a fresh issue and provide steps to repeat with an example
