### ISSUE TITLE
A potential NPE bug

### ISSUE THREAD

**Issue by JulyChen728** [TooTallNate/Java-WebSocket#1096]
Hi all,
our bug scanner has reported a NPE bug.

A possible call chain may be [ProtoclHandshakeRejectionTest.java#L478](https://github.com/TooTallNate/Java-WebSocket/blob/12bb2f52aead157ea7fc23481982f054b8641a1d/src/test/java/org/java_websocket/protocols/ProtoclHandshakeRejectionTest.java#L478) => [getProtocol()](https://github.com/TooTallNate/Java-WebSocket/blob/12bb2f52aead157ea7fc23481982f054b8641a1d/src/main/java/org/java_websocket/client/WebSocketClient.java#L915) => [getProtocol()](https://github.com/TooTallNate/Java-WebSocket/blob/12bb2f52aead157ea7fc23481982f054b8641a1d/src/main/java/org/java_websocket/WebSocketImpl.java#L837). Since the method [getProtocol()](https://github.com/TooTallNate/Java-WebSocket/blob/12bb2f52aead157ea7fc23481982f054b8641a1d/src/main/java/org/java_websocket/WebSocketImpl.java#L839) may return null, a NPE bug may take place at [ProtoclHandshakeRejectionTest.java#L478](https://github.com/TooTallNate/Java-WebSocket/blob/12bb2f52aead157ea7fc23481982f054b8641a1d/src/test/java/org/java_websocket/protocols/ProtoclHandshakeRejectionTest.java#L478).

Thanks.

**Comment by PhilipRoman** [comment]
The code is a part of an unit test. If a NPE happens, the test will still fail, which is what we want.
