### ISSUE TITLE
Looking for guidance with my hanging code

### ISSUE THREAD

**Issue by jpaulm** [TooTallNate/Java-WebSocket#1097]
Hi @marci4 or @Davidiusdadi , I am just looking for some guidance on where to look to solve a bug in my own code - I'm afraid I am just a beginner with Websockets and keystores...  My app, https://github.com/jpaulm/javafbp-websockets , is based on Java-WebSocket, which is great, but I am probably using it all wrong!  

My code worked fine with client ws: before, and works fine with wss: if I use Chrome for my client, and specify `chrome://flags/#allow-insecure-localhost` .  The problem arises if I disable this Chrome option - then my app seems to hang on the `select` statement in WindowsSelectorImpl line 141...  Since the difference is that this case uses `keystore`, which I built using the instructions in Java-WebSocket, I assume that this is wrong in some way...  It also seems odd that it would just hang, rather than giving me an error message...   The keystore-related code (which may well be in the wrong place!) is in https://github.com/jpaulm/javafbp-websockets/blob/master/src/main/java/com/jpaulmorrison/fbp/components/WebSocketReceive.java - lines 117 - 142 .

BTW I tried it using SunX509 for the `kmf` and `tmf` instances, but no change!

Any pointers would be much appreciated! 

Added:  I should have mentioned that my clients are HTML5 and JavaScript - I don't see any examples to crib from in your web site - can you point me at some...?

**Comment by jpaulm** [comment]
Re this issue, it looks like the problem must be a bad keystore value.  However, if this is the case, the code should not just hang on `org.java_websocket.server.WebSocketServer` `selector.select` - it should give some kind of error message.  Maybe I'm wrong, but one of you guys should be able to point me in the right direction if so.

If I'm right, I would like to raise this as a feature request.  Thanks in advance!

**Comment by jpaulm** [comment]
I know this is a dumb question, but I can't find the answer online: how do I pass a security key to WebSocket in JavaScript called by HTML?  I suspect that the WebSocket call is getting rejected before it can even get to the server side.  I am attaching my HTML5 file - please let me know if it is totally wrong!!!

I am afraid I have had to rename the file type to `.txt` 

[chat1.txt](https://github.com/TooTallNate/Java-WebSocket/files/5608746/chat1.txt)

**Comment by marci4** [comment]
Hallo @jpaulm,

if you are using a self-signed certificate, you have to make the browser trust the certificate.

Therefore open https://localhost:<Your port> (in your case https://localhost:8887).

A website will open and chrome will say that "You're connection is not private".
There should be a button "Advanced", click that one and then click "Proceed to localhost(unsafe)".

With the click on "Proceed to localhost" you make the browser trust your certificate.

Then you should be able to open a normal connection with wss.

If that does not help you, you may need to provide the console error log of your browser.

Best regards,
Marcel

**Comment by jpaulm** [comment]
Merci, Marcel!

Thanks for the advice - unfortunately I can't find that Chrome setting.
However, fortunately(!), I already found the
`chrome://flags/#allow-insecure-localhost`
setting, so that should have the same effect!

My app works with that setting - but I wanted to be able to run it with a
valid password, but I have no idea where to put a password or keystore when
the client is JavaScript - and I can't find any documentation that talks
about this case!  Help would be much appreciated...   Of course, if it is
just not possible, I would like documentation to that effect!

Merci d'avance,

J. Paul

**Comment by marci4** [comment]
Hey
What Password do you mean?

Chrome cannot use your Java keystore, that's not how it works. Chrome and other browsers have a number of trusted root certificates. To not require any special flag of action, your certificate has to be signed by one of those root ca. 

Best regards,
Marcel

**Comment by jpaulm** [comment]
Thanks, Marcel - that helps, but I'm afraid my question is more basic: how do I specify a certificate in a HTML5/JavaScript request (not sure if that's the right term)?    Maybe a function call in the `send()` function?  Once I find that out, I can work on building the certificate...  TIA

Here is the link to the HTML: https://github.com/jpaulm/javafbp-websockets/blob/master/src/main/resources/scripts/chat1.html

**Comment by marci4** [comment]
No there is no way to specify a certificate.
See https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications
The certificate to use will be determined by the browser by asking the server. If the browser trusts the certificate, a connection will be opened.

Best regards,
Marcel

**Comment by jpaulm** [comment]
Thanks @marci4 !  That helps!  However when I disable allow-inscure-localhost, it just hangs!  I expected it would go to onError (or onOpen), and it doesn't seem to do either...  Maybe something I can do in the handshaking support...?

**Comment by marci4** [comment]
Are there any errors on the console?
Have you trusted your self signed certificate?

No need to ping everyone here...

**Comment by jpaulm** [comment]
Sorry, Marcel!  Nothing on the console... and I don't know where to put the d***n certificate!  If I knew that, I could concentrate on fixing it up!  Maybe my question is pretty obvious to people who know, but I haven't been able to find it out!  TIA

**Comment by jpaulm** [comment]
Thanks, @marci4 , I seem to be looking at the right area of code now, as tracing is now working for some reason!  I will carry on, so many thanks for your help!

Best regards, and stay safe!

**Comment by jpaulm** [comment]
@marci4 Sorry to bother you again, but I can't find any code entitled `onHandshakeReceived`, which would have been useful in solving my problem...  There *is* a comment referring to it, in WebSocketListener.onWebsocketMessage, but no code!  It's not on some other project on Github either... ???   Do you know what is going on?  Thx

**Comment by jpaulm** [comment]
Hi @marci4 , it turns out that `onWebsocketClose()` in https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/server/WebSocketServer.java was preventing display of the real reason for my IOException.  I have experimentally added `log.error(reason);` at the beginning of the method, and can now see the _real_ reason for the IOException (which is a bad certificate, as I suspected)!  Should I raise a PR (if I'm allowed to?), or do you want to do this?  

BTW I am seeing a tight loop in the IOException!  The `cause` of the IOException is IOException, and the `cause` of that one is the same IOException, and so on all the way down!  Haven't pursued that!

**Comment by marci4** [comment]
@jpaulm you can always open a PR.
Then we can discuss if and how we add the changes separate to this thread here

**Comment by jpaulm** [comment]
Merci!  Will do later today...

Paul

**Comment by jpaulm** [comment]
Trying to use WebSocket in JavaScript, talking to my Java server (built using Java-WebSocket, for which thanks!) via SSL.  I am now getting messages
        WebSocketSelector-35, READ: TLSv1.2 Alert, length = 2
        WebSocketSelector-35, RECV TLSv1.2 ALERT:  fatal, certificate_unknown

I think I have a good private key (on the server side) but I think I need a public key to pass to JavaScript WebSocket...  I may be totally wrong, but if this is correct, how do I do that?  Thanks in advance!
