### ISSUE TITLE
"The default package '.' is not permitted by the Import-Package syntax.   Maven Build Problem

### ISSUE THREAD

**Issue by jpaulm** [TooTallNate/Java-WebSocket#1100]
Maven Build Problem under Eclipse - pom.xml line 83  (downloaded unchanged from Maven)

"The default package '.' is not permitted by the Import-Package syntax.  

This can be caused by compile errors in Eclipse because Eclipse creates valid class files regardless of compile errors. The following package(s) import from the default package null (biz.aQute.bnd:bnd-maven-plugin:4.3.1:bnd-process:default:process-classes)  org.apache.maven.plugin.MojoFailureException: The default package '.' is not permitted by the Import-Package syntax.  This can be caused by compile errors in Eclipse because Eclipse creates valid class files regardless of compile errors. The following package(s) import from the default package null 	at aQute.bnd.maven.plugin.BndMavenPlugin.reportErrorsAndWarnings(BndMavenPlugin.java:611) 	at aQute.bnd.maven.plugin.BndMavenPlugin.execute(BndMavenPlugin.java:451) 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137) 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:332) 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1380) 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179) 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114) 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1379) 	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:54) 	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135) 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169) 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1) 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114) 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179) 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114) 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105) 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179) 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153) 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101) 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88) 	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197) 	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832) 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45) 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220) 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263) 	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316) 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45) 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319) 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:278) 	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:467) 	at org.eclipse.core.internal.resources.Project$1.run(Project.java:565) 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292) 	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:603) 	at org.eclipse.core.internal.resources.Project.build(Project.java:116) 	at org.eclipse.debug.core.model.LaunchConfigurationDelegate.lambda$0(LaunchConfigurationDelegate.java:406) 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292) 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2312) 	at org.eclipse.debug.core.model.LaunchConfigurationDelegate.buildProjects(LaunchConfigurationDelegate.java:412) 	at org.eclipse.debug.core.model.LaunchConfigurationDelegate.buildForLaunch(LaunchConfigurationDelegate.java:122) 	i.DebugUIPlugin$2.run(DebugUIPlugin.java:1224) 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63) 	pom.xml	/Java-WebSocket	line 83	Maven Build Problem

**Comment by marci4** [comment]
Hello @jpaulm 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
Marcel

**Comment by jpaulm** [comment]
---
name: Bug report
about: Create a report to help us improve

---

**Describe the bug**
Maven Build Problem under Eclipse - Java-WebSocket - pom.xml line 83

Message: The default package '.' is not permitted by the Import-Package syntax.

**To Reproduce**
Steps to reproduce the behavior:
1. . Download the Java-WebSocket source, including pom - https://github.com/TooTallNate/Java-WebSocket
2. .. Run Eclipse
3. ... Execute "Build project" in Package Explorer


** To get a clean compile:
1.. Comment out `biz.aQute.bnd` plugin in pom.xml

**Example application to reproduce the issue**
A link to a github project/gist to reproduce the issue.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Debug log**
Log given in original post (above), starting with:

`This can be caused by compile errors in Eclipse because Eclipse creates valid class files regardless of compile errors. The following package(s) import from the default package null (biz.aQute.bnd:bnd-maven-plugin:4.3.1:bnd-process:default:process-classes) org.apache.maven.plugin.MojoFailureException: The default package '.' is not permitted by the Import-Package syntax. This can be caused by compile errors in Eclipse because Eclipse creates valid class files regardless of compile errors. The following package(s) import from the default package null at aQute.bnd.maven.plugin.BndMavenPlugin.reportErrorsAndWarnings(BndMavenPlugin.java:611) at ...`

**Environment (please complete the following information):**
 - Version used: Eclipse 2020-03 *and* 2020-09
 - Java version: java version "1.8.0_271"
         Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
         Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
 - Operating System and version: Windows 10
 - Endpoint Name and version:
 - Link to your project: (not relevant?   compile error is in https://github.com/TooTallNate/Java-WebSocket
-  My project is at https://github.com/jpaulm/javafbp-websockets  

**Additional context**
Add any other context about the problem here.

**Comment by marci4** [comment]
Cannot reproduce the issue: Was able to build lib with maven in eclipse.

`[INFO] Building jar: Java-WebSocket-1.5.2-SNAPSHOT-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:09 min
[INFO] Finished at: 2020-11-29T18:11:51+01:00
[INFO] ------------------------------------------------------------------------`

**Comment by jpaulm** [comment]
I don't know if I can reopen this - I am still getting this error...

I have tried adding biz.aQute.bnd:bnd-maven-plugin:4.3.1  as a Maven dependency, and I still get this error in Eclipse in the pom.  Eclipse puts a red line underneath the first `execution` in `executions` within the aQute plugin group (line 83 in the pom).  It doesns't seem to hurt, but I'd like to get rid of it!  Thanks.
