### ISSUE TITLE
Nullpointer exception, ssl == null (client: browser, server: android), handshake cancelled web app error 

### ISSUE THREAD

**Issue by dss-kenya** [TooTallNate/Java-WebSocket#1102]
I seem to be getting this issue with the current version of this library. So then do we have to use BKS format vs JKS as you have it in the Sample Server file? Additionally, i tried it with BKS but then handshake doesnt happen between the client and server. Any idea what i should do? I keep getting "handshake cancelled" error message from the wss client (a web application), and android is my server. And android throws the error: Null pointer exception, ssl = null. I have added the certificate to the android device that is acting as the server, and accepted the certificate but still have the problem. 

I used the same BKS logic posted in this repo and also the SSLCustomFactory class, but i still get the above error. Please assist.

Thanks

_Originally posted by @dss-kenya in https://github.com/TooTallNate/Java-WebSocket/issues/885#issuecomment-739491104_

**Comment by dss-kenya** [comment]
Adding in additional information here: I use key store manager to generate for me the public and private key, while i use openssl commands to generate the signed ca certificate that has common name assigned the value: 127.0.0.1 since i would want to run it as localhost instead of a specific ip address.

**Comment by marci4** [comment]
Hello @dss-kenya,
Android does not support JKS, it supports BKS and a few others (check https://developer.android.com/reference/java/security/KeyStore, search for `Android provides the following KeyStore types:`).

No, without any code I have no idea. Please use the template provided or this issue will be closed.

Best regards,
Marcel

**Comment by marci4** [comment]
No infos --> Close
