### ISSUE TITLE
"Software caused connection abort"

### ISSUE THREAD

**Issue by rjpacket** [TooTallNate/Java-WebSocket#1105]
When I use this lib, I got 3000 errors like "Read error ******* Software caused connection abort".
But client can reconnect a few moment.
What causes this?

**Comment by marci4** [comment]
Hello @rjpacket,

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4
