### ISSUE TITLE
SSLServerLetsEncryptExample - what is the password ?

### ISSUE THREAD

**Issue by sadzas** [TooTallNate/Java-WebSocket#1106]
The example of SSL Lets Encrypt says the following:

`
SSLContext context;

    String password = "CHANGEIT";

    String pathname = "pem";
    try {
      context = SSLContext.getInstance("TLS");
      byte[] certBytes = parseDERFromPEM(getBytes(new File(pathname + File.separator + "cert.pem")),
          "-----BEGIN CERTIFICATE-----", "-----END CERTIFICATE-----");
      byte[] keyBytes = parseDERFromPEM(
          getBytes(new File(pathname + File.separator + "privkey.pem")),
          "-----BEGIN PRIVATE KEY-----", "-----END PRIVATE KEY-----");`

I'm not sure what the password means. cert and privkey doesn't need password at all. I've got both files but no password. If I let the password empty is not working anyway.

That's funny, 'cause using self certificate [https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLServerExample.java](url) works fine.

Please, I need some help here.

THANKS in advance.

**Comment by marci4** [comment]
Hey,
The password is needed to create the keystore (see https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLServerLetsEncryptExample.java for the full example).
You can leave it like this or change it to something different.

Best regards,
Marcel

**Comment by sadzas** [comment]
Hi marci4,

I'm so sorry but I don't get it.

That link is what I'm using. And the part of the code for kEYSTORE is null:

     `KeyStore keystore = KeyStore.getInstance("JKS");
      keystore.load(null);
      keystore.setCertificateEntry("cert-alias", cert);
      keystore.setKeyEntry("key-alias", key, password.toCharArray(), new Certificate[]{cert});`

Both cert.pem and privkey.pem has no password and I don't understand where I have to use it.

Sorry if I'm donig a dumb question.

**Comment by marci4** [comment]
But the following line contains the password 
keystore.setKeyEntry("key-alias", key, **password** .toCharArray(), new Certificate[]{cert});`

**Comment by sadzas** [comment]
Thanks marci4 for the patience! I really appreciate it.

What I don't understand is what is that password for. As I said, cert.pem and privkey.pem has no password. So, I don't get the point of that password.

**Comment by marci4** [comment]
https://docs.oracle.com/javase/7/docs/api/java/security/KeyStore.html#setKeyEntry(java.lang.String,%20byte[],%20java.security.cert.Certificate[]) 
setKeyEntry requires a key to be associated with they keyalias

**Comment by sadzas** [comment]
marci4, I've left the password empty and it is working fine.

Thanks!!!!
