### ISSUE TITLE
WebSocketClient.getRemoteSocketAddress() documentation issue

### ISSUE THREAD

**Issue by EclipseKnight** [TooTallNate/Java-WebSocket#1108]
The documentation for [this method](https://github.com/TooTallNate/Java-WebSocket/blob/cfde6e05cb5e0c525dd36030ed085d240690c564/src/main/java/org/java_websocket/WebSocketListener.java#L199) indicates it can return null in the description but then states in the Returns: never return null.

Also spacing issue with "ornull"

That's all, also which does it return lol.

![image](https://user-images.githubusercontent.com/32472185/102961967-bc110980-44b3-11eb-81c6-6b9fe68ccd03.png)

**Comment by prashanttholia** [comment]
Hi @marci4, 

I have a raised a pull request with documentation fixes for WebSocketClient.getRemoteSocketAddress() and WebSocketClient.getLocalSocketAddress() methods. 

I request you to review it.

The pull request is failing "SonarQube" check. I'd appreciate any guidance towards fixing it. If the check is not as important, I'd request you to accept the pull request.

Thanks.
