### ISSUE TITLE
send and return response async

### ISSUE THREAD

**Issue by EclipseKnight** [TooTallNate/Java-WebSocket#1109]
What I'm trying to do is send a message and return the response without trying to read the response from onMessage and ensure it's the corresponding response.

**Describe the solution you'd considered**
I tired using a CompletableFuture but not having an easy way to alter the existing send method makes things messy.

**Comment by marci4** [comment]
Hey,

I am currently not sure if this is even possible.

Could you provide your example code please?

Best regards,
Marcel

**Comment by EclipseKnight** [comment]
The best example i can find is on stackoverflow [here](https://stackoverflow.com/questions/53489023/java-websocket-get-response-outside-of-listener).

As you can see this solution returns the response of the sent message by using the completablefuture object. It sends the message and sets a new completablefuture, once a message is received it unblocks and returns the response. 

An issue or two I found when trying to do it with this library are the following:

- Inability to customize the implementation of send() very well. Of course you can override it but its difficult to reproduce the initial implementation just to add this feature on top.
- onMessage doesn't return the response and is instead void. This means you have to then pass the response to a, likely static, method to be able to handle it elsewhere. 
- ^ previous issue but for most of the required implementations of WebSocketClient don't return anything. 

Here is an example from my attempt at trying to handle a message when received.
```
WebSocketHandler.java
public static String onMessage(String text) {
	responseFuture.complete(text);
	return text;
}

PPSSPPClient.java (websocketclient)
@Override
public void onMessage(String message) {
	System.out.println("received message: " + message);
	WebSocketHandler.onMessage(message);
}

The issue with this is I'd have to avoid making the WebSocketHandler's method non-static, I'd have to pass the object into the client which can get pretty messing when you are constantly creating new clients. 

This outlines most of the issues I'm having. If you have any other questions or confusion let me know. Aside from this, the library has been really good and easy to use so thank you!

**Comment by marci4** [comment]
Are there any outstanding issues?

**Comment by EclipseKnight** [comment]
I think i got a bit side tracked, my main question is still in regards being able to send and return the response once it is received. Like javascripts asynchronous send and receive

**Comment by marci4** [comment]
Do you mean something like this?
```java
@Override
public void onMessage(String message) {
if ("request".equals(message)) {
send("response");
}
}
```

If not please rephrase your question.

Best regards,
Marcel

**Comment by EclipseKnight** [comment]
Let me try to rephase the question.

In javascript, you have the `await` keyword which waits until the Promise is settled. so if I send a request to a server and await, it will block further execution until the request is rejected or fulfilled. Once it is rejected or fulfilled you can assign that response to a variable and do what you want with it. 
```
returnValue = await.request();
```

That is what I'm trying to achieve with the websocketclient send method.

**Comment by marci4** [comment]
The HTML5 WebSocket API does not provide any promises. It just enqueues the message, the same thing we are doing.

The websocket protocol is not designed to be request->response only.
You may never get a specific response to your request. This is not required by the protocol.

Best regards,
Marcel

**Comment by EclipseKnight** [comment]
Sorry for the late response,

That perfectly answers my question. I apologize for any confusion.

Thank you very much!
