### ISSUE TITLE
Broadcast server->client to specific connection

### ISSUE THREAD

**Issue by trippy22** [TooTallNate/Java-WebSocket#1110]
In a ChatServer + ChatClient implementation, I was interested in fetching a list of clients connected to the server and sending each specific one a different message. Is this possible with the current impl?

**Comment by trippy22** [comment]
I am guessing I can just iterate over `private final Collection<WebSocket> connections` in `WebSocketServer`, but perhaps I missed methods for passing in a specific WebSocket connection to broadcast to?

**Comment by trippy22** [comment]
Perhaps im answering my own questions here but it looks like `doBroadcast` has the functionality I am looking for (albeit sends to all clients is what it was meant to do). I was hoping there was an out of box method for parameterized sending to a specific client in the collection (that said, I think I could reuse code to do this on my own, unless some method exists to do what I need)

**Comment by marci4** [comment]
Hey @trippy22,
[Websocket.send](https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.1/org/java_websocket/WebSocket.html#send-java.lang.String-) allows you to send to a specific websocket.
[broadcast](https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.1/org/java_websocket/server/WebSocketServer.html#broadcast-java.nio.ByteBuffer-java.util.Collection-) has a second optional argument, where you can specific your own Collection.
[getConnections](https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.1/org/java_websocket/server/WebSocketServer.html#getConnections--) is the way to access the current active clients.

Best regards,
Marcel

**Comment by trippy22** [comment]
Thank you, @marci4 ! For `Websocket.send`, where is the parameter to send to the specific socket? I only see `String text` in the particular one linked. It looks like the API is designed in such a way where every message is designed to be broadcasted to all clients (unless I start creating collections with 1 client in them)

**Comment by marci4** [comment]
Hello @trippy22,
the instance of the WebSocket is the specific socket ;)

No, broadcasts were only added later.

Best regards,
Marcel

**Comment by trippy22** [comment]
Sorry - I meant the specific client connection, not socket (oops). 

It would be awesome (I guess as a feature request), where broadcast had an argument where you could pass in a `WebSocket` object rather than `Collection<WebSocket>`. I think I will have to reuse some of the code otherwise to send a specific message to specific clients only.

**Comment by marci4** [comment]
I think there is a misunderstanding.

You can do both of the following things.
```java
List<WebSocket> list = new ArrayList<WebSocket>();
list.Add(conn);
broadcast("hello world", list);
// OR
conn.send("hello world");
```

Best regards,
Marcel

**Comment by NoahAndrews** [comment]
"Specific client connection" and "socket" are the same thing. `WebSocket` is a reference to the connection between the server and one single client.

**Comment by trippy22** [comment]
What if i had `client1, client2, client3` connected to my server and I wanted to send 

- Message A to client 3 only
- Message B to client 2 only
-  Message C to client 1 only

I am left writing code like this:

```
List<WebSocket> list1 = new ArrayList<WebSocket>();
list1.add(client1);
broadcast("Message C", list1);

List<WebSocket> list2 = new ArrayList<WebSocket>();
list2.add(client2);
broadcast("Message B", list2);

List<WebSocket> list3 = new ArrayList<WebSocket>();
list3.add(client3);
broadcast("Message A", list3);
```

I need to be able to fetch a list of `getConnections()`, then be able to send specific messages to specific clients (from the server to the client).

**Comment by trippy22** [comment]
Ah, I think I might understand now. Will try conn.send and hopefully close the issue out if it is working as intended!
