### ISSUE TITLE
Force websocket to use proxy on client end?

### ISSUE THREAD

**Issue by Cynosphere** [TooTallNate/Java-WebSocket#1111]
Is it possible to force websockets to use proxy on a client's end? I've tried with -Dhttp(s).proxyHost/Port and even system proxy but neither of these have been successful.

**Comment by marci4** [comment]
Hey,

I think you want to do this right?

https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/ProxyClientExample.java

Best regards,
Marcel

**Comment by valeciawolf34** [comment]
Valecia G Rodriguez

**Comment by Cynosphere** [comment]
For clarification, I do not have access to the source code. I am wanting to use a proxy with an existing project that uses this project.

**Comment by marci4** [comment]
Hello @Cynosphere,

you may try reflection, but that is more a general topic.

No other way possible to my knowledge (apart from the one you found).

Best regards,
Marcel

**Comment by daluu** [comment]
Curious, maybe you can make the request to that other project that uses this library to have configurable proxy support, since this library can support it.
