### ISSUE TITLE
WebSocketClient set ssl and proxy，but cannot use the proxy

### ISSUE THREAD

**Issue by ranan05** [TooTallNate/Java-WebSocket#1112]
i read the code of WebSocketClient.class，the method:run() has code blocks:

public void run() {
		InputStream istream;
		try {
			boolean isNewSocket = false;
			if (socketFactory != null) {
				socket = socketFactory.createSocket();
			} else if( socket == null ) {
				socket = new Socket( proxy );
				isNewSocket = true;
			} else if( socket.isClosed() ) {
				throw new IOException();
			}

i found if i set socketFactory, it won't use the proxy. But wss must set the socketFactory, also it has other method?
thanks

**Comment by marci4** [comment]
See #1070

Best regards,
Marcel
