### ISSUE TITLE
CORs issue connecting with socket.io (Vue or React) based web pages.

### ISSUE THREAD

**Issue by SteveyO** [TooTallNate/Java-WebSocket#1113]
Hey,  I have a question related to socket.io.  I am creating a typical Chat Application using the javascript socket.io library.  All the 'many' internet examples use express as the server so you never see this issue, however I am trying to do the server part in Java (using WebSocketServer running on port 8080). 

 I keep getting the CORs issue in my browser (see below).

`Access to XMLHttpRequest at 'http://localhost:8080/socket.io/?foo-bar=undefined&EIO=3&transport=polling&t=NRV069u' from origin 'http://localhost:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

So my Java code extends WebSocketServer and I am overriding onWebsocketHandshakeReceivedAsServer.
My builder has: builder.put( "Access-Control-Allow-Origin" , "*");  which I believe is what solves the CORs issue.

However, my question is:  My onWebsocketHandshakeReceivedAsServer method is never called.  I have no idea why. Should this be called when the client (ie browser) issues a socket.connect(). or when it first connects with a handshake?  I have tried both, but can never get this method called.   Maybe am doing something stupid, so any hints/tips would be much appreciated!

**Comment by marci4** [comment]
Hello @SteveyO,
could you please provide a simple example application and your webserver configuration?

Stupid question, but you say you are running the websocket server on 8080, but isnt the webserver already running on that port?

Thank you

**Comment by SteveyO** [comment]
Hi @marci4   Thanks for the quick reply.  Nope, the webserver is running on port 8081 (Vue runs on 8080, but if its busy it shifts the number by 1).  In any case running 2 servers on the same port would give me a binding exception.

So when I start the server the onStart() sysout is printed to the console, but as mentioned above, my question is how the onWebsocketHanshakeReceivedAsServer is triggered?  I haven't managed to get this method called (hence the CORs issue)

```
public class SignallingServer extends WebSocketServer {

    private static final int PORT = 8080;

    public static void main(String args[]) {
        SignallingServer server = new SignallingServer();
        server.start();
    }
    @Override
    public void onStart() {
        System.out.println("onStart");
    }

    @Override
    public ServerHandshakeBuilder onWebsocketHandshakeReceivedAsServer(WebSocket conn, Draft draft, ClientHandshake request)  {
        System.out.println("OnWebsocketHandshakeReceivedAsServer");
        ServerHandshakeBuilder builder = null;
        try {
            builder = super.onWebsocketHandshakeReceivedAsServer( conn, draft, request );
        } catch (InvalidDataException e) {
           System.out.println(" Server Invalid Data Exception");
        }
        builder.put( "Access-Control-Allow-Origin" , "*");
        return builder;
    }

    public SignallingServer() {
        super(new InetSocketAddress(PORT));
        System.out.println("JAVA Signalling server started on PORT: " + PORT);
    }
```

My WebCode looks something like this (and I see the CORS issue in the Browser Developer tools so its definitely finding the WebSocketServer).  I suspect it may be due to the options (which includes the handshake) but not sure, as am just starting out with these JavaScript frameworks.

```
Vue.use(new VueSocketIO({
  debug: true,
  connection: 'http://localhost:8080',
  options: { autoConnect: false, query: "foo-bar" },
  query: "foo-bar"
}))
```

**Comment by NoahAndrews** [comment]
If you want to use a Java server, you can't use socket.io (which is fine, I don't think it adds much utility compared to bare websockets, as long as you don't care about supporting ancient browsers). 

![Screenshot_20210108-212246~2.png](https://user-images.githubusercontent.com/10224994/104081985-7ae15f00-5200-11eb-96cf-7401a589208c.png)

**Comment by SteveyO** [comment]
@NoahAndrews Wow,  thanks a lot for the response.  I feel kinda stupid now.  I tried ages to get that working and I was missing that pretty valuable piece of information.

I will try again with one of the recommendations.
Thanks a lot for this,  you saved me many more hours hopelessly trying to get this to work :-)

**Comment by NoahAndrews** [comment]
Haha, no worries. It's easy to miss.
