### ISSUE TITLE
.java_websocket.exceptions.WebsocketNotConnectedException

### ISSUE THREAD

**Issue by wang0420** [TooTallNate/Java-WebSocket#1114]
#13302 org.java_websocket.exceptions.WebsocketNotConnectedException
org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)

**Comment by PhilipRoman** [comment]
Please clarify your problem.

This exception happens when the socket you're trying to use is not connected.

**Comment by wang0420** [comment]
在发送消息之前  我已经确认webSocket 已经连接上了

 public synchronized void sendMessage(String message) {

        try {
            if (webSocketClient != null) {
                if (webSocketClient.isOpen()) {
              
                    webSocketClient.send(message);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

**Comment by PhilipRoman** [comment]
It is possible (and normal) that the socket was closed between between checking and sending. Even a simple loop like this can throw a WebsocketNotConnectedException:
```java
while(socket.isOpen())
    socket.send("...");
```

Instead of checking before sending, simply send and then catch the exception if the socket was closed.
