### ISSUE TITLE
How to use a WebSocket offline?

### ISSUE THREAD

**Issue by denebchorny** [TooTallNate/Java-WebSocket#1119]
**Describe what you would like to know or do**
I am working on an IoT project where two devices communicate; a phone and a camera.

1. The camera opens a hotspot.
2. The phone connects to a hotspot
3. And now I need communication between devices using socket. 

How can I use a socket over a hotspot without access to the internet?

**Comment by marci4** [comment]
hello @denebchorny,

as long as they are both in the same network and have two different ip addresses, you should be able to access them.

Best regards,
Marcel
