### ISSUE TITLE
The problem I encountered while using reconnect

### ISSUE THREAD

**Issue by shaohongwu** [TooTallNate/Java-WebSocket#1120]
I use reconnect() in the onClose method

```
@Override
            public void onClose(int code, String reason, boolean remote) {
                log.info("[websocket] onClose");
                reconnect();
            }
```
Receive exception message in onError method: Socket closed.
What is the correct way to use reconnect ？

**Comment by marci4** [comment]
Hello,
Just reconnect from a different thread or start a different thread executing the reconnect in onClose.

Best regards,
Marcel

**Comment by HePingLaoSan** [comment]
Hello, 
Would there be any issues if I directly reconnect in the onClose thread?
Should I execute reconnection logic in onError as well? Or is it sufficient to perform reconnection only in onClose?

Best regards

**Comment by sante85** [comment]
@marci4 can post an example how to reconnect?
