### ISSUE TITLE
my cpu occupancy rate about to 100% when i use reconnect()

### ISSUE THREAD

**Issue by xusonfan** [TooTallNate/Java-WebSocket#1122]

**Comment by xusonfan** [comment]
public void onClose(int code, String reason, boolean remote) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                LocalCache.this.reconnect();
            }
        }).start();
    }

this is my code,when i stop the server and just run the client,the cpu is above to 100% usage,how to fix it?  /(ㄒoㄒ)/~~

**Comment by marci4** [comment]
Hello @xusonfan 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4
