### ISSUE TITLE
the cpu usage is about to 100% when i use reconnect in onClose() method

### ISSUE THREAD

**Issue by xusonfan** [TooTallNate/Java-WebSocket#1125]
**Describe what you would like to know or do**
I want to reconnect to server when connect is closed to keep the connection always alive,but when server is closed,i run the client,i expect it will keep retry to connect to server when the server is restart,but i noticed that the cpu usage is about to 100% when it reconnect,it seems that the program created many new thread which lead to this situation.so,what is the right way to keep reconnect when the server is closed?please help me!

**Describe the solution you'd considered**
i want the client to keep try to reconnect to server then the server is closed.

**Additional context**
this is my code:

    @Override
    public void onClose(int code, String reason, boolean remote) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                if(getReadyState().equals(ReadyState.CLOSED)){
                    reconnect();
                }
            }
        }).start();
    }

    @Override
    public void onError(Exception ex) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                if(getReadyState().equals(ReadyState.CLOSED)){
                    reconnect();
                }
            }
        }).start();
    }

**Comment by marci4** [comment]
Hello @xusonfan 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4
