### ISSUE TITLE
Module Not Found - JDK 11+

### ISSUE THREAD

**Issue by LoboMetalurgico** [TooTallNate/Java-WebSocket#1128]
**Describe the bug**
When trying to compile the application using java 11+ and declaring the Java.WebSocket module in module-info.java, maven returns "module not found: Java.WebSocket"

**To Reproduce**
1. Install JDK 11+
2. Create a simple program
3. Add a module-info.java and declare Java.WebSocket
4. Try compile with maven

**Example application to reproduce the issue**
https://github.com/twitchapis/JavaTwitchAPI/

**Expected behavior**
Compile normally

**Debug log**
https://github.com/twitchapis/JavaTwitchAPI/actions/runs/628523021 (Ubuntu 20.04)
https://github.com/twitchapis/JavaTwitchAPI/actions/runs/615627627 (Ubuntu 18.04)

**Environment(please complete the following information):**
 - Version used: 1.5.1
 - Java version: JDK 11 (github workflow) and 15 (local machine)
 - Operating System and version: Windows 10 and Ubuntu 18.04 / 20.04
 - Link to your project: https://github.com/twitchapis/JavaTwitchAPI/

**Additional context**

When using IntelliJ Idea to run, the code works normally, but when trying to compile with maven on github or the local machine, the error happens.

**Comment by marci4** [comment]
@PhilipRoman I never worked with Java modules. Do you have an idea?

**Comment by PhilipRoman** [comment]
This library doesn't use the Java module system, so by default it falls in the "unnamed module". There is no module called Java.WebSocket that you mention here: https://github.com/twitchapis/JavaTwitchAPI/blob/main/src/main/java/module-info.java, so you need to remove that line.

If your project uses modules but your dependency doesn't, you need to explicitly depend on the "unnamed module". One way to do this is to add the following option to `javac`: `--add-reads 'JavaTwitchAPI=ALL-UNNAMED'`. I don't use Maven much, so I don't know how to configure it. In Gradle it would look like this
```gradle
compileJava {
   options.compilerArgs += ['--add-reads', 'JavaTwitchAPI=ALL-UNNAMED']
}
```

**Comment by LoboMetalurgico** [comment]
Oh ok. Thank you for the information. This plugin was placed by IJ, so I thought everything was ok. I think it would be a good observation for docs.
