### ISSUE TITLE
Not getting messages from wss server if the code is written under @Test in TestNG.

### ISSUE THREAD

**Issue by leelaram-j** [TooTallNate/Java-WebSocket#1129]
**Describe what you would like to know or do**

Not getting messages from wss server if the code is written under @Test in TestNG. How can I achieve the same?
The same code is working if the code is written under public static void main.

**Describe the solution you'd considered**

-

**Additional context**

-

**Comment by marci4** [comment]
Hello @leelaram-j

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4
