### ISSUE TITLE
WSS Client: Extension unknown: DER encoded OCTET string

### ISSUE THREAD

**Issue by mtarjoianu** [TooTallNate/Java-WebSocket#1131]
Hello, 

**Describe what you would like to know or do**
I am trying to connect to a wss server.
The wss server is developed by a company and it is working 
(I connected and communicated with it in Chrome using the online client from https://www.wss-websocket.net/).

When I'm trying to connect to that wss server using TooTallNate, my GET is denied.
I get no exception, but in log, at "*** Certificate chain" , I see: "Extension unknown: DER encoded OCTET string".

**Describe the solution you'd considered**
I took and modified this example wss client:

`import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.net.URI;
import java.nio.file.Paths;
import java.security.KeyStore;
import java.util.HashMap;
import java.util.Map;

import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocketFactory;
import javax.net.ssl.TrustManagerFactory;

import org.java_websocket.client.WebSocketClient;
import org.java_websocket.handshake.ServerHandshake;

class WebSocketChatClient extends WebSocketClient {

	public WebSocketChatClient (URI serverUri) {
		super(serverUri);
	}
	
	public WebSocketChatClient (URI serverUri, Map<String, String> _headers) {
		super(serverUri, _headers);
	}

	@Override
	public void onOpen(ServerHandshake handshakedata) {
		System.out.println("Connected");

	}

	@Override
	public void onMessage(String message) {
		System.out.println("got: " + message);

	}

	@Override
	public void onClose(int code, String reason, boolean remote) {
		System.out.println(System.currentTimeMillis() + "Disconnected");

	}

	@Override
	public void onError(Exception ex) {
		ex.printStackTrace();

	}

}

public class WSSClient {

	/*
	 * Keystore with certificate created like so (in JKS format):
	 *
	 *keytool -genkey -keyalg RSA -validity 3650 -keystore "keystore.jks" -storepass "storepassword" -keypass "keypassword" -alias "default" -dname "CN=127.0.0.1, OU=MyOrgUnit, O=MyOrg, L=MyCity, S=MyRegion, C=MyCountry"
	 */
	public static void main(String[] args) throws Exception {
		
		Map<String, String> _headers = new HashMap<String, String>();
		_headers.put("Authorization","Basic <my base64 string>");
		
		WebSocketChatClient chatclient = new WebSocketChatClient(new URI("wss://lek3co.public.ocpp-broker.com/ocpp/cp/socket/16/RO*LEK*E000100"), _headers);
		
		// load up the key store
		String STORETYPE = "JKS";
		String KEYSTORE = Paths.get("src", "test", "java", "org", "java_websocket", "keystore.jks").toString();
		String STOREPASSWORD = "storepassword";
		String KEYPASSWORD = "keypassword";

		KeyStore ks = KeyStore.getInstance(STORETYPE);
		File kf = new File(KEYSTORE);
		ks.load(new FileInputStream(kf), STOREPASSWORD.toCharArray());

		KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509");
		kmf.init(ks, KEYPASSWORD.toCharArray());
		TrustManagerFactory tmf = TrustManagerFactory.getInstance("SunX509");
		tmf.init(ks);

		SSLContext sslContext = null;
		sslContext = SSLContext.getInstance("TLSv1.2");
		//sslContext = SSLContext.getInstance("TLS");
		sslContext.init(kmf.getKeyManagers(), tmf.getTrustManagers(), null);
		//sslContext.init( null, null, null ); // will use java's default key and trust store which is sufficient unless you deal with self-signed certificates

		SSLSocketFactory factory = sslContext
				.getSocketFactory();// (SSLSocketFactory) SSLSocketFactory.getDefault();

		chatclient.setSocketFactory(factory);
                System.out.println(System.currentTimeMillis() + "connecting");
		chatclient.connectBlocking();

		BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
		while (true) {
			String line = reader.readLine();
			if (line.equals("close")) {
				chatclient.closeBlocking();
			} else if (line.equals("open")) {
				chatclient.reconnect();
			} else {
				chatclient.send(line);
			}
		}
	}
}`

From https://lek3co.public.ocpp-broker.com opened in Chrome I downloaded the certificate.
Then I used this command:
`keytool -import -trustcacerts -keystore "keystore.jks" -storepass "storepassword" -keypass "keypassword" -alias "default" -file myRoot.cer`

Then I verified the keystore:

> keytool -list -keystore keystore.jks
Enter keystore password:
Keystore type: jks
Keystore provider: SUN
Your keystore contains 1 entry
default, 16-Mar-2021, trustedCertEntry,
Certificate fingerprint (SHA1): A8:98:5D:3A:65:E5:E5:C4:B2:D7:D6:6D:40:C6:DD:2F:B1:9C:54:36

I set:  -Djavax.net.debug=all
Then I run the program.
In the log I receive DENY at the GET step and I see "Extension unknown: DER encoded OCTET string".
This is the log file: 
[log.log](https://github.com/TooTallNate/Java-WebSocket/files/6170984/log.log)

The GET looks the same as the one made by the online wss client from https://www.wss-websocket.net/:
![image](https://user-images.githubusercontent.com/50733603/111778798-ebba8c80-88bd-11eb-9474-ba57f56dff4e.png)

I tried with root certificate, with intermediate certificate and with leaf certificate and I had no success.

Do you have any idea about what am I doing wrong?

Thank you very much for your help.

Best Regards,
M.T.

**Comment by marci4** [comment]
Hello @mtarjoianu,

if your certificate is trusted by a CA, you do not need to import the certificate into a keystore.
You can simple connect via your address.

I was not able to reproduce the issue without the keystore. Have you tried that?

Best regards,
Marcel

**Comment by mtarjoianu** [comment]
Hello marci4, 

Thank you very much for your response.

I modified the WSSClient, the log is indeed different, but I still get DENY at the GET step.
I use  Java-WebSocket-1.5.1.jar.

This is my new WSSClient:
`import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URI;
import java.util.HashMap;
import java.util.Map;

import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocketFactory;

import org.java_websocket.client.WebSocketClient;
import org.java_websocket.handshake.ServerHandshake;

class WebSocketChatClient extends WebSocketClient {

	public WebSocketChatClient (URI serverUri) {
		super(serverUri);
	}
	
	public WebSocketChatClient (URI serverUri, Map<String, String> _headers) {
		super(serverUri, _headers);
	}

	@Override
	public void onOpen(ServerHandshake handshakedata) {
		System.out.println("Connected");

	}

	@Override
	public void onMessage(String message) {
		System.out.println("got: " + message);

	}

	@Override
	public void onClose(int code, String reason, boolean remote) {
		System.out.println(System.currentTimeMillis() + "Disconnected");

	}

	@Override
	public void onError(Exception ex) {
		ex.printStackTrace();

	}
}


public class WSSClient {

	
	public static void main(String[] args) throws Exception {
		
		Map<String, String> _headers = new HashMap<String, String>();
		_headers.put("Authorization","Basic <my base64 string>");
		
		WebSocketChatClient chatclient = new WebSocketChatClient(new URI("wss://lek3co.public.ocpp-broker.com/ocpp/cp/socket/16/RO*LEK*E000100"), _headers);

		SSLContext sslContext = null;
		sslContext = SSLContext.getInstance("TLSv1.2");
		sslContext.init( null, null, null ); // will use java's default key and trust store which is sufficient unless you deal with self-signed certificates

		SSLSocketFactory factory = sslContext
				.getSocketFactory();// (SSLSocketFactory) SSLSocketFactory.getDefault();

		chatclient.setSocketFactory(factory);
		System.out.println(System.currentTimeMillis() + "connecting");
		chatclient.connectBlocking();

		BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
		while (true) {
			String line = reader.readLine();
			if (line.equals("close")) {
				chatclient.closeBlocking();
			} else if (line.equals("open")) {
				chatclient.reconnect();
			} else {
				chatclient.send(line);
			}
		}
	}
}
`

And this is the new log file: 
[new log.txt](https://github.com/TooTallNate/Java-WebSocket/files/6176235/new.log.txt)


Thank you very much for you help.

Best Regards,
M.T.

**Comment by marci4** [comment]
Hey
You don't have to use the socket factory.

Only 
WebSocketChatClient chatclient = new WebSocketChatClient(new URI("wss://lek3co.public.ocpp-broker.com/ocpp/cp/socket/16/RO*LEK*E000100"), _headers);
chatclient.connectBlocking()

Best regards
Marcel

**Comment by mtarjoianu** [comment]
Hello Marcel, 

Thank you for your response.
I made the modification. I still receive DENY at the GET step.
I checked the string used for Basic Authentication in GET. It is correct, it is the same as the one in the log of the online wss client from https://www.wss-websocket.net/.

My current WSSClient:
[WSSClient.txt](https://github.com/TooTallNate/Java-WebSocket/files/6177222/WSSClient.txt)

The obtained log:
[log3.txt](https://github.com/TooTallNate/Java-WebSocket/files/6177227/log3.txt)

Thank you very much for your help.

Best Regards,
M.T.

**Comment by marci4** [comment]
Hello @mtarjoianu,
right now I do not think it is an issue with the certificate.

I tried it with different other certificates and get the same reported message.
Nevertheless, I do NOT get any Disconnect message there.

Could you maybe provide a full log including trace information for Java-WebSocket?
Whats onClose called with?
Whats onError called with?
Thx

Best regards,
Marcel

**Comment by mtarjoianu** [comment]
Hello, 
I set   org.slf4j.simpleLogger.defaultLogLevel=trace  in  simplelogger.properties.

After DENY, there appeared:

> 1177 [WebSocketConnectReadThread-11] TRACE org.java_websocket.WebSocketImpl - process(396): (HTTP/1.1 101 Switching Protocols
Server: nginx
Date: Sun, 21 Mar 2021 16:22:41 GMT
Connection: upgrade
Sec-WebSocket-Accept: jr5qun/R/aJBMntQqyHi/p6+7rQ=
Upgrade: WebSocket
Sec-WebSocket-Protocol: ocpp1.6
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
)
1185 [WebSocketConnectReadThread-11] TRACE org.java_websocket.drafts.Draft_6455 - acceptHandshakeAsClient - Matching extension found: DefaultExtension
1185 [WebSocketConnectReadThread-11] TRACE org.java_websocket.drafts.Draft_6455 - acceptHandshakeAsClient - No matching extension or protocol found.
1186 [WebSocketConnectReadThread-11] TRACE org.java_websocket.WebSocketImpl - Closing due to protocol error: draft Draft_6455 extension: DefaultExtension max frame size: 2147483647 refuses handshake


This is now the obtained log:
[log4.txt](https://github.com/TooTallNate/Java-WebSocket/files/6177903/log4.txt)


Thank you for your help.

Best Regards,
M.T.

**Comment by marci4** [comment]
Hey,

check out https://github.com/TooTallNate/Java-WebSocket/wiki/Specifing-a-Sec-WebSocket-Protocol on how to specify the required Sec-WebSocket-Protocol.

Best regards,
Marcel

**Comment by mtarjoianu** [comment]
Hello marci4, 

It works!!!  I could connect and change messages.

Thank you very much for your help !

Best Regards,
M.T.
