### ISSUE TITLE
Implement Stomp 1.2 Spec

### ISSUE THREAD

**Issue by ed0906** [TooTallNate/Java-WebSocket#1135]
**Is your feature request related to a problem? Please describe.**
This library seems like the main alternative to spring equivalents. 
It'd be great if there was an implementation of the [Stomp 1.2](https://stomp.github.io/stomp-specification-1.2.html) Spec on top of this library to save developers from having to pull in all the spring transitive dependencies that come along with spring-messaging.

**Describe the solution you'd like**
A similar interface to WebSocketServer & WebSocketClient that allows Stomp based communications over WS

**Describe alternatives you've considered**
I've tried the spring-messaging library, but to use that it's expected that the project will be running within the spring ecosystem. I plan to build a library (rather than spring service) so a non-spring equivalent is desired.

**Comment by marci4** [comment]
Hello @ed0906,
we have no plans to implement any protocol, which uses websockets.
Want to keep this library clean.

Maybe there is a community project already using this lib.

Best regards,
Marcel
