### ISSUE TITLE
How to use wss client on android without certificate on phone

### ISSUE THREAD

**Issue by nsmith1024** [TooTallNate/Java-WebSocket#1139]
Hi,

I saw your code called SSLClientExample. where the client uses a local certificate from a keyStore and then uses that to make the wss connection.

Is it possible to just make a wss connection without doing all of that? like below

     socket = new WebSocketChatClient(new URI("wss://mysite.com),this);
     socket.connectBlocking();

Then immediately start sending/receiving data using that. Will it still be secure? How secure will it be? I just have self signed certificate on the server.

Here is your SSLClientConnection Example code, I would like to skip all this if possible?

                socket = new WebSocketChatClient(new URI(url),this);
                globals.Log2("yogig","-->WEB socket created result="+socket);

                String STORETYPE = "JKS";
                String KEYSTORE = Paths.get("src", "test", "java", "org", "java_websocket", "keystore.jks").toString();
                String STOREPASSWORD = "storepassword";
                String KEYPASSWORD = "keypassword";

                KeyStore ks = KeyStore.getInstance(STORETYPE);
                File kf = new File(KEYSTORE);
                ks.load(new FileInputStream(kf), STOREPASSWORD.toCharArray());

                KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509");
                kmf.init(ks, KEYPASSWORD.toCharArray());
                TrustManagerFactory tmf = TrustManagerFactory.getInstance("SunX509");
                tmf.init(ks);

                SSLContext sslContext = SSLContext.getInstance("TLS");
                sslContext.init(kmf.getKeyManagers(), tmf.getTrustManagers(), null);
                // sslContext.init( null, null, null ); // will use java's default key and trust store which is sufficient unless you deal with self-signed certificates

                SSLSocketFactory factory = sslContext.getSocketFactory();// (SSLSocketFactory) SSLSocketFactory.getDefault();

                socket.setSocketFactory(factory);
                socket.connectBlocking();

**Comment by PhilipRoman** [comment]
Depends what you are doing, and what you want to verify. If you want to be sure that the server you're connecting to is actually the server it claims to be, you don't need a client side certificate.

If the server wants to be able to verify the identity of a client, your client will need a certificate.

**Comment by nsmith1024** [comment]
So if i just want to verify the server and connect with wss, i can just do this??

     socket = new WebSocketChatClient(new URI("wss://mysite.com),this);
     socket.connectBlocking();

**Comment by marci4** [comment]
You could also get a certificate from let's encrypt.
Most android versions should trust the CA.

**Comment by PhilipRoman** [comment]
@nsmith1024 Yes, assuming your server has a SSL certificate.
To connect with a timeout, check out the documentation here: https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.2/org/java_websocket/client/WebSocketClient.html#connectBlocking-long-java.util.concurrent.TimeUnit-

**Comment by Pripun** [comment]
i have probleem too.... Error show "**No subjectAltNames on the certificate match**".
My AndroidManifest.xml have to set  **android:usesCleartextTraffic="true"**. But If my android prgram access "**Https**" protocol, The error not show.

> @nsmith1024 Yes, assuming your server has a SSL certificate.
> To connect with a timeout, check out the documentation here: https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.2/org/java_websocket/client/WebSocketClient.html#connectBlocking-long-java.util.concurrent.TimeUnit-

**Comment by PhilipRoman** [comment]
@Pripun Please clarify your problem and provide example code. Are you sure your issue is related to this library?

**Comment by Pripun** [comment]
The same way when i use **connect** or **connectBlocking**   
```
val BASE_URL = "wss://mysite.com"
        var draf=Draft_6455()
        val cc:WebSocketClient
        try {
         //cc=object :WebSocketClient(URI(BASE_URL),draf)
            cc=object :WebSocketClient(URI(BASE_URL)){
                override fun onOpen(handshakedata: ServerHandshake?) {
                    println("Test " +handshakedata.toString())
                }

                override fun onMessage(message: String?) {
                    println("Test " + message.toString())
                }

                override fun onClose(code: Int, reason: String?, remote: Boolean) {
                    println("Test " + reason.toString())
                }

                override fun onError(ex: Exception?) {
                    println("Test  " +ex.toString())
                }

            }
            //cc.connectBlocking(10000,TimeUnit.SECONDS)
          cc.connect()
        }catch (e:URISyntaxException){
            println("ERROR URI"+e.toString())
        }
```

> @Pripun Please clarify your problem and provide example code. Are you sure your issue is related to this library?

**Comment by PhilipRoman** [comment]
@Pripun If I understand correctly, the problem happens because the server's SSL certificate doesn't cover the domain name you're accessing. For example, if the server has a SSL certificate for name `example.com`, but you're accessing it through the domain name `subdomain.example.com` or `example2.com`, you will get this error.

If you can connect to the exact same domain name using https://www.websocket.org/echo.html, but not this library, please include the full stacktrace of the error, as well as the domain name you're connecting to.

**Comment by Pripun** [comment]
> @Pripun If I understand correctly, the problem happens because the server's SSL certificate doesn't cover the domain name you're accessing. For example, if the server has a SSL certificate for name `example.com`, but you're accessing it through the domain name `subdomain.example.com` or `example2.com`, you will get this error.
> 
> If you can connect to the exact same domain name using https://www.websocket.org/echo.html, but not this library, please include the full stacktrace of the error, as well as the domain name you're connecting to.

I have test it with **WebSocket Test Client** pluggin on chrome the resut is success...:D. But if i use your sdk error show like that.

**Comment by marci4** [comment]
Please provide an example application!

**Comment by marci4** [comment]
@Pripun could you please provide a full example project including your domain?

Best regards,
Marcel
