### ISSUE TITLE
more control on pre-WebSocket Creation stage

### ISSUE THREAD

**Issue by nort3x** [TooTallNate/Java-WebSocket#1140]
i would like to add some policy on socket level in WebSocketServer, even before a websocket is created and onOpen is triggered
i think it could be useful to have some more control on that stage because of these reasons(to name a few):

1- custom policies
2- custom monitors
3- hooking into that socket 

i want to trigger an scheduled task when a socket is accepted and give it a short time to handshake and authenticate 
but if client never do a handshake i have no control over that socket and its draining the resources resulting a window for multiple DOS attacks.
ofcourse these kind of problems can be solved with introducing a proxy socket either inside the process itself or as a micro-service but it is not the best option because we are introducing some re-emission

i can think of two possible ways to extend for these controls:

1- feeding WebSocketServer live sockets and leaving the rest to it
2- giving it some consumers as an extra option and letting it customize that socket for us when they are created

personally i think (1) is not a good choice because connection acceptance is implemented in WebSocketServer and by going in this path we loose that feature 
(2) can cause loose of generality and probably have some more complexities but more solid than first choice, 

i would gladly accept some insights and tips and humbly offer this community my help

-h

**Comment by PhilipRoman** [comment]
I'm not sure about giving the user access to pre-handshake sockets, but we should definitely implement some sort of a configurable connection/read timeout. I assumed that such a timeout already existed, but I've been `netcat`'ing my localhost for 5 minutes and nothing has happened (Whereas programs like nginx closed my connection after 1 minute).

**Comment by nort3x** [comment]
yes i encountered this when i was trying to check if listener opened a port succefully so i did telnet to it,it didnt close the connection and when ever i send it something unacceptable it seems to deny it with:
`trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
s
HTTP/1.1 404 WebSocket Upgrade Failure
Content-Type: text/html
Server: TooTallNate Java-WebSocket
Content-Length: 77

<html><head></head><body><h1>404 WebSocket Upgrade Failure</h1></body></html>
` 
and waits for an acceptable request (retry stage! why?)
so its actually letting a user drain lots of bandwidth with a single character  + process power, i wish we could have the option to just drop the connection (convention over configuration, overriding some default behaviors and injection of interfaces between stages)
and i totally understand why you suggest 'avoiding user access to pre-handshake sockets' and increasing complexities but it can become very handy in the sense of "little projects can stay standalone,minimal and safe" and making this library more popular

**Comment by tt1c** [comment]
any update on this?

**Comment by PhilipRoman** [comment]
@tt1c No, I don't think anything has changed here. Patches are welcome!
