### ISSUE TITLE
Invalid status code received

### ISSUE THREAD

**Issue by wuilmerj24** [TooTallNate/Java-WebSocket#1141]
**Describe the bug**
Reason: Invalid status code received: 200 Status line: HTTP/1.1 200 OK

**To Reproduce**
Connect

**Example application to reproduce the issue**
A link to a github project/gist to reproduce the issue.
`https://github.com/vkusenko/SignalR-Client-Android`

**Expected behavior**
Connect

**Debug log**
The the debug log (set the log level to `TRACE`) to help explain your problem.

**Environment(please complete the following information):**
 - Version used:1.5.2
 - Java version:1.8
 - Operating System and version:android
 - Endpoint Name and version:
 - Link to your project:

**Additional context**

**Comment by FilipsR** [comment]
You should use `ws://` url instead of `http://`

**Comment by PhilipRoman** [comment]
You should use `ws://` url instead of `http://`

**Comment by wuilmerj24** [comment]
@PhilipRoman I changed it and it doesn't work

**Comment by PhilipRoman** [comment]
Are you getting a different error after changing it?

**Comment by marci4** [comment]
@wuilmerj24  I am not into signal but I think the project you are using is just outdated.
It seems that there is no negotiation happening and therefore the SignalR server responds with a bad request.

Thats at least what I see.

There is however a official java library available (https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-5.0)

Closing this issue as it is out of our reach.

Best regards,
Marcel

**Comment by wuilmerj24** [comment]
ok thnks.
