### ISSUE TITLE
Subdomain with _ not working

### ISSUE THREAD

**Issue by SirLennox** [TooTallNate/Java-WebSocket#1144]
**Describe what you would like to know or do**
I tried to open a wss connection to a host with a _ in the subdomain, but it says 'java.security.cert.CertificateException: Illegal given domain name'

**Describe the solution you'd considered**
Can I change 'IDN.USE_STD3_ASCII_RULES' to '0' or something else?

**Comment by marci4** [comment]
Most likely an outdated runtime, see https://stackoverflow.com/a/48444910

**Comment by SirLennox** [comment]
> Most likely an outdated runtime, see https://stackoverflow.com/a/48444910

I tried to update to java 16 and java 11, nothing changed.

**Comment by marci4** [comment]
Not much we can do here. We have no control over the exception cause.

**Comment by SirLennox** [comment]
I found an API that fixed it, thank you for your help.

**Comment by marci4** [comment]
You mind sharing with others having a similar issue?

**Comment by SirLennox** [comment]
oh, I dont know the project, I am on my mobile rn
