### ISSUE TITLE
NoClassDefFoundError:Failed resolution of:Lorg/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by JakeWoki** [TooTallNate/Java-WebSocket#1146]
Didn't find class "org.slf4j.LoggerFactory"
version:1.5.2
Android

**Comment by PhilipRoman** [comment]
This library depends on [slf4j-api](https://mvnrepository.com/artifact/org.slf4j/slf4j-api/1.7.25)

**Comment by NoahAndrews** [comment]
To elaborate, that means that your code needs to depend on one of the slf4j implementations, that hooks into whatever logger your application uses.

**Comment by JakeWoki** [comment]
Android does not use slf4j-api. suggest remove it

**Comment by NoahAndrews** [comment]
The point is that you can use a slf4j implementation library that prints to your logging system. For Android, I've used slf4j-handroid

**Comment by marci4** [comment]
Closing this issue as it is solved.
We dont have any plans to remove slf4j and Android is not our main target.

Best regards,
Marcel
