### ISSUE TITLE
Two Android devices are paired, can the number of connections be controlled?

### ISSUE THREAD

**Issue by cl-6666** [TooTallNate/Java-WebSocket#1147]
Hello, our current scenario is that two Android devices are paired, one as the server and the other as the client. The problem we have now is that the server can have multiple connections. What we want now is 1 to 1 Effect, other devices want to connect but not connect

**Comment by marci4** [comment]
Hey,

I dont think this is the main idea behind web sockets.
You can however run one device as server and one as client and limit the number of connection by e.g. rejecting a handshake (https://github.com/TooTallNate/Java-WebSocket/wiki/Rejecting-a-handshake).

Best regards,
Marcel
