### ISSUE TITLE
Websocket with Libgdx GWT

### ISSUE THREAD

**Issue by ange-black69** [TooTallNate/Java-WebSocket#1148]
Hello !
I developped a libgdx html5 using GWT.
The server use your Java-WebSocket project whereas the client used to run on [](https://github.com/czyzby/gdx-lml/tree/master/websocket) which are outdated now I am affraid.
I want to port my client implementation to yours but I don't see anything about the GWT part.
Does is it possible to use this project with libgdx GWT ?
If so, how ?
Thank you for your help,
Regard

**Comment by PhilipRoman** [comment]
I don't think you will be able to run this library on GWT. I looked at http://www.gwtproject.org/doc/latest/RefJreEmulation.html and it seems that (for obvious reasons) java standard library networking and IO are not available.

I would recommend calling some Javascript code from your GWT client, which can then use the browser WebSocket API.

**Comment by ange-black69** [comment]
Strange, why did it worked perfectly with czyzby/websocket before ?
I see [https://stackoverflow.com/questions/30800088/how-to-achieve-network-communication-in-html5-libgdx-gwt](url)
and it said that this implementation can target most libgdx platform.
any hint ?

**Comment by ange-black69** [comment]
unfortunatly, the html5 part was my only interest :(
So to be clear, It worked good before, but from now, once the websocket communication is established, I got a "unable to send packet" error.
I send the packet via socket.send(Object) method
Do you know why I got this error ?

**Comment by PhilipRoman** [comment]
No idea what could have caused that.

**Comment by PhilipRoman** [comment]
Well, it seems to be thrown from here: https://github.com/czyzby/gdx-lml/blob/4d866e87d6cfef56b19180bc324d8dbe6f97a45b/websocket/src/main/java/com/github/czyzby/websocket/impl/AbstractWebSocket.java#L173. From there, it's just a matter of debugging to find out.

If you are not interested in platforms other than html5, then using the browser's native WebSocket API seems like an easy solution to your problem.

**Comment by ange-black69** [comment]
Ok thank you for your help I appreciate it !
Yes the problem is I want to make the game multi-platform like android also.
I will try to debug my first idea on czyzby.
The server using this project is perfectly working !
Thanks again for your help
