### ISSUE TITLE
  Android websocket can't connect. I need help

### ISSUE THREAD

**Issue by seasons12138** [TooTallNate/Java-WebSocket#1149]
I'm a beginner of Android
When you use your Java wecsocket. 1.4.0 jar package to develop websocket client, when you connect to the server, you will directly call the onerror() method -- > onclose() method. I can confirm that the server code is OK and can be connected, and the client code is OK, And I find a lot of other people's client code to test, but also can't.
I don't know whether it's a code problem or a configuration problem, or some problems I didn't think of. I've been looking online for a long time and haven't found the answer, so I'm here for help.
If anyone can see my problem and know the solution, please reply to me. Thank you very much.

##This is my running report
05/15 21:53:46: Launching 'app' on Pixel 2 API 29.
App restart successful without requiring a re-install.
$ adb shell am start -n "com.example.study_01/com.example.study_01.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 13200 on device 'emulator-5554'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
W/RenderThread: type=1400 audit(0.0:350): avc: denied { write } for name="property_service" dev="tmpfs" ino=6777 scontext=u:r:untrusted_app:s0:c157,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0
W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
W/xample.study_0: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/xample.study_0: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
D/HostConnection: HostConnection::get() New Host Connection established 0xde942190, tid 13232
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation: eglCreateContext: 0xde91a120: maj 3 min 0 rcv 3
E/MyClient: onError: 
    onClose: 
D/EGL_emulation: eglMakeCurrent: 0xde91a120: ver 3 0 (tinfo 0xde90f400)
W/Gralloc3: mapper 3.x is not supported
D/HostConnection: createUnique: call
    HostConnection::get() New Host Connection established 0xde942410, tid 13232
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/eglCodecCommon: allocate: Ask for block of size 0x1000
    allocate: ioctl allocate returned offset 0x3ffff4000 size 0x2000
D/EGL_emulation: eglMakeCurrent: 0xde91a120: ver 3 0 (tinfo 0xde90f400)
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 1 0
E/MainActivity: onServiceConnected: execute

I know this problem may seem very simple, but I really can't find a suitable solution. If there is a big guy who can solve it, please reply me.
I'm really in a hurry.
Thanks again.

**Comment by marci4** [comment]
Hey,
If you want to get support, please provide a full example application.
Apart from that, check the provided error as well as the close code and close message.
All these arguments are good indicator what caused the aborted connection.

Best regards,
Marcel
