### ISSUE TITLE
Is it possible to specify subprotocols?

### ISSUE THREAD

**Issue by alifa133** [TooTallNate/Java-WebSocket#1151]
I want to specify subprotocols when creating a client. Is this possible?

I have a python client that works (connects and gets messages from the url) ,I can do this in it like this:

`
    ws = websocket.WebSocketApp( connection_url,
                            subprotocols=['graphql-ws'],
                            on_open = on_open,
                            on_message = on_message,
                            on_error = on_error,
                            on_close = on_close,)
`

Now I get this error when I try to create a new client:

`opened connection
received: {"payload":{"errors":[{"message":"NoProtocolError","errorCode":400}]},"type":"connection_error"}
Connection closed by remote peer Code: 1006 Reason: `

subprotocls in the rfc. Not sure if this is implemented or not since it is specified as  _This section is non-normative._
https://datatracker.ietf.org/doc/html/rfc6455#section-1.9

**Comment by marci4** [comment]
Hey,
Check out this example on how to specify a Sec-WebSocket-Protocol:
https://github.com/TooTallNate/Java-WebSocket/wiki/Specifing-a-Sec-WebSocket-Protocol

Best regards,
Marcel

**Comment by alifa133** [comment]
Hi @marci4 ,

Thanks a lot for pointing me to the sample. My client connects successfully now.

Cheers,
Ali Fakhraee
