### ISSUE TITLE
How to recognize fatal error and restart ?

### ISSUE THREAD

**Issue by workingenius** [TooTallNate/Java-WebSocket#1155]
**Describe what you would like to know or do**

Sometimes the server fails and the port is even no longer listening.
It's unavoidable but I'd like to be notified and try to restart by my own strategy. 

But for now, when my `onError` is called, I can't tell if it's a fatal error or not, which will cause the server down.
I guess `exception == null` in `onError` can do this. But I can't make sure.
Maybe there are situations that the `exception == null` but the server won't down.

Of course I can keep checking if the port is serving, but I think the framework can do something.

**Describe the solution you'd considered**

Can I use `exception == null` to tell ?

Some proposals on it:
Maybe a new `onFatalError` callback method?
Or there could be a "main thread" that I could join, and work with systemd or docker ?
Or a `runForever` method and throw exception if server down ? also friendly to systemd.

Or how should I implement this ?

Thank you

**Comment by marci4** [comment]
Hey,

Could you provide an example when the server fails?

Would be much better to fix the bug then workaround an issue.

Best regards,
Marcel
