### ISSUE TITLE
Can onClosing be called without onClose being called?

### ISSUE THREAD

**Issue by ParticleCore** [TooTallNate/Java-WebSocket#1156]
I have detected on a few occasions (unable to recreate deliberately) the websocket client `onClosing` being called, but `onClose` did not.

I tried to look for the behavior around these two in the documentation, but I could not find anything confirming whether or not this is possible.

I also looked at the source code to try and understand this for myself, and it appears that it is possible the `onClosing` is called, without calling `onClose` after.

Whenever this happened in my tests, it was always with `remote` as false, which is when the app is closing the websocket.

I can work around this by always assuming that `onClosing` and `onClose` can be called without the other being called, but I would like to know if this is normal/expected, since it is not very intuitive. I was expecting that `onClose` would always be called, except for abnormal situations, like an error, for example.

Is it possible for `onClose` to not be called after `onClosing` was called?

**Comment by marci4** [comment]
Hey,
No, right now I would not say there is any good reason why onClosing is called but not onClose.

If you can reproduce, feel free to open a bug.

You should only need to rely on onClose, no need to use onClosing (Think of it like e.g. the javascript API)

Best regards,
Marcel

**Comment by ParticleCore** [comment]
Understood, that's what I wanted to clarify exactly, thanks!
