### ISSUE TITLE
How to check if server is currently running after start()

### ISSUE THREAD

**Issue by attotushek** [TooTallNate/Java-WebSocket#1162]
I am running a simple WebSocket server through my java program and was wondering if there is any reliable method of obtaining the server's status within the calling class.

More specifically, i have a main class creating and starting the WebSocket server, and then the main class runs a separate while loop. I would like this loop to end when the server stops (through crash or built-in stop() method). Is there a method that I would be able to call that can check the server's status? Similarly to the WebSocket client method isOpen()?

Thank you.

**Comment by PhilipRoman** [comment]
Your best option is to have your own stopping method that sets a boolean flag which the main loop reads (depending on how you call it, it might have to be volatile) and also stops the server.

To handle "crashes" you first have to decide what errors do you consider fatal (probably where `conn == null`). All exceptions within the server are passed to onError callback in which you can call your created stopping method if necessary.

**Comment by attotushek** [comment]
After some quick testing, that seemed to work perfectly. Thank you much!

Will close the issue now.
