### ISSUE TITLE
[Android & Node.js Server] Problem using PerMessageDeflateExtension with custom ping/pong messages ? 

### ISSUE THREAD

**Issue by SaraHan774** [TooTallNate/Java-WebSocket#1164]
Hi, I have a question about using `PerMessageDeflateExtension`.

```
E/SessionManager: ◖[Session] WebSocket error #Network	⚑[SessionManager$listenToEvents$6.accept:358]
E/SessionManager: ◖ org.java_websocket.exceptions.InvalidFrameException: RSV1 bit must be set for DataFrames.
E/SessionManager: ◖	at org.java_websocket.extensions.permessage_deflate.PerMessageDeflateExtension.isFrameValid(PerMessageDeflateExtension.java:321)
E/SessionManager: ◖	at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:565)
E/SessionManager: ◖	at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:739)
E/SessionManager: ◖	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:398)
E/SessionManager: ◖	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
E/SessionManager: ◖	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
E/SessionManager: ◖	at java.lang.Thread.run(Thread.java:923)
E/SessionManager: ◖ 
```

I ran into above error log, so I made a break point like below. 

<img width="1547" alt="image" src="https://user-images.githubusercontent.com/42170276/126436997-58b2ff96-4bdf-4eae-8994-23e31ac8809d.png">

![image](https://user-images.githubusercontent.com/42170276/126437098-58af17ce-b622-4f1f-b094-a9c581c2b4dc.png)

If you see the log, the payload contains our custom ping message which is being transferred in TextFrame. I would like to know if this kind of custom ping/pong message could interfere with using PerMessageDeflateExtensions properly. (I checked the RFC 6455 document and read that Ping/Pong Frames have different opcodes) 

Also, I couldn't understand the purpose of the below lines. 

```java
    public void isFrameValid(Framedata inputFrame) throws InvalidDataException {
        if((inputFrame instanceof TextFrame || inputFrame instanceof BinaryFrame) && !inputFrame.isRSV1())
            throw new InvalidFrameException("RSV1 bit must be set for DataFrames.");
```

Does this mean that all TextFrame & BinaryFrame data should have isRSV1() set to true ? If so, how does it handle situations when server compresses data selectively? 

Best Regards, 
Sara. 

---

* Java-WebSocket Version 1.5.2
* Java 1.8 
* Node.js uses ws websocket library

**Comment by marci4** [comment]
Hey 
Could you provide an example application for both java and node js?

I may have to recheck the specification but I thought it is only compressed or uncompressed. Mixing not allowed.

Best regards,
Marcel

**Comment by SaraHan774** [comment]
Node.js Server added below code for supporting permessage-deflate. `transformer: 'websockets'` indicates that the server will use `ws` module for websocket. https://github.com/primus/primus#websockets 

```javascript 
const primus = new Primus(createHttpServer(...), {
  transformer: 'websockets',
  compression: true, 
... 
```

<img width="919" alt="image" src="https://user-images.githubusercontent.com/42170276/126448914-3fdcab02-95ce-49fa-947f-9269d273e14c.png">

`compression : true` enables permessage deflate. 


In android, there is a WebSocketClient like below,

```kotlin
internal class WebSocketManager(private val wssUrl: URI) {
    companion object {
...
        // For receiving compressed data from the server
        private val perMessageDeflateDraft = Draft_6455(PerMessageDeflateExtension())
    }

    private inner class Client : WebSocketClient {
        constructor(wssUrl: URI) : super(wssUrl)
        constructor(wssUrl: URI, perMessageDeflateDraft: Draft_6455) : super(
            wssUrl,
            perMessageDeflateDraft
        )
...

// overrided functions from WebSocketClient ... 
    }
```

And when calling WebSocketManager.connect(), the client object is initialized like this 

```kotlin
            client = Client(wssUrl, perMessageDeflateDraft).apply {
                connectionLostTimeout = DEFAULT_CONNECTION_CHECK_INTERVAL
                addHeader(USER_AGENT_HEADER_NAME, getUserAgentString())
            }
            client!!.connect()
```

For the android part, I basically followed this library's wiki on PerMessageDeflateExtension.

**Comment by PhilipRoman** [comment]
FYI: you don't have to wait for new releases, you can always use https://oss.sonatype.org/content/repositories/snapshots/org/java-websocket/Java-WebSocket/1.5.3-SNAPSHOT/ or Jitpack (https://jitpack.io/#TooTallNate/Java-WebSocket/master-SNAPSHOT)

**Comment by SaraHan774** [comment]
Thank you for the answer! 

Best Regards, Sara.
