### ISSUE TITLE
connection lost if connection lost timeout is not used

### ISSUE THREAD

**Issue by mdeanda** [TooTallNate/Java-WebSocket#1169]
**Describe the bug**
If connection lost timeout is not set or set to 0 the connection is still closed by the following code:

```
			while ( !isClosing() && !isClosed() && ( readBytes = istream.read( rawbuffer ) ) != -1 ) {
				engine.decode( ByteBuffer.wrap( rawbuffer, 0, readBytes ) );
			}
			engine.eot();
```

It seems like the only way the heartbeat is sent is by actively running the connection lost timeout which also helps keep the connection alive.

**To Reproduce**
1. client = new ...
2. client.setConnectionLostTimeout(30);
3. client.connect
4. log the onClose event on the client.
5. to let connection close, remove step 2.

**Expected behavior**
The heartbeat should probably continue to run independently of the connection lost timeout to allow the connection to stay open.

**Environment(please complete the following information):**
 - Version used: 1.5.1
 - Java version: 15.0.1
 - Operating System and version: Arch linux
 - Endpoint Name and version: Camect NVR device, the following library works perfectly fine w/o connection issues: https://github.com/camect/camect-py/blob/master/camect/__init__.py

**Additional context**
I created a simple project using the camect library in python and it doesn't seem to have any connection issues on the same websocket server.

**Comment by marci4** [comment]
Hello @mdeanda,
could you provide a full example to reproduce the issue? Please include both server and client.

About what heartbeat are you talking? TCP or WebSocket or Connection Lost feature by this library?

Best regards,
Marcel

**Comment by mdeanda** [comment]
Here is some sample code I used to produce the issue:

```
package com.thedeanda;

import lombok.extern.slf4j.Slf4j;
import org.java_websocket.client.WebSocketClient;
import org.java_websocket.handshake.ServerHandshake;

import java.net.URI;
import java.util.Base64;
import java.util.Map;

@Slf4j
public class Main {
    public static void main(String[] args) throws Exception {
        new Main();
    }

    public Main() throws Exception {
        String user = "";
        String password = "";
        String wsUri = "wss://echo.websocket.org/";
        wsUri = "wss://11aa1111a.l.home.camect.com:443/api/event_ws";

        String auth = "Basic " + Base64.getEncoder().encodeToString(String.valueOf(user + ":" + password).getBytes());
        Map<String, String> headers = Map.<String, String>of("Authorization", auth);

        URI uri = URI.create(wsUri);
        MyWebSocketClient client = new MyWebSocketClient(uri, headers);

        log.warn("connect to {}", uri);
        client.connect();

        Thread thread = new Thread(() -> {
            while (!Thread.interrupted()) {
                try {
                    Thread.sleep(15000);
                } catch (InterruptedException e) {
                    return;
                }
                if (client.isOpen()) {
                    log.debug("sending ping");
                    client.sendPing();
                }
            }
        });
        thread.start();

        log.warn("connected");
        System.in.read();

        log.warn("closing connection");
        thread.interrupt();
        client.closeBlocking();
    }

    private static class MyWebSocketClient extends WebSocketClient {

        public MyWebSocketClient(URI uri, Map<String, String> httpHeaders) {
            super(uri, httpHeaders);
        }

        @Override
        public void onOpen(ServerHandshake handshakedata) {
            log.info("onOpen");
        }

        @Override
        public void onMessage(String message) {
            log.info("onMessage {}", message);
        }

        @Override
        public void onClose(int code, String reason, boolean remote) {
            log.info("onClose code: {}, reason: {}, remote: {}", code, reason, remote);
        }

        @Override
        public void onError(Exception ex) {
            log.info("onError", ex);
        }
    }
}
```

It seems to be specific to the server config (which I dont have access/control over) but my guess is that the server has a keep-alive time set to 45 seconds as it always disconnects in 45 seconds unless I add that "ping thread" or if I call `setConnectionLostTimeout` with any value less than 45.

Perhaps if there was a way to trigger the "sendPing" thread but not be tied to the connection lost timeout

**Comment by mdeanda** [comment]
just to clarify, this issue does not happen on any of the public test/echo servers i found so i know its specific to the configuration of this server. the python library referenced somehow handles the same situation without issues it seems.

on a separate note, i notice this library does not follow 301 redirects. i can investigate further and create a separate issue though.

**Comment by marci4** [comment]
To be honest right now I am thinking that the server endpoint requires some specific message and if this message is not recieved, the connection will simply be closed by the server.

Could you do me a favor and turn the LogLevel for this library to trace and create a log with the outputs of the lib and your log.info messages?
Just without the ping stuff you are doing.

Also a few things:
You can use connectBlocking();
You dont have to do sendPing() if you let setConnectionLostTimeout enabled (like you did in this example).

Best regards,
Marcel

**Comment by marci4** [comment]
Any update?

**Comment by mdeanda** [comment]
sorry for the delay. here are logs with trace enabled:

```
[TRACE] org.java_websocket.drafts.Draft_6455 - acceptHandshakeAsClient - Matching extension found: DefaultExtension
[TRACE] org.java_websocket.drafts.Draft_6455 - acceptHandshake - Matching protocol found: 
[TRACE] org.java_websocket.WebSocketImpl - open using draft: Draft_6455 extension: DefaultExtension protocol:  max frame size: 2147483647
[TRACE] org.java_websocket.AbstractWebSocket - Connection lost timer started
[INFO] com.thedeanda.Main - onOpen
[TRACE] org.java_websocket.AbstractWebSocket - Connection lost timer stopped
[INFO] com.thedeanda.Main - onClose code: 1006, reason: , remote: true
```

**Comment by marci4** [comment]
All good :).

Hmm thats the complete log.
Does not really make sense.

This can only really happen if the stream reached the end of the file.
Are you connecting over wifi and/or is there a firewall in between?
Have you tried updating the java version?

Sorry to be honest I dont have any real idea.

Best regards,
Marcel

**Comment by marci4** [comment]
No update. Closing issue
