### ISSUE TITLE
SHA1 Security Implications

### ISSUE THREAD

**Issue by tcolligan** [TooTallNate/Java-WebSocket#1178]
Our Veracode security software flagged the use of sha1 hashing for [Draft_6455.java](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/drafts/Draft_6455.java) on line 814

If possible it should be changed to SHA-256 or greater. Use of MD5 or SHA1 for any purpose is not recommended as collisions have been demonstrably generated for different inputs for these algorithms.

```  /**
   * Generate a final key from a input string
   *
   * @param in the input string
   * @return a final key
   */
  private String generateFinalKey(String in) {
    String seckey = in.trim();
    String acc = seckey + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
    MessageDigest sh1;
    try {
      sh1 = MessageDigest.getInstance("SHA1");
    } catch (NoSuchAlgorithmException e) {
      throw new IllegalStateException(e);
    }
    return Base64.encodeBytes(sh1.digest(acc.getBytes()));
  }```

**Comment by marci4** [comment]
Hey 
No this is not correct.
It is required by the specification.
Please check the specific section in the specification and the additional section which takes about collision.


From https://datatracker.ietf.org/doc/html/rfc6455#section-10.8
Use of SHA-1 by the WebSocket Handshake

   The WebSocket handshake described in this document doesn't depend on any security properties of SHA-1, such as collision resistance or  resistance to the second pre-image attack (as described in  [RFC4270]).

Best regards
Marcel
