### ISSUE TITLE
Example for manage server Multiple-url/topic

### ISSUE THREAD

**Issue by marcoberri** [TooTallNate/Java-WebSocket#1180]
hello, how can I manage the multi-topics based on the url for the server part? could you give an example? 

Thank you.

**Comment by marcoberri** [comment]
example: 
1 connect to server wss://test.com/A
2 connect with other client to  wss://test.com/B
2 from server send only message on path client wss://test.com/A and not broadcast to wss://test.com/A and wss://test.com/B

**Comment by PhilipRoman** [comment]
See #1071
