### ISSUE TITLE
decode in Base64

### ISSUE THREAD

**Issue by zinouzl** [TooTallNate/Java-WebSocket#1182]
Hello, 

Why you have removed the decode methods in Base64 class in latest versions, and what is the alternative that you suggest please ? 

Thank you

**Comment by PhilipRoman** [comment]
The methods were removed in 3b35a67fa. Since Java 1.8, Base64 encoding/decoding is a part of the standard library: https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html
