### ISSUE TITLE
Get Custom Header from WebSocket Server

### ISSUE THREAD

**Issue by marcoberri** [TooTallNate/Java-WebSocket#1184]
Hi, in this [example ](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/CustomHeaderClientExample.java)  is possible use custom header.

Is it possible to have an example of reading the headers on the web socket server side?

tnx

**Comment by marci4** [comment]
Check out https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/ServerRejectHandshakeExample.java
ClientHandshake is also provided as argument in onOpen.

Best regards,
Marcel

**Comment by marcoberri** [comment]
thanks always very kind!
