### ISSUE TITLE
How to catch Interrupted Exception or handle websocketserver close?

### ISSUE THREAD

**Issue by ange-black69** [TooTallNate/Java-WebSocket#1191]
Hello,
How can I catch when the WebSocketServer is closing and all of the workers shutdown?

**Comment by marci4** [comment]
Hey,
please provide an example application and steps to repeat.

Please also provide a debug log with loglevel trace.

Best regards,
Marcel

**Comment by ange-black69** [comment]
For some reason my websocketserver got shutdown when serving like 110 clients.
I can't seems to handle the error.
How can can I handle when the WebSocketServer got shutdown?*
It will help me for debugging.
Also i'm using log4j and the sfl4j wrapper.

**Comment by marci4** [comment]
Try catch around your OnMessage

Check OnError

**Comment by marci4** [comment]
Any update`?
