### ISSUE TITLE
bug on device 6.0 with version 1.5.2

### ISSUE THREAD

**Issue by tianshaokai** [TooTallNate/Java-WebSocket#1192]
No virtual method setEndpointIdentificationAlgorithm(Ljava/lang/String;)V in class Ljavax/net/ssl/SSLParameters; or its super classes (declaration of 'javax.net.ssl.SSLParameters' appears in /system/framework/core-libart.jar)

org.java_websocket.client.WebSocketClient.onSetSSLParameters(WebSocketClient.java:570)

**Comment by marci4** [comment]
https://github.com/TooTallNate/Java-WebSocket/wiki/No-such-method-error-setEndpointIdentificationAlgorithm

Best regards,
Marcel
