### ISSUE TITLE
SSLHandshakeException is caught when connect socket

### ISSUE THREAD

**Issue by 4Mi** [TooTallNate/Java-WebSocket#1195]
Precondition: 
1.wireless signal is instability
2.set ConnectionLostTimeout to 15 seconds
3.url: "wss://..."

Reproduce step:
1.onClose is called because pong message has not been received in time:
 onClose code: 1006 reason: The connection was closed because the other endpoint did not respond with a pong in time. For more information check: https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection remote: false

2.after 5 seconds, create a new socket with connect timeout parameter(5s) and call connect method as following:
    public MySocket(URI serverUri) {
        super(serverUri, new Draft_6455(), null, 5000);
    }
3.after calling socket.connect(), the onOpen is not called, but after 15 minutes, onError is called with following stack:
onError e: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x8f209c80: I/O error during system call, Connection timed out
 at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
 at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
 at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:629)
 at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:591)
 at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:407)
 at java.lang.Thread.run(Thread.java:818)
4.Also during the 15 minutes, i try closing the opening socket, but the onClose is not called, nothing happened
after calling socket.close().

Expected behavior
I think the onError should be called after 5 seconds after calling connect.

Debug log:

Environment:
 - Java version:1.8
 - Operating System and version:Android 6.0

**Comment by marci4** [comment]
Duplicates #1194
