### ISSUE TITLE
Shutting down websocket and starting it back up immediently? 

### ISSUE THREAD

**Issue by ddc-projects** [TooTallNate/Java-WebSocket#1197]
**Describe what you would like to know or do**
A clear and concise description of what the problem is.

When running my program with the web socket server it starts normally. If I stop the program and try to start it again I have to start and stop multiple times before the web socket server starts again. Is there a way to correctly shut down the web socket server so that it can be reliably restarted again?

**Comment by PhilipRoman** [comment]
https://github.com/TooTallNate/Java-WebSocket/wiki/Enable-SO_REUSEADDR

**Comment by ddc-projects** [comment]
Thank you for the clarification.
