### ISSUE TITLE
Is there some kind of callback function like Ack?

### ISSUE THREAD

**Issue by Chibilena** [TooTallNate/Java-WebSocket#1199]
Is it possible when sending as an example like socket.io
app.emitMessage(message, new Ack() {} for callback

**Comment by PhilipRoman** [comment]
If i understand correctly, you want something like this: https://socket.io/docs/v4/emitting-events/#acknowledgements ?
Socket.io is a higher level framework on top of websockets. This library doesn't provide acknowledgements. You would have to program that part yourself.
