### ISSUE TITLE
Closing wss connections might not work as expected

### ISSUE THREAD

**Issue by Davidiusdadi** [TooTallNate/Java-WebSocket#120]
Communication via wss in general works fine by now.

Unfortunately closing  wss connections is implemented in a very basic way:

``` java
public void close() throws IOException {
        sslEngine.closeOutbound();
        sslEngine.getSession().invalidate();
        if( sc.isOpen() )
            sc.write( wrap( emptybuffer ) );
        sc.close();
    }
```

It is possible that _sc.write_ will not send enough bytes ( i measured 37 bytes ) at once to complete the TLS close notify. Calling _sc.write_ in a loop might block the current thread indefinitely so that is not an option.

**As a result your peer host might complain about an unexpectedly closed connection after _HE_ initiated the websocket close handshake.**

It will take me a few days to implement the close handshaking the nonblocking way.

Please excuse my humble English.

**Comment by marci4** [comment]
Code changed with #488.

Closing issue!
Greetings
marci4
