### ISSUE TITLE
class WebSocketServer, run() method, int iShutdownCount = 5;

### ISSUE THREAD

**Issue by NaMa5Te** [TooTallNate/Java-WebSocket#1202]
My websockerserver is not accepting any reqs (accept/read) after some 300-400 connections sometimes and I don't get any logs as well, so I looked into the code(using lib version 1.4.1).

I was trying to understand the logic of websocketserver thread, other codes I was able to understand, can you help me understand the reason behind `int iShutdownCount = 5;`

`public void run() {
		if (!doEnsureSingleThread()) {
			return;
		}
		if (!doSetupSelectorAndServerThread()) {
			return;
		}
		try {
			int iShutdownCount = 5;
			int selectTimeout = 0;`

**Comment by marci4** [comment]
This was added with #620

**Comment by marci4** [comment]
Closing this question as answered.
