### ISSUE TITLE
Ask for advice on communication between two Android devices

### ISSUE THREAD

**Issue by cl-6666** [TooTallNate/Java-WebSocket#1206]
Hello, I have encountered such a problem. Two Android devices communicate, one as a server and the other as a client. When the client is disconnected, the server cannot monitor it. What do I need to do here? Is it possible to monitor whether the client is connected and disconnected in real time?

**Comment by cl-6666** [comment]
![image](https://user-images.githubusercontent.com/51937265/147182695-f94ec84b-8c6c-459f-8087-a88ffef9bf28.png)
The current client has been disconnected for a long time, and as a result, the server can still print out the connected device. Theoretically, it should be 0.

**Comment by PhilipRoman** [comment]
Closing as this is very old issue, if you still need help with this, provide a small program which shows the issue.
