### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.java_websocket.server.WebSocketServer

### ISSUE THREAD

**Issue by Novaytre** [TooTallNate/Java-WebSocket#1208]
Hi, I get a different error when I start my Maven project as a dependency when I start it. I will use it for a game but when I start the Game Server I get an error.

![image](https://user-images.githubusercontent.com/66137132/147408555-7596117e-8607-4499-a3f6-eeae7f5f2413.png)
![image](https://user-images.githubusercontent.com/66137132/147408563-b2d13227-346c-486d-bb30-9ac83a31cc56.png)

**Comment by marci4** [comment]
Hey,
I am not an expert for maven, but could it be that you are not including the lib in your resulting jar?

I had to use this plugin for my projects to get a jar with all dependencies https://maven.apache.org/plugins/maven-shade-plugin/

Best regards,
Marcel

**Comment by Novaytre** [comment]
I solved the case using maven shade
