### ISSUE TITLE
WebSocket Stopped Working on Android 5 API21

### ISSUE THREAD

**Issue by ehsanbayat** [TooTallNate/Java-WebSocket#1209]
FATAL EXCEPTION: WebSocketConnectReadThread-280
    java.lang.NoSuchMethodError: No virtual method setEndpointIdentificationAlgorithm(Ljava/lang/String;)V in class Ljavax/net/ssl/SSLParameters; or its super classes (declaration of 'javax.net.ssl.SSLParameters' appears in /system/framework/core-libart.jar)
    
 I did All configs as in medium explained
https://medium.com/codex/android-tutorial-part-2-using-java-websocket-with-kotlin-dd3105bd3eed

**Comment by ehsanbayat** [comment]
I did All configs as in medium explained
https://medium.com/codex/android-tutorial-part-2-using-java-websocket-with-kotlin-dd3105bd3eed

**Comment by marci4** [comment]
See https://github.com/TooTallNate/Java-WebSocket/wiki/No-such-method-error-setEndpointIdentificationAlgorithm

**Comment by ehsanbayat** [comment]
exactly I found it yesterday and problem solved 
thanks anyway for your reply
