### ISSUE TITLE
My Game Server is interrupted when I create and discard the plugin.

### ISSUE THREAD

**Issue by Novaytre** [TooTallNate/Java-WebSocket#1210]
When I start my Game Server without the add-on, I can enter the game without any problems, but when I add my add-on, I get the message 'server started successfully' and nothing else loads. I can't even type the `stop` command, which is the command of my game server, why?

**Note : I know the errors I got when we added the plugin, I just paused them to fix the websocket**

With the plugin attached: ![image](https://user-images.githubusercontent.com/66137132/147495751-c3fdf5bc-a8b6-47b9-87d1-1112cc2b86f7.png)

Without the plugin: 
![image](https://user-images.githubusercontent.com/66137132/147495862-26c31087-9be6-44f0-a50b-4fe188827925.png)

**Comment by marci4** [comment]
Please provide an example application and steps to repeat

**Comment by Novaytre** [comment]
> Please provide an example application and steps to repeat

I'm sorry but I don't understand

**Comment by Novaytre** [comment]
I have a game emulator. We activate the game by starting this emulator, and when I start this emulator and add the plugin I wrote to the emulator, I cannot log in to the game and CMD seems to freeze, nothing is done.

> > Please provide an example application and steps to repeat
> 
> I'm sorry but I don't understand

**Comment by PhilipRoman** [comment]
This project is just a java websocket library, we have no idea what your game emulator or plugin does, so we cannot help with that. We are not a general purpose tech support team :)

From your description I would guess you are using the blocking method `WebSocketServer.run`, instead of `WebSocketServer.start`. See the documentation of the methods and make sure you are not blocking your main thread.

**Comment by Novaytre** [comment]
> This project is just a java websocket library, we have no idea what your game emulator or plugin does, so we cannot help with that. We are not a general purpose tech support team :)
> 
> From your description I would guess you are using the blocking method `WebSocketServer.run`, instead of `WebSocketServer.start`. See the documentation of the methods and make sure you are not blocking your main thread.

WebSocketServer.run(); I was using and it was WebSocketServer.start(); I ran it as and now my problem is solved

Thanks for everything

**Comment by PhilipRoman** [comment]
Closing as solved. For the record, looks like the same issue as in #1047
