### ISSUE TITLE
Any idea to increase maximun size string received?

### ISSUE THREAD

**Issue by Tengufb** [TooTallNate/Java-WebSocket#1215]
i am using it to receibe large data from server, but string get truncated on receive message. Any way to increase size of message in websocketclient ?

**Comment by marci4** [comment]
Hey,
What limit do you hit?

Could you provide a small example application?

Best regards,
Marcel

**Comment by Tengufb** [comment]
in onmessage  when i try to get string given by server,... this get cuted...
here is a sample of incoming message, if you see last chars, you will see what i mean.
lenght of string is 4700 more or less
"},{"o":"NzzYilzMkIT0YQzi","r":0.00005941,"a":5.4600032,"v":0.00032438,"t":1,"d":1643362104470,"s":"undefined"},{"o":"MIcZJE2zNZ3GNNDQ","r":0.00005941,"a":7.2534388,"v":0.00043093,"t":1,"d":1643363092538,"s":"undefined"},{"o":"DIZQjNjNYMxMIwjZ","r":0.00005941,"a":5.5323107,"v":0.00032867,"t":1,"d":1643365942202,"s":"undefined"},{"o":"ZDNh2mxAx2DY12Gi","r":0.00005941,"a":6.1179833,"v":0.00036347,"t":1,"d":1643365979522,"s":"undefined"}],"asks":[{"o":"DQUwgZWmTNyyDlhN","r":0.0000601,"a":3123,"v":0.1876923,"t":0,"d":1643383761477,"s":"undefined"},{"o":"iNNmNMmDTizTNZVT","r":0.00006053,"a":156.84511,"v":0.00949383,"t":0,"d":1643383762191,"s":"undefined"},{"o":"OgMTlmkWZZMJZwcE","r":0.00006175,"a":1,"v":0.00006175,"t":0,"d":1643343279075,"s":"undefined"},{"o":"GzE44N2MOGyUQO5k","r":0.00006196,"a":11,"v":0.00068156,"t":0,"d":1643341997868,"s":"undefined"},{"o":"NUz2NxWIGkMMTJ0D","r":0.00006272,"a":5000,"v":0.3136,"t":0,"d":1643383650371,"s":"undefined"},{"o":"2wlMkkIkINmhwNOF","r":0.00006274,"a":2.02789939,"v":0.00012723,"t":0,"d":1643301766458,"s":"undefined"},{"o":"OZzgM5IOYihMRGNN","r":0.00006299,"a":22,"v":0.00138578,"t":0,"d":1643342011795,"s":"undefined"},{"o":"ONiiNYFhYjTJgMiR","r":0.000063,"a":11.70558438,"v":0.00073745,"t":0,"d":1643295424066,"s":"undefined"},{"o":"JY1TYUgMhZlU1NZG","r":0.0000635,"a":8,"v":0.000508,"t":0,"d":1643316784568,"s":"undefined"},{"o":"VDDTiZNl0MTNwQmN","r":0.00006363,"a":4.71475719,"v":0.0003,"t":0,"d":1643339599976,"s":"undefined"},{"o":"w5i2ZhDOW5WlYYzN","r":0.00006394,"a":11,"v":0.00070334,"t":0,"d":1643342041165,"s":"undefined"},{"o":"JQ4ZDQOTz2RTzNiY","r":0.000064,"a":35.71056346,"v":0.00228548,"t":0,"d":1642899029211,"s":"undefined"},{"o":"UmlYymUMO1DkOYUM","r":0.00006415,"a":25.32012028,"v":0.00162429,"t":0,"d":1643334735671,"s":"undefined"},{"o":"mMdkRjzZTMYNjyEy","r":0.00006448,"a":1.4210357,"v":0.00009163,"t":0,"d":1642804096924,"s":"undefined"},{"o":"VYzc5jkFTgYDzmOE","r":0.00006491,"a":11,"v":0.00071401,"t":0,"d":1643342051517,"s":"undefined"},{"o":"ZAzIQDjNNGhlwMOT","r":0.000065,"a":67,"v":0.004355,"t":0,"d":1643292969510,"s":"undefined"},{"o":"GNENU1TlIVRIFkG3","r":0.000065,"a":4.00368158,"v":0.00026024,"t":0,"d":1643339542896,"s":"undefined"},{"o":"DZEDUZM0O3MAWZTA","r":0.00006

**Comment by marci4** [comment]
Please provide an example application
