### ISSUE TITLE
Issue in one WebsocketWorker brings down everything.

### ISSUE THREAD

**Issue by Hellgin** [TooTallNate/Java-WebSocket#1218]
Hi, 

I have a server app that has alot of websocket connections from alot of clients, every once in a while i get this on the console
[org.java_websocket.server.WebSocketServer] Uncaught exception in thread WebSocketWorker-22: {}

the 22 could of course be any other number.

When this happens I stop receiving data on ALL websocket connections from ALL connected clients, and at the same time no new connections can be made, requiring me to restart the entire application. Does anyone have an idea what's going on, how to fix it or just how to gather more information?

I'm also uncertain weather there is perhaps only one we socket worker to begin with that handles all connections.

Thanks!

**Comment by marci4** [comment]
Hey,

Please provide StR.
Otherwise there is no way to fix any issue.

Best regards,
Marcel
