### ISSUE TITLE
How to have a webSocket(in javascript web) connect to a websocket server(in java) using wss

### ISSUE THREAD

**Issue by zaze06** [TooTallNate/Java-WebSocket#1219]
**Describe what you would like to know or do**
So I want to connect to the server using WSS because HTTPS won't allow WS connections

**Describe the solution you'd considered**
none I don't know how to get this fixed

**Additional context**
i don't think any other context is needed more then i have a WebSocket server in java and a WebSocket client in web JavaScript

**Comment by zaze06** [comment]
i get this from FireFox `Firefox can’t establish a connection to the server at wss://<my public ip>:8080/.`

**Comment by marci4** [comment]
One problem could be a self signed certificate.
You can accept them e.g. by opening https://<my public ip>:8080.

Otherwise you dont have to do something special.

Best regards,
Marcel

**Comment by marci4** [comment]
You can trust a self signed certificate in your browser by opening a connection via https.
Or you could add the certificate to your trusted certificates.

After the certificate is trusted you have to connect with was://

**Comment by zaze06** [comment]
ok, so after i have done that can anyone connect to the wss or do that have to do it too?

**Comment by PhilipRoman** [comment]
If it is a self-signed certificate, then no. If you want others to be able to connect without manually marking your certificate as trusted, then you need a certificate signed by another trusted authority. LetsEncrypt is a popular one and is easy to install: https://letsencrypt.org/
