### ISSUE TITLE
Can I write date into websocketclient outputstream directly

### ISSUE THREAD

**Issue by steeveen** [TooTallNate/Java-WebSocket#1220]
**Describe what you would like to know or do**
Hello. I have a Recorder Object which need to connect to a outputStream. I need to send the data from outputStream by websocket.

**Describe the solution you'd considered**
Now my solution is like this:
```
ByteArrayOutputStream baos=new ByteArrayOutputStream();
FFmpegFrameRecorder recorder=new FFmpegFrameRecorder(baos,2);
recorder.record(xxxx);
baos.toByteArray();
webSocketClient.send(baos.toByteArray());
```
It works. But I must care about when the baos has data.
I am wondering if there is a solution that allows me to directly connect the stream to the websocket
I have tried this:
```
FFmpegFrameRecorder recorder=new FFmpegFrameRecorder(webSocketClient.getSocket().getOutputStream(),2);
```
But the problem runs into fails. Can anyone give me some advice?
Looking forward to your replays.

**Additional context**
No other context

**Comment by PhilipRoman** [comment]
It sounds like you could create your own OutputStream subclass which forwards to WebSocket:
```java
public class WebSocketOutputStream extends OutputStream {
	private final WebSocket ws;

	public WebSocketOutputStream(WebSocket ws) {
		this.ws = ws;
	}

	@Override
	public void write(int b) {
		ws.send(new byte[]{(byte)b});
	}

	@Override
	public void write(byte[] b) {
		ws.send(b);
	}

	@Override
	public void write(byte[] b, int off, int len) {
		ws.send(ByteBuffer.wrap(b, off, len));
	}

	@Override
	public void close() {
		/* depending on your use case possibly close socket */
	}
}
```

Then you can simply pass it to FFmpeg:
```java
FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(new WebSocketOutputStream(webSocketClient), 2);
```

**Comment by steeveen** [comment]
Thanks. Sounds Good! I'll have a try.
By the way. Is there any problem in my code like:
```
FFmpegFrameRecorder recorder=new FFmpegFrameRecorder(webSocketClient.getSocket().getOutputStream(),2);
```

**Comment by PhilipRoman** [comment]
The websocket protocol wraps all messages using its own encoding scheme. Your code writes directly to the underlying TCP socket. Since the ffmpeg output is not valid websocket data (as specified in [RFC 6455](https://datatracker.ietf.org/doc/html/rfc6455#section-5)), the other endpoint will get errors when trying to decode the websocket frames.

**Comment by steeveen** [comment]
It works well. Thanks
