### ISSUE TITLE
Socket Connection

### ISSUE THREAD

**Issue by SumitSharmaNagwan** [TooTallNate/Java-WebSocket#1222]
onClose:  1002    Invalid status code received: 301 Status line: HTTP/1.1 301 Moved Permanently  false
device android 10

**Comment by marci4** [comment]
Hello @SumitSharmaNagwan 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4
