### ISSUE TITLE
Why are a large number of connections disconnected every hour

### ISSUE THREAD

**Issue by emirbobo** [TooTallNate/Java-WebSocket#1225]
**Describe what you would like to know or do**

The maximum number of connections is 640. If it exceeds 640, a large number of connections will be disconnected

**Describe the solution you'd considered**
When I increase the number of threads to 50, I still have this problem. It is deployed on an independent server without any other services

how to solve this， plz

**Comment by emirbobo** [comment]
The server closes the log and prompts 1006 code. The nginx log shows upstream time out (110: unknown error) while connecting to upstream ，we have no through cloudflare

**Comment by marci4** [comment]
No clear information.

Closing issue
