### ISSUE TITLE
sending data from different file to websocket

### ISSUE THREAD

**Issue by explid** [TooTallNate/Java-WebSocket#1231]
How do I send data in a different file with Websocket?

For example :

ChatServer.java
// WebsocketServer

SendChatMessage.java
// here I need to send message to websocket.

**Comment by PhilipRoman** [comment]
Use the `WebSocket.send` method as usual?: https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.2/org/java_websocket/WebSocket.html#send-java.lang.String-

Im not sure what your problem is so I cant help.

**Comment by explid** [comment]
> Use the `WebSocket.send` method as usual?: https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.2/org/java_websocket/WebSocket.html#send-java.lang.String-
> 
> Im not sure what your problem is so I cant help.

For example I have a websocket server in ChatServer.java. I'm making a plugin for a game and I want to send a message to my javascript side when I type a command in that plugin.

![image](https://user-images.githubusercontent.com/66137132/161373106-b843255b-3f84-4021-95c0-302853b39626.png)

The area shown in red is my websocket server, the area shown in green is the part that runs when my user writes a command. I want to send data to the javascript side when my user writes a command.

**Comment by PhilipRoman** [comment]
You need a way to know which WebSocket object corresponds to your target user. This can be accomplished in several ways: passing it as parameter, storing the WebSocket objects in a `Map<Object, WebSocket>`, etc.

I don't know what API you are working with so I can't help with that.

After you have the WebSocket object, just call its `send()` method.

This question is about general Java knowledge and is off-topic here.

**Comment by explid** [comment]
> You need a way to know which WebSocket object corresponds to your target user. This can be accomplished in several ways: passing it as parameter, storing the WebSocket objects in a `Map<Object, WebSocket>`, etc.
> 
> I don't know what API you are working with so I can't help with that.
> 
> After you have the WebSocket object, just call its `send()` method.
> 
> This question is about general Java knowledge and is off-topic here.

Thanks for your help, I was asking because I have little knowledge of java. I guess I should do some research. I'm using the Habbo Retro API. really thanks for your help
