### ISSUE TITLE
Websocket Server Unidirectional packet loss

### ISSUE THREAD

**Issue by Ruokwok** [TooTallNate/Java-WebSocket#1233]
Hello, I used this library to build a websocket server to communicate with the browser. There was no problem in the local and LAN tests, but when I deployed it to the public network server, there was a serious packet loss problem.
After the connection is established, the data sent by the browser to the server is normally received, but the data sent by the server to the browser will probably be lost. Even if it is received, there will be a high delay, and the packet loss is one-way. Then the server will throw websocketnotconnectedexception.
I confirm that this is not a network or bandwidth problem, because other websocket server software on the same host is working normally

Here are some codes
`......

public class WSServer extends WebSocketServer {

    public WSServer(int port) {
        super(new InetSocketAddress(port));
        setConnectionLostTimeout(10000);
    }

    @Override
    public void onOpen(WebSocket webSocket, ClientHandshake clientHandshake) {
    }

    @Override
    public void onClose(WebSocket webSocket, int i, String s, boolean b) {
        
    }

    @Override
    public void onMessage(WebSocket webSocket, String s) {
        try {
            String[] split = s.split("@");
            int id = Integer.parseInt(split[0]);
            String key;
            String m = split[1];
            if (id == 0) {
                key = Math.md5(PanelConfig.password);
                String decrypt = Aes256.decrypt(m, key);
                AdminJson json = new Gson().fromJson(decrypt, AdminJson.class);
                new Thread(() -> {
                    try {
                        Handler.execute(webSocket, json);
                    } catch (WebsocketNotConnectedException e) {
                        e.printStackTrace();
                    }
                }).start();
            } else {
                key = Math.md5(Daemon.getInstance().getInstanceById(id).getTags("password"));
                String decrypt = Aes256.decrypt(m, key);
                Json json = new Gson().fromJson(decrypt, Json.class);
                json.id = id;
                Instance instance = Daemon.getInstance().getInstanceById(id);
                new Thread(() -> Handler.execute(instance, webSocket, json)).start();
            }
        } catch (BadPaddingException e) {
            webSocket.send(new LoginJson(false).toString());
        } catch (Exception e) {
            webSocket.send(new LoginJson(false).toString());
        }
    }

    @Override
    public void onMessage(WebSocket webSocket, ByteBuffer message) {

    }

    @Override
    public void onError(WebSocket webSocket, Exception e) {

    }

    @Override
    public void onStart() {

    }
}
`

In the above code, the websocket object will be passed to the `Handler.execute(WebSocket ws, Json json);` and sending data to the browser is also carried out in this method. This method is blocking, but it won't last long.

I'm not a native speaker of English. I hope my expression is clear enough. Thank you

**Comment by PhilipRoman** [comment]
Hi! Thanks for your report.
Can you enable logging with timestamps and see when exactly the messages are sent? (Add any slf4j backend to classpath and set log level to TRACE. slf4j-simple is the easiest to set up: https://mvnrepository.com/artifact/org.slf4j/slf4j-simple/1.7.25)

What version of library are you using?

**Comment by Ruokwok** [comment]
[server.log](https://github.com/TooTallNate/Java-WebSocket/files/8442087/server.log)

**Comment by Ruokwok** [comment]
Hello, here are some logs (including logs of other modules). I use version 1.5.2

**Comment by Ruokwok** [comment]
After testing, I found that the delay of each time the browser receives data is increasing, from thousands of milliseconds to hundreds of thousands of milliseconds, until it times out. The timing starts from the execution of the `websocket.send()` method, so it should not be the delay caused by my business code.

**Comment by Ruokwok** [comment]
Hello, I did some new tests and found that the problem is not only in the public network environment, but also in the local connection on CentOS. There is no problem with the local connection on Ubuntu, and there is no problem with the public network environment on Windows system. I now suspect that this is not by org java_websocket, I'm sorry! Thank you for your help. I'll come back and close this iusse after I find out everything.
 Thank you.

**Comment by marci4** [comment]
Hey
Does the observed behaviour change when you enable TCP_NoDelay? (https://github.com/TooTallNate/Java-WebSocket/wiki/Enable TCP_NODELAY)

Thank you very much for investigating!

Best regards
Marcel

**Comment by Ruokwok** [comment]
Hello, I have found the problem. Before sending the data, I carried out aes256 encryption operation. That's the problem. Thanks for your help
