### ISSUE TITLE
Websocket and http connection on same port and same java application

### ISSUE THREAD

**Issue by abhishekM0106** [TooTallNate/Java-WebSocket#1234]
**Describe what you would like to know or do**
Hi, i am creating a websocket Java application for which i am using the library provided by you. Apart from the websocket connection, I also want a REST web service endpoint for health check of application, which when hit will return status code 200. The problem i am facing is that i am not able to accept both, websocket and http requests, on same port. I would like to know if there is some method which might help me to deal with this case.

**Describe the solution you'd considered**
A possible solution that came to my mind was to pass same server instance to both websocket and http server while initialising them. This is possible in javascript websocket library where websocket server accepts an instance of httpserver as a parameter. 

Sample code for javascript websocket:
```
var server = http.createServer(function(request, response) {
    console.log((new Date()) + ' Received request for ' + request.url);
    response.writeHead(404);
    response.end();
});
server.listen(8080, function() {
    console.log((new Date()) + ' Server is listening on port 8080');
});

wsServer = new WebSocketServer({
    httpServer: server,
});
```
But i am not sure if a similar feature is available for java. 
Reference: https://github.com/theturtle32/WebSocket-Node

Java Websocket Handler Code: 
```
public class JavaWebsocketHandler extends WebSocketServer {
    ObjectMapper objectMapper = new ObjectMapper();

    public JavaWebsocketHandler(int port) {
        super(new InetSocketAddress(port));
    }

    public JavaWebsocketHandler(InetSocketAddress address) {
        super(address);
    }

    @Override
    public void onOpen(WebSocket conn, ClientHandshake handshake) {
    }

    @Override
    public void onClose(WebSocket conn, int code, String reason, boolean remote) {
        System.out.println(conn + " Disconnected!");
    }

    @Override
    public void onMessage(WebSocket conn, String message) {
        
    }

    @Override
    public void onError(WebSocket conn, Exception ex) {

    }

    @Override
    public void onStart() {

    }

    public static void main(String[] args) throws Exception {
            int port = 8080; 
            JavaWebsocketHandler s = new JavaWebsocketHandler(port);
            s.setTcpNoDelay( true );
            s.start();
            System.out.println("BroadcastClientApplication started on port: " + s.getPort());
        }
}
```

**Comment by marci4** [comment]
We do not support having a http server and a ws server on the same port.

**Comment by PhilipRoman** [comment]
The simplest way would probably be to tunnel websocket requests to a different port using nginx (proxy_pass).
