### ISSUE TITLE
Traffic is not displayed in charles and proxymen

### ISSUE THREAD

**Issue by elizavetamikhailova** [TooTallNate/Java-WebSocket#1235]
Hello! 

When using Java-WebSocket library in Charles and Proxyman, the hosts used by the device are not displayed. At the same time, the same host is used by colleagues in another application with the scarlet library, and they can view traffic in various sniffers.
My question is: **is there some specific protocol/technology used in this library that sniffers like Charles and Postman don't support?**

How I use the library:

<img width="772" alt="Снимок экрана 2022-04-08 в 09 45 58" src="https://user-images.githubusercontent.com/44157370/162379758-e6371d98-6307-466b-8d62-1700b6befff1.png">

WebSocketWrapper extends WebSocketClient

<img width="761" alt="Снимок экрана 2022-04-08 в 09 46 20" src="https://user-images.githubusercontent.com/44157370/162379805-d5848880-686d-4753-acc9-3ce3d9bc617f.png">

<img width="924" alt="Снимок экрана 2022-04-08 в 09 46 30" src="https://user-images.githubusercontent.com/44157370/162379817-7ed5dfcd-a82e-46cf-a99e-949706c517e9.png">

**Comment by marci4** [comment]
Hey,
No we are not doing anything special.

Best regards,
Marcel

**Comment by elizavetamikhailova** [comment]
Thanks for your reply!
What sniffer are you using? Do you use it at all?

**Comment by marci4** [comment]
I dont use any at all.

**Comment by PhilipRoman** [comment]
I usually debug websockets with Wireshark, haven't got any problems with this library.
