### ISSUE TITLE
Method waiting forever on closeBlocking() on reconnect.

### ISSUE THREAD

**Issue by srilakshmikanthanp** [TooTallNate/Java-WebSocket#1236]
Hai, Once the server closes the connection then I try to reconnect but unfortunately the method blocks forever on  the `closeBlocking()`, Here is the sample code,

On Close

~~~java
@Override
public void onClose(int code, String reason, boolean remote) {
    this.logger.info("Connection Closed : " + code + " " + reason + " by server " + remote);
    this.trytoreconnect();
    this.hFetch(Fetcher.getInstance().getLastData());
    this.notifyAll();
}
~~~

try to reconnect

~~~java
private void trytoreconnect() {
    Runnable runnable = () -> {
        try {
            WSocket.this.logger.info("Reconnecting");
            while (!this.reconnectBlocking()) {
                Thread.sleep(1000);
                WSocket.this.logger.info("Reconnecting");
            }
            WSocket.this.logger.info("Reconnected");
        } catch (InterruptedException e) {
             WSocket.this.logger.severe(e.getMessage());
        }
    };

    var thread = new Thread(runnable, "Reconnect Thread");
    thread.start();
    while(thread.isAlive()) {
        try { thread.join(); } catch (InterruptedException e) {
            this.logger.severe(e.getMessage());
        }
    }
}
~~~

The line blocking is https://github.com/TooTallNate/Java-WebSocket/blob/5d840995e710d8075885911070dcc2ee9c27134a/src/main/java/org/java_websocket/client/WebSocketClient.java#L343

The message on close

`INFO: Connection Closed : 1006 <no reason>  by server true`

**Comment by zhujinsheng** [comment]
I also encountered this ANR problem , can you tell me how to solve it?

**Comment by neoyxm** [comment]
I met the same on calling **WebSocketClient.reconnect()**  when the network was unstable.

The reconnect function was blocked by reset() -> closeBlocking();

Here is backtrace :

```
"OnScheduleThread" prio=5 tid=119 Waiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x13bc0218 self=0xa7e0ca00
  | sysTid=12684 nice=0 cgrp=default sched=0/0 handle=0x98de31c0
  | state=S schedstat=( 420058886 166418548 3340 ) utm=17 stm=24 core=7 HZ=100
  | stack=0x98ce0000-0x98ce2000 stackSize=1040KB
  | held mutexes=
  at sun.misc.Unsafe.park(Native method)
  - waiting on an unknown object
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:874)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1044)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1366)
  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
  at s.g.f.b.closeBlocking(WebSocketClient.java:2)
  at s.g.f.b.reset(WebSocketClient.java:3)
  at s.g.f.b.reconnect(WebSocketClient.java:1)
```

**Comment by zhujinsheng** [comment]
When it comes to reconnecting function calls, using sub-threads will not block the main thread

**Comment by zhujinsheng** [comment]
When it comes to reconnecting function calls, using sub-threads will not block the main thread

**Comment by zhujinsheng** [comment]
When it comes to reconnecting function calls, using sub-threads will not block the main thread

**Comment by neoyxm** [comment]
@zhujinsheng 
> When it comes to reconnecting function calls, using sub-threads will not block the main thread

Yeah, this can help to workaround the ANR issue, but how to exit the blocked sub-thread elegantly?

**Comment by YunYe-Pu** [comment]
I met exactly the same problem. The solution I took is to interrupt() the sub-thread if it blocks for a long time, something like:
```java
Thread th = new Thread(() -> this.reconnect());
th.start();
try { th.join(5000); } catch (InterruptedException e) { }
if (th.isAlive()) th.interrupt();
```
Besides, it does not seem appropriate for me to call a blocking method(`closeBlocking()`) inside `reconnect()` which is documented 'does not block'... Hope this could be fixed in some future release.

**Comment by marci4** [comment]
Anyone got clear StR?

**Comment by marci4** [comment]
No StR
