### ISSUE TITLE
Preview build using loom

### ISSUE THREAD

**Issue by StevenCurran** [TooTallNate/Java-WebSocket#1240]
Hey all, I was looking into this library recently, and have also been using some early builds of loom from open jdk. Do you have any automated performance tests / benchmarks that I am missing? I forked down this repo, and built it against a loom jdk. I also change the thread creation factories to that of virtual threads, and I was interested in how this would affect CPU usage / throughput. 

Are there any plans for the future to migrate to loom when it becomes GA, or what is the strategy for that? 

Many thanks.

**Comment by PhilipRoman** [comment]
This library maintains compatibility with JDK 1.7, so it's unlikely that we can migrate to Loom.

If project Loom provides significant performance/memory benefits, we could potentially maintain a patch on a separate branch which enables Loom support (depending on how much effort it requires) for those who want to build it themselves.
