### ISSUE TITLE
OOM Exception

### ISSUE THREAD

**Issue by Kodak1234** [TooTallNate/Java-WebSocket#1241]
**Describe the bug**
Failed to allocate byte buffer when receiving a large file.

**To Reproduce**
1. Transfers a very large data from one device to another.

**Expected behavior**
Should have a way to write received data to file instead of holding in memory

**Environment(please complete the following information):**
 - Version used: 1.5.3
 - Java version: kotlin 1.6.10
 - Operating System and version: Android

**Comment by Kodak1234** [comment]
Please any recommendation on how to avoid OOM exception?

**Comment by PhilipRoman** [comment]
This library does not currently have a streaming API.
Websockets are primarily used to allow connections from browsers and the javascript websocket API does not have a way to send messages larger than RAM anyway.

I would recommend splitting the file and sending over several messages.

**Comment by marci4** [comment]
No clear StR and websockets in general are not designed to be used as file streams.

Closing issue
