### ISSUE TITLE
Executable jar

### ISSUE THREAD

**Issue by gancarani** [TooTallNate/Java-WebSocket#1243]
I’ve successfully creaste a Java application that is working using the websocket library. Everything works with IntelliJ, after I buliod with maven an executable jar that I want to run from a shell, I get a no class found exception for the websocket server. It seems that the jar does not have all the library needed, is there a way to handle this?

**Comment by marci4** [comment]
Hey,

I think you are just missing the library in your path.
You may want to take a look at https://maven.apache.org/plugins/maven-shade-plugin/.

This is however nothing related to the library itself.

Best regards,
Marcel
