### ISSUE TITLE
 java.net.Socket cannot be cast to javax.net.ssl.SSLSocket 

### ISSUE THREAD

**Issue by KimiChiu** [TooTallNate/Java-WebSocket#1244]
**Describe the bug**
I'm using this workaround to fix connection issues on devices below API 24.
https://github.com/TooTallNate/Java-WebSocket/wiki/No-such-method-error-setEndpointIdentificationAlgorithm

But I have a Firebase report showing this exception.
` java.net.Socket cannot be cast to javax.net.ssl.SSLSocket `

Is it possible to use a `java.net.Socket` rather than `javax.net.ssl.SSLSocket` while using `wss` protocol?
The device status is 100% rooted. Is it related?

Should I check the return value of `connectBlocking` before verifying hostname?

**To Reproduce**
Can't be reproduced on our side.

**Example application to reproduce the issue**
https://github.com/TooTallNate/Java-WebSocket/wiki/Verify-hostname-after-handshake

**Expected behavior**
Connect the server without exception.

**Debug log**
```
Fatal Exception: java.lang.ClassCastException: java.net.Socket cannot be cast to javax.net.ssl.SSLSocket
       at com.kimieno.sync.remote.SyncSocket.connect(SyncSocket.java:178)
       at com.kimieno.sync.handler.SyncClientHelper$3.run(SyncClientHelper.java:530)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Environment(please complete the following information):**
 - Version used: 1.5.3
 - Java version: Open JDK 11
 - Operating System and version: Android API 23

**Comment by marci4** [comment]
Hey,

I'm not doing anything with Android. 
I would expect the socket to be a SSLSocket, but with Androids SSL implementation I guess you cannot be sure.

Not sure how I can help you there. Maybe just try to catch this case.

Best regards,
Marcel
