### ISSUE TITLE
Can clients broadcast to all other connections?

### ISSUE THREAD

**Issue by trippy22** [TooTallNate/Java-WebSocket#1245]
If I have a WebSocketClient, can it broadcast to all other connected clients (assume the server is hosted in a third party location and you don't necessarily have access to the WebSocketServer object)

**Comment by PhilipRoman** [comment]
No, there is no such functionality in the WebSocket specification. This would be a major vulnerability if it were possible. Broadcasting to all clients can only be done from the server using one of the `broadcast()` methods of `WebSocketServer`.

Obviously some applications (like chat servers) using the WebSocket protocol can define their own way to broadcast messages from clients but that depends on the server side to support it.
