### ISSUE TITLE
How to receive response as client

### ISSUE THREAD

**Issue by trippy22** [TooTallNate/Java-WebSocket#1246]
Hi, if I have a WebSocketClient and sent a message to the server, how can I wait for a response from the server programmatically?

**Comment by PhilipRoman** [comment]
When a message arrives from the server, the `onMessage` method will be called in your WebSocketClient. In this method you can process the response.
Here is an example of how to use WebSocketClient: https://github.com/TooTallNate/Java-WebSocket/blob/bdf928b487b8c643868f410300e66de3df9c51d2/src/main/example/ExampleClient.java

**Comment by trippy22** [comment]
Is there a different way to catch the message which isn't event based, something like:

```
ExampleClient c = new ExampleClient(new URI( "ws://localhost:8887"));
c.connect();
c.send("Hello, World!");
String response = c.getResponse();
```

**Comment by PhilipRoman** [comment]
This is the simplest way to do this:
In your event handler, push to a BlockingQueue:
```java
BlockingQueue<String> messageQueue = new ArrayBlockingQueue<>(100);
@Override
public void onMessage(String message) {
    messageQueue.put(message);
}
```
Then you can use all the facilities of blocking queue when processing messages - wait for value, wait with timeout, etc:
```java
ExampleClient c = new ExampleClient(new URI( "ws://localhost:8887"));
c.connectBlocking();
c.send("Hello, World!");
String response = c.messageQueue.take();
```
If the messages arrive faster than you can process, the `put()` call in `onMessage()` will block which is what would happen normally.

Keep in mind that there are also binary messages which are separate from text ones, so if you want to process those, you would either need to use two queues or change the type to BlockingQueue<Object> and put both kinds in the same queue.
