### ISSUE TITLE
Adding Routes When Sending A Message As A Client

### ISSUE THREAD

**Issue by dterefe** [TooTallNate/Java-WebSocket#1249]
Hey,

so I have been using this library's websocket-client for a project of mine and I'd like to know,
if possible, how I could add routes  to the URI specifically when sending a message to a websocket-server?

**Comment by PhilipRoman** [comment]
Can you clarify your problem? You should be able to pass it to WebSocketClient constructor.

**Comment by PhilipRoman** [comment]
No, this is not possible. There is no such functionality described in the [Websocket specification](https://datatracker.ietf.org/doc/html/rfc6455). You would have to open a separate connection to send messages to a different path.
