### ISSUE TITLE
No onConnect on my client

### ISSUE THREAD

**Issue by tho1294** [TooTallNate/Java-WebSocket#1250]
Hello i try to make a websocket server
but on my client (A c# unity 3d socket io client)

i have the connection event on server but not on client
i use socket io 4 on my client

do you have any idea?

**Comment by PhilipRoman** [comment]
Socket.io is not the same protocol as websockets.

From https://socket.io/docs/v4/:
> Although Socket.IO indeed uses WebSocket for transport when possible, it adds additional metadata to each packet. That is why a WebSocket client will not be able to successfully connect to a Socket.IO server, and a Socket.IO client will not be able to connect to a plain WebSocket server either.

You need a server library that supports socket.io protocol.
