### ISSUE TITLE
onError triggered outside of websocket

### ISSUE THREAD

**Issue by f6qpQNBA3p** [TooTallNate/Java-WebSocket#1252]
Hello, when I get an error that has nothing to do with the websocket, it pass through the onError method....
I mean the onError method is triggered to display the errors...
(using latest websocket client with android studio)

Do you have an idea of what is causing this strange thing ?

**Comment by PhilipRoman** [comment]
Can you post the specific errors that happen in onError()?
This callback is mostly used for internal errors such as IOException from sockets, thread interrupts, etc.

**Comment by f6qpQNBA3p** [comment]
> 

hello, here is the last error i got : Only the original thread that created a view hierarchy can touch its views. (i was changing the visibility of a view) so I fixed it using "runOnUiThread"... nothing to do with the websocket...
I don't understand why the errors pass by the websocket onError method...

**Comment by PhilipRoman** [comment]
Yes, this is normal behavior when exception is thrown within a callback like `onMessage`, etc. Otherwise there would be no way to let the user handle such errors without crashing the entire server/client.

**Comment by f6qpQNBA3p** [comment]
> Yes, this is normal behavior when exception is thrown within a callback like `onMessage`, etc. Otherwise there would be no way to let the user handle such errors without crashing the entire server/client.

Oh ok i thank you for explaining me.
