### ISSUE TITLE
Always reporting an error invalidframeexception: bad RSV rsv1: true rsv2: false rsv3: false code:1002 what is the reason?

### ISSUE THREAD

**Issue by pjx2019** [TooTallNate/Java-WebSocket#1257]
**Describe what you would like to know or do**
A clear and concise description of what the problem is.

**Describe the solution you'd considered**
A clear and concise description of any solutions you've considered.

**Additional context**
Add any other context or links about the question here.

**Comment by PhilipRoman** [comment]
What library version are you using? This looks like it might have been fixed in #1232 which was released with version 1.5.3.
