### ISSUE TITLE
android

### ISSUE THREAD

**Issue by khangTi** [TooTallNate/Java-WebSocket#1260]
hi admin
i am using this library to create 1 server socket on android, and using windows machine to connect to this server but i am facing the following problem:
my windows machine can connect to the following server (at this time i can ping and telnet to the server) then i reset the windows machine and reconnect it can't connect (this time i ping the server ok but telnet is down error) have to clear the android app and reopen it before the windows machine can connect again, I'm trying to find this error don't know if you have any solution to solve this problem
thanks admin

**Comment by NoahAndrews** [comment]
It's possible that you need to enable SO_REUSEADDR: https://github.com/TooTallNate/Java-WebSocket/wiki/Enable-SO_REUSEADDR

**Comment by khangTi** [comment]
I turned on SO_REUSEADDR but it still can't be admin
