### ISSUE TITLE
I am also facing this issue,“Attempt to invoke virtual method 'void java.net.Socket.close()' on a null object reference”

### ISSUE THREAD

**Issue by 18722650553** [TooTallNate/Java-WebSocket#1262]
#java.lang.NullPointerException
org.java_websocket.client.WebSocketClient$WebsocketWriteThread.closeSocket(WebSocketClient.java:835)
org.java_websocket.client.WebSocketClient$WebsocketWriteThread.run(WebSocketClient.java:803)
java.lang.Thread.run(Thread.java:923)

    /**
     * Closing the socket
     */
    private void closeSocket() {
      try {
        if (socket != null) {
          socket.close();
        }
      } catch (IOException ex) {
        onWebsocketError(webSocketClient, ex);
      }
    }

The bug happens when I close the socket

**Comment by marci4** [comment]
No Steps to repeat provided.
