### ISSUE TITLE
Why can't I create one client immediately after I close another client?

### ISSUE THREAD

**Issue by Joey777210** [TooTallNate/Java-WebSocket#1265]
**Describe what you would like to know or do**
I'm trying to create one client between the same ip address immediately after I close one wsclient. Just like code down here.
```
            try {
                WsClient client = new WsClient(new URI("ws://localhost:8080/websocket/chat"), "client");
                client.connect();

                UserDto user = buildUser();
                WsChatMsg init = buildInitMsg(user);
                client.send(JSONObject.toJSONString(init));
                log.info("send-init-{}", init);
                client.close();
            } catch (URISyntaxException e) {
                throw new RuntimeException(e);
            }

        try {
            WsClient client1 = new WsClient(new URI("ws://localhost:8080/websocket/chat"), "client1");
            client1.connect();
            UserDto user = buildUser();
            WsChatMsg init = buildInitMsg(user);
            client1.send(JSONObject.toJSONString(init));
            log.info("send-init-{}", init);
            client1.close();
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }
```

If I run this code, I got `org.java_websocket.exceptions.WebsocketNotConnectedException`

**Describe the solution you'd considered**
I've tryed catch tcp/websocket package use wireshark, It seems the the second will send RST immediatly after handshake.

![image](https://user-images.githubusercontent.com/53630996/182391344-1c7f4fd8-06a8-43c5-8419-c570dfda4da6.png)

**Additional context**
Add any other context or links about the question here.

**Comment by PhilipRoman** [comment]
Try using `connectBlocking()` instead of `connect()`, that way it should block the code until the connection succeeds or not.

**Comment by Joey777210** [comment]
> 

Thank you very much, it works!!
Althought, why would that happen?

**Comment by PhilipRoman** [comment]
`connect()` returns (almost) immediately and schedules the connection on a separate thread. Sometimes it appears to work but that depends on computer and network speed, etc.

`connect()` is useful for when you expect the server to send the first message.
