### ISSUE TITLE
Heads up: User just edited the Wiki home page to link to malware

### ISSUE THREAD

**Issue by NoahAndrews** [TooTallNate/Java-WebSocket#1272]
When I accidentally clicked on the link that @FrankFeng added [in this commit](https://github.com/TooTallNate/Java-WebSocket/wiki/Home/_compare/736e5e92fc5179feee5865686a70b03f3d7eaab1...a4f3c9f1266fb230d5abf8c1e70bdeafbfcbf5e8), Firefox warned me that it was malware. I've reported this user to GitHub.

**Comment by NoahAndrews** [comment]
I did undo the change.

**Comment by NoahAndrews** [comment]
GitHub appears to have banned the user. I'll close this, but consider this a reminder to keep an eye on wiki edits. It's too bad GitHub wikis don't support pull requests.

**Comment by marci4** [comment]
Thank you very much!!

**Comment by NoahAndrews** [comment]
I've reported the user and reverted the change.

**Comment by PhilipRoman** [comment]
Worst case scenario we could restrict wiki editing to collaborators only for now but unfortunately I think only the repo owner can do this, not collaborators.

**Comment by marci4** [comment]
@TooTallNate could you please change this? Thx

**Comment by marci4** [comment]
Not much I can do here. Closing issue for now
