### ISSUE TITLE
Handshake refusing because of the some handshake specific field values

### ISSUE THREAD

**Issue by maslanz** [TooTallNate/Java-WebSocket#1274]
Hello,

As a client, we want to establish a websocket connection to a server. However, we get the "handshake refused" error. When we examined the reason for this, we observed that some handshake specific field values were not equal to the expected values. Our problem is that the two fields below are sent two times.

Expected field : value pair
UPGRADE : websocket
CONNECTION : Upgrade

field : value pair sent by the server we are trying to establish a connection as a client
UPGRADE : websocket; websocket
CONNECTION : Upgrade; upgrade

Is it possible for us to ignore this situation or should we request changes for this issue on server side?

Our Environment:
Version used: Java-WebSocket 1.4.0
Java version: 11
Operating System: ubuntu 18.04

**Comment by marci4** [comment]
Well https://www.rfc-editor.org/rfc/rfc6455#section-4.2.1 is pretty specific in this case.
I would expect that you will get problems with other clients as well.

Best regards,
Marcel

**Comment by maslanz** [comment]
Hello @marci4 ,

Thanks for the comment and the link. You can examine the content of the response sent to us by the server from the screenshot below.

![Screenshot from 2022-09-05 16-49-06](https://user-images.githubusercontent.com/32645943/191914747-d1c3a0b0-ab0b-4628-820a-3fa564eb3baa.png)

As you can see, "UPGRADE" and "CONNECTION" handshake specific fields are sent two times. When we asked the server side about this issue, they gave us the following answer.

"I think the issue is that backend repeated twice to send the values of "UPGRADE" & "CONNECTION". It is because our backend has 2 individual sets of IoT server. Client side should ignore this issue. Once a successful connection response is received, the handshake can be considered successful. Then proceed to the websocket persistent connection."

Honestly, that answer didn't make much sense to me either. However, can we ignore this issue as a client side?
At org.java_websocket.drafts.Draft.translateHandshakeHttp(Draft.java:109) Is it possible to cancel the append operation mentioned at the comment line? Even if it is possible, do you think this is correct behavior?

Best regards.

**Comment by marci4** [comment]
Hey,
I would consider the spec pretty specific in this case.
See
`If the server chooses to accept the incoming connection, it MUST
       reply with a valid HTTP response indicating the following.

       1.  A Status-Line with a 101 response code as per [RFC 2616](https://www.rfc-editor.org/rfc/rfc2616)
           [[RFC2616](https://www.rfc-editor.org/rfc/rfc2616)].  Such a response could look like "HTTP/1.1 101
           Switching Protocols".

       2.  An |Upgrade| header field with value "websocket" as per [RFC](https://www.rfc-editor.org/rfc/rfc2616)
           [2616](https://www.rfc-editor.org/rfc/rfc2616) [[RFC2616](https://www.rfc-editor.org/rfc/rfc2616)].

       3.  A |Connection| header field with value "Upgrade".
`

Best regards,
Marcel

**Comment by maslanz** [comment]
Hi @marci4 ,

Thanks for the quick answers. We can close the issue.
