### ISSUE TITLE
Identical byte arrays

### ISSUE THREAD

**Issue by Krizis112** [TooTallNate/Java-WebSocket#1276]
I tried to write a client for one game, but I ran into a bug. For some reason, the server sends
almost identical arrays of bytes, while with the same client, but there are no such problems in JavaScript.

**Comment by PhilipRoman** [comment]
Hi, please add steps to reproduce your problem. Currently there is not enough information to help you.

**Comment by Krizis112** [comment]
> Hi, please add steps to reproduce your problem. Currently there is not enough information to help you.

1. I create a websocket client object and connect it.
2. I am starting to receive messages from the server and they are very strange.
3. Sample response in Java
```[47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
[47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
[47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
[47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
[47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
[47, 14127, 47, 5935, 47, 12335, 47, 12335, 47, 47]
```
4. Sample response in JavaScript
![image](https://user-images.githubusercontent.com/59326567/193488273-da734390-ac42-413b-b3ce-4aeed381fbb2.png)

**Comment by Krizis112** [comment]
> > Hi, please add steps to reproduce your problem. Currently there is not enough information to help you.
> 
> 1. I create a websocket client object and connect it.
> 2. I am starting to receive messages from the server and they are very strange.
> 3. Sample response in Java
> 
> ```
> [47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
> [47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
> [47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
> [47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
> [47, 14127, 47, 5935, 47, 12335, 47, 12335, 47, 47]
> ```
> 
> 4. Sample response in JavaScript
>    ![image](https://user-images.githubusercontent.com/59326567/193488273-da734390-ac42-413b-b3ce-4aeed381fbb2.png)

Oh, yes, I forgot to say. I bring them to the short array type through this method.
```
	public short[] getPosition(ByteBuffer buffer) {
		short[] sa = new short[buffer.capacity() / 2];
		
		for(int i = 0; i < sa.length; i++) {
			ByteBuffer bb = ByteBuffer.allocate(2);
			bb.order(ByteOrder.LITTLE_ENDIAN);
			bb.put(buffer.get(2 * 1));
			bb.put(buffer.get(2 * i + 1));
			sa[i] = bb.getShort(0);
		}
		
		return sa;
	}
}
```

**Comment by PhilipRoman** [comment]
It looks like the issue is in this line:
```
bb.put(buffer.get(2 * 1));
```
`1` should probably be `i`.
This issue is not related to the library and is off-topic.

**Comment by Krizis112** [comment]
> Похоже, проблема в этой строке:
> 
> ```
> bb.put(buffer.get(2 * 1));
> ```
> 
> `1`наверное должно быть `i`. Эта проблема не связана с библиотекой и не по теме.

Thank you very much, I copied this method and it seems to be wrong

**Comment by PhilipRoman** [comment]
Also, your entire function can be replaced with
```
short[] sa = new short[buffer.remaining() / 2];
buffer.asShortBuffer().get(sa);
return sa;
```
