### ISSUE TITLE
How I can send "Protocol" header like js 

### ISSUE THREAD

**Issue by abhi-coditas** [TooTallNate/Java-WebSocket#1280]
I want to pass the jwt in protocol header in connection request. Which is possible in JS like below. 

`const socket = new WebSocket(url, jwt)`

I wanted to know how that can be done using **WebSocketClient** if possible?

Using this library in Android. 
Release version: 1.5.1

**Comment by PhilipRoman** [comment]
Hi, I'm not 100% sure but as far as I know, the protocol parameter simply sets the `Sec-WebSocket-Protocol` HTTP header so you might be able to just do something like this:
```java
new WebSocketClient(uri, Map.of("Sec-WebSocket-Protocol", "my-protocol"))
```

**Comment by marci4** [comment]
See https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SecWebSocketProtocolClientExample.java

**Comment by abhi-coditas** [comment]
Thanks @marci4, its working :-)
