### ISSUE TITLE
expecting ';' or ',' at or before "("             

### ISSUE THREAD

**Issue by swankystar** [TooTallNate/Java-WebSocket#1281]
I'm working on an Airline booking program and I have been stuck on an error when initializing the boolean function, checkPromo. I've checked curly braces, semi colons but everything seems to be in order.

 I've tried declaring the method as "public boolean", "public static boolean" and switching the order of the method within the Ticket Class but no dice. 

Any help would be greatly appreciated! 

import java.util.Arrays; 
import java.util.Scanner;
import java.util.*;
import java. io.*;
import java.lang.Math;   

public class Ticket {
   int[] ticketNumber;
   int quantOfTickets;
   double ticketPrice;
   String customerOrigin;
   String customerDestination;
   String customerName;
   String flightClass;
   String customerCode;

   public void main(String[] args) {
      
     
      Scanner customerTicket = new Scanner(System.in);
      System.out.println("Hello, valuable customer! \nWelcome to Princess Diana's Airlines!");
      System.out.println("Please enter your name: ");
      customerName = customerTicket.nextLine();
      
      System.out.println("\nPlease enter your origin city: ");
      customerOrigin = customerTicket.nextLine();
      
      System.out.println("\nPlease enter your destination: ");
      customerDestination = customerTicket.nextLine();
      
      System.out.println("\nHow many tickets would you like to purchase?");
      quantOfTickets = Integer.parseInt(customerTicket.nextLine());
      
      System.out.println("\nDo you have a PROMO CODE?");
      customerCode = customerTicket.nextLine(); 
     
      System.out.println("\nYour ticket number is " + Math.random());
      
      System.out.println("\n" + NewTicket());
      

      
   }
   
   Ticket (String customerNameIn, String customerOriginIn, String customerDestinationIn, int quantOfTicketsIn, String flightClassIn, int ticketNumberIn) {
      customerName = customerNameIn;
      customerOrigin = customerOriginIn;
      customerDestination = customerDestinationIn;
      quantOfTickets = quantOfTicketsIn;
      flightClass = flightClassIn;
      ticketNumber = ticketNumberIn;
      Ticket NewTicket = new Ticket();
     
    boolean checkPromo() {
      String[] promoCodes = {"SAVINGS", "IJUSTGOTPAID", "YESSIRRR", "YEEHAW"};
      String correctPromo = promoCodes[4];
      for (int i = 0; i < promoCodes.length; i++) {
         if (customerCode == correctPromo ) {
            return true;
            System.out.println("YEEHAW INDEED! You're savin' partner!");
            customerCode = customerTicket.nextLine();
            break;
         } else {
            return false;
            System.out.println("Gosh darn...that don't work! Better luck next time...");
            customerCode = customerTicket.nextLine();
            break;
         }
      
      }
          
   }
   
   }
   
}

**Comment by PhilipRoman** [comment]
This issue is off-topic here. This repository is about the Java-WebSocket library and your question has nothing to do with it.

btw, the issue is that your `checkPromo` method is inside your constructor.
So instead of
```java
class Ticket {
    Ticket() {
        boolean checkPromo() {
            ...
        }
    }
}
```
it should be
```java
class Ticket {
    Ticket() {
        ...
    }
    boolean checkPromo() {
        ...
    }
}
```

There are too many other issues in your code as well which I don't have the time to explain.
