### ISSUE TITLE
[Question] How to check if WebSocketServer is already running ?

### ISSUE THREAD

**Issue by umer0586** [TooTallNate/Java-WebSocket#1284]
I am using this `WebSocketServer` in Android's [Foreground Service](https://developer.android.com/guide/components/foreground-services),  where I constantly need to check if server is alive. Is there any method like `server.isRunning()` to check server's state ?

**Comment by umer0586** [comment]
I am using boolean flag to keep track of server's state but i wonder if this approach is 100% reliable or not.

**Comment by PhilipRoman** [comment]
I don't see why it shouldn't be (aside from multithreading issues). If you want to be really precise, you could do something like this:
```java
AtomicBoolean running = new AtomicBoolean(true);
// ...
var server = new Server();
server.setReuseAddr(true);
server.run(); // unlike "start", "run" is a blocking call, put this block in a new thread if needed
// this part will be reached when the server exits
System.out.println("server exited");
running.set(false);

```
