### ISSUE TITLE
how upgrade https to wss

### ISSUE THREAD

**Issue by 371873574** [TooTallNate/Java-WebSocket#1305]
how upgrade https to wss, instead of nginx:
location /wss/ {
        proxy_pass https://k8s.tudoucloud.com:6443/apis/subresources.kubevirt.io/v1/namespaces/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
    }

**Comment by marci4** [comment]
Not relevant to this library.
