### ISSUE TITLE
Ping from JavaScript client

### ISSUE THREAD

**Issue by Varshaav16** [TooTallNate/Java-WebSocket#1315]
**Describe what you would like to know or do**
I would like to send  PING message from client

**Describe the solution you'd considered**
Is there an option to send PING message in terms of Frame?  
I am able to achieve ping-pong using send() but I want to do the same using Frames.  

**Additional context**
setConnectionTimeout() works for Java client but I am looking for something similar in JavaScript, so that the client can know when the server shuts down.

**Comment by PhilipRoman** [comment]
It looks like there is no browser function for sending ping frames. Your only option is to implement your own ping system with normal frames and handle it at the application layer.

**Comment by Varshaav16** [comment]
ah thanks
