### ISSUE TITLE
How to properly close a connection from client?

### ISSUE THREAD

**Issue by svalaskevicius** [TooTallNate/Java-WebSocket#1325]
**Describe what you would like to know or do**

Hi, I cannot find a proper way to close the connection fully from the client side:
 - there is a close() method, but it seems it leaves the actual threads and socket hanging - or am I missing anything?
 - there is reset(), but it private and only used in reconnect()

**Describe the solution you'd considered**

 - opening up the `reset()` method could be nice

**Additional context**

**Comment by karan1908** [comment]
I closed the connection in following manner, but I don't think this is the grace full approach.

`public static void main(String[] args) throws Exception {
        MYWebSocketClient myWebSocketClient = new MYWebSocketClient(new URI(
                "wss://.../"));

        myWebSocketClient.connectBlocking(30, TimeUnit.SECONDS);

        responseLatch.await(1, TimeUnit.SECONDS);

        myWebSocketClient.closeBlocking();
    }`

**Comment by PhilipRoman** [comment]
Yes, close() and closeBlocking() are the correct ways to close a socket. Are you getting any specific problems? I just checked, and no threads are left hanging.
