### ISSUE TITLE
Origin

### ISSUE THREAD

**Issue by FollowerCultBZZ** [TooTallNate/Java-WebSocket#1349]
Is it possible to specify origin using this library?

**Comment by PhilipRoman** [comment]
You can specify any custom HTTP header for client.
See example: https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/CustomHeaderClientExample.java

**Comment by FollowerCultBZZ** [comment]
> You can specify any custom HTTP header for client. See example: https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/CustomHeaderClientExample.java

thx
