### ISSUE TITLE
SOCKS: Connection refused

### ISSUE THREAD

**Issue by FollowerCultBZZ** [TooTallNate/Java-WebSocket#1352]
I'm trying to connect to a websocket using a proxy, but it gives me that the connection is refused. What could be causing this error? Is the proxy to blame, or is it something in my code?

**Comment by PhilipRoman** [comment]
Can you clarify your setup?
Are you explicitly setting the proxy with the setProxy method or connecting otherwise?
If possible, please show your client side code which does the connection.

**Comment by FollowerCultBZZ** [comment]
The reason for the error was in the proxy type. IPv4 required.
