### ISSUE TITLE
How can I get the unique identification of a connection of websocket  ?

### ISSUE THREAD

**Issue by better-github-hub** [TooTallNate/Java-WebSocket#1354]
How to distinguish the uniqueness of each session of connect  ?

   @Override
    public void onOpen(WebSocket conn, ClientHandshake handshake) {
        conn.send("Welcome to the server!"); //This method sends a message to the new client
        broadcast( "new connection: " + handshake.getResourceDescriptor() ); //This method sends a message to all clients connected
        System.out.println("new connection to " + conn.getRemoteSocketAddress());
    }

**Comment by better-github-hub** [comment]
For example this Session ：
public void onOpen(Session session,@PathParam("userId") String userId) ;

I want to get   the Session when the clinet to connect  webSocketServer . please help me, thank you very much.

**Comment by better-github-hub** [comment]
For example this Session ：
public void onOpen(Session session,@PathParam("userId") String userId) ;

I want to get the Session when a client to connect webSocketServer . please help me, thank you very much.

**Comment by PhilipRoman** [comment]
I don't think Java provides a built in way to parse URL query parameters. You can get the full query string by doing `URI.create(handshake.getResourceDescriptor()).getQuery()`
But for splitting and decoding it, you either need a library or just search for code online

**Comment by better-github-hub** [comment]
I just want to get the unique identification of a connection of websocket  . How can I get the unique identification  ?

**Comment by PhilipRoman** [comment]
Web sockets don't really have a unique connection ID, you can either use the WebSocket object itself or generate a random ID in the onOpen function and store it in the WebSocket with the setAttachment method.

**Comment by better-github-hub** [comment]
the  "Sec-WebSocket-Key"  in the  headers , Can does  as  a unique connection ID  ?

as follows:

@Override
    public void onOpen(WebSocket conn, ClientHandshake handshake) {
        String webSocketKey = handshake.getFieldValue("Sec-WebSocket-Key");
        cache.set(webSocketKey,conn);
        conn.send("Welcome to the server!"); //This method sends a message to the new client
        broadcast( "new connection: " + handshake.getResourceDescriptor() ); //This method sends a message to all clients connected
        System.out.println("new connection to " + conn.getRemoteSocketAddress());
    }

**Comment by better-github-hub** [comment]
Thank you .  setAttachment method can store any values of I want  ?

**Comment by PhilipRoman** [comment]
Yes, setAttachment and getAttachment can be used for anything you want. 

But keep in mind that Sec-WebSocket-Key is generated by the client, and a malicious client could send multiple connections with the same Sec-WebSocket-Key. So you can't rely on it being unique.
