### ISSUE TITLE
How to integrate the WebSocketServer  into springboot ? 

### ISSUE THREAD

**Issue by better-github-hub** [TooTallNate/Java-WebSocket#1355]
**This is usually how we start:**

    public static void main(String[] args) {
            String host = "localhost";
            int port = 8887;
            WebSocketServer server = new SimpleWebSocketServer(new InetSocketAddress(host, port));
            server.run();
      }

**BUT ,I want to  create WebSocketServer  bean , and start the application use springboot , as follow:**  

    @Bean
    public WebSocketServer getWebSocketServer(){
        WebSocketServer server = new SimpleWebSocketServer(new InetSocketAddress(host, port));
        return server;
    }

    @SpringBootApplication(scanBasePackages = "com.github")
    public class FrameworkWebsocketApplication {
        public static void main(String[] args) {
            SpringApplication.run(FrameworkWebsocketApplication.class, args);
            System.out.println("Application start success !");
        }
    }

**Comment by better-github-hub** [comment]
Anybody answer me?

**Comment by better-github-hub** [comment]
I need help , Who can asked me ,how to do ?

**Comment by better-github-hub** [comment]
I create a new Thread run WebSocketServer, this way can  integrate into springboot. like this:

 @Bean
    public WebSocketServer runWebSocketServer(LocalCache cache){
        WebSocketServer server = new SimpleWebSocketServer(new InetSocketAddress(host, port),cache);
        ThreadPoolUtil.getCachedThreadPool().execute(() -> server.run());
        return server;
    }

And, are there any disadvantages to this approach ?

**Comment by PhilipRoman** [comment]
Closing as this is off topic
Might be better to ask this in a Spring discussion forum, not here
