### ISSUE TITLE
WebSocket Client doesn't terminate after close or closeConnection

### ISSUE THREAD

**Issue by BenedictLelanz** [TooTallNate/Java-WebSocket#1357]
After creating a connection in my WebSocketClient extending class with

super(URI.create("wss://"+WEBSITE+":443"));

and

super.connect()

I have the problem that the application doesn't terminate although I called the close() method or the closeConnection() method after a while. Maybe some Threads are still running? I know I could trigger System.exit(), but in my case I need to open and close connections over a long time again and again. It would be horrible if there will be more and more threads running in the background and slowing down the system.

Is this a bug? Or do Ihave to trigger some special method?

**Comment by PhilipRoman** [comment]
Can you please post a small program which reproduces this issue?

**Comment by BenedictLelanz** [comment]
I'm sorry, I just realized it was my fault :D
