### ISSUE TITLE
Multiple WebSocketClients in one thread

### ISSUE THREAD

**Issue by popov-aa** [TooTallNate/Java-WebSocket#1366]
I need to connect from one application to a hundred websocket servers and receive messages from them. How do I do this, without creating a thread for each client?

**Comment by PhilipRoman** [comment]
Hi, this is currently not possible without creating many threads. There are no plans to implement this as it would require rewriting most of the client code and we don't have enough contributors :P

I'm closing this as completed, let me know if there is anything I can help with.

**Comment by popov-aa** [comment]
Thank you. I found solution on c++: https://github.com/zaphoyd/websocketpp

**Comment by HePingLaoSan** [comment]
> Hi, this is currently not possible without creating many threads. There are no plans to implement this as it would require rewriting most of the client code and we don't have enough contributors :P
> 
> I'm closing this as completed, let me know if there is anything I can help with.

So, the correct way to use this library is to perform the creation operation of each WebSocket in its own thread, right?
