### ISSUE TITLE
Got fatal error during frame processing

### ISSUE THREAD

**Issue by HePingLaoSan** [TooTallNate/Java-WebSocket#1369]
**Describe the bug**
I'm using version 1.5.3 of this library, and while troubleshooting through the logs, I came across the error message `org.java_websocket.WebSocketImpl.414: Got fatal error during frame processing.` However, this error log did not trigger the onError callback or the onClose callback. I'm not sure why this is happening.

***To Reproduce**
An occasional case, no idea how to reproduce

Expected behavior
trigger onError or onClose

**Debug log**
`org.java_websocket.WebSocketImpl.414: Got fatal error during frame processing.`

**Version used: 1.5.3**
**Java version: 17**
**Operating System and version: Ubuntu 20.04**

**Comment by marci4** [comment]
This message is printed out when one of the following exceptions are triggered.
VirtualMachineError | ThreadDeath | LinkageError 

As I cannot reproduce the issue, I cannot improve the error handling here.

**Comment by HePingLaoSan** [comment]
> This message is printed out when one of the following exceptions are triggered. VirtualMachineError | ThreadDeath | LinkageError
> 
> As I cannot reproduce the issue, I cannot improve the error handling here.

Thank you for your response. As a developer, what is the usual way for us to correctly handle this kind of error?

**Comment by evoisard** [comment]
This has been fixed in 2022 for WebSocketServer: #1223, WebSocketClient should get the fix too.
