### ISSUE TITLE
onMessage process order is not received order.

### ISSUE THREAD

**Issue by anzhaozhong** [TooTallNate/Java-WebSocket#1379]
**Describe the bug**
Client onMessage process order is not received order.

**To Reproduce**
1. Send a request message to server.
2. server return multi messages
3. onMessage process latest to oldest message

**Example application to reproduce the issue**
A link to a github project/gist to reproduce the issue.

**Expected behavior**
The process order should be FIFO.

**Comment by PhilipRoman** [comment]
Do you have an example application which reproduces the issue? Also, what library version are you using?
