### ISSUE TITLE
How wo broadcat part of cient?

### ISSUE THREAD

**Issue by yummyChina** [TooTallNate/Java-WebSocket#1384]
Onlye broast part of client
For example client1 client2 client3 connect with server
At the side of server ,just send data to client1 ,client2 ,except cient3,I try somethiong,but not working

**Comment by PhilipRoman** [comment]
There is a function in WebSocketServer:
```java
public void broadcast(byte[] data, Collection<WebSocket> clients)
```
This should do what you want. There are also versions for String and ByteBuffer instead of byte[]
