### ISSUE TITLE
Android device link speed is slow

### ISSUE THREAD

**Issue by chenqinggang001** [TooTallNate/Java-WebSocket#1389]
The websocket works properly，But it's too slow to create links

Can be seen in the screenshot from the receipt of a request ` onWebsocketHandshakeReceivedAsServer ` callback, until the callback onOpen， It took tens of seconds，How can I improve

<img width="489" alt="image" src="https://github.com/TooTallNate/Java-WebSocket/assets/74290987/c84f84e0-6ad8-4387-a40e-306efe49f0c5">

<img width="1285" alt="image" src="https://github.com/TooTallNate/Java-WebSocket/assets/74290987/26d89c6a-0bf0-4d99-8950-b40838d76543">

**Comment by chenqinggang001** [comment]
I found that the cause of the problem was the use of this callback, it was very slow on some devices, I commented out this part of the code and the link speed was normal

```
@Override
    public ServerHandshakeBuilder onWebsocketHandshakeReceivedAsServer(WebSocket conn, Draft draft, ClientHandshake request) throws InvalidDataException {
        ServerHandshakeBuilder builder = super.onWebsocketHandshakeReceivedAsServer( conn, draft, request );
        Log.d("zb", "WebSocketServer onWebsocketHandshakeReceivedAsServer: " + conn.getLocalSocketAddress() + "  " + conn.getRemoteSocketAddress());
        if (Objects.equals(conn.getLocalSocketAddress().getHostName(), conn.getRemoteSocketAddress().getHostName())) {
            // 判断是否是自己，拒绝自己连接，减少广播数据消耗
            throw new InvalidDataException(CloseFrame.POLICY_VALIDATION, "Not accepted!");
        }
        return builder;
    }
```

**Comment by NoahAndrews** [comment]
I think that code actually does two DNS lookups, which would certainly make it slow. Look at the documentation for` getHostname()`.

**Comment by chenqinggang001** [comment]
I removed the getHostName method and replaced it with getAddress, and the problem disappeared
