### ISSUE TITLE
lose data without connection close ballback

### ISSUE THREAD

**Issue by yummyChina** [TooTallNate/Java-WebSocket#1392]
sometimes data lost,but connection is normal

**Comment by marci4** [comment]
Hello @yummyChina 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE/bug_report.md and do not forget link to the example application!

Without a full bug report this will be closed.

Best regards,
marci4

**Comment by yummyChina** [comment]
More information:
1 both server and client run on android device
2 socket.setReuseAddr(true);
3 when repeat connection several times. send data with no response
