### ISSUE TITLE
java.lang.InterruptedException: null

### ISSUE THREAD

**Issue by bai-xuan** [TooTallNate/Java-WebSocket#1412]
**Describe what you would like to know or do**
A clear and concise description of what the problem is.

After the connection is disconnected, try the failure caused by the continuous connection

**Describe the solution you'd considered**
A clear and concise description of any solutions you've considered.

This is the log of printing：
![image](https://github.com/TooTallNate/Java-WebSocket/assets/38934025/a303bd3a-abb8-4e94-a6a6-8aa67eb6421d)

This is the code that is reconflowing：
![image](https://github.com/TooTallNate/Java-WebSocket/assets/38934025/1ee0ac3d-2977-46a8-8510-9a17582f3ba4)

**Additional context**
Add any other context or links about the question here.

I wonder if the code for disconnecting and reconnecting has data that has not been cleaned up. The problem is that 'pong' is not received within the corresponding time, and then it is automatically disconnected. I tried to call 'reconnectBlocking', but received 'java. lang.InterruptedException: null' error

**Comment by bai-xuan** [comment]
I seem to have found a problem. Is this a code problem or a problem on my part?
![image](https://github.com/TooTallNate/Java-WebSocket/assets/38934025/650dba42-2d2c-45c6-a4f0-2ca4685bf624)

![image](https://github.com/TooTallNate/Java-WebSocket/assets/38934025/84bc690c-c6a1-466f-9f62-0094c26ae42d)

**Comment by bai-xuan** [comment]
Sorry, I accidentally ordered the problem that I just accidentally ordered the problem. I have reached this problem again.

**Comment by marci4** [comment]
Yeah reconnecting inside the onClose can not work.
