### ISSUE TITLE
Javadoc Comments

### ISSUE THREAD

**Issue by varunsingh87** [TooTallNate/Java-WebSocket#1414]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am unsure what a class, method, or package is for, and I am given no context by the library documentation. As someone who is brand new to web sockets, I find using the web sockets library much more difficult to use without any guidance. 

**Describe the solution you'd like**
I would like for there to be Javadoc comments over classes and methods, at least the important/basic ones, and I would like these Javadoc comments to be shipped in the release. 

**Describe alternatives you've considered**
I can try to infer context from the examples, but these are still minimal and do not help with deeper bug investigations.

**Comment by PhilipRoman** [comment]
Can you point to some important classes/functions which are missing a javadoc? As far as I can tell the code is reasonably well documented (always room for improvement of course)

Or is the issue that javadoc cannot be viewed from your IDE?

**Comment by varunsingh87** [comment]
I cannot see the documentation in my IDE (IntelliJ) when I hover over classes.

**Comment by varunsingh87** [comment]
Oh I see, it was an issue on my end. I did not "Download sources" so it excluded the Javadoc because it was decompiling the bytecode.
