### ISSUE TITLE
Unable to catch port binding Exception 

### ISSUE THREAD

**Issue by LiJianGuo123** [TooTallNate/Java-WebSocket#1415]
How to catch the error that the service starts and the port is still bound, I can't get the Exception through the Try Catch Start method

**Comment by PhilipRoman** [comment]
Hi, the exception will be passed to the [onError](https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.6/org/java_websocket/server/WebSocketServer.html#onError(org.java_websocket.WebSocket,java.lang.Exception)) callback of the server, you can handle it there.

By the way, if you're dealing with port binding issues, you may be intrested in [setReuseAddr](https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.6/org/java_websocket/AbstractWebSocket.html#setReuseAddr(boolean)) which helps avoid this when quickly restarting the service
