### ISSUE TITLE
Blocking until response returned.

### ISSUE THREAD

**Issue by nd185084** [TooTallNate/Java-WebSocket#1417]
Is there a way to block after sending message untill response is accepted from other side?
In such case, is it possible to get the response object as well?

java version "22.0.1" 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

org.java-websocket version 1.5.6

**Comment by PhilipRoman** [comment]
There are lots of ways to implement this, here is one example using BlockingQueue: https://github.com/TooTallNate/Java-WebSocket/issues/1246#issuecomment-1129648585

Also some more discussion here: https://github.com/TooTallNate/Java-WebSocket/issues/1037
