### ISSUE TITLE
SSL without the need for a client side certificate?

### ISSUE THREAD

**Issue by burjorjee** [TooTallNate/Java-WebSocket#143]
Thanks for the great work. The Java-Websocket's API is amongst the best available for websocket programming in Java

Currently, to get an SSL connection going, both the client and the server must be be set up with certificates.

In the vast majority of cases, the authenticity of the client does not matter, so (as explained in the following) SSL works with just a server certificate. 

http://stackoverflow.com/questions/3107625/ssl-works-without-client-certificate

Any plans to add support for this very common use case?

**Comment by nirmala-mist** [comment]
I am very new to security. How do I configure the trust manager of the client to make it all work with self-signed certificate?
