### ISSUE TITLE
Change URI before reconnect

### ISSUE THREAD

**Issue by AlexChecker** [TooTallNate/Java-WebSocket#1431]
**Describe what you would like to know or do**
I'm writing discord bot without JDA. So, my only way is to use websockets. But there is one thing, that I can't understand: can I change URI for my websocket client without  re-initializing whole class? I can't check this myself, because situations, where I need to change URI are rare.

**Additional context**
The way it's implemented in my code now:
`this.uri = new URI(resume_url);`
`this.reconnect();`

**Comment by marci4** [comment]
The intention was not to adjust the URI. Just reinitialize the whole class.
