### ISSUE TITLE
Upgrade from an existing http(s) connection

### ISSUE THREAD

**Issue by neoedmund** [TooTallNate/Java-WebSocket#1441]
**Describe what you would like to know or do**

I used this library a long time, by binding ws/wss server to a specified port. 
But it takes another port, besides my own http(s) server.
Can I use in another usecase? Say in the normal http server, If I found 'Upgrade: websocket' in the http header, I can let this library to take over the following work?
If this library cannot , do anyone knows which other java websocket library can do this?
Thanks.

**Describe the solution you'd considered**
 

**Additional context**

**Comment by marci4** [comment]
No I have no plans to include a http service.
