### ISSUE TITLE
Android(< 3.0) SSLEngine Bug 12955 workaround?

### ISSUE THREAD

**Issue by Davidiusdadi** [TooTallNate/Java-WebSocket#155]
Moved form pull #153:
@2fours:
There seem to be problems on older android platforms because of this bug in SSLEngine : https://code.google.com/p/android/issues/detail?id=12955#c12. It appears that the only way this will work on these platforms is to abandon SSLEngine and use SSLSocket. Any chance of that happening?

---

@Davidiusdadi
Do you mean that your code is working fine but there is a problem with what i merged?

If there is a general problem i would like to know the exact exception or build error message and the android version you are working on. 

The solution suggested in #141 might solve the problem.

**Comment by marci4** [comment]
This Android version is not active any more! 

Closing. 
Greetings marci4
