### ISSUE TITLE
Need onClose event if internet connection turned off or interrupted

### ISSUE THREAD

**Issue by timmolter** [TooTallNate/Java-WebSocket#180]
Hi, I'm writing in regards to an inquiry on XChange here: https://github.com/timmolter/XChange/issues/109

Does Java-websockets have any internal mechanism to detect when the Interent connection goes down? Perhaps with a timeout parameter?

At XChange, we already have a way to reconnect, but it relies on receiving an onClose message from Java-Websockets.

Any idea how we can deal with this? Thanks in advance!

**Comment by marci4** [comment]
Closing this issue.
Will be released with 1.3.4

See #473
