### ISSUE TITLE
WebSocket Server not starting on Android

### ISSUE THREAD

**Issue by jbelstner** [TooTallNate/Java-WebSocket#181]
I am trying to migrate a LocalSocket implementation to use this WebSocket implementation in Android.  Just like my LocalSocket implementation, both the Server and the Client app exist on the same device.  The Client app is running in the foreground while the Server is instantiated inside a Service running in the background.  Inside the Service, I start a new thread and call the WebSocketServer.start() method from inside Thread.run().  When I try to WebSocketClient.send() something from the client, I always get the NotYetConnectedException.

An interesting observation is that if I try to use WebSocketServer.run() instead of WebSocketServer.start(), the ServerSocketChannel.open() method always throws an IOException and exits.

I've run the sample Java code here on my Mac and it works great.  Has anyone gotten the server code to run in Android that might be able to point me in the right direction?

Thanks so much!

**Comment by vikramsingh88** [comment]
I have created a websocket server in android app
public class WebsocketServer extends WebSocketServer {
}

And starting it from Application class
int port = 1000;
InetSocketAddress inetSockAddress = new InetSocketAddress(port);
WebsocketServer wsServer = new WebsocketServer(inetSockAddress);
wsServer.run();

Also add the permission in Manifest file
<uses-permission android:name="android.permission.INTERNET"/>

But getting permission denied exception as soon as Application class starts the server
D  Error on websocket connection: Permission denied
at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:567)
at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:367)

**Comment by PhilipRoman** [comment]
Have you added the network permission to your app manifest file?
```
<uses-permission
    android:name="android.permission.INTERNET" />
```

**Comment by PhilipRoman** [comment]
Nevermind, I see that you are using port 1000. Ports below 1024 are reserved for root users, try with port greater than 1024.

**Comment by vikramsingh88** [comment]
Thanks Philip for quick reply, yes I tried using port 8000 and it worked.
