### ISSUE TITLE
Enable synchronous send

### ISSUE THREAD

**Issue by ghost** [TooTallNate/Java-WebSocket#185]
I'm not sure if its possible but I'd like to block until all data has been received by my websocket server. As a workaround I tried doing this in my WebSocketClient, but that didn't seem to work, maybe that's just checking that local data has been sent, not yet received:

``` java
while (super.getConnection().hasBufferedData()) {
    logger.info("Waiting to finish sending...");
    Thread.sleep(500);
}
```

**Comment by marci4** [comment]
Hello everyone,

I feel that this is not accomplished in a easy way. 
I, of course, could just add a callback, if frame with fin bit set, is send to a different endpoint.
Providing a callback for every frame send would force the application user to decode the frame on his own.

I am open for any other ideas :)

Greetings
marci4

**Comment by bcersows** [comment]
If both the server and the client are in the dev's hand, the easiest would be to send some kind of ACK once the whole data was received (and parsed).  
As for the callback, maybe call it once in the `WebsocketWriteThread` the `outQueue.isEmpty()` again after some data were queued for sending? For the use cases mentioned in this issue, this should be enough.

**Comment by marci4** [comment]
Hello @bcersows,

thank you very much for your input.

Well I am not sure if that would be enough for the use case.
There are some reasons for this:
- Another frame could be added to the `outQueue` while still writing the huge frame
- An empty `outQueue` does not ensure that the other endpoint already received the frame or the frame is flushed for sure.

Of course we can just add a callback for all the bytes written on the socket, but I cannot ensure that the other endpoint received them.

Greetings
marci4

**Comment by marci4** [comment]
No real solution on my mind and others.

Closing it. If someone has a good idea, feel free to ping me!

Best regards,
marci4
