### ISSUE TITLE
Regular Socket Implementation Server Reader

### ISSUE THREAD

**Issue by jaimegarzon** [TooTallNate/Java-WebSocket#202]
Hi, I have many socket's client with a specific protocol connection, generally is:

/*
sc = new Socket( HOST , PORT );

out= new DataOutputStream(sc.getOutputStream());
out.write("Hello".getBytes());

sc.close();
*/

This connection is not possible to change to the new websocket protocol, because the clients are hardware device with specific connection by tcp.

Is possible to add a reader for regular tcp in the server?

Thank you.

**Comment by marci4** [comment]
Not gonna implement this. Please use a seperat socket server and let this server communicate with your websocket server.

Greetings
marci4
