### ISSUE TITLE
Reconnect Websocket - The Best Practice?

### ISSUE THREAD

**Issue by jaimegarzon** [TooTallNate/Java-WebSocket#204]
What is the best practice to reconnect websocket when the network fall. because I close and open the connection and the websocket is not reusable. If I create a new websocket connection, in the server is received two connections.

Thanks.

**Comment by phutang2359media** [comment]
Hi, 

Do you have any solution for reconnect?

**Comment by blue86** [comment]
I have Build a Pong Check

Vom iPhone gesendet

**Comment by phutang2359media** [comment]
I'm implement a voice service base on websocket. I also use Pong check. But if it drop for a long time (over 30sec) It can't connect to server anymore, so I close and connect but can't.

**Comment by blue86** [comment]
From Handy or pc?

Vom iPhone gesendet

**Comment by phutang2359media** [comment]
From android device, you can easy to simulate, if it the network doesn't stable (EDGE or 3G), it's very easy to reproduce

**Comment by blue86** [comment]
I have the Problem too. You Must fast Send Ponks if this fail you Must reconnect

Vom iPhone gesendet

**Comment by phutang2359media** [comment]
The problem is how to reconnect. If I create a new websocketclient, server side is detect as a new client and can't drop the previous. That's why I need a help from you

**Comment by blue86** [comment]
You Need a Java Script Funktion width timeout if the Ponk Test fail

Vom iPhone gesendet

**Comment by marci4** [comment]
Pong check implemented with #473
