### ISSUE TITLE
Fragmentation error on very large messages

### ISSUE THREAD

**Issue by rgillan** [TooTallNate/Java-WebSocket#209]
We are getting some errors when we are receiving some very large packets with fragmentation (16kB) from our server.  We have other WS implementations on iOS that correctly reassemble the large packets (up to 4MB) and we've verified data validity with Wireshark (so we're pretty sure it's not a server side thing).  Smaller data packets (70kB) are passed through correctly to onFragment with isFin set correctly.  For much larger packets (470kB) we are getting errors when we try and process the reassembled message (which is JSON).

We have looked through the framing code (specifically .append) but are unsure whether we're running into a buffer capacity/allocation limit or something with the Fin detection.  Any suggestions/help very much appreciated.

Cheers
Rob

**Comment by marci4** [comment]
Fragmented frames are verified by the autobahn test case.

Greetings
marci4
