### ISSUE TITLE
WebSocket.getRemoteSocketAddress() returns null in onClose()

### ISSUE THREAD

**Issue by snaef999** [TooTallNate/Java-WebSocket#211]
I am trying to determine the client that is disconnecting.  I thought the natural place to find out the remote address would be to query the connection object in my overridden `WebSocketServer.onClose(WebSocket conn, int code, String reason, boolean remote)` method.

However, when I call `getRemoteSocketAddress()` it returns null.  This seems to only happen in the onClose event.  If I call this method on the socket while it is in use it works and returns the correct address.

Am I using this correctly?  Or is there a different way to get the remote address after the socket is closed?

Thank you,
snaef

**Comment by marci4** [comment]
Looks like @Davidiusdadi already fixed that one.

Closing issue.
Greetings
marci4

**Comment by ichavchavadze** [comment]
Version 1.5.5, conn.getRemoteSocketAddress() returns null in onClose() 

```
<dependency>
  <groupId>org.java-websocket</groupId>
  <artifactId>Java-WebSocket</artifactId>
  <version>1.5.5</version>
</dependency>
```
