### ISSUE TITLE
Server locks up/stops receiving messages after a while

### ISSUE THREAD

**Issue by Paril** [TooTallNate/Java-WebSocket#212]
Alright, so I've got an odd issue happening here. I suspect it may have something to do with my code, but I figure I'd post it here if maybe others have the same issue as I.

I am using this awesome server to run a highly specialized chat service. After about 30 minutes of running the server, I get an odd error logged in my console:

[SEVERE] Sep 28, 2013 8:01:07 PM: error while parsing message: {"action":"login","token":"a706a0a2a011b2fc4087fa8ef6fa3bdf121608774964945314fa9f7774cd3b0e2ca0a0c49d3389350b8051968f7fc39b3fe16a0f3421d8238fce5faa81603405d734325bca6106c4d64ed93d3d81718310f72ef885bf6bd48864b539eeb8102e67cd14864150b6b96f6ad3b8c30fc34ca0632e2e79525b0b5c5b304ccdb3a6eb69e2affd58e64e6439a71d8a086d4a91"}

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "WebSocketWorker-15"

The first SEVERE is not a problem, as I catch those errors safely - the odd part is the NPE. This is not normally thrown after an error. 
This NPE should not be thrown, let alone be uncaught. I suspect this may be an issue with my error handler, but I am not positive at this point;

```
@Override
public void onError(WebSocket ws, Exception excptn)
{
    Main.getLogger().log(Level.SEVERE, "an error occured in socket " + ws.getRemoteSocketAddress().toString(), excptn);
    excptn.printStackTrace(System.err);

    IConnectedUser user = _userData.get(ws);

    if (user != null && user.isLoggedIn())
        user.disconnect();
    else
        _connectingUsers.remove(ws);

    if (ws.isOpen())
        ws.close();
}
```

Anyways, after receiving this error, 10 minutes later or so the chat will become completely unresponsive. If I break the service, it looks like this: http://i.imgur.com/VAvFkZB.png

There are no detected deadlocks. I am at a loss as to what is causing this NPE, as the stack trace is not being output to the console/logger.

EDIT: I realized that during handleFatal it calls onError with a null WebSocket, so I adapted my code to handle it. I'm running the server again to catch that case and see what it's actually giving me.

**Comment by metamorphy** [comment]
I was getting:
`Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "WebSocketWorker-XX"`
and worried it was an error in the library. However, it turned out the exception was thrown in my onMessage handler, which was not caught until the `catch ( RuntimeException e )` in the code posted in #207. The exception was thrown by an incorrect assert() in my code and I didn't realize Eclipse wasn't configured to catch AssertionError.

Anyway, if you see this error, you might try to put a catch in your onMessage handler.

**Comment by soylomass** [comment]
@metamorphy Hi, may I know how did you solve it? I've put a try catch there, but it still crashes. https://github.com/TooTallNate/Java-WebSocket/issues/379

**Comment by metamorphy** [comment]
Like I wrote, I put it a catch in my onMessage handler, which solved it for me. So now my code is:

```
@Override
public void onMessage(WebSocket conn, ByteBuffer message) {
	// If the message is in bytes, this method is called.
	String m = null;
	try {
		m = new String(message.array());
		onMessage(conn, m);

	} catch (Exception e) {
		// Catch all exceptions, otherwise they cryptically show up in WebSocketWorker
		logger.error("Uncaught exception when processing onMessage(ByteBuffer): '" + (m != null ? m : "(null)") + "' -- " + e.getMessage(), e);
	}
}

@Override
public void onMessage(WebSocket ws, String message) {
	if (ws == null) {
		logger.error("onMessage with null websocket. Message: " + message);
		return;
	}
				
	try {
...lots of stuff...		
	} catch (Exception e) {
		// Catch all exceptions, otherwise they cryptically show up in WebSocketWorker
		logger.error("Uncaught exception when processing onMessage(String): '" + message + "' -- " + e.getMessage(), e);
	}
}
```

**Comment by marci4** [comment]
duplicate/extends #379
