### ISSUE TITLE
WebSocketClient and writeThread cannot be garbage collected

### ISSUE THREAD

**Issue by ddrscott** [TooTallNate/Java-WebSocket#217]
![screen shot 2013-11-21 at 9 42 42 am](https://f.cloud.github.com/assets/1975119/1592922/e0eab754-52c3-11e3-967e-5cefa00420eb.png)

**Comment by marci4** [comment]
Thx for your input in this project!

This is merged to the main branch now :)

Greetings
marci4

**Comment by marci4** [comment]
Well I quess I f**ked up here.

Checking the related pull request #218 and using the StressTest doesnt show any problems.

Greetings
marci4
