### ISSUE TITLE
Other Request Handlers....

### ISSUE THREAD

**Issue by supertick** [TooTallNate/Java-WebSocket#221]
Hello David,

I have been away for a while, but as I mentioned in my last post https://github.com/TooTallNate/Java-WebSocket/issues/197 I'd be back :)

Previously I had mentioned that I'd like to have a call-back for the user, so HTTP requests could be relayed to the user's code.  I'm still very interested in this topic.

There seems to have been a lot of activity to Java-websockets project.  Again, thanks for
sharing such a great project.  I've looked over some of the design and code and appreciate the 
density of functionality and compactness.  It's nice to have a well designed project without a bazillion dependencies dragged along. 
Nice !

I've noticed the clientHeader is no longer available and the decoding is attempted in each Draft.
It made me think that if the Draft decoding finishes and there were no successful upgrades, then
that would be the time for the connection to be sent to the user.

This is my attempt to implement the "non-websocket" call back.
I tried to implement it with the least amount of impact and following the same style and design as what I saw in java_websockets

The changes are small and confined only to two files:

WebSocketImpl.java - had to handle draft == null on opening and closing connections

WebSocketListener.java gets a new callback method :
/*\* This method is activated when no valid websocket Draft is found. */
    public void onRawOpen(WebSocket conn, ByteBuffer d);
An example of a silly HTTP 1.0 response would be the following:
@Override
    public void onRawOpen(WebSocket conn, ByteBuffer d) {
        String s = new String(d.array());
        String sub = s.substring(0, d.limit());

```
    log.info(String.format("onRawOpen %s", sub));
    String response =
        "HTTP/1.0 200 OK\r\n"
                    + "Content-Type: text/html; charset=utf-8\r\n"
                    + "\r\n"
                    + "<html>\r\n"
                    + "hello java_websocket !\r\n"
                    + "</html>\r\n"
                    + "\r\n";
    conn.send(response);
    conn.close();
}
```

Obviously, more dynamic response handlers could be used, but all would depend on the users code and not Java-WebSocket library.
The user would then have the ability to implement any type of response handler they thought was important.. e.g. 
 HTTP 1.1, REST API, SOAP, JSP etc, etc....  
without further changes to the java-websocket library.

I would like to send you the 2 files for you to review...
Thanks.

Regards,
Greg.

**Comment by marci4** [comment]
Closing this issue for #490 

Greetings
marci4
