### ISSUE TITLE
Worker threads do not close if bind() fails

### ISSUE THREAD

**Issue by GiGurra** [TooTallNate/Java-WebSocket#222]
In case the host port (e.g. 80) is occupied on the host (let's say running another web server), you expect a bind error and then the server to close down.

The server's main thread/selector thread does shut down in that scenario, but its worker threads do not.

The reason is that in case of bind() failure, WebSocketServer.run() returns before the try-catch-finally-block which in finally contains shutdown of worker threads.

**Comment by marci4** [comment]
Fixed with #477
