### ISSUE TITLE
can this connect to node ws server?

### ISSUE THREAD

**Issue by ken-okabe** [TooTallNate/Java-WebSocket#229]
The node server side endpoint is verified with other Java UDP client, so permission or the other factors should be no problem

Now, I made a server with  node.js  - ws
`ws`: The fastest RFC-6455 WebSocket implementation for Node.js.

http://einaros.github.com/ws
https://github.com/einaros/ws

The Java client has an error:

`-1 draft org.java_websocket.drafts.Draft_17@533651a8 refuses handshake`

Has anyone succeeded to connect node ws server?

The client device is Android Emulator(Genymotion).
The server is the hostMahcine localhost: 'ws://10.0.3.2:9000'

Just in case.

**Comment by zjulia** [comment]
This is an old thread but I am getting the same `draft org.java_websocket.drafts.Draft_17@4566ba50 refuses handshake` error. How did you fix it? Does anyone know? I am also trying to connect to a ws server.
