### ISSUE TITLE
use java-websocket wss as server on android？

### ISSUE THREAD

**Issue by zjbpku** [TooTallNate/Java-WebSocket#230]
i study the project for three days , want to use wss in my project ,but i doesn't solve the  
problem : how to connect to server on android via browser , where can i find a demo like this ?plz

**Comment by munnadroid** [comment]
+1

**Comment by marci4** [comment]
Hello @zjbpku,

you can find a simple example [here](https://github.com/marci4/AndroidJavaWebsocketExample).

Greetings
marci4
