### ISSUE TITLE
How to limit message size before transmission complete? (Anti-DoS)

### ISSUE THREAD

**Issue by ghost** [TooTallNate/Java-WebSocket#234]
Is it possible to limit the size of an incoming message before it has been fully transmitted?

I'm trying to harden my server against DoS attacks using large messages.

Love this lib!

**Comment by dOhx** [comment]
Is not working for me i use Draft from "org.java-websocket:Java-WebSocket:1.5.1", but Draft_17() not exists, only Draft_6455(), but this has no Setter for setMaximumPayloadSize().
