### ISSUE TITLE
List of all send() related exceptions.

### ISSUE THREAD

**Issue by ghost** [TooTallNate/Java-WebSocket#237]
(Java noob)

Thank you all for such a great lib!

I'm making a peer to peer application that both accepts and seeks connections, so I'm using both `WebSocketClient` and `WebSocketServer`.

After having fun with `NullPointerException` when trying to use a closed connection, I've noticed that `send()` throws `NotYetConnectedException` and `IllegalArgumentException`.

I also noticed however `WebsocketNotConnectedException` as well.  Can `send()` throw that?

Also, are there any other exceptions that could be thrown when trying to send from another thread which manages all communications for both clients and servers?

**Comment by marci4** [comment]
I updated the wiki with short explanations for all the relevant exceptions.

Closing the issue.
Greetings
marci4
