### ISSUE TITLE
Putting WebSocket/ClientWebSocket in a Map costs ~130MB

### ISSUE THREAD

**Issue by ghost** [TooTallNate/Java-WebSocket#243]
If I put a WebSocket or WebSocketClient into a Map, WeakHashMap, or ConcurrentHashMap as a key, it costs ~130MB of memory.

Is this normal, or am I doing something incorrectly?  I can provide code if necessary.

**Comment by rjbergTU** [comment]
Well, I do not know if this is still relevant after 2 years, but it might be due to the fact you are using a HashMap. They use a lot of extra memory as empty space.

**Comment by marci4** [comment]
This and it is also not the correct way to measure the size of an object.

Keep in mind, what you see using the system monitor is the total ram used including handling handshakes, de/-encrypting messages etc etc.
The actual size if a websocket object is way lower!

Apart from this, the user is not any more part of github and this thread is over 2 years old.
Closing it!

Greetings
marci4
