### ISSUE TITLE
Deploy new version into Maven Central

### ISSUE THREAD

**Issue by mparis** [TooTallNate/Java-WebSocket#252]
Hello,
I am working with WSS and it works well ;).
I have got it downloading the source code and installing it in local with maven, but I want to use Maven Central dependency (http://mvnrepository.com/artifact/org.java-websocket/Java-WebSocket).
The problem is that the current version is 1.3.0 and WSS is available in 1.3.1-SNAPSHOT version.
As I see, the code is stable since few months ago. So, is it possible to deploy a new release to Maven Central?

**Comment by daluu** [comment]
@jasminsehic I have question for you under your pull request.

**Comment by daluu** [comment]
Also, for others, if clojars repo doesn't seem to be working for you, or you want to host this project's JAR in internal repo or locally with your project, you can do something like what I did here:

https://gist.github.com/daluu/52af7eef52563ddf78fe

it's no big deal for those of us who are using maven anyways, so build your own copy of the latest JAR with maven and then package it for local hosting or dependency management. Granted having an official public repo to pull from is better.

**Comment by marci4** [comment]
I pushed an update to clojars.

Greetings
marci4
