### ISSUE TITLE
Subprotocol Negotiation

### ISSUE THREAD

**Issue by darkl** [TooTallNate/Java-WebSocket#253]
Hi,
Thanks for the work on this library!
I've been playing with it and it looks great.

I have a question - I'm trying to use the WebsocketClient with a given sub-protocol, and I'm not sure how to do this.
Any pointers on this?

Thanks

**Comment by dbrgn** [comment]
There's more discussion and a possible solution in #311.

**Comment by marci4** [comment]
Hello @darkl,

I added an example to the wiki how you can implement a custom Sec-Websocket-Protocol.
Check it out [here](https://github.com/TooTallNate/Java-WebSocket/wiki/Implementing-your-own-Sec-WebSocket-Protocol).

Hope this helps you!

Greetings
marci4
