### ISSUE TITLE
Server establish with android wifi and hotspot off

### ISSUE THREAD

**Issue by stereo720712** [TooTallNate/Java-WebSocket#254]
Excuse me,Does it can establish Websocket Server with the localohst string?
It's like this:
                    server = new SimpleServer(new InetSocketAddress("localhost",10000));

I hope I can use it when the android's wifi & hotspot are both disabled.
Now the localhost is fail to Create Server.

**Comment by marci4** [comment]
Hello @stereo720712 
have you tried using 127.0.0.1 instead?

Greetings
marci4

**Comment by marci4** [comment]
Testet it also with the latest version running client and server in an app!

Works with 127.0.0.1

Closing issue!
Greetings
marci4
