### ISSUE TITLE
how to reconnect websocket

### ISSUE THREAD

**Issue by YangLzy** [TooTallNate/Java-WebSocket#256]
Hi,
Thanks for the work on this library!
I've been playing with it and it looks great.
My question is :how can i reconnect websocket? Here is my mehtod in my app:
![socketcode](https://cloud.githubusercontent.com/assets/7455060/2849605/6cd86d44-d0df-11e3-8975-222d3b8b4744.jpg)

the problem is when I reconnect websocket my reconnectWebSocket method stuff sometimes,even reconect method donot work(i guess that my reconectThread is recycled??),here is my code about reconnect websocket:
    // Reconect websocket Receiver
    private class ReconnectReceiver extends BroadCastReceiver {
        public void onReceive(Context ctx, Intent i) {
            // to reconect websocket
            reconnectWebSocket();
        }
    }

```
private void reconnectWebSocket() {
    // TODO Auto-generated method stub
    new Thread() {
        private URI mSocketUri;

        @Override
        public void run() {
            super.run();
            boolean connectBlocking = new WebSocketClient(mSocketUri,
                    new Draft_17()).connectBlocking();
        }
    };
}
```

 any one can give my any suggestion? Thanks!

**Comment by yin450561200** [comment]
Anyone successful in reconnecting ?

**Comment by marci4** [comment]
Hello everyone,

right now the best way to reconnect is just to call the constructor again and use a new instance of a websocketclient.

Greetings
marci4

**Comment by lixuebo0630** [comment]
Anyone successful in reconnecting ?

**Comment by tiagosantos1988** [comment]
Here is an example class that reconnects the websocket whenever the connection is lost:

`public class JWebSocketClient {

   private final int PING_INTERVAL = 50000;
   private final int RECONNECT_INTERVAL = 10000;
   private final int WEBSOCKET_TIMEOUT = 5;
   private static JWebSocketClient instance;

   private WebSocketClient websocketClient;
   private IWebSocketListener listener;

   private String myChannel;
   private String myInstance;
   private String myWebSocket;
   private static Boolean isReconnecting = false;
   private static Boolean isStarting = false;

   public static JWebSocketClient getInstance() {
      if (instance == null) {
         instance = new JWebSocketClient();
      }
      return instance;
   }

   public boolean isConnected() {
      try {
         return websocketClient != null && websocketClient.getConnection().isOpen();
      } catch (Exception e) {
         return false;
      }
   }

   public void start(String userEmail, String userInstance, String webSocketHost, IWebSocketListener listener) {
      this.myChannel = "uc_" + userEmail.replace("@", "_").replace(".", "_");
      this.myInstance = userInstance + "." + userEmail;
      this.myWebSocket = webSocketHost + "/v1/service/" + myInstance;
      this.listener = listener;

      if (!isConnected() && !isStarting) {
         isStarting = true;
         new JStartWebSocket().run();
      }
   }

   public void stop() {
      try {
         if (isConnected()) {
            websocketClient.close();
         }
      } catch (Exception e) {
      } finally {
         websocketClient = null;
      }
   }

   public boolean sendMessage(String message) {
      try {
         if (isConnected() && message != null) {
            websocketClient.send(message);
            return true;
         } else {
            return false;
         }
      } catch (NotYetConnectedException e) {
         return false;
      }
   }

   private void reconnect() {
      if (!isReconnecting && !isConnected()) {
         isReconnecting = true;
         new JRestartWebSocket();
      }
   }

   private void sendDelayedMessage() {
      new JSendDelayMessage();
   }

   private class JStartWebSocket implements Runnable {

      public JStartWebSocket() {
         ThreadFactory customThreadfactory = new JThreadFactoryBuilder().setNamePrefix("thread_JStartWebSocket").build();
         customThreadfactory.newThread(this);
      }

      @Override
      public void run() {
         try {
            websocketClient = null;
            System.out.println("******** NEW WEBSOCKET INSTANCE ********");
            System.out.println("**** URL: " + myWebSocket + " ****");
            websocketClient = new WebSocketClient(new URI(myWebSocket), new Draft_6455()) {

               @Override
               public void onMessage(String message) {
                  listener.onWebSocketMessageReceive(message);
               }

               @Override
               public void onOpen(ServerHandshake handshake) {
                  System.out.println("******** WEBSOCKET CONNECTED ********");
                  sendDelayedMessage();

                  listener.onWebSocketConnect();
               }

               @Override
               public void onWebsocketPing(WebSocket conn, Framedata f) {
                  try {
                     FramedataImpl1 frame = new FramedataImpl1(Opcode.PONG) {
                        @Override
                        public void isValid() throws InvalidDataException {
                        }
                     };
                     frame.setFin(true);
                     if (isConnected() && conn != null && conn.isOpen()) {
                        conn.sendFrame(frame);
                     }
                     System.out.println("******** WEBSOCKET PING-PONG ********");
                  } catch (NotYetConnectedException e) {
                  }
               }

               @Override
               public void onClose(int code, String reason, boolean remote) {
                  System.out.println("********\n\nWEBSOCKET CLOSED\n\nReason:" + reason + "\nCode: " + code + "\nRemote: " + remote + "\n\n********");
                  if (remote || code != 1000) {
                     reconnect();
                  }
                  listener.onWebSocketClose(code, reason, remote);
               }

               @Override
               public void onError(Exception ex) {
                  System.out.println("WEBSOCKET ERROR: " + ex.toString());
                  reconnect();
                  listener.onWebSocketError(ex);
               }
            };

            if (myWebSocket.startsWith("wss")) {
               SSLSocketFactory socketFactory = getSSLSocketFactory();
               websocketClient.setSocket(socketFactory.createSocket());
               websocketClient.setConnectionLostTimeout(WEBSOCKET_TIMEOUT);
               websocketClient.connect();
               //System.out.println(websocketClient.getConnection().toString());
            }

         } catch (IOException | URISyntaxException e) {
            System.out.println("WS error: " + e);
         } finally {
            isStarting = false;
         }
      }
   }

   private class JRestartWebSocket implements Runnable {

      private ScheduledExecutorService scheduler = null;

      public JRestartWebSocket() {
         ThreadFactory customThreadfactory = new JThreadFactoryBuilder().setNamePrefix("thread_JRestartWebSocket").build();
         scheduler = Executors.newScheduledThreadPool(1, customThreadfactory);
         scheduler.schedule(this, RECONNECT_INTERVAL, TimeUnit.MILLISECONDS);

      }

      @Override
      public void run() {
         if (!isConnected()) {
            System.out.println("********* RECONNECT WEBSOCKET **********");
            try {
               if (!isStarting) {
                  isStarting = true;
                  new JStartWebSocket().run();
               }
            } catch (Exception ex) {
               System.out.println("WebSocket Connect Error " + ex.toString());
            } finally {
               scheduler.schedule(this, RECONNECT_INTERVAL, TimeUnit.MILLISECONDS);
            }
         } else {
            isReconnecting = false;
         }
      }
   }

   private class JSendDelayMessage implements Runnable {

      private ScheduledExecutorService scheduler = null;

      public JSendDelayMessage() {
         ThreadFactory customThreadfactory = new JThreadFactoryBuilder().setNamePrefix("thread_JSendDelayMessage").build();
         scheduler = Executors.newScheduledThreadPool(1, customThreadfactory);
         scheduler.schedule(this, PING_INTERVAL, TimeUnit.MILLISECONDS);
      }

      @Override
      public void run() {
         if (isConnected()) {
            try {
               sendMessage(myChannel);
            } catch (NotYetConnectedException ex) {
               System.out.println("WebSocket Send Channel Error " + ex.toString());
            } finally{
               scheduler.schedule(this, PING_INTERVAL, TimeUnit.MILLISECONDS);
            }
         }
      }
   }

   private SSLSocketFactory getSSLSocketFactory() {
      try {
         SSLContext sslContext;
         TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
            @Override
            public java.security.cert.X509Certificate[] getAcceptedIssuers() {
               return new java.security.cert.X509Certificate[]{};
            }

            @Override
            public void checkClientTrusted(X509Certificate[] chain,
                    String authType) throws CertificateException {
            }

            @Override
            public void checkServerTrusted(X509Certificate[] chain,
                    String authType) throws CertificateException {
            }
         }};

         KeyManager[] keyManager = null;
         try {
            final KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
            KeyManagerFactory factory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            factory.init(keyStore, null);
            keyManager = factory.getKeyManagers();
         } catch (NoSuchAlgorithmException | UnrecoverableKeyException | KeyStoreException e) {
         }

         try {
            sslContext = SSLContext.getInstance("TLS");
            sslContext.init(keyManager, trustAllCerts, new java.security.SecureRandom());
            return sslContext.getSocketFactory();
         } catch (KeyManagementException | NoSuchAlgorithmException e) {
            return null;
         }
      } catch (Exception ex) {
         System.out.println("Erro no getSSLContext");
         return null;
      }
   }
}`

**Comment by marci4** [comment]
Hey everyone, 

I will try to provide a working solution for this!

Greetings
marci4

**Comment by yuksels** [comment]
Release 1.3.8  ?
