### ISSUE TITLE
DoS attacks

### ISSUE THREAD

**Issue by mwambler** [TooTallNate/Java-WebSocket#262]
This  is more of a question about the API.  I was reviewing the API last night, and it seems a good place to intercept the growing incoming message size is:

WebSocketImpl
public void decode( ByteBuffer socketBuffer )

Please let me know if there's a better place to test for the incremental message size, or if this is already implemented somewhere.  I'd like to prevent users, and or attackers from posting large amounts of data through the server by closing the connection once a certain size limit is reached.

thanks

-Mark

**Comment by marci4** [comment]
This issue is implemented with #598.

Best regards,
marci4
