### ISSUE TITLE
How to use a SSL WebSocket client

### ISSUE THREAD

**Issue by yellowiscool** [TooTallNate/Java-WebSocket#263]
Hello

I am trying to use your library with a SSL Websocket Server.

I tried to use something like `new MyClient(new URI("wss://example.net/"));` but I got this error : `400 The plain HTTP request was sent to HTTPS port`

Then, I found [an example related to the 1.3.0 version on the repository](https://github.com/TooTallNate/Java-WebSocket/blob/Java-WebSocket-1.3.0/src/main/example/SSLClientExample.java#L60-L84). But it's extremely complex, I should be missing something.

Do you have an example for a simple SSL WebSocket client ?

**Comment by AngellusMortis** [comment]
I am also having trouble getting an SSL connection to work. I am using nodeJS+[ws](https://github.com/websockets/ws) and when I turn off SSL and use `ws://` it works, but when SSL is on and I use `wss://` it does not. The server is set up and configured fine as I have a JavaScript client connecting to it and using it with the `wss://` and SSL. It is also not a self-signed cert. 

Code:

    public SocketClientHandler(Plugin plugin, URI socket_url) throws InvalidClassException {
        super(socket_url, new Draft_17());
        this.plugin = plugin;

        if (socket_url.toString().startsWith("wss")) {
            this.plugin.getLogger().info("Socket: Using SSL");
            try {
                SSLContext sslContext = null;
                sslContext = SSLContext.getInstance("TLS");
                sslContext.init(null, null, null);
                this.setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sslContext));
            } catch (NoSuchAlgorithmException | KeyManagementException e) {
                throw new InvalidClassException("Could not initialize SSL connection");
            }
        }
    }

Logs (without SSL):

    [08:22:57] [Thread-10/INFO]: write(151): {GET / HTTP/1.1
    Connection: Upgrade
    Host: somehost.com:9000
    Sec-WebSocket-Key: KkCG4JWnHB9laXGxi/82uQ==
    Sec-WebSocket-Version: 13
    Upgrade: websocket

    }
    [08:22:57] [Thread-10/INFO]: process(129): {HTTP/1.1 101 Switching Protocols
    Upgrade: websocket
    Connection: Upgrade
    Sec-WebSocket-Accept: o8XnegQLdYlURafEgvKhAqwukz0=

    }
    [08:22:57] [Thread-10/INFO]: open using draft: Draft_17
    [08:22:57] [Thread-10/INFO]: Sockets: onOpen

Logs (with SSL):

    [08:31:12] [Server thread/INFO]: Socket: Using SSL
    [08:31:12] [Thread-10/INFO]: write(151): {GET / HTTP/1.1
    Connection: Upgrade
    Host: somehost.com:9000
    Sec-WebSocket-Key: GQ6/FA8/Hz0wktFml+q4hQ==
    Sec-WebSocket-Version: 13
    Upgrade: websocket

    }
    [08:31:12] [Thread-10/INFO]: Sockets: onClose: -1  true

**Comment by ilber** [comment]
I have the same problem here. 

Closed draft org.java_websocket.drafts.Draft_10@14e30802 refuses handshake .... And then:

 Error ssl == null
    java.lang.NullPointerException: ssl == null
            at com.android.org.conscrypt.NativeCrypto.SSL_read_BIO(Native Method)
            at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:477)
            at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1006)
            at org.java_websocket.SSLSocketChannel2.unwrap(SSLSocketChannel2.java:150)
            at org.java_websocket.SSLSocketChannel2.readRemaining(SSLSocketChannel2.java:254)
            at org.java_websocket.SSLSocketChannel2.readMore(SSLSocketChannel2.java:321)
            at org.java_websocket.SocketChannelIOHelper.readMore(SocketChannelIOHelper.java:28)
            at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:238)
            at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
            at java.lang.Thread.run(Thread.java:818)

Someone has any idea? Its working fine with the wss://echo.websocket.org but not with my production server.

Thank you for your help.

Regards,

Ilber

**Comment by chetbox** [comment]
Note that you can also use `SSLContext.getDefault()` rather than the somewhat mysterious `init(null, null, null)`.

```java
if (uri.getScheme().equals("wss")) {
    try {
        SSLContext sslContext = SSLContext.getDefault();
        setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sslContext));
    } catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
    }
}
```

In my case the issue was that I hadn't included the full certificate authority (CA) chain on my server. Chrome happens to include the intermediate CA my server certificate is signed with as well as the root CA but Android only includes the root CA. (Their names were subtly different which I hand't noticed before.)

You can see which CAs your device recognises by going to
`Settings` > `Security` > `Trusted credentials`

**Comment by pkolanda** [comment]
I got  - refuses handshake , false    - then changed the code as below:
        SSLContext sslContext = null;
        try {
            sslContext = SSLContext.getDefault();
        } catch (NoSuchAlgorithmException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sslContext));

Draft_17. 
I get : closed connection -1 ,  , true. 
Any help here. This happens during socket creation. I know this very old thread. But now i am in this stage only.

**Comment by pkolanda** [comment]
Need to create sslcontext like below. it skips the certificate. I was successfully able make a connection without certificate

SSLContext sslContext = SSLContext.getInstance("SSL");

// set up a TrustManager that trusts everything
sslContext.init(null, new TrustManager[] { new X509TrustManager() {
            public X509Certificate[] getAcceptedIssuers() {
                    System.out.println("getAcceptedIssuers =============");
                    return null;
            }

            public void checkClientTrusted(X509Certificate[] certs,
                            String authType) {
                    System.out.println("checkClientTrusted =============");
            }

            public void checkServerTrusted(X509Certificate[] certs,
                            String authType) {
                    System.out.println("checkServerTrusted =============");
            }
} }, new SecureRandom());

**Comment by marci4** [comment]
Hello everyone,
is this currently still an issue with the latest version of the lib?

Using SSL in production without any problems!

Greetings
marci4

**Comment by cong91** [comment]
Hi everyone. 
is this currently my problem. But lastest version in class WebSocketClient delete function setWebSocketFactory. I can't found same function for SSL in WebSocketClient. 
Please share for you tutorial.
Thanks for share.
CongNT

**Comment by marci4** [comment]
Hello @cong91,

sorry for that :( it was removed a long time ago, but nobody updated the lib!

Please check out this example for SSL in the WebSocketClient https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLClientExample.java

Greetings
marci4

**Comment by marci4** [comment]
No answer for over two months. 

Mentioned issues are also covered by other issues!

Closing this one.
Greetings
marci4

**Comment by clackmac** [comment]
Hey @marci4 , is it possible `setSocketFactory` is not available? I noticed a `@since 1.4.0` which I believe is no longer released.

**Comment by marci4** [comment]
Hello @clackmac,

this was added with #764

Best regards,
marci4

**Comment by clackmac** [comment]
Thanks for the quick response and sorry to bother but do you have any idea when the next release is going to be? 
BTW: I'm using the library on an android project

**Comment by marci4** [comment]
No ETA since I am just to busy with RL and trying to reduce my stress levels.

**Comment by clackmac** [comment]
More than fair! haha
Have a good one man 🍻and thank you for your work =D.

**Comment by marci4** [comment]
You can however always use the latest snapshot ;) https://oss.sonatype.org/content/repositories/snapshots/org/java-websocket/Java-WebSocket/

**Comment by clackmac** [comment]
Cool! Thanks man, really appreciate it 🙏
I'll test my app a little bit more with 1.3.9 which seems to be working at the moment but I'll keep your suggestion as an option in case something arises.

**Comment by feng612266** [comment]
> 
> 
> Cool! Thanks man, really appreciate it 🙏
> I'll test my app a little bit more with 1.3.9 which seems to be working at the moment but I'll keep your suggestion as an option in case something arises.

hello,clackmac,I had use the latest snapshot lib,and setSocketFactory after new webcokctclient ,but still have SSLHandshakeException java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. if i use this sslContext.init( null, null, null ),the "keystore.jks" can not set is that?

**Comment by clackmac** [comment]
Hey @feng612266, in my scenario the latest version worked just fine. FYI: I was not using client cert validation via keystore.
Having said that, I had another test environment having a certificate with an invalid CA chain and in that case I tried the latest snapshot (1.4.0) using the sample code, again, without using cert validation via keystore but accepting all certificates as valid. Even though the latter worked, that's not very secure, but that specific implementation was for testing purposes and not my final approach.

**Comment by feng612266** [comment]
> 
> 
> Hey @feng612266, in my scenario the latest version worked just fine. FYI: I was not using client cert validation via keystore.
> Having said that, I had another test environment having a certificate with an invalid CA chain and in that case I tried the latest snapshot (1.4.0) using the sample code, again, without using cert validation via keystore but accepting all certificates as valid. Even though the latter worked, that's not very secure, but that specific implementation was for testing purposes and not my final approach.

thank you @clackmac now it worked fine , I was not using client cert validation via keystore too. I fund this way online:
                   try {
                            sslContext.init(null, new TrustManager[]{
                                    new X509TrustManager() {

                                        @Override
                                        public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) {

                                        }

                                        @Override
                                        public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) {

                                        }

                                        @Override
                                        public X509Certificate[] getAcceptedIssuers() {
                                            return new X509Certificate[0];
                                        }
                                    }
                            }, new SecureRandom());
                        } catch (KeyManagementException e) {
                            e.printStackTrace();
                        }
                        SSLSocketFactory factory = sslContext.getSocketFactory();
                        mWebSocket.setSocketFactory(factory);
