### ISSUE TITLE
Swallowing exceptions.

### ISSUE THREAD

**Issue by ps2** [TooTallNate/Java-WebSocket#265]
https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/client/WebSocketClient.java#L189

The above line swallows exceptions such as the following:
javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair

According to http://stackoverflow.com/questions/6851461/java-why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception, that particular exception is a bug in java, but it was difficult to track down what was happening, since java-websocket was swallowing the exception, and making it look like the websocket was closing.

**Comment by BrushfireDigitalServices** [comment]
Agreed, behavior should differ based on whether the exception arose from a bug in our code or in other libraries. I will mention the problem and its location as part of my documentation pass on WebSocketClient, and leave the fix up to the next bug-fixing pass.

**Comment by marci4** [comment]
SSLExceptions will call onError now as well (see #516)

Closing issue!
Greetings
marci4
