### ISSUE TITLE
Problem connecting to server using Draft-76

### ISSUE THREAD

**Issue by MarcoDisco** [TooTallNate/Java-WebSocket#266]
Hi,

Like a previous poster, I am hoping that this issue can be resolved with some advice.  Essentially I cannot get an android client using java-websockets with draft_76 to connect to a websocket server that uses Hixie-76.

I have created a test app from your example code.   When I do mWebSocketClient.connect() neither the onOpen or onError callbacks are executed.  I notice onClose is called.  I was wondering if this is a protocol handshake issue?

For background,
I am implementing a project that is using Redis for some publish/subscribe functionality. Our servers will publish updates to Redis and subscribed clients (android app) will receive the updates.

Webdis is a http-based front-end to Redis and advertises that it can handle websocket clients using Hixie-76 protocol.  I was hoping that our android-based clients could use java-websockets + Draft_76 to implement the client subscription functionality.

The Webdis+websockets component has been tested using Chrome/Javascript, and all seems to work well.  I can create a javascript www page to connect to the Webdis websockets port ws://192.168.2.4:7379/.java and issue a subscribe command via the websocket 'SUBSCRIBE/42' (where 42 is the channel).   Then, using a browser I can just navigate to (for example) http://192.168.2.4/PUBLISH/42/TestMessage  and 'TestMessage' will be received by the client javascript page.

I have made wireshark packet-captures of the traffic exchanged during a successful connect to Webdis via my Javascript client, and the unsuccessful attempt using the java-websockets based Android client.  Both look very similar, just that nothing happens in Java after the response is received from Webdis.

Here is my connect method, called from a button onClick:

```
private void connectWebSocket() {
    URI uri;
    try {
        uri = new URI("ws://192.168.2.4:7379/.json");
    } catch (URISyntaxException e) {
        System.out.println("Error creating URI");
        e.printStackTrace();
        return;
    }

    Draft_76 mydraft76 = new Draft_76();

    Log.v(APPNAME, "Before instantiating WebSocketClient");
        mWebSocketClient = new WebSocketClient(uri, mydraft76) {

        @Override
        public void onOpen(ServerHandshake serverHandshake) {
            runOnUiThread(new Runnable() {
                @Override
                public void run() {

                System.out.println("websocket opened");
                //Log.i("Websocket", "Opened");
                //mWebSocketClient.send("Hello from " + Build.MANUFACTURER + " " + Build.MODEL);

                Log.v(APPNAME, "trying subscribe 1");
                mWebSocketClient.send("\"SUBSCRIBE/42\"");

                }
            });
        }
        @Override
        public void onMessage(String s) {
            final String message = s;
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Log.v(APPNAME, "Message received " + message);
                }
            });
        }
        @Override
        public void onClose(int i, String s, boolean b) {
            //Log.i("Websocket", "Closed " + s);
            Log.v(APPNAME, "Websocket Closed " + s);
        }
        @Override
        public void onError(Exception e) {
            Log.v(APPNAME, "Websocket Error" + e.getMessage());
        }
    };

   Log.v(APPNAME, "Before websocket connect.....");
    mWebSocketClient.connect();
    Log.v(APPNAME, "After websocket connect.");
}
```

I would very much appreciate any suggestions that you might have on this issue.

Thanks,
Mark

**Comment by derekcsm** [comment]
Hey did you end up solving this?

**Comment by marci4** [comment]
Hello @MarcoDisco 

please dont use Draft_75 any more!

It is recommended to use Draft_17!
(Read up on drafts [here](https://github.com/TooTallNate/Java-WebSocket/wiki/Drafts))

Greetings
marci4
