### ISSUE TITLE
FYI - WebSocket server may not respond on Android L dev release

### ISSUE THREAD

**Issue by RoundSparrow** [TooTallNate/Java-WebSocket#267]
Android L release on Nexus 7 seems to not respond on Websocket server hosting. Identical code on Android 4.4.4 and 4.3 releases do not seem to have this same problem.

For reference, https://github.com/koush/AndroidAsync Websocket Server does not seem to have this behavioral difference - works fine on all the same versions.  Tested clients: Firefox and Chrome.

**Comment by marci4** [comment]
duplicate of #424
