### ISSUE TITLE
There is no notification for websocket server success start

### ISSUE THREAD

**Issue by farin** [TooTallNate/Java-WebSocket#271]
I can listen to onError to get startup errors (like: bind, address alredy used) - (it still not perfect because it is not limited to start up errors only) But is still  impossible to wait for success start.

Practical example - I have app which runs websocket server and connect to it internally. Additionally basic (server+client) to mode it can be used in strictly client mode connecting remotely to another running app. 

When starting internal server in basic mode app also needs to connect it.  I can start and connect immediatelly, that works for common user scenario. But what if another app instance in basic mode is already running. Server start() triggers onError (but in it's own thread) and my immdiate connect makes connection to alredy running app instance.  (but that is wrong, i wanna only connection to my server or fail. Without waiting for success start i am unable to prevent wrong connection.

**Comment by marci4** [comment]
Hello @farin,

I added a method onStart() for you and others to get notified, when no error occurred during startup.

Greetings
marci4
