### ISSUE TITLE
Add possibility to override worker thread allocation logic in WebSocketServer 

### ISSUE THREAD

**Issue by viagraphs** [TooTallNate/Java-WebSocket#279]
Hey, may I ask you for accepting a PR that does just 2 minor things, making 

```
WebSocketServer#decoders 
WebSocketServer#queue
```

protected field/method in order to do what's described here in the server's description : 
https://github.com/viagraphs/reactive-websocket
https://github.com/viagraphs/reactive-websocket/blob/master/jvm/src/main/scala/com/viagraphs/websocket/RxWebSocketServer.scala#L69

I'd like to contribute to Java-WebSocket in following several months when I'm gonna build a project around it.

**Comment by BrushfireDigitalServices** [comment]
@viagraphs On behalf of the whole Java-Websockets project, apologies for not getting to this sooner. This project is being actively administrated again, and any and all pull requests are welcome.

We are currently pushing to complete documentation and expand unit test coverage in anticipation of a new stable release. The new release prioritizes fixing our wss and race condition bugs, and may include new features.

Yours would be an excellent feature for inclusion. If you are still interested, please send us pull requests, participate in discussions, etc.

**Comment by marci4** [comment]
Thank you for your work!

Merged your changes into main branch!
Greetings
marci4
