### ISSUE TITLE
Get client cert on connection?

### ISSUE THREAD

**Issue by cgross** [TooTallNate/Java-WebSocket#283]
Is there a way to get the details of the client cert after connecting using SSL?  I don't see anything obvious in the API.

**Comment by marci4** [comment]
A quick search around the apis found nothing.

If anyone has a solution, feel free to post it here!

Best regards,
Marcel

**Comment by marci4** [comment]
Closing it for now as I see no solution.

If anyone has one, please ping me!

Best regards,
Marcel
