### ISSUE TITLE
"refuses handhsake" error after upgrafe from glassfish 4.0 to 4.1

### ISSUE THREAD

**Issue by greg-witczak** [TooTallNate/Java-WebSocket#284]
My Android app works as expected when application server is Glassfish 4.0 (with websocket 1.0). But after upgrading it to 4.1 (with websocket 1.1, which is fully backward compatible), I get error and `onClose` is called, instead of `onOpen`, with parameters:

`public void onClose(int code, String reason, boolean remote)`
Code: -1
Reason: draft org.java_websocket.drafts.Draft_10@42664cc0 refuses handshake
Remote: false

**Comment by CalvinKern** [comment]
For anyone else experiencing this problem, I was able to get a success by creating the WebSocket with a different draft type.

For example:
```
mWebSocket = new WebSocketClient(uri, new Draft_17()) {
...
}
```

**Comment by marci4** [comment]
Hello @greg-witczak,

as mentioned by @CalvinKern please use Draft_17!

Greetings
marci4

**Comment by sushant36** [comment]
did not help me Draft_17 deprecated in 1.3.4

**Comment by marci4** [comment]
Sorry. I deprecated Draft_17 with 1.3.4 because I want people to use the upcoming features for RFC_6455.

The new draft is now Draft_6455

Greetings
marci4
