### ISSUE TITLE
Dist JAR needs update.

### ISSUE THREAD

**Issue by raxetul** [TooTallNate/Java-WebSocket#286]
Dist JAR is not updated, some issues exist while source is working well.

**Comment by hellojinjie** [comment]
+1

**Comment by BrushfireDigitalServices** [comment]
Thanks for pointing out the problem! This bug will remain open until the jar is updated.

In the meantime, the master branch here is still the best place to find stable code. Now that this project is actively administrated again, you can expect more fixes, expanded documentation and test coverage, and (eventually) a new release.

The more community involvement and discussion, the better. Please keep contributing as you are interested and able.

**Comment by daluu** [comment]
I guess in the meantime, manually compile the needed Dist JAR with the sources (and maven) from this repo? If you don't want to link with sources and rather have a JAR that is.

**Comment by bendem** [comment]
The jar should be removed, not updated, storing binaries in repos is bad and as we can see, cause problems because maintainers forget to update it.

**Comment by raxetul** [comment]
Of course jars should not be in repos, but  they might be kept under
"release" with the source code which they are compiled from.
3 Ara 2015 22:50 tarihinde "bendem" <notifications@github.com> yazdı:

**Comment by daluu** [comment]
I didn't even notice the JAR was in the source code repo. I downloaded from the website homepage rather than Github page and assumed I was downloading a zip of the full package source + binary. Agree that the JAR should be under Github releases as a binary asset for download (for those that don't use maven, gradle, etc.)

**Comment by marci4** [comment]
Updated with #444
