### ISSUE TITLE
Android client Garbage collector issue

### ISSUE THREAD

**Issue by szczepaan** [TooTallNate/Java-WebSocket#290]
on android when i move to another activity and i finish activity with 

<pre>   private WebSocketClient mWebSocketClient;
</pre>

I see in logcat going mad message every 10 ms

<pre>
GC_FOR_ALLOC freed 512K, 4% free 17338K/17896K, paused 13ms, total 13ms
</pre>

how to propertly close websocket client and alla associated resources ?
I do

<pre> mWebSocketClient.close(); </pre>

but apparently it is not sufficient

when I set up the client I also use code

<pre>
SSLContext sslContext = null;
        try {
            sslContext = SSLContext.getInstance("TLS");
            sslContext.init(null, null, null); // will use java's default key and trust store which is sufficient unless you deal with self-signed certificates
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (KeyManagementException e) {
            e.printStackTrace();
        }
//
        mWebSocketClient.setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sslContext));
</pre>

maybe that has to do with it,
also when I tried to investigate what's allocated I found it was about

<pre>
AllocatedClass javax.net.ssl.SSLEngineResult    
Allocated in org.apache.harmony.xnet.provider.jsse.SSLEngineImpl    unwrap  
</pre>

any help?

**Comment by rzorzal** [comment]
I have this same problem, I tried create and connect using ```AsyncTask ```, ```Service on Background``` and on ``` Application Class ```, but still not working. 

Always 50 sec after connecting, it disconnected and then stops the communication with Object instantiated before. I think it happens , because all Threads and Objects has a lifetime and lifecycle and when that Objects are no longer used, they are destroyed and then the connection with server ends. But i don't have solution yet. 


PS: I'm not using SSL connection . I think is the same problem with garbage collector .

**Comment by douglasjunior** [comment]
I had this problem in version 1.3.0. 

I downloaded the current source code and put into my project, problem solved.

**Comment by renaudboulard** [comment]
I had the same issue with webSocket.close() and the GC, on my Android app.
@douglasjunior  what do you mean by "I downloaded the current source code and put into my project, problem solved" your downloaded source code, isn't the same as version 1.3.0 ?

**Comment by douglasjunior** [comment]
I did a `git Clone`. But that was a long time ago, I dont know how it is now.

**Comment by marci4** [comment]
Hello @renaudboulard and @szczepaan 

is this still an issue for you with the latest version of the lib?

Greetings
marci4

**Comment by marci4** [comment]
Probably related to #217

**Comment by marci4** [comment]
No feedback.

@douglasjunior mentioned that it is solved.

If there is still a problem, feel free to reopen the issue.
Greetings
marci4
