### ISSUE TITLE
Android 5.0 Lollipop wss stopped working

### ISSUE THREAD

**Issue by szczepaan** [TooTallNate/Java-WebSocket#293]
Hey,

below code worked for Android 4.x.x (also Kitkat), and stopped working on Lollipop

<pre>
SSLContext sslContext = null;
        try {
            sslContext = SSLContext.getInstance("TLS");
            sslContext.init(null, null, null); // will use java's default key and trust store which is sufficient unless you deal with self-signed certificates
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (KeyManagementException e) {
            e.printStackTrace();
        }
        mWebSocketClient.setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sslContext));

mWebSocketClient.connect();
</pre>

I dont get any error, it just doesnt connect to wss server, onOpen() is never called :/

Please help

**Comment by andrepew** [comment]
I had this issue and rewrote SSLSocketChannel2 to use SSLEngine in the way I saw several other projects use it. The code seems to work for me but it definitely needs more testing.

https://github.com/andrepew/Java-WebSocket/tree/1.3.0-Android-SSL-Fix

**Comment by earlymarket-oc** [comment]
I can confirm, on Nexus 5 with Lollipop WSS is not working at all.

**Comment by porkyhead** [comment]
Can confirm that the issue exists on Nexus 9 Lollipop. 

Andrepew's solution is working on Lollipop but crashes on Kitkat (and maybe even older Android versions), so there is no single solution for using websocket SSL on Android in general :(

**Comment by juanjo75es** [comment]
Couldn't it be that Lollipop has a different list of supported CA's and now your root certificate is not accepted by your client?

**Comment by phutang2359media** [comment]
I have a same problem with Nexus 5 (5.0.1) but seem work on 5.1. do you have any idea to fix it?

**Comment by Jullekungfu** [comment]
@andrepew I had the exact same issue as described above, your provided fix solved everything!
Thanks! :D

**Comment by sristi** [comment]
@andrepew I confirm that I had tested your version of java_websocket.jar with WSS protocol on Android 4.1.2 to 6.0 emulators and devices from major android device vendors. Moreover, I had tried wss connections on older version of device/emulators having android 4.0.3 and previous ones. But wss did not work for them and I simply make a fallback to ws protocol to those devices. Hats off to your work !

**Comment by marci4** [comment]
dupliacte of #293

**Comment by YudizVinay** [comment]
@marci4 this question is duplicate of this question??? wow, nice reason to close this issue (clap)

**Comment by marci4** [comment]
I quess I meant #424....

**Comment by hdjx520** [comment]
use ws |||_|||
