### ISSUE TITLE
Long messages from Chrome will not be accepted

### ISSUE THREAD

**Issue by Dflz** [TooTallNate/Java-WebSocket#299]
Start receiving:
process(16384): {too big to display}
.......
process(7731): {too big to display}
matched frame: Framedata{ optcode:BINARY, fin:false, payloadlength:[pos:0, len:122405],...
.....
process(16384): {too big to display}
.....
process(16398): {too big to display}
matched frame: Framedata{ optcode:CONTINUOUS, fin:false, payloadlength:...
process(16384): {too big to display}
..
process(14670): {too big to display}
matched frame: Framedata{ optcode:CONTINUOUS, fin:true, payloadlength:[pos:0, len:63814]...

 try { wsl.onWebsocketMessageFragment(this, f);
        } catch (RuntimeException e) {
          wsl.onWebsocketError(this, e);
         }
-->
 @Override
    @Deprecated
    public/*final*/ void onWebsocketMessageFragment(WebSocket conn, Framedata frame) {// onFragment should be overloaded instead
        onFragment(conn, frame);
    }
-->
    public void onFragment(WebSocket conn, Framedata fragment) {

    }

**Comment by LAX1DUDE** [comment]
same here :/

**Comment by marci4** [comment]
Hello @LAX1DUDE,

I can't do anything with such a bug report. Please comment a detailed bug report and steps to repeat including the versions of different endpoints on the active topic #525.

I would really like to understand and fix this problem, but if I cant reproduce it, I cant do anything...

Greetings
marci4

**Comment by LAX1DUDE** [comment]
Sorry, should have mentioned I figured my mistake out myself

**Comment by marci4** [comment]
Hello @LAX1DUDE,

I would like to know your mistake. Maybe others made the same mistake and that would help them as well.

Greetings
marci4
