### ISSUE TITLE
Long messages from Chrome will not be accepted.

### ISSUE THREAD

**Issue by Dflz** [TooTallNate/Java-WebSocket#300]
the last fragments

process(16384): {too big to display}
....
process(16398): {too big to display}
matched frame: Framedata{ optcode:CONTINUOUS, fin:false, payloadlength:[pos:0, len:131072], payload:[13,....
process(16384): {too big to display}
......
process(14670): {too big to display}
matched frame: Framedata{ optcode:CONTINUOUS, fin:true, payloadlength:[pos:0, len:63814], payload:[35.....

class WebSocketImpl {
....
private void decodeFrames(ByteBuffer socketBuffer) {
....
    try {
                        wsl.onWebsocketMessageFragment(this, f);
                    } catch (RuntimeException e) {
                        wsl.onWebsocketError(this, e);
            }
-->
    @Override
    @Deprecated
    public/_final_/ void onWebsocketMessageFragment(WebSocket conn, Framedata frame) {// onFragment should be overloaded instead
        onFragment(conn, frame);
    }
-->
    public void onFragment(WebSocket conn, Framedata fragment) {
    }

**Comment by din** [comment]
I can confirm the issue. Is there anything that can fix the issue?

**Comment by BrushfireDigitalServices** [comment]
@dflz @din, thank you for taking the time to report and confirm this issue. At this time, I do not know of a fix.

Have either of you made any progress towards a fix? Even a failing test case would be helpful at this stage. Would you be interested in finding and contributing the solution?

**Comment by Dflz** [comment]
I solved this problem without using ws, and for my project this question is removed. but it is very desirable to find a solution. It may be necessary to address to developers chrome?

**Comment by marci4** [comment]
Could you please check if #570 is fixing this issue for you?

Greetings
marci4

**Comment by marci4** [comment]
This issue should be solved. If not feel free to open a new issue!

Greetings
marci4
