### ISSUE TITLE
ssl client with signalr

### ISSUE THREAD

**Issue by e82eric** [TooTallNate/Java-WebSocket#304]
Is there anything extra that needs to be done to use wss://

I am trying to connect using the java signalr sdk that uses this library for the websocket transport.  It works when I use ws:// but not wss://

The site I a trying to connect to is hosted in a azurewebsite that has a valid certificate.  And I don't get any not trusted exceptions.

This is code where the connect happens.  I added a small patch for uri = new URI(url.replace("https://", "wss://"));

https://github.com/SignalR/java-client/blob/master/signalr-client-sdk/src/main/java/microsoft/aspnet/signalr/client/transport/WebsocketTransport.java

**Comment by marci4** [comment]
Hello @e82eric,

please check out the SLL client example provided [here](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLClientExample.java) 

Greetings
marci4
