### ISSUE TITLE
We got SSL issue which seems fixed in the latest code. Could you bump up a new version including recent changes since 1.3?

### ISSUE THREAD

**Issue by dytsai** [TooTallNate/Java-WebSocket#305]
We are using socket.io and its transport layer is handled by engine.io which uses Java-WebSocket as underlying websocket library. Recently we encountered an SSL issue that socket.io cannot upgrade from xhr long polling to websocket when using https while http works just fine.

After tracking down the source we found that there might be some issues in 1.3 and they were actually fixed in the latest code. We tried to replace 1.3 with the master in engine.io and our problems are gone. However, the author of socket.io cannot apply the latest master of Java-WebSocket because we don't know if it's stable or not. You can check out issue below https://github.com/nkzawa/socket.io-client.java/issues/88#issuecomment-72863135

**Comment by b95505017** [comment]
Agree. Please upgrade to maven!!

**Comment by jakehilton** [comment]
I'm also seeing an SSL issue.. I'm seeing this in my logs which eludes to some internal isssue:

Using SSLEngineImpl.
Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 for TLSv1.1
WebsocketSelector32, fatal error: 80: problem unwrapping net record
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
WebsocketSelector32, SEND TLSv1.2 ALERT:  fatal, description = internal_error
WebsocketSelector32, WRITE: TLSv1.2 Alert, length = 2

I tried java 7 and 8 but have the same problem.

Any help would be great on this!
Thanks

**Comment by mhmeadows63** [comment]
I have a Wireshark trace of a Java Desktop app attempting an HTTPS connect to a NodeJS SocketIO server, and it shows the websocket-upgrade request is transmitted as plain-text, while XHR polling requests are encrypted.

Sadly, I don't think sharing the trace would be much help without my TLS key for decode.

However, the following ladder diagrams attempts to detail my observation:
1) encrypted XHR poll exchange to port 8080

```
[----------Client----------]    [----------Server:8080-----------]
                         SYN ->
                             <- SYN,ACK
                         ACK ->
        TLSv1.2(ClientHello) ->
                             <- ACK
                             <- TLSv1.2(ServerHello)
                             <- TLSv1.2(Certificate)
                         ACK ->
  TLSv1.2(ClientKeyExchange) ->
   TLSv1.2(ChangeCipherSpec) ->
           TLSv1.2(Finished) ->
                             <- ACK
                             <- TLSv1.2(ChangeCipherSpec,Finished)
   TLS(GET /socket.io/..etc) ->
                             <- HTTP(200 OK)
TLSv1.2(Alert,Warning:Close) ->
                     FIN,ACK ->
                             <- FIN,ACK
                         ACK ->
```

2) plain-text websocket-upgrade to port 8080
```
[----------Client----------]    [----------Server:8080-----------]
                         SYN ->
                             <- SYN,ACK
                         ACK ->
 PLAIN(GET /socket.io/..etc) ->
                             <- ACK
                     RST,ACK ->
```

Anybody else this this might be relevant?

**Comment by jakehilton** [comment]
Sadly I ended up using an haproxy front for the SSL exchange because I
couldn't get the built-in SSL stuff working properly.

I hope to be able to revisit this again soon but for now I must press
onward!

Thanks for the help though!

**Comment by BrushfireDigitalServices** [comment]
Hello all, based on volume of new issues, the current master branch is more stable than the 1.3.0 snapshot. 

We are pushing to fix more issues and make new contributions easier. If you have time, please test with the new code--your troubles may already be fixed. If not, there should be a new stable snapshot in the next few months.
