### ISSUE TITLE
What is the latest version of this library ?

### ISSUE THREAD

**Issue by jsrikrishna** [TooTallNate/Java-WebSocket#306]
Hi,

Which is the latest version of this library ? 1.3.0 or 1.3.1.1?? or something ??

**Comment by bdbergeron** [comment]
Trying to use the latest version of Pusher's Android/Java library (0.3.3) fails due to the lack of a 1.3.1 release of Java-WebSocket. Had to go back to 0.3.1 in order to get it working. Can we get a new release?

**Comment by brcolow** [comment]
From what I can tell 1.3.1 has been released to the clojars.org repo, but *not* Maven Central. This is obviously an issue.

**Comment by ThreaT** [comment]
I suggest you wait until around October 2015 when [JEP 110](http://openjdk.java.net/jeps/110) is complete. Since this repository is open source, there won't necessarily be a dedicated developer working on it.

**Comment by SKART1** [comment]
I think you should increase you version number in `build.gradle`  - because now it is `version = '1.2.1-SNAPSHOT'`, and maven suddenly have version 1.3.0 - which was released **2** years ago! 
I was confused when maven version which has bigger release number was actually so out-of-dated!
So please at least make version in `build.gradle` actual, and if possible update maven version too.



P.S. Great job! Were good and useful library :+1:

**Comment by daluu** [comment]
I guess in the interim, one will want to pull from the clojars repo with maven? Or manually compile the latest JAR with maven from the codebase here and link to your project rather than use maven to pull it off maven central (or host the manually compiled version in your own local maven repo).

**Comment by daluu** [comment]
Btw, anyone use/try from clojars or use Clojure? I thought to give it a try with my maven pom & this was the result snippet below (running `mvn eclipse:eclipse`). I wonder if the info on clojars.org regarding v1.3.1 is even accurate or not. I wasn't able to pull the JAR/POM for 1.3.1 nor 1.3.0 (tested manually via pasting URL to browser), but was able to pull 1.3.0 from maven central by URL just no 1.3.1 available.

For maven pom, I simply inserted the clojar repository snippet & the maven dependency snippet from clojars.org into my pom file, following https://clojars.org/org.java-websocket/java-websocket

```
Downloading: http://clojars.org/repo/org/java-websocket/Java-WebSocket/1.3.1/Java-WebSocket-1.3.1.pom
Downloading: https://repo.maven.apache.org/maven2/org/java-websocket/Java-WebSocket/1.3.1/Java-WebSocket-1.3.1.pom
[WARNING] Missing POM for org.java-websocket:Java-WebSocket:jar:1.3.1
Downloading: http://clojars.org/repo/org/java-websocket/Java-WebSocket/1.3.1/Java-WebSocket-1.3.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/java-websocket/Java-WebSocket/1.3.1/Java-WebSocket-1.3.1.jar
[WARNING] An error occurred during dependency resolution.
    Failed to retrieve org.java-websocket:Java-WebSocket-1.3.1
Caused by: Could not find artifact org.java-websocket:Java-WebSocket:jar:1.3.1 in clojars.org (http://clojars.org/repo)

Try downloading the file manually from the project website.

Then, install it using the command: 
    mvn install:install-file -DgroupId=org.java-websocket -DartifactId=Java-WebSocket -Dversion=1.3.1 -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there: 
    mvn deploy:deploy-file -DgroupId=org.java-websocket -DartifactId=Java-WebSocket -Dversion=1.3.1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

Path to dependency: 
	1) your maven project
	2) org.java-websocket:Java-WebSocket:jar:1.3.1


  org.java-websocket:Java-WebSocket:jar:1.3.1

from the specified remote repositories:
  clojars.org (http://clojars.org/repo, releases=true, snapshots=true),
  central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)

[INFO] Unable to read jar manifest from /Users/daluu/.m2/repository/org/java-websocket/Java-WebSocket/1.3.1/Java-WebSocket-1.3.1.jar
```

**Comment by lichtamberg** [comment]
Is the 1.3.1 version still not released on gradle? looks like it.. :/

**Comment by marci4** [comment]
I pushed an update to clojars.

Greetings
marci4
