### ISSUE TITLE
Compile error at SSLClientExample.java : 84 cannot resolve method

### ISSUE THREAD

**Issue by vach** [TooTallNate/Java-WebSocket#308]
Done as said in description. Got a dependency on 

<dependency>
            <groupId>org.java-websocket</groupId>
            <artifactId>Java-WebSocket</artifactId>
            <version>1.3.0</version>
        </dependency>

and get that compile error on line 84, no method .setSocket()...

**Comment by Fi5t** [comment]
Similar problem!

**Comment by BrushfireDigitalServices** [comment]
The method is there in the latest (several) commits and everything compiles ok on my end. @Fi5t @vach Did pulling from Github fix the error?

**Comment by btiernay** [comment]
I hit the same issue. I guess this was never released to central?
