### ISSUE TITLE
GitHub Repo Missing DefaultSSLWebSocketClientFactory

### ISSUE THREAD

**Issue by sandrum** [TooTallNate/Java-WebSocket#310]
For some reason, *.client.DefaultSSLWebSocketClientFactory is missing from this version of the repo while it exists in the maven version and claims to be related to this version (1.3.0).  Is there an "official" version? And if the GitHub version is official, what happened to DefaultSSLWebSocketClientFacotry?  The ServerFactory version still exists...

Thanks!

**Comment by sandrum** [comment]
The maven version I am asking about is here: http://mvnrepository.com/artifact/org.java-websocket/Java-WebSocket/1.3.0, the jar size of which is quite different and DOES contain the SSLClientFactory.java

**Comment by intari** [comment]
Looks like SSLClientFactory got removed in https://github.com/TooTallNate/Java-WebSocket/commit/115477eb2b95a9204fe8997cb549aa553057aa28
