### ISSUE TITLE
Tomcat

### ISSUE THREAD

**Issue by Hugolarson** [TooTallNate/Java-WebSocket#312]
Hello,

Does anybody have problem with using WebSocketClient with Tomcat-7.0.61.

Client Code.

ExampleClient c = new ExampleClient( new URI( "ws://localhost:8080/WebSocketProxy/websocket/echoAnnotation"), new Draft_17() );
c.connect();
c.send("hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh");

onOpen is called and replies.
onMessage is never called whatever i do.

//Server code on Tomcat
@ServerEndpoint("/websocket/echoAnnotation")
public class EchoAnnotation {
    @OnMessage
    public void onMessage(Session session, String message ) {
        System.out.println( "server received: " + message );
    }
    @OnMessage
    public void onMessage(Session session, ByteBuffer message ) {
        System.out.println( "server onMessage bytebuf: ");

```
    try {
        session.getBasicRemote().sendBinary(message);
    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
}
@OnOpen
public void open(Session session) {
    System.out.println("onopen");
    try {
        session.getBasicRemote().sendText("hello from server");
    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
}
```

}

Thanks,
Hugo

**Comment by ThreaT** [comment]
Sounds like the socket is being closed right after opening, could be that the client is not compatible with Tomcat... Have you tried using a JS client?

**Comment by marci4** [comment]
Closing old issue without any clear exception.

Greetings
marci4
