### ISSUE TITLE
Add more content to wiki

### ISSUE THREAD

**Issue by ThreaT** [TooTallNate/Java-WebSocket#313]
It is difficult for users to contribute properly without understanding the code correctly. 

There are a lot of unknowns that need more details:
https://github.com/TooTallNate/Java-WebSocket/wiki/2-Project-Structure

It would be beneficial if more content were added to the wiki. Anyone that has knowledge in any part of this repository is encouraged to share their knowledge.

**Comment by jfranki** [comment]
It would be great even a little javadoc...

**Comment by ThreaT** [comment]
@jfranki it seems this whole repo has gone dead due to lack of administration

**Comment by BrushfireDigitalServices** [comment]
If there's not a more active fork already, I'm willing to fork and begin administrating the documentation process. We should identify who wants to take on which tasks (and which tasks no-one is interested in) so folks aren't wasting time writing substantially similar pull requests.

I would start by sorting out what contract the abstract methods actually have and what is added by concrete implementations.

**Comment by ThreaT** [comment]
The problem is redirecting future pull requests as well. We can't edit the readme because there's no administration unless someone is able to contact the author or administrator directly.

**Comment by BrushfireDigitalServices** [comment]
Working on trackng him down. If all else fails, we could try opening an issue titled something like "Active support can be found at [address of active fork]" and see how many users follow the redirect.

**Comment by TooTallNate** [comment]
Sadly, I don't really have time to maintain this project anymore, and don't really do Java these days so I'm kind of out-of-the-loop as well.

If any of you would like to be added as a contributor to this repo, then that would be awesome!

**Comment by ThreaT** [comment]
@TooTallNate No worries, I think @BrushfireDigitalServices mentioned that he would like to administrate this repo. If that's not possible then would it at least be possible to mention his fork in the readme?

**Comment by TooTallNate** [comment]
Ok, added @BrushfireDigitalServices as a collaborator on this repo. Thanks in advance for any help you can put towards it!

**Comment by ThreaT** [comment]
@TooTallNate Can you add me as well please

**Comment by TooTallNate** [comment]
The more the merrier! Added @ThreaT as a collaborator.

**Comment by BrushfireDigitalServices** [comment]
Outstanding. Thank you, @TooTallNate, for taking the time to address this. In the near future I'll mainly be helping expand and clarify documentation.

**Comment by rob-baily** [comment]
All, while this project was great for getting started you may want  to consider the Jetty WebSocket client at http://www.eclipse.org/jetty/documentation/current/jetty-websocket-client-api.html and drop this project.  I've been using the Jetty client and it appears to be very full featured and does not require the entire Jetty infrastructure to run.

**Comment by ThreaT** [comment]
@rob-baily There are lots of open source solutions out there. Personally, I find that Jetty has too many tightly coupled lines of code to comprehend or change for project-specific requirements. This solution offers a clear start for projects without necessarily having a full on implementation that people may not fully understand.

**Comment by marci4** [comment]
Added examples [TCP_NODELAY](for https://github.com/TooTallNate/Java-WebSocket/wiki/Enable-TCP_NODELAY)

**Comment by marci4** [comment]
Added examples for [Lost connection detection](https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection)

**Comment by marci4** [comment]
TODO: 
- Extend #473 documentation
- Frames
- #510
