### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by ThreaT** [TooTallNate/Java-WebSocket#318]
If someone has experience writing tests, it would make merging pull requests a lot easier if we had them

**Comment by BrushfireDigitalServices** [comment]
Agreed, @ThreaT. 

I would like to push for major additions and bugfixes to include tests, perhaps as a new requirement for merge approval. For the pull requests I have merged this week, I expect to be able to deliver at least partial JUnit test classes by the end of next week.

Ideally, the folks who wrote the patch will also write documentation and tests, but in the cases where the original authors cannot do so, or are not interested, I suggest using tags to track which items lack such metadata. This way, interested parties can find items to work on quickly and easily, and urgent fixes with community-reported correctness (such as #171) don't have to wait for a merge.

What are your thoughts?

**Comment by ThreaT** [comment]
@BrushfireDigitalServices  I absolutely agree. I don't generally like processes but requesting pull requests to add tests would make many things better and easier.

**Comment by BrushfireDigitalServices** [comment]
An unbiased perspective is definitely desirable. I'm open to using acceptance tests, but have no experience writing them.

Test inclusion being strongly encouraged but not required sounds like the way to go.

**Comment by ThreaT** [comment]
I've added a [prototype](https://github.com/TooTallNate/Java-WebSocket/compare/master...ThreaT:master). I don't have time to make it perfect but it's a good place to start I think. It needs a code review and some bug fixes before merging:

**Comment by BrushfireDigitalServices** [comment]
@bendem are you interested in code reviewing @ThreaT's proposed acceptance tests? Your recent contributions are quite valuable, and we're trying to define a unit and acceptance test suite that can automatically check that fixed bugs are not reopened by future changes.

**Comment by bendem** [comment]
I agree that all libraries should aim to improve test coverage at all time; but it's easy for me to say that when I have very little experience in writing those.
I'm not sure how to go about writing unit tests for a multi threaded network application like this one. I'm not familiar with the websocket protocol (thus why I use a lib) and my time is quite limited as of today.

I'll continue to be involved with the repo as long as we use the library in our product, but I can't promise anything about reviewing code on a regular basis.

As for @ThreaT's acceptance test, I have no idea what it is about, but I can try and take a look later this week.

Another point I'd like to be considered is the code style consistency and internal doc (javadoc) of the codebase. Fixing this would lower the contributing barrier considerably imo.

**Comment by bendem** [comment]
Reviewed @ThreaT's tests, they were basically not doing anything, now they do. Each `// TODO Implement check` is a check that I didn't find how to fulfill and that either needs to be removed or fixed.

Remember that I didn't know anything about Acceptance tests before this day and I might have understood the (poor) cucumber doc wrong.

**Comment by ThreaT** [comment]
@bendem Thank you for the above. I've reviewed it and it seems 99% fine. Can you please start a pull request to my fork so that I can make a couple minor changes and pull to master?

**Comment by ThreaT** [comment]
@bendem @BrushfireDigitalServices acceptance tests merged into master. Would be good if there were more, but it's a good start I think.

**Comment by bendem** [comment]
Might want to reenable travis to test PRs.
