### ISSUE TITLE
WSS Server does not provide certificate

### ISSUE THREAD

**Issue by xelixua** [TooTallNate/Java-WebSocket#320]
Hello
Used this library to implement websocket server, it works perfect.
Now I need to implement websocket secure. I created keystore as in example https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLServerExample.java and implemented WSS server
Now when trying to connect the server with my JS client, successfull connect attempts are only 10% of all attempts. In rest 90% cases, Chrome console says "TIMEOUT" for WSS connection. 
Tried to connect server using OpenSSL, WSS server provides certificate only one time after server starts
From console:
Using SSLEngineImpl.
Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 for SSLv2Hello
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 for SSLv2Hello
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA256 for SSLv2Hello
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 for SSLv2Hello
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 for SSLv2Hello
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 for SSLv2Hello
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 for SSLv2Hello
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 for TLSv1.1
[Raw read]: length = 5
0000: 16 03 01 00 94                                     .....
[Raw read]: length = 148
0000: 01 00 00 90 03 03 3F 41   BA 59 AE 98 8B 40 F0 09  ......?A.Y...@..
0010: 7A 19 E8 A1 69 69 A2 74   40 14 32 72 D3 D7 2F D4  z...ii.t@.2r../.
0020: A3 6B 7C 3C 73 57 00 00   16 C0 2B C0 2F C0 0A C0  .k.<sW....+./...
0030: 09 C0 13 C0 14 00 33 00   39 00 2F 00 35 00 0A 01  ......3.9./.5...
0040: 00 00 51 FF 01 00 01 00   00 0A 00 08 00 06 00 17  ..Q.............
0050: 00 18 00 19 00 0B 00 02   01 00 00 23 00 00 33 74  ...........#..3t
0060: 00 00 00 10 00 0B 00 09   08 68 74 74 70 2F 31 2E  .........http/1.
0070: 31 00 05 00 05 01 00 00   00 00 00 0D 00 16 00 14  1...............
0080: 04 01 05 01 06 01 02 01   04 03 05 03 06 03 02 03  ................
0090: 04 02 02 02                                        ....
WebsocketSelector35, READ: TLSv1 Handshake, length = 148

Please give me an advice how to fix this

**Comment by bendem** [comment]
I used [these instructions](http://stackoverflow.com/a/8224863) to setup my wss keystore, worked nicely.

**Comment by marci4** [comment]
Hello @xelixua,

is this still an issue for you with the latest version of the lib?

You can also check the wiki for an example how to use a [SSLContext](https://github.com/TooTallNate/Java-WebSocket/wiki/Getting-a-SSLContext-from-different-sources).

Greetings
marci4

**Comment by marci4** [comment]
No update for months.

For me this issue is solved with the reference to the wiki entry.
Closing issue!
Greetings
marci4
