### ISSUE TITLE
Does master branch include all the fixes?

### ISSUE THREAD

**Issue by srikanthhugar** [TooTallNate/Java-WebSocket#324]
Hello,

I have been using Java-Websocket and noticed memory and CPU usage issues.
I think problem is same as https://github.com/TooTallNate/Java-WebSocket/issues/171

Wanted to know if i pull master branch code and build, will the fixes be included? Noticed some of the commits at https://github.com/pmonteiro/Java-WebSocket/commit/0424566a295e17753db3a9df0347f71fd8c67639 is not available in master.

Please correct me if i am wrong.

**Comment by BrushfireDigitalServices** [comment]
Thanks for being proactive about reporting troubles with this library! #171 has an update that should answer this question.

Perhaps in the process we can collaborate on creating the test code for the new patch?

Please pull the current master branch and retry. Hopefully everything works for you now. If you still experience bugs, open a new issue here.
