### ISSUE TITLE
NullPointerException at SocketChannelIOHelper.batch(SocketChannelIOHelper.java:64)

### ISSUE THREAD

**Issue by Animaleante** [TooTallNate/Java-WebSocket#335]
Don't really know what happened here, as I don't have any logs showing what kind of message was the server working on.

Stacktrace:
java.lang.NullPointerException
	at org.java_websocket.SocketChannelIOHelper.batch(SocketChannelIOHelper.java:64)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:352)
	at java.lang.Thread.run(Thread.java:745)

But the problem is that this seems to have killed my WebSocketServer Thread, and so I'd like to know if there is a way to check if the server thread has been interrupted, or ended, and then restart the server, all from within the subclass of WebSocketServer.

**Comment by bendem** [comment]
I think this issue was fixed in https://github.com/TooTallNate/Java-WebSocket/commit/dbced22dd20c54db7ccc27c1397a186c1ed56763

**Comment by Animaleante** [comment]
Hnm, well, I've been using the jar that can be found on the dist folder, and just now saw that it is 3 years old.

Will compile a recent build here, thanks.
