### ISSUE TITLE
Include a proper license header in source files

### ISSUE THREAD

**Issue by hegjon** [TooTallNate/Java-WebSocket#336]
It would make it easier to redistribute Java-WebSocket in Fedora if each source file contains a license header.

Missing or generated license headers:

```
src/main/java/org/java_websocket/AbstractWrappedByteChannel.java
src/main/java/org/java_websocket/SSLSocketChannel2.java
src/main/java/org/java_websocket/SocketChannelIOHelper.java
src/main/java/org/java_websocket/WebSocket.java
src/main/java/org/java_websocket/WebSocketAdapter.java
src/main/java/org/java_websocket/WebSocketFactory.java
src/main/java/org/java_websocket/WebSocketImpl.java
src/main/java/org/java_websocket/WebSocketListener.java
src/main/java/org/java_websocket/WrappedByteChannel.java
src/main/java/org/java_websocket/client/AbstractClientProxyChannel.java
src/main/java/org/java_websocket/client/DefaultSSLWebSocketClientFactory.java
src/main/java/org/java_websocket/client/DefaultWebSocketClientFactory.java
src/main/java/org/java_websocket/client/WebSocketClient.java
src/main/java/org/java_websocket/drafts/Draft.java
src/main/java/org/java_websocket/drafts/Draft_10.java
src/main/java/org/java_websocket/drafts/Draft_17.java
src/main/java/org/java_websocket/drafts/Draft_75.java
src/main/java/org/java_websocket/drafts/Draft_76.java
src/main/java/org/java_websocket/exceptions/IncompleteHandshakeException.java
src/main/java/org/java_websocket/exceptions/InvalidDataException.java
src/main/java/org/java_websocket/exceptions/InvalidFrameException.java
src/main/java/org/java_websocket/exceptions/InvalidHandshakeException.java
src/main/java/org/java_websocket/exceptions/LimitExedeedException.java
src/main/java/org/java_websocket/exceptions/NotSendableException.java
src/main/java/org/java_websocket/exceptions/WebsocketNotConnectedException.java
src/main/java/org/java_websocket/framing/CloseFrame.java
src/main/java/org/java_websocket/framing/CloseFrameBuilder.java
src/main/java/org/java_websocket/framing/FrameBuilder.java
src/main/java/org/java_websocket/framing/Framedata.java
src/main/java/org/java_websocket/framing/FramedataImpl1.java
src/main/java/org/java_websocket/handshake/ClientHandshake.java
src/main/java/org/java_websocket/handshake/ClientHandshakeBuilder.java
src/main/java/org/java_websocket/handshake/HandshakeBuilder.java
src/main/java/org/java_websocket/handshake/HandshakeImpl1Client.java
src/main/java/org/java_websocket/handshake/HandshakeImpl1Server.java
src/main/java/org/java_websocket/handshake/Handshakedata.java
src/main/java/org/java_websocket/handshake/HandshakedataImpl1.java
src/main/java/org/java_websocket/handshake/ServerHandshake.java
src/main/java/org/java_websocket/handshake/ServerHandshakeBuilder.java
src/main/java/org/java_websocket/server/DefaultSSLWebSocketServerFactory.java
src/main/java/org/java_websocket/server/DefaultWebSocketServerFactory.java
src/main/java/org/java_websocket/server/WebSocketServer.java
```

The review can be found here: https://bugzilla.redhat.com/show_bug.cgi?id=1231570

**Comment by BrushfireDigitalServices** [comment]
Agreed, each file should carry its own license notice.

Looks like you're packaging the 1.3.0 snapshot. Although 1.3.0 is still heavily used, it is much less stable than the current master branch. We're working towards a new official release. Like the other recent fixes, the license notice will be added to the above files before we've officially tagged and jar-ed 1.4.0.

**Comment by hegjon** [comment]
> Agreed, each file should carry its own license notice.

Thanks, glad to hear :)

> Looks like you're packaging the 1.3.0 snapshot.

We are using https://github.com/TooTallNate/Java-WebSocket/archive/Java-WebSocket-1.3.0.tar.gz today. I assume that is the snapshot you are referring to.

> Although 1.3.0 is still heavily used, it is much less stable than the current master branch. We're working towards a new official release.

Thanks for letting me know, do you have an idea when the release is planned? I can update to the master branch before the release.

**Comment by blunden** [comment]
I'm not sure it's such a great idea to bundle this lib in Fedora until it properly implements the disconnect handshake that is required by the WebSocket RFCs. Last time I tried it, it didn't. That might be fixed already though.

**Comment by BrushfireDigitalServices** [comment]
@hegjon, @blunden

A truly "five star" package for Fedora is probably a long way off. That said, a lot of progress is still being made. In particular, we're starting to get more and more confirmation from the community that fixes here are in fact working on their projects.

The deadline for an updated release number is fast approaching, but was chosen arbitrarily as a motivating factor just as this repo was being revived and before the rate of new development was clear. This deadline should be reexamined, and this time set with community input.

Going forward, I've started a new job and expect to be checking in to admin here approximately two days a week.

Updating to the master branch is a good idea in any case.

**Comment by hegjon** [comment]
Thanks for the feedback, I will work on updating to a snapshot of the master branch, since several of the developers recommend that over the 0.3 version.

**Comment by marci4** [comment]
Included license headers for all files!

Greetings
marci4
