### ISSUE TITLE
WSS Example throw an exception when i use netcat  to check whether port in the listening state

### ISSUE THREAD

**Issue by chasing95** [TooTallNate/Java-WebSocket#337]
Repeat steps:
1, start SSLServerExample
2, start SSLClientExample
At this point, the client and the server can be normal interaction.
3, use netcat check WSS port is ok
     #nc - vw 2 - z 127.0.0.1 8887
     #[127.0.0.1] 8887 (?)The open
     Test results is normal, but SSLServerExample throw the following exception:
Java. IO. IOException: connection closed unexpectedly by peer
         The at org. Java_websocket. SSLSocketChannel2. ProcessHandshake (SSLSocketChannel2. Java: 118)
         The at org. Java_websocket. SSLSocketChannel2. < init > (SSLSocketChannel2. Java: 75)
         The at org. Java_websocket. Server. DefaultSSLWebSocketServerFactory. WrapChannel (39) DefaultSSLWebSocketServerFactory. Java:
         The at org. Java_websocket. Server. WebSocketServer. Run (WebSocketServer. Java: 317)
         The at Java. Lang. Thread. The run (Thread. Java: 745)
Java. Lang. NullPointerException
          The at org. Java_websocket. SocketChannelIOHelper. Read (SocketChannelIOHelper. Java: 12)
          The at org. Java_websocket. Server. WebSocketServer. Run (WebSocketServer. Java: 327)
          The at Java. Lang. Thread. The run (Thread. Java: 745)

When I check the port again, output is like following:
       #[127.0.0.1] 8887 (?): connection refused

When I check the WebSocketServer.java source, found that when catch exceptions
catch (IOException ex) {
       if (key! = null)
             key. The cancel ();
       handleIOException (key, conn, ex);
}

Th key variables associated with SocketServerChannle, after cancel and close the channel, the server will no longer receive new connection requests.

Please forgive my poor English. Thanks

**Comment by bendem** [comment]
From what I see, [WebSocketServer. Java: 327](https://github.com/TooTallNate/Java-WebSocket/blob/e4c248a69f0cb36f87e5b3d3100bd2b46e027289/src/main/java/org/java_websocket/server/WebSocketServer.java#L317) is empty and [WebSocketServer. Java: 327](https://github.com/TooTallNate/Java-WebSocket/blob/e4c248a69f0cb36f87e5b3d3100bd2b46e027289/src/main/java/org/java_websocket/server/WebSocketServer.java#L327) cannot NPE, `conn` is not null (it's used before).

Which version are you using?

Also, would you mind pasting the real stack trace? That one looks like it's been auto corrected by a dumb phone dictionary or something.

**Comment by chasing95** [comment]
Thank you for your prompt reply.
I use java_websocket 1.3.0, so it may be different from the current call stack. My call stack is:
```java
java.io.IOException: connection closed unexpectedly by peer
Connection closed because ofjava.io.IOException: connection closed unexpectedly by peer
	at org.java_websocket.SSLSocketChannel2.processHandshake(SSLSocketChannel2.java:118)
	at org.java_websocket.SSLSocketChannel2.<init>(SSLSocketChannel2.java:75)
	at org.java_websocket.server.DefaultSSLWebSocketServerFactory.wrapChannel(DefaultSSLWebSocketServerFactory.java:39)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:317)  -- now is line 312
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by chasing95** [comment]
Sorry, my operation error.

**Comment by bendem** [comment]
oh, took me a while to realize your stacktraces are reversed, the IOException happened at `org.java_websocket.SSLSocketChannel2.processHandshake(SSLSocketChannel2.java:118)` and the NPE at `org.java_websocket.SocketChannelIOHelper.read(SocketChannelIOHelper.java:12)`.

Could you try and compile master to see if it hasn't been fixed by a recent commit and so it's easier to see which line correspond to which in your stacktraces?

**Comment by chasing95** [comment]
I download the latest master code, and run SSLServerExample and SSLClientExample, everything seems to be very good, but when I use netcat(``` nc -vw 2 -z 127.0.0.1 8887 ```) to check whthere the server is ok, the server side called the exception as follows:
```
java. lang. NullPointerException
the at org. Java_websocket. SocketChannelIOHelper. Read (SocketChannelIOHelper. Java: 14)
the at org. Java_websocket. Server. WebSocketServer. Run (WebSocketServer. Java: 322)
the at Java. Lang. Thread. The run (Thread. Java: 745)
```
The client output:
```
Disconnected
```

Thanks

**Comment by bendem** [comment]
Hm, I suppose netcat doesn't implement the websocket protocol. That'd explain the error in the handshake.

We might want to consolidate the error handling in case of erroneous protocol, but I don't think it prevents you from using the lib with a real client.

**Comment by chasing95** [comment]
Thank you for your reply. 
WebSocket client and server can normally interaction, but if the server become unavailable when someone just check whethere the server port can connect, scanning is not available on the server, this may seems a bit fragile.

**Comment by bendem** [comment]
Does this crash the server or just print a stacktrace?

**Comment by chasing95** [comment]
Yes, after the port scan, the server is not receiving the new request.

**Comment by BrushfireDigitalServices** [comment]
The stacktraces look different, but the symptoms are the same as #326.

**Comment by FelixTony** [comment]
My god you guys are pussies...

the bugs aren't in TooTallNate's code,  their in yours or those of your
clients' monoliths.

if you wanna expand on TTN's work then start a new, OPEN SOURCE
project....  who cares what your boss thinks.
