### ISSUE TITLE
setTCPNoDelay inaccessible

### ISSUE THREAD

**Issue by Lloren** [TooTallNate/Java-WebSocket#339]
I am developing a game off this server code and ran into TCP buffering (Nagle's algorithm) while I was trying to keep my clients updated at 90 tick.

I hacked in to hardcode setTcpNoDelay to true on the client socket that was created. (WebSocketServer.java:309)

I can create a pull request but I am not sure how much you would want that universality architected (setting of Socket or SocketChenel options)

**Comment by marci4** [comment]
added with #462
