### ISSUE TITLE
Need to close selector

### ISSUE THREAD

**Issue by arpruss** [TooTallNate/Java-WebSocket#341]
In WebSocketServer.stop(int timeout), the selector is never closed. As a result, the ServerSocketChannel doesn't close properly, and starting a new WebSocketServer on the same port results in a BindException. Easy fix:
            if ( selector != null) {
                try {
                    selector.close();
                } 
                catch(Exception e) {}
            }
shortly before server.close().

I also set SO_REUSEADDR for the ServerSocketChannel in case a server is closed and started in quick succession.

**Comment by marci4** [comment]
fixed with #272
