### ISSUE TITLE
Auto-Disconnect with CODE = 1006 and REASON = "" (i.e. empty)

### ISSUE THREAD

**Issue by mfsi-ankitb** [TooTallNate/Java-WebSocket#343]
I am using WebSocket connection within Service (in Android), the connection is working fine sending and receiving messages. I also maintain Heartbeat - after every 20 sec send ping to server and after every 2 min get default response from server.

The connection disconnects randomly with above mentioned code. I checked with Server Guy... there is no error log on that side and we tried with 5 sec Heartbeat interval as well. But, it got disconnected even in that scenario.

Can you help me find anything I am missing which is raising this error ?

**Comment by brobits** [comment]
I am running into a similar issue.  I can operate normally for a few hours, then I start getting error code 1000 disconnects with no reason.  unable to reconnect until I relaunch the process

**Comment by NotGGhost** [comment]
Still an issue.

**Comment by marci4** [comment]
Hello @mfsi-ankitb and @brobits 

do you still run into this issue with the latest version?

Greetings
marci4

**Comment by mfsi-ankitb** [comment]
Hello @marci4 
After updating to latest version I didn't faced this issue again.
Thanks for this reminder, I must close this bug.

Regards,
mfsi-ankitb

**Comment by IOCyanfox** [comment]
This happens again in version 1.3.8. The websocket disconnects with either code 1000 or 1006 with empty reason.
