### ISSUE TITLE
RuntimeExceotion : not yet implemented

### ISSUE THREAD

**Issue by leiripmeester** [TooTallNate/Java-WebSocket#345]
10-08 12:34:32.524 326-326/teaonly.droideye E/AndroidRuntime: java.lang.RuntimeException: not yet implemented
10-08 12:34:32.524 326-326/teaonly.droideye E/AndroidRuntime:     at org.java_websocket.drafts.Draft_75.createFrames(Draft_75.java:84)
10-08 12:34:32.524 326-326/teaonly.droideye E/AndroidRuntime:     at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:471)

When streaming video from a android 5.0.1 device to a webview of a other device i get a RuntimeExceotion.

in the following code: 
  public List<Framedata> createFrames(ByteBuffer binary, boolean mask) {
    throw new RuntimeException("not yet implemented");
  }

**Comment by marci4** [comment]
Hello @leiripmeester,

Please don't use the Draft_75 any more! 

I recommend the Draft_17 for you!

Greetings
marci4
