### ISSUE TITLE
WebSocketClient.close() does not work

### ISSUE THREAD

**Issue by oakkitten** [TooTallNate/Java-WebSocket#346]
what it does do it calls methods such as `onWebsocketCloseInitiated` or `onWebsocketClosing` on the current thread. what it doesn't do it doesn't call `onClose`, does not close the socket and doesn't interrupt the thread. `closeBlocking` hangs forever.

i found that `getConnection().closeConnection(1000, "foo")` _does_ close the connection with the respective code and message and is safe to call after `close()`.

i'm not sure whether it is how i'm supposed to close the WebSocketClient, but a method called `close` that doesn't close anything looks highly suspicious, and i didn't manage to find any meaningful documentation, so i'm creating this issue.

tested on 1.3.0 (from maven) and 58d17786958ec2b629b75de1eed00915b3e4f7c4

**Comment by JulienChene** [comment]
Actually this is not an issue at all. According to [Web Socket Protocol (RFC 6465)][1]:

> If an endpoint receives a Close frame and did not previously send a
>    Close frame, ***the endpoint MUST send a Close frame in response***.  (When
>    sending a Close frame in response, the endpoint typically echos the
>    status code it received.)  It SHOULD do so as soon as practical.  An
>    endpoint MAY delay sending a Close frame until its current message is
>    sent (for instance, if the majority of a fragmented message is
>    already sent, an endpoint MAY send the remaining fragments before
>    sending a Close frame).  However, there is no guarantee that the
>    endpoint that has already sent a Close frame will continue to process
>    data.

So what `close()` does, [is set `readyState` to `CLOSING`][2] (hence you receiving the `onClosing()` callback) and [send a `CLOSE` message][3].

Again, you're supposed to receive a response from the endpoint.
So your Web Socket is just waiting for the endpoint to send a `CLOSE` frame.
Which is done [here][4].

The only case where this is not working, is if you lose internet connection, in which case I would call `closeConnection()` just like you mentioned.

I was stuck on the same issue and ended up digging a bit more. Hope that helps you !

[1]: https://tools.ietf.org/html/rfc6455#section-5.5.1
[2]: https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/WebSocketImpl.java#L409
[3]: https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/WebSocketImpl.java#L414
[4]: https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/WebSocketImpl.java#L336

**Comment by marci4** [comment]
as posted in #347, the server passes all the close tests without any problems.

Greetings
marci4

**Comment by oakkitten** [comment]
just writing to confirm that this has been resolved
