### ISSUE TITLE
how to reconnect to the same interface , same instance if internet down .

### ISSUE THREAD

**Issue by mhdjazmati** [TooTallNate/Java-WebSocket#348]
hello , in my android if i lost connection , the onClose() method triggered in my android but it is not in my server (PHP Using Ratchet) .

since the websocket instance is not reusable , so i reassign new instance and establish new connection  
THUS : the server will have new interface to this client and the old interface will remain open .

Could i connect to the same old interface ????

**Comment by marci4** [comment]
Hello @mhdjazmati,

the problem you describe looks like a bug in your server.

From the android point it should be possible but it depends on your server.

Greetings
marci4
