### ISSUE TITLE
Issue with wss

### ISSUE THREAD

**Issue by vusarath** [TooTallNate/Java-WebSocket#350]
Hi 

I am using this jar in my android app and when trying to work with WSS it is throwing this error 
org.java_websocket.drafts.Draft_17@2efb56af refuses handshake-false

This is how i am using the websocketclient 
public class BroadcastReceiver extends WebSocketClient
{
	public BroadcastReceiver(URI serverURI, Map<String, String> httpHeaders)
	{
		super(serverURI, new Draft_17(), httpHeaders, 0);
	}
}

is their any thing else which i am missing

**Comment by douglasjunior** [comment]
See my example here https://github.com/TooTallNate/Java-WebSocket/issues/141#issuecomment-149303289

I hope it helps.
