### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by friendOfOurs** [TooTallNate/Java-WebSocket#352]
Hi!

Is it somehow possible to employ custom thread management for WebSocketServer?
I've went through the code briefly and as far as I see it is per default thread per connection and is not modifiable?

Thanks,
Regards

**Comment by bendem** [comment]
You can provide the amount of decoders (threads used to handle connections) in the constructor. If you don't provide that parameter, `Runtime.getRuntime().availableProcessors()` is used.

**Comment by friendOfOurs** [comment]
That should do the job :) Thank you!
