### ISSUE TITLE
Release to Maven Central

### ISSUE THREAD

**Issue by samczsun** [TooTallNate/Java-WebSocket#356]
When will the snapshot be released?

**Comment by bendem** [comment]
https://github.com/TooTallNate/Java-WebSocket/issues/306#issuecomment-113890135

**Comment by samczsun** [comment]
Unfortunately, I have a library which is reaching a stable build, but is dependant on the snapshot version of this library. Maven Central won't accept a release which depends on something which is not in central so that's why I'm hoping this snapshot can be promoted to a release.

**Comment by samczsun** [comment]
Found a solution using the release version
