### ISSUE TITLE
Lib should not : throw new InvalidFrameException( "bad rsv " + rsv );

### ISSUE THREAD

**Issue by DeepSnowNeeL** [TooTallNate/Java-WebSocket#358]
On Draft_10.java when rsv is != 0 it throws InvalidFrameException but the RFC states :
https://tools.ietf.org/html/rfc6455#page-28

> ```
>  RSV1, RSV2, RSV3:  1 bit each
>  MUST be 0 unless an extension is negotiated that defines meanings
>  for non-zero values.  If a nonzero value is received and none of
>  the negotiated extensions defines the meaning of such a nonzero
> value, the receiving endpoint MUST _Fail the WebSocket
> Connection_.
> ```

So it should be the role of the user of your lib to fail if non-expected rsv value is received.

**Comment by marci4** [comment]
Hello @DeepSnowNeeL ,

you are mixing up different specs!!
Draft_10 is an implementation of [Hypi 10](https://tools.ietf.org/id/draft-ietf-hybi-thewebsocketprotocol-10.txt).

The spec you are revering to is implemented with Draft_17!

Greetings
marci4

**Comment by DeepSnowNeeL** [comment]
Allright ! Thanks for the info :)
