### ISSUE TITLE
Exceptions are Unclear

### ISSUE THREAD

**Issue by ghost** [TooTallNate/Java-WebSocket#360]
When an exception is thrown in a thread run by this library, the full stack trace is not printed, making debugging a lot, lot more difficult.

E.g. `Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "WebSocketWorker-11"` tells me almost nothing.

Thanks for any help.

**Comment by marci4** [comment]
Going to look into that.
Ran into the same problem!

**Comment by marci4** [comment]
duplicates #379
