### ISSUE TITLE
race problem when starting server with port 0

### ISSUE THREAD

**Issue by PerBothner** [TooTallNate/Java-WebSocket#362]
I'm starting the server with a port of 0, so I can then immediately open a client of the server, without hard-wiring in a specific port.  Before I start the client, I need to call getPort().  But that may not work, since the server field may not have been set yet, and that happens in a separate thread.  My suggestion is to move the initial socket.bind to the start method, _before_ the run method in the new thread.  See included patch.

[startserver-patch.txt](https://github.com/TooTallNate/Java-WebSocket/files/79338/startserver-patch.txt)

**Comment by marci4** [comment]
Hello @PerBothner 
could you please open a pull request for your commit?

Thx

Greetings
marci4

**Comment by PerBothner** [comment]
I no longer use Java-WebSocket (for [Domterm](http://domterm.org) I use [libwebsockets](https://libwebsockets.org/) instead).
However, I created a quick pull request #449 .
I tested that it still compiles, but I haven't otherwise tested it.

Glad to see Java-WebSocket is seeing some love again, even though I no longer use it myself.

**Comment by marci4** [comment]
Hello @PerBothner 

thx for your pull request.
Gonna test it soon :)

Closing the issue.
Greetings
marci4
