### ISSUE TITLE
Help ! ! ! ! ! !  com.android.org.conscrypt.OpenSSLSessionImpl cannot be cast to com.android.org.conscrypt.SSLSessionImpl

### ISSUE THREAD

**Issue by SteveMobile** [TooTallNate/Java-WebSocket#363]
Help ! ! ! ! ! !
java.lang.ClassCastException: com.android.org.conscrypt.OpenSSLSessionImpl cannot be cast to com.android.org.conscrypt.SSLSessionImpl
01-07 21:22:40.320 29089-31249/com.ringcentral.glip W/System.err:     at com.android.org.conscrypt.ClientHandshakeImpl.findSessionToResume(ClientHandshakeImpl.java:596)
01-07 21:22:40.320 29089-31249/com.ringcentral.glip W/System.err:     at com.android.org.conscrypt.ClientHandshakeImpl.start(ClientHandshakeImpl.java:74)
01-07 21:22:40.320 29089-31249/com.ringcentral.glip W/System.err:     at com.android.org.conscrypt.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:118)
01-07 21:22:40.320 29089-31249/com.ringcentral.glip W/System.err:     at com.android.org.conscrypt.SSLEngineImpl.wrap(SSLEngineImpl.java:587)
01-07 21:22:40.320 29089-31249/com.ringcentral.glip W/System.err:     at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:462)
01-07 21:22:40.320 29089-31249/com.ringcentral.glip W/System.err:     at org.java_websocket.SSLSocketChannel2.wrap(SSLSocketChannel2.java:141)
01-07 21:22:40.320 29089-31249/com.ringcentral.glip W/System.err:     at org.java_websocket.SSLSocketChannel2.<init>(SSLSocketChannel2.java:74)
01-07 21:22:40.330 29089-31249/com.ringcentral.glip W/System.err:     at org.java_websocket.client.DefaultSSLWebSocketClientFactory.wrapChannel(DefaultSSLWebSocketClientFactory.java:40)
01-07 21:22:40.330 29089-31249/com.ringcentral.glip W/System.err:     at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:242)
01-07 21:22:40.330 29089-31249/com.ringcentral.glip W/System.err:     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:219)
01-07 21:22:40.330 29089-31249/com.ringcentral.glip W/System.err:     at java.lang.Thread.run(Thread.java:841)

the code 
TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
            public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                return new java.security.cert.X509Certificate[]{};
            }

```
        public void checkClientTrusted(X509Certificate[] chain,
                                       String authType) throws CertificateException {
        }

        public void checkServerTrusted(X509Certificate[] chain,
                                       String authType) throws CertificateException {
        }
    }};

    KeyManager[] keyManager = null;
    try {
        final KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
        KeyManagerFactory factory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        factory.init(keyStore, null);
        keyManager = factory.getKeyManagers();
    } catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
    } catch (UnrecoverableKeyException e) {
        e.printStackTrace();
    } catch (KeyStoreException e) {
        e.printStackTrace();
    }

    try {
        sslContext = SSLContext.getInstance("TLS");
        sslContext.init(keyManager, trustAllCerts, new java.security.SecureRandom());
        HttpsURLConnection.setDefaultSSLSocketFactory(sslContext.getSocketFactory());
        SocketIO.setDefaultSSLSocketFactory(sslContext);
    } catch (Exception e) {
        e.printStackTrace();
    }
```

**Comment by SteveMobile** [comment]
I'm check the android source code ,ClientHandshakeImpl : 
private SSLSessionImpl findSessionToResume()  , 
ClientSessionContext context = parameters.getClientSessionContext();
SSLSessionImpl session= (SSLSessionImpl) context.getSession(host, port);

context.getSession(host, port) //return opensslsessionimpl , how to change the session to sslsessionimpl

**Comment by vinod1054** [comment]
same problem with me

**Comment by marci4** [comment]
Hello @SteveMobile and @vinod1054,

is this still an issue with the current version 1.3.2? 

Greetings
marci4

**Comment by marci4** [comment]
No update for months.
Closing issue!

Greetings
marci4

**Comment by sanat51289** [comment]
@marci4 I'm seeing this issue as well, when I use your library on Android SDK 19.
