### ISSUE TITLE
How to support Chinese characters in new WebSocketClient()  

### ISSUE THREAD

**Issue by 9992800** [TooTallNate/Java-WebSocket#365]
when I add parameters at the end of url  as follow:

wss://xxx.com/online_test?system=-1&80010086=-1&80010087=-1&userName=我是.

WebSocketClient() translate the Chinese words to ??:3   

I try to change the headers , but failed.
 Map<String, String> headers = new HashMap<String, String>();
headers.put("Content-Type", "application/json; charset=utf-8");

Still wrong :

write(293): {GET /online_test?system=-1&80010086=-1&80010087=-1&self=3&userName=??:3&token=a45dac5adfa4w HTTP/1.1

**Comment by marci4** [comment]
Hello @9992800,

you have to html encode all the chinese characters to valid html.

Greetings
marci4
