### ISSUE TITLE
wss not connecting on moto e 2nd gen with v5.0.1 OS

### ISSUE THREAD

**Issue by vinod1054** [TooTallNate/Java-WebSocket#368]
Connect mWebSocket
 I/art: Background sticky concurrent mark sweep GC freed 38812(4MB) AllocSpace objects, 13(208KB) LOS objects, 19% free, 10MB/13MB, paused 2.404ms total 119.211ms
 I/art: Background sticky concurrent mark sweep GC freed 3024(2MB) AllocSpace objects, 0(0B) LOS objects, 17% free, 10MB/13MB, paused 5.422ms total 76.754ms
 I/art: Background sticky concurrent mark sweep GC freed 3088(2MB) AllocSpace objects, 0(0B) LOS objects, 15% free, 11MB/13MB, paused 8.810ms total 30.418ms
 I/art: Background sticky concurrent mark sweep GC freed 2647(2MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 11MB/13MB, paused 6.132ms total 30.881ms
 I/art: Background sticky concurrent mark sweep GC freed 2229(1817KB) AllocSpace objects, 0(0B) LOS objects, 12% free, 11MB/13MB, paused 10.111ms total 43.919ms
W/art: Suspending all threads took: 21.536ms

**Comment by marci4** [comment]
Hello @vinod1054,

do you still have this issue?
Could you build the jar directly from the sources here on github?

Greetings
marci4

**Comment by marci4** [comment]
duplicates #424
