### ISSUE TITLE
receive bytebuffer with WebSocketClient

### ISSUE THREAD

**Issue by sebaber** [TooTallNate/Java-WebSocket#369]
Hi i have a problem with WebSocketClient class, when i want to change the receive type, the onMessage only accepts String, there is a way to change the type to bytebuffer? or have the two alternatives together?

public class MyWebSocketClient extends WebSocketClient {

```
    public MyWebSocketClient(URI serverURI) {
    super(serverURI);
}

   // Here i want to receive Bytebuffer not string
@Override
public void onMessage(String message) {
    }
```

}

**Comment by andiwand** [comment]
overwrite the `public void onMessage(ByteBuffer bytes)` method?

**Comment by kishordesai** [comment]
Override onMessage() method like this. It's working for me.
 @Override
    public void onMessage(WebSocket conn, ByteBuffer buff)

**Comment by marci4** [comment]
Issue answered. closing

Greetings
marci4

**Comment by amirreza-sobhdel** [comment]
> Override onMessage() method like this. It's working for me.
> @override
> public void onMessage(WebSocket conn, ByteBuffer buff)

nah it didnt work , still have to implenment onMessage(String string)

**Comment by NoahAndrews** [comment]
> nah it didnt work , still have to implenment onMessage(String string)

Just implement it as an empty function if you want to ignore all String messages.

**Comment by amirreza-sobhdel** [comment]
yes , it worked , thanks ;)

‫‪Noah Andrews‬‏ <‪notifications@github.com‬‏> در تاریخ دوشنبه ۱۱ فوریهٔ
۲۰۱۹ ساعت ۱۹:۱۶ نوشت:‬
