### ISSUE TITLE
Release a new version of the library (JitPack.io)

### ISSUE THREAD

**Issue by rockwotj** [TooTallNate/Java-WebSocket#371]
Hello, 

I've seen the other issues about releasing a new version of the library, and I'm not sure why there has not been a release. If there are complications, I suggest to moving to @jitpack to make things easier. All you then have to do is push a github release, and then you can use JitPack to distribute your project. 

I forked the repo and did this for myself in my own fork. You can see information about it here: https://jitpack.io/#rockwotj/Java-WebSocket/v1.4.0

**Comment by gang018** [comment]
can't download your release from jitpack, Android Studio shows an error "can't find"

**Comment by rockwotj** [comment]
Sorry, I deleted by fork of this repo, as I found another library for my use case. @gang018 what you can do instead is find the [commit](https://github.com/TooTallNate/Java-WebSocket/commits/master) of Java-WebSocket that you want, and then grab that from JitPack.

Checkout out this link for the latest commit at the time of writing. This should work for you.

https://jitpack.io/#TooTallNate/Java-WebSocket/58d17786958ec2b629b75de1eed00915b3e4f7c4

Then if a new feature comes along that you'd like, you can just update the commit SHA and you'll have a new version! :beers:

**Comment by gang018** [comment]
@rockwotj Thanks for quick response)

**Comment by bluebluby** [comment]
@rockwotj Which library did you find? I picked this one because it was the first one i found that supports ssl. Have you found a better one?

**Comment by rockwotj** [comment]
@bluebluby I only need a client. So I am using: https://github.com/TakahikoKawasaki/nv-websocket-client

It is working really well for me in an android app in production, over wss.
