### ISSUE TITLE
WebsocketNotConnectedException during send from server

### ISSUE THREAD

**Issue by jackwilliambell** [TooTallNate/Java-WebSocket#376]
Connecting to websocket server from Firefox using localhost. Firefox shows the connection is open and does not get a connection closed event. My use case is 'push' only, so I am using the connection to send data to the web page. When I send the data I get a WebsocketNotConnectedException.

Digging into this further I found that the Draft_10.java translateSingleFrame() method was reading a Opcode.CLOSING byte from the buffer during the send. Which I don't understand, because I believe decode() in the implementation is only called for messages sent from the client. If I am correct in this, than possibly Firefox is sending a close event?

My server code sends the message to the connection by iterating through the open connections and calling send() on each. In my testing I only have the one connection.

NOTE: I can be available on the IRC channel at any time you name to discuss this.

My client code looks like this:

```
var ws;
var $ = require('jquery');
var $body = $(document.body);

function onMessage (event) {
    var data = JSON.parse(event.data);
    if (data.type) {
        $body.trigger(data.type, data);
    }
}

module.exports = {
    /**
     * Connects to server via WebSocket connection
     * @return {WebSocket}
     */
    connect: function(port){
        ws = new WebSocket('ws://localhost:' + port);
        ws.onopen = function(){
            console.info('WebSocket connected');
        };

        ws.onmessage = onMessage;

        return ws;
    },

    /**
     * Bind event handler
     * @param  {string}   eventType   'type' property that comes with json (e.g., "screenUpdate")
     * @param  {Function} callback    Called with 2 parameters: 1st - jQuery event object, 2nd - data
     */
    on: function(eventType, callback){
        $body.on(eventType, callback);
    },

    /**
     * @return {WebSocket}
     */
    getWebSocket: function(){
        return ws;
    }
};
```

**Comment by jackwilliambell** [comment]
Update...

I restarted both my IDE (IDEA) and loaded a completely new copy of the web page. I did not restart FIrefox. I ran my test again and this time it appeared to work. 

Is it possible that earlier crashes or incomplete shutdowns left Websocket threads running or left the Websocket server code in an invalid state somehow? If yes, that was my problem; and I would like to know if there is an easy way to reset/shut down properly to avoid this in a production application. I had thought that when I killed the app it also killed all the running threads, but maybe I was wrong.

Thanks;

Jack

**Comment by jackwilliambell** [comment]
Update. I am continuing to get this error. If I reboot my machine and start over from scratch the server will send one message to the client. After that I get the error on every try, even if I kill the server process and start it again. Every time I reload the client code in Firefox it says it is connected to the websocket server, but I still get the error. I will now try the same on some different browsers.

**Comment by marci4** [comment]
Hello @jackwilliambell 

I would recommend to you to use Draft_17 and not Draft_10!

Greetings
marci4
