### ISSUE TITLE
Help! New to java, struggling with getting this into Eclipse

### ISSUE THREAD

**Issue by clickstan** [TooTallNate/Java-WebSocket#377]
Hey, I'm new to java development (using it for speeding up my real-time game server, coming from python)

I downloaded the ZIP of this repository, but can't find out how to add this so that it can be used in eclipse. 
![screen shot 2016-04-18 at 9 24 11 pm](https://cloud.githubusercontent.com/assets/8376113/14624811/e9ad8342-05ab-11e6-822b-dec6ec91ff12.png)

There is a big folder of folders, and I don't know where to start:
![screen shot 2016-04-18 at 9 25 58 pm](https://cloud.githubusercontent.com/assets/8376113/14624840/2a1fb2e2-05ac-11e6-9745-eb5aba1db428.png)

There isn't much help online that I could find for this case, is there a way to compile this into a single .JAR to add to eclipse? (I've had this problem with other .GIT repositories) Here is my simple project right now:
![screen shot 2016-04-18 at 9 25 11 pm](https://cloud.githubusercontent.com/assets/8376113/14624829/0d541b9e-05ac-11e6-8c08-247d73e1b868.png)

Any help is greatly appreciated! (I'm on mac os X btw, not that it should be different)

**Comment by Wulf** [comment]
You can find the JAR [here](http://mvnrepository.com/artifact/org.java-websocket/Java-WebSocket/1.3.0). I suggest you use Gradle or even Maven to manage your dependencies for you. It could get tricky juggling all the JARs.

All the best~

**Comment by marci4** [comment]
Looks like problem is answered.

Greetings
marci4

**Comment by clickstan** [comment]
I ended up figuring out that you can build the repository by callling 'ant' after cding to the root folder of the package. Also, ended up tweaking this lib for my own uses :)

**Comment by marci4** [comment]
@clickstan if you have anything to share feel free to open a pull request ;)
