### ISSUE TITLE
Server stops receiving/sending data when Exception

### ISSUE THREAD

**Issue by soylomass** [TooTallNate/Java-WebSocket#379]
I've been trying to solve this problem since a few days ago, and it prevents me of doing further testing of my game.

I'm using this Websocket libray, plus JSON simple for parsing messages.

When I receive a message, I parse it and then work on the JSONObject. The problem is that sometimes the parser would throw an exception, and even if my try { } catch {} catches it, the UncaughtHandlerException in the server will act.

` 

```
        @Override
           public void onMessage(WebSocket arg0, String arg1) {
            GameWebSocket ws = (GameWebSocket) arg0;

            try {
                Object obj = parser.parse(arg1);

                JSONObject jsonObject = (JSONObject) obj;

                if(jsonObject.containsKey("userId")){
                    ......
                }
            } catch (ParseException e) {
                System.out.println("COULDN'T PARSE "+arg1);
                e.printStackTrace();
            } catch (NullPointerException e){
                e.printStackTrace();
            }
        }
```

`

The error I always get (sometimes the message and worker ID is different):

`
COULDN'T PARSE {"unpressedKey":29}

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "WebSocketWorker-10"
Unexpected token END OF FILE at position 17.
    at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
    at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
    at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
    at com.ouwi.tankario.desktop.WSGameServer$1.onMessage(WSGameServer.java:174)
    at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:487)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:705)
`

As you see, the "COULDN'T PARSE {"unpressedKey":29}" message proves that the Try Catch is catching the ParseException exception.

I'd be extremely thankful if someone could help me, as I've tried a lot of things.

**Comment by marci4** [comment]
Hello @soylomass,

do you still have this issue?

I ran into the same issue and the problem and made sure that the problem doesn't happen any more by catching all exceptions!

Would recommend this to you too.

Anyway, I'm gonna merch a pull request printing a stacktrace for exceptions caught by the UncaughtExceptionHandler 

Greetings
marci4

**Comment by marci4** [comment]
fixed with #437

**Comment by Purikov** [comment]
I am having same issue with 1.4.0

**Comment by marci4** [comment]
@Purikov please open a fresh issue with steps to repeat...
