### ISSUE TITLE
when i invoke client.close method ,the onClose will be invoked after about 1min ,why so late?

### ISSUE THREAD

**Issue by happycodinggirl** [TooTallNate/Java-WebSocket#381]

**Comment by happycodinggirl** [comment]
when i invoke client.close method ,the onClose will be invoked after about 1min ,why so late?

**Comment by jpatel531** [comment]
+1

**Comment by marci4** [comment]
Hello @happycodinggirl,

does this issue still exists for you with the most recent lib version?

Greetings
marci4

**Comment by happycodinggirl** [comment]
no,i found it missing.the question may be solved.Thank you for the library!
