### ISSUE TITLE
chatclient.setSocket(factory.createSocket()) - > setSocket function not found.

### ISSUE THREAD

**Issue by hiteshpurohit** [TooTallNate/Java-WebSocket#382]
This project is most useful for me so far.but i got stuck as setSocket does not exists. i am using _.jar_ from dist folder in a android project.
please tell me if i am doing something wrong or it is a problem with _.jar_ file

**Comment by HellerCommaA** [comment]
@hiteshpurohit I'm willing to bet you pulled the project file from Maven / equivalent. Checkout 58d17786958ec2b629b75de1eed00915b3e4f7c4 from this repo. I believe the Maven build is broken.

**Comment by kishordesai** [comment]
Hi Hitesh,
 
I was also facing same issue. I tried following code instead of "chatclient.setSocket()". It's working fine.
	chatclient.setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sslContext));

Refer:
http://www.juliankrone.com/connect-and-transfer-data-with-secure-websockets-in-android/

**Comment by marci4** [comment]
Looks like the issue is answered.

Greetings
marci4
