### ISSUE TITLE
Chat example client is not functional

### ISSUE THREAD

**Issue by thoughtspile** [TooTallNate/Java-WebSocket#386]
The HTML part is broken for these reasons:
1. "document.observe is not a function": consider moving the logic into the bottom of the body or wrapping document with prototype object.
2. Prototype library isn't bundled with the example: it  should be either included or linked to via CDN.
3. On FF button clicks on form trigger page reload. This is fixed by adding `action="javascript:void 0"` to form elements.

Not sure how contributing works, but I guess I could even fix it.

**Comment by becast** [comment]
I checked this out, I can't reproduce a single issue here.
1.) Works for me  
2.) prototype.js is bundled (https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/prototype.js)
3.) Does not trigger a reload for me with Firefox 47.0

**Comment by marci4** [comment]
Cannot reproduce
