### ISSUE TITLE
NullPointerException in SocketChannelIOHelper when ping to server

### ISSUE THREAD

**Issue by picolino0** [TooTallNate/Java-WebSocket#388]
I used http://www.yougetsignal.com/tools/open-ports/ to check if the port of my server was open. When I'm connected with my server via simple Javascript websockets and then ping using that website, I get the following exception:
`java.lang.NullPointerException
 	at org.java_websocket.SocketChannelIOHelper.read(SocketChannelIOHelper.java:14)
 	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:322)
 	at java.lang.Thread.run(Unknown Source)`

That's all. So this can't be because of my own code.

I tried to solve it by adding
`// Ignore if channel is null
if (conn.channel == null)
continue;`

right above the `if (SocketChannelIOHelper.read(buf, conn, conn.channel))`. This prevents the server from crashing and there's no exception. However, the websocket is still closed and im unable to reconnected without restarting the server.

I'm running a TLS server if that makes any difference.

**Comment by picolino0** [comment]
apparently #277 is supposed to fix this problem. I implemented it, but nothing changed.

**Comment by becast** [comment]
Have a look at this: https://github.com/TooTallNate/Java-WebSocket/issues/349#issuecomment-212691018

**Comment by picolino0** [comment]
That didn't solve it. Now it keeps saying the port is open, but I'm unable to connect once I've pinged once

**Comment by becast** [comment]
Yeah I faced the same issue. I solved it but to be honest I have no clue what the deciding change was.
I added this
```
if( key.isReadable() ) {
							conn = (WebSocketImpl) key.attachment();
							ByteBuffer buf = takeBuffer();
							try {
								if(conn.channel == null){
									if( key != null )
										key.cancel();
									
									handleIOException( key, conn, new IOException() );
									continue;
								}
```
Maybe it helps, since my library is quite altered at this point I can't guarantee it, but I'll open a PR if you confirm this as the working change.

**Comment by picolino0** [comment]
Yes! this did the trick. Thank you so much it finally works now.
