### ISSUE TITLE
make continuation response from server, following client->server PING

### ISSUE THREAD

**Issue by twoi** [TooTallNate/Java-WebSocket#392]
… (yes, not PONG), work; `.Net`'s `System.ServiceModel.WebSockets.WebSocket` client will by default send a PING to the server every 50 seconds

A Pull Request to fix this: https://github.com/TooTallNate/Java-WebSocket/pull/383

Absent this pull request, the following exception will be thrown upon the server continuation frame:

```
2016/05/17 08:32:01.951,E,Thread-0,WebSocketHandler.java(113) [Main.onError],onError
org.java_websocket.exceptions.InvalidFrameException: bad rsv 1
        at org.java_websocket.drafts.Draft_10.translateSingleFrame(Draft_10.java:309) ~[Java-WebSocket-1.3.0.jar:na]
        at org.java_websocket.drafts.Draft_10.translateFrame(Draft_10.java:286) ~[Java-WebSocket-1.3.0.jar:na]
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:312) [Java-WebSocket-1.3.0.jar:na]
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157) [Java-WebSocket-1.3.0.jar:na]
        at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230) [Java-WebSocket-1.3.0.jar:na]
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188) [Java-WebSocket-1.3.0.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

```

I'm not sure if this is conforming to WebSocket standards, but this is what (one of the many) official MS WebSocket client implementation does by default: sending PINGs to the server.

Attached are screenshots of the 3 TCP frames that make up such a client initiated heartbeat exchange

![ms-1-client-server-ping](https://cloud.githubusercontent.com/assets/1841686/15313183/a1f7e5d8-1c44-11e6-9433-c781254affd2.png)
![ms-2-server-client-continuation](https://cloud.githubusercontent.com/assets/1841686/15313189/abfd638c-1c44-11e6-9409-964a4b962149.png)
![ms-3-client-server-tcp-ack](https://cloud.githubusercontent.com/assets/1841686/15313192/b12b4c52-1c44-11e6-939c-7a11718530a4.png)

**Comment by marci4** [comment]
hey @twoi,

I went through the spec and at chapter [11.8](https://tools.ietf.org/html/rfc6455#section-11.8) all the opcodes are specified!

But it could be that there is a bug that the opcode continuation is not correctly dealt with

Greetings
marci4

**Comment by twoi** [comment]
Thanks @marci4 for looking into this. Yes, so Continuation is one of the specified opcodes (opcode = 0). However the RFC you referenced does not define a scenario like the one `System.ServiceModel.WebSockets.WebSocket` has implemented.

I wonder why MS did that - was it perhaps part of an older version of a spec? Because you'd think when implementing a standard protocol, you'd do so for interoperability.

But according to the spec,

1. `Upon receipt of a Ping frame, an endpoint MUST send a Pong frame in response`
2. There is no such thing as a standalone, even empty (Payload Len: 0) CONTINUATION frame with the FIN bit clear.

As to the second point, although other uses are no specifically excluded, the purpose of CONTINUATION frames is to allow fragmentation of frames. The defined opcodes and FIN bit values for fragmented frames:

```
   o  An unfragmented message consists of a single frame with the FIN
      bit set (Section 5.2) and an opcode other than 0.

   o  A fragmented message consists of a single frame with the FIN bit
      clear and an opcode other than 0, followed by zero or more frames
      with the FIN bit clear and the opcode set to 0, and terminated by
      a single frame with the FIN bit set and an opcode of 0.
```
So what `System.ServiceModel.WebSockets.WebSocket` is doing in effect is sending a (empty payload) middle-fragment of a fragmented message in response to a PING from the client.

This contravenes the spec, but enabling this by default is not doing any harm, other than NOT throwing an exception in this case that other websocket implementations do not produce.

However, after reading the spec, understanding what CONTINUATION is all about, and looking again at the Java-WebSocket code, adding a new OpCode.CONTINUATION (in addition to the existing Opcode.CONTINUOUS with the same byte value) and  an `onWebsocketContinuation()` method to the `WebSocketClient` etc does not look like the right thing to do.

Allowing/Ignoring the MS style CONTINUATION frame should be integrated with the existing handling of the CONTINUOUS opcode. If and when requests/pressure from clients comes again, I'd be willing to look into this again, as they have to cope with our MS server implementation. Then I'd come up with something that integrates better into the existing code base.

For the time being, rejecting my PR will be the right thing to do. This issue however could still stay open

**Comment by marci4** [comment]
Hello @twoi,

sorry to ping you about this issue again.

Have you, by any chance, checked if this is still an issue for you with the latest version?

Greetings
marci4

**Comment by twoi** [comment]
@marci4 I'm not involved in that project any more, and so unfortunately I currently have no easy way to test the latest version.

So I won't cry if you close this issue :)

**Comment by marci4** [comment]
Thank your feedback!

Since no one else seems to have this issue and you are fine with it, I will close it!

If however anyone has the same problem, feel free to reopen this!

Best regards,
marci4
