### ISSUE TITLE
Incorrect parameter type in ProxyClientExample.java

### ISSUE THREAD

**Issue by DonnyLi** [TooTallNate/Java-WebSocket#393]
The setProxy method in the WebSocketClient class is looking for an argument of type InetSocketAddress instead of type Proxy.

**Comment by marci4** [comment]
Hello @DonnyLi,

have you tried to update your lib? 

On the current codebase this is the setter for a proxy.
```java
public void setProxy( Proxy proxy ) {
if( proxy == null )
throw new IllegalArgumentException();
this.proxy = proxy;
}
```

Greetings
marci4
