### ISSUE TITLE
TLSv1.2 Record Layer: Alert (Level: Fatal, Description: Internal Error)

### ISSUE THREAD

**Issue by patelrahul2040** [TooTallNate/Java-WebSocket#394]
why i am getting this error message 
TLSv1.2 Record Layer: Alert (Level: Fatal, Description: Internal Error)
from client side during SSL handshake .

**Comment by marci4** [comment]
Hey @patelrahul2040,

for me that looks like an internal error in your tls implementation/lib.

Does this problem still exists?

Greetings
marci4

**Comment by marci4** [comment]
No update for months and no clear description.

Closing issue!
Greetings
marci4

**Comment by abhi484** [comment]
@marci4 I am facing a similar change as described above. Please find the image below: 
![image](https://user-images.githubusercontent.com/67599173/93101299-b98a6100-f6c7-11ea-86d1-8de4417c0810.png)

Also, please note this is happening on the app only when it is going through a CDN. The browser seems to work fine in any case i.e. with CDN or without CDN. Please let me know if you require any other details. TIA.

**Comment by marci4** [comment]
@abhi484 please create a new issue with an example application and clear steps to repeat 

Best regards
Marcel

**Comment by abhi484** [comment]
@marci4 apologies, I have opened https://github.com/TooTallNate/Java-WebSocket/issues/1067 for the same.
