### ISSUE TITLE
need help ,someone have any idea about this problem ? connect with draft 17

### ISSUE THREAD

**Issue by busyfree** [TooTallNate/Java-WebSocket#395]
Default server url not specified: defaulting to 'ws://***_/ws/room/wsocket'
write(216): {GET /ws/room/wsocket HTTP/1.1
Connection: Upgrade
Host: ***_*
Sec-WebSocket-Key: MqqPrhKBFR0lr/R0qc5dDg==
Sec-WebSocket-Version: 13
Upgrade: websocket

}
process(135): {HTTP/1.1 403 Forbidden
Server: nginx
Date: Mon, 15 Aug 2016 10:51:10 GMT
Transfer-Encoding: chunked
Connection: keep-alive

0

}

**Comment by marci4** [comment]
hello @busyfree,

have you fixed your problem yet?

I think he problem is the additional file path at the end of ws://**.

Try to remove this and it should hopefully be fixed.

Greetings
marci4

**Comment by busyfree** [comment]
sorry ,forgot to closed
