### ISSUE TITLE
How I can connect java-webSocket with Sokect.io

### ISSUE THREAD

**Issue by johnsh** [TooTallNate/Java-WebSocket#396]
Hi

(First my english isn't good.)

I've developed an app on android that implements Java-WebSockets (Client) and I'd like to connect with Sockect.io (Server). 

Is possible the above ?, please if someone has examples could be good

**Comment by IllusionaryOne** [comment]
You cannot actually.  Socket.IO uses a different handshake protocol among other things.  I was unable to use this library to connect to a Socket.IO server in Java and had to use another one (I still use this library for other means though, connecting to websocket servers that follow the RFC for websockets).

**Comment by johnsh** [comment]
Hi, @IllusionaryOne thanks for you soon reply. 

Which library might I use for connect Android ( Client ) and node js (Server) ?

Thanks

**Comment by IllusionaryOne** [comment]
@johnsh I did not develop for Android but I used https://github.com/socketio/socket.io-client-java  It has dependencies, be sure to follow that through in their documentation.

Cheers!

**Comment by johnsh** [comment]
Hi, @IllusionaryOne 

I've followed this tutorial https://www.youtube.com/watch?v=WFfd4QbmWpI

Now I have the connection between android and node js
