### ISSUE TITLE
need help ,someone have any idea about this problem ? Closed websocket, onClose method is not correction

### ISSUE THREAD

**Issue by youyuanme** [TooTallNate/Java-WebSocket#397]
Connect me WebSocket called after WebSocketClient. After the close method not onclose callback method, but the service has been closed the connection.

**Comment by marci4** [comment]
Hello @youyuanme,

I do not really understand your issue. 
For my projects onClose will always be called when the server closes the connection.

Greetings
marci4

**Comment by qktang** [comment]
I also met. Do not operate for a long time, the client can not receive the message, the server is closed, but the client does not call closure method

**Comment by qktang** [comment]
I also met. Do not operate for a long time, the client can not receive the message, the server is closed, but the client does not call onClose

**Comment by marci4** [comment]
Hello @qktang,

are you on the latest version 1.3.2?
Right now this version is passing all the tests provided by the autobahn testsuite including closing behavior, so for me this works.

Greetings
marci4

**Comment by hattie0312** [comment]
I also met. The version is 1.3.4. I called close(), but never received onClose(int code, String reason, boolean remote). 
Oh my god. My project will be blocked in this situation.

**Comment by marci4** [comment]
hello @hattie0312,
could you provide some steps to reproduce for me?
what are you doing on the client side and what are you doing on the server side?

Greetings 
marci4

**Comment by marci4** [comment]
No feedback!

If you still have this issue, please open a separate thread!
Greetings
marci4
