### ISSUE TITLE
Mismatch code repository on org.java-websocket:Java-WebSocket and Github

### ISSUE THREAD

**Issue by SnitramDev** [TooTallNate/Java-WebSocket#398]
In my android app I've imported this library using the following dependency:
compile 'org.java-websocket:Java-WebSocket:1.+'

However, if you take a look at the WebSocketClient class you see it differs a lot from the one available through this github repository. In fact, the "timeout" doesn't seem to be used on the library downloaded through Maven. This variable has different names (timeout in Maven and connecttimeout in Github).

See attached both files. Could you please update so I can download this library using the gradle file?
[WebSocketClient_Github.txt](https://github.com/TooTallNate/Java-WebSocket/files/495426/WebSocketClient_Github.txt)
[WebSocketClient_Maven.txt](https://github.com/TooTallNate/Java-WebSocket/files/495425/WebSocketClient_Maven.txt)

What's the dependency the link I should use in gradle to retrieve the github repository instead?
I'm trying to use this without success: com.github.tootallnate:java-websocket:1.0+

Thanks

**Comment by SnitramDev** [comment]
What's the dependency the link I should use in gradle to retrieve the github repository instead?
I'm trying to use this without success: com.github.tootallnate:java-websocket:1.0+

**Comment by SnitramDev** [comment]
In the meanwhile, I've compiled the library and manually imported into my project.

**Comment by marci4** [comment]
I personally don't have any access to maven. 

Gonna try to get in contact with @TooTallNate 

Greetings
marci4

**Comment by TooTallNate** [comment]
I don't have access to Maven either. I have no idea who is (was) maintaining that.

**Comment by marci4** [comment]
I looked into it a bit more and found out that this website:
https://mvnrepository.com/artifact/org.java-websocket/Java-WebSocket/1.3.0

Looks like @TooTallNate is the founder and @Davidiusdadi is the current maintainer.

Greetings

**Comment by marci4** [comment]
Same as #306

**Comment by marci4** [comment]
I pushed an update to clojars.

Greetings
marci4
