### ISSUE TITLE
https:// not connect in java web socket library 

### ISSUE THREAD

**Issue by piyurabadiya** [TooTallNate/Java-WebSocket#401]
I am using this library :- 'org.java-websocket:Java-WebSocket:1.3.0'
when I connect https url  throw exception unknown scheme https and  also use protocols ws:// or wss://(similar to http://, https://) but i get exception malformedurlexception unknown protocol wss

**Comment by marci4** [comment]
Hello @piyurabadiya,

have you tried the example provided [here](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLClientExample.java)?

Greetings
marci4

**Comment by marci4** [comment]
No response after one months..
Looks like wrongy used constructor.

Closing issue.
Greetings
marci4
