### ISSUE TITLE
Why  WebsocketClient.sendhandshake  use  uri.getQuery?

### ISSUE THREAD

**Issue by 37du** [TooTallNate/Java-WebSocket#402]
In sendHandshake() method, I see  uri.getQuery(),  why not use uri.getRawQuery().
uri.getQuery() invoke decode.   if  query of uri has encoded,  and Server always decode, there is problem.

**Comment by piyurabadiya** [comment]
I have try your way .But not working  and I got exception like RuntimeException: unknown scheme  https.I don't retract the issue.what is requirement for connecting https URL??

**Comment by 37du** [comment]
In my case,  scheme use ws://,    or  use wss://

**Comment by 37du** [comment]
@piyurabadiya     In my case, scheme use ws://, or use wss://

**Comment by piyurabadiya** [comment]
I also try this way but in my case not work and thrown exception MalformedURLException

**Comment by 37du** [comment]
I pass URI to WebsocketClient,   URI can accept ws scheme

**Comment by marci4** [comment]
Hello @37du  and @piyurabadiya 

please use the following example when you call the constructor:
`new URI("ws://example.org)"`

Greetings
marci4
