### ISSUE TITLE
Will this work on a Primus server?

### ISSUE THREAD

**Issue by jojonarte** [TooTallNate/Java-WebSocket#405]

**Comment by Kenny-House** [comment]
I've used Java-WebSocket with Primus before, and it can definitely work well. I believe we used the WebSockets transformer.

Keep in mind, no matter what transformer you use, Primus has a heartbeat protocol you'll want to implement for your client: https://github.com/primus/primus#heartbeats-and-latency

**Comment by marci4** [comment]
Looks like his question was answered.

Closing issue

Greetings
marci4
