### ISSUE TITLE
serving static files on the same port?

### ISSUE THREAD

**Issue by PerBothner** [TooTallNate/Java-WebSocket#406]
Is there a way to serve static content (such as the final JavaScript file for the client) using this library?  Or more generally serve http:/https:in addition to ws:/wss:

Of course using two ports isn't terrible, but it seems easier to setup and configure if only one port is needed.

I see other server implementations that appears to handle both http and ws, but I can't find anything that is both truly lightweight and pure Java. Something like [libwebsockets](https://libwebsockets.org/index.html) would probably work - were it written in Java rather than C.

**Comment by marci4** [comment]
Hello @PerBothner,

no right now it is not possible for the libary to serve http/https and ws/wss.

You could just implement your own webserver into your application running parallel to your ws-server.

Greetings
marci4

**Comment by PerBothner** [comment]
For DomTerm, I've switched to using libwebsockets.  For my Java applications, I'm using AJAX as a fallback.

**Comment by nospam2k** [comment]
Sorry to reopen this, but didn't want to open a new request on the same topic.

I have implemented your websockets server with NanoHTTPD and it's working fine using two ports. I've only briefly read about how websockets and http server can use the same port. Is there (without taking much of your time) a way to join the two together so I can just use port 80. I know I need to some how hand off the connection to upgrade to ws but not sure where/how that happens. Thanks for a great lib!

**Comment by marci4** [comment]
Hello @nospam2k,

I dont think there is a easy way to merge these two projects.
However nanoHttpd already includes a websocket as far as I can tell.
https://github.com/NanoHttpd/nanohttpd/blob/master/websocket/src/main/java/org/nanohttpd/protocols/websockets/WebSocket.java

Best regards,
Marcel

**Comment by nospam2k** [comment]
Ugh! Thanks (embarrassed) I've been using a chiseled up version of NanoHttpd with only the barebones http server components for so long I didn't even look at the original code. Thanks (and sorry) for (wasting) your time.

**Comment by NoahAndrews** [comment]
@nospam2k I'd recommend against using the NanoHTTPD websocket server. I started with that because I was already using NanoHTTPD, and kept finding bugs and weird issues. The code quality seemed questionable to me as well. As a result, I'm using Java-Websocket on a different port from NanoHTTPD.

**Comment by nospam2k** [comment]
Thanks for the tip. So... is it possible to fiddle your websocketlistener to respond to a ws://server/websocket rather then a port number without too much trouble?

**Comment by NoahAndrews** [comment]
No, you need to run it on a different port than NanoHTTPD. That's not to say integration of the two is impossible, but I don't think it's going to happen "without too much trouble", as @marci4 said.
