### ISSUE TITLE
tcp_nodelay fix

### ISSUE THREAD

**Issue by clickstan** [TooTallNate/Java-WebSocket#409]
In the latest version, the only way to turn ON tcp_nodelay (reduces jitter for real-time games), is to replace websocketserver.java with the following (it will then ALWAYS BE ON):
 (You can thank me quietly, Im only posting this because others here have helped with their posted info- giving back) Would be great if this was made a public option for the lib

[WebSocketServer.java.zip](https://github.com/TooTallNate/Java-WebSocket/files/572507/WebSocketServer.java.zip)

**Comment by marci4** [comment]
Hello @clickstan, 
could you please open a pull request for your commit?

Greetings
marci4

**Comment by clickstan** [comment]
I'm actually interested in learning GIT more, so i'll do it!

**Comment by marci4** [comment]
possible duplicates #339 (internal for me)

**Comment by marci4** [comment]
added with #462

**Comment by marci4** [comment]
https://github.com/TooTallNate/Java-WebSocket/wiki/Enable-TCP_NODELAY
