### ISSUE TITLE
DefaultSSLWebSocketClientFactory class is missing?

### ISSUE THREAD

**Issue by FavoRiteKK** [TooTallNate/Java-WebSocket#410]
Hello, I pull this project and I want to use the class DefaultSSLWebSocketClientFactory in my source, but this class is not exists. Why is it?

**Comment by atonamy** [comment]
Here you can get missing files https://github.com/Kicksend/Initiative/tree/master/WebSocketServer/src/main/java/org/java_websocket/client

**Comment by marci4** [comment]
The class exists in the current master branch.

Greetings
marci4

**Comment by leokho** [comment]
Hi!
I've just updated the library in my gradle and seems like this file isn't being downloaded. 
"Error:(81, 33) error: cannot find symbol class DefaultSSLWebSocketClientFactory"

I've just updated to 1.3.8 from 1.3.0

Thanks
