### ISSUE TITLE
GC_CONCURRENT freed ... (android)

### ISSUE THREAD

**Issue by atonamy** [TooTallNate/Java-WebSocket#411]
This code generate unstoppable  

> GC_CONCURRENT freed 

feed in the log  

Tested in Android:

```
 URI uri;
        try {
            uri = new URI("wss://some-secure-websocket.com"); // issue only with wss
        } catch (URISyntaxException e) {
            e.printStackTrace();
            return;
        }

        final WebSocketClient mWebSocketClient = new WebSocketClient(uri, new Draft_17()) {
            @Override
            public void onOpen(ServerHandshake serverHandshake) {
              mWebSocketClient.close();
            }

            @Override
            public void onMessage(String s) {
               
             //some code here
            }

            @Override
            public void onClose(int i, String s, boolean b) {
                
             //some code here
            }

            @Override
            public void onError(Exception e) {
                Log.i("Websocket", "Error " + e.getMessage());
                //some code here
            }
        };
        SSLContext sslContext = null;
        try {
            sslContext = SSLContext.getInstance( "TLS" );
            sslContext.init( null, null, null );
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (KeyManagementException e) {
            e.printStackTrace();
        }
        mWebSocketClient.setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sslContext));
        mWebSocketClient.connect();
```

Most probably there memory leak in your code that you have to fix.

P.S. In new version of Android looks like no issue is only in Android 4.1.X

**Comment by rajathvsm** [comment]
I face this issue too, especially when the server disconnects for some reason. I am passing the auth info as URI args, and I disconnect on the server side if they are not right. On the client side, I'm using self-signed certs, with this code to trust all hosts:

`TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
                public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                    return new java.security.cert.X509Certificate[]{};
                }
                public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
                }
                public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
                }
            }};
`
Rest of the code looks pretty similar to the one posted before this.
With the right credentials, I do not get the constant GC. But with incorrect credentials, the objects GC'ed are allocated as shown below:
![screenshot from 2017-01-17 15-24-37](https://cloud.githubusercontent.com/assets/5296079/22044394/624f3fda-dcc9-11e6-9266-b02e60fbd8bd.png)
I can add more details if needed.

**Comment by atonamy** [comment]
@rajathvsm thnaks

I solved this problem to recompile all library from source and missing files I took from here https://github.com/Kicksend/Initiative/tree/master/WebSocketServer/src/main/java/org/java_websocket

And works like a charm without any issue now.

**Comment by marci4** [comment]
Hello @atonamy,

can you tell me which files were missing?

Would like to fix this issue for you and others!

Greetings
marci4

**Comment by atonamy** [comment]
@marci4
I don't remember which exactly files. I can send you my custom build if you want. Anyway this library seems to be outdated already. I recently discovered featured and solid nv-websocket-client  and very happy to use it in Android.

**Comment by marci4** [comment]
Yes please send me a mail to admin at marci4.de 


Greetings 
Marci4

**Comment by atonamy** [comment]
@marci4 
Just sent you email.

**Comment by marci4** [comment]
@atonamy thx for the respone. Got your mail :)

Gonna have to update the documentation, this files are not needed any more.

Closing issue.
Greetings
marci4
