### ISSUE TITLE
Question about wss://

### ISSUE THREAD

**Issue by whitebian** [TooTallNate/Java-WebSocket#412]
I built a server on Android device by Java-WebSocket, and built a client on web page of HTML5. Now, they can communicate by WebSocket when used http:// and ws://, but cannot talk by https:// and wss://. Is there  any settings on Android platform when I built server?

**Comment by IllusionaryOne** [comment]
Did you extend your class to support TLS and link it to a certificate?

**Comment by whitebian** [comment]
@IllusionaryOne Yes, I also tried to build a TrustManager which doesn't validate any certificate chains. But it still cannot be connected.  Below is my code:

`    try {
            int port = 8887;
            mJavaWebSocketServer = new JavaWebSocketServer(this, port);
            WebSocketImpl.DEBUG = true;
            // Install the all-trusting trust manager
            SSLContext sc = SSLContext.getInstance("TLS");
            sc.init(null, trustAllCerts, new java.security.SecureRandom());
            mJavaWebSocketServer.setWebSocketFactory(new DefaultSSLWebSocketServerFactory(sc));

            mJavaWebSocketServer.start();
            Log.d(LOG_TAG, "startServer()");
        } catch (Exception e) {
            Log.e(LOG_TAG, "Exception when started server: " + e);
        }`

**Comment by munnadroid** [comment]
@whitebian have you got any progress ? I am stuck in this problem. @IllusionaryOne

**Comment by marci4** [comment]
Hello @munnadroid and @whitebian 

Could you please check out the wiki [here](https://github.com/TooTallNate/Java-WebSocket/wiki/Getting-a-SSLContext-from-different-sources) and give me feedback if this helps you?

Greetings
marci4

**Comment by marci4** [comment]
I can use wss on android and connect from different sources to it.

Closing the issue.
Greetings
marci4
