### ISSUE TITLE
Crash app by OutOfMemoryError

### ISSUE THREAD

**Issue by pvtai** [TooTallNate/Java-WebSocket#416]
It happen when run app a long time, how to fix this?
Thank you,
```
java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
	at java.lang.VMThread.create(Native Method)
	at java.lang.Thread.start(Thread.java:1029)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:181)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by Didi95** [comment]
it seems that the server spawns too many threads, if you run the server too long.

**Comment by pvtai** [comment]
Yes, I'm run the server too long time, but I don't know how to fix it :)

**Comment by marci4** [comment]
hey @pvtai,

do you still have this issue?

Could you please provide your calls for the constructors of the WebSocketClient and WebSocketServer?

Greetings
marci4

**Comment by marci4** [comment]
Closing this issue since there is no additional feedback and I also merged some fixes for shuting down threads.
Also not having any open threads in the profiler.

Greetings marci4
