### ISSUE TITLE
Question for Nate

### ISSUE THREAD

**Issue by ORESoftware** [TooTallNate/Java-WebSocket#418]
@TooTallNate I know you from the Node.js world. Given this library that you wrote (Java-WebSocket), I figure you might have an answer to the following SO question. I have a Node.js parent process and it may need to communicate with Java, Python, Go, and even the browser at some point. Websockets seem to be a good way to generally solve it. Can you take a look at this:

http://stackoverflow.com/questions/41069063/websockets-with-ephemeral-ports

Sorry for spamming this channel, let me know if there is a better place to put this and  I will move it, thanks!

**Comment by marci4** [comment]
TooTallNate is not active any more on this repository. Maybe just tweet him and if he has time he may check it.

Greetings
marci4
