### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by brobits** [TooTallNate/Java-WebSocket#419]
legitimate open PRs have been open since the spring/summer, with no reply from the maintainer.  is this project dead?

**Comment by vedi0boy** [comment]
Unfortunately, it looks like it is.

**Comment by yoiang** [comment]
Is the project still a good websocket library resource? If not are there others that you would recommend? (I am new to websocket work in Java)

**Comment by MarkehMe** [comment]
I'm curious too. Why aren't we just using ```javax.websocket```? I can't seem to find an informative comparison

**Comment by yoiang** [comment]
Java.websocket is only available on Java EE, no?

**Comment by MarkehMe** [comment]
I believe you can still use it though. However its complicated, I guess thats why this project was born. 

Just tested this project, and although it appears to not be actively maintained it seems to be working fine.

**Comment by kazimuth** [comment]
It might be reasonably to make a fork and apply all the open PRs.

**Comment by brobits** [comment]
I think with some discretion that doesn't sound like a bad idea.  I'm not certain, but I recall having some framing issues with a TLS endpoint using this library recently. Might have been an issue with the SSL handshake but I didn't dive in.

**Comment by MarkehMe** [comment]
Perhaps we should find out what the future of this project is first? I [just tweeted](https://twitter.com/_markeh/status/814631707173220352) @TooTallNate to see whats happening

**Comment by brobits** [comment]
I think it's safe to say with nearly 6 mo of maintainer absence, a fork is acceptable

**Comment by TooTallNate** [comment]
Thanks for reaching out. This was my very first open-source project and I was doing a lot of Java coding in those days. For that reason this project will always be special to me.

However, I don't have much interest in maintaining this project myself. There are a couple collaborators with commit access to the repo but it appears that they've been busy lately as well.

I would be happy to give collaborator access to anybody that would like to step up to the plate, in the spirit of open-source! Short of that feel free to fork of course. Consider this an official call for maintainers.

**Comment by marci4** [comment]
Would be great if this project keeps on going!

Not sure how long I would be able to maintain this project due to RL (end of university and so on) but really would like to step up!

**Comment by TooTallNate** [comment]
Hey @marci4, sorry I didn't see this initially. I've added you as a collaborator. Thank you in advance for any work that you end up putting into this project ❤️
