### ISSUE TITLE
Limited size for the messages sent throw websockets?

### ISSUE THREAD

**Issue by Horsetopus** [TooTallNate/Java-WebSocket#423]
Hello,

I am using your library for one of my project.
Among others, one of my needs is to upload some files.

But when I send a message over a certain size from the client, the message does not reach my code in the server.
I don't get an error either, nothing.
I tried without specifying a draft, and by specifying Draft_17.

So, I have two questions:
- are there some limits on size?
- what are they?
- if the value varies, is there a way to get it at runtime?

This is not my area of expertise and I couldn't find anything clear on Google.

Thank you.

**Comment by ainsley** [comment]
Having the exact same issue. The internal buffer size appears to be 16 kilobytes, which I assumed would be chunked so that there was no limit except for JVM memory capacity. I modified this to a much higher figure (4 megabytes) whilst keeping messages sent less than 2 megabytes, and messages were still being dropped.

The protocol code is complex therefore I don't understand exactly what is happening, but for sure, there are problems with larger messages.

Horsetopus: Were you able to solve your issue?

**Comment by marci4** [comment]
Hey @ainsley and @Horsetopus,

could you provide any simple example for me to reproduce this issue and hopefully fix it.

Can't really promise to much because I didn't implement it but I would really like to help you!

Greetings
marci4

**Comment by ainsley** [comment]
Thanks for replying to this. I'll try to put one together in the next few days.

**Comment by marci4** [comment]
possible duplicates #300  (internal for me)

**Comment by solomon-chen** [comment]
add the bold codes here in WebSocketImp.java:

else if( fin ) {
						if( current_continuous_frame == null )
							...
						if( current_continuous_frame.getOpcode() == Opcode.TEXT ) {
							...
							if( !Charsetfunctions.isValidUTF8( current_continuous_frame.getPayloadData(), off ) ) {
								throw new InvalidDataException( CloseFrame.NO_UTF8 );
							}


                                             **try {
								wsl.onWebsocketMessage( this, Charsetfunctions.stringUtf8( current_continuous_frame.getPayloadData() ) );
							} catch ( RuntimeException e ) {
								wsl.onWebsocketError( this, e );
							}**

**Comment by marci4** [comment]
Hello @solomon-chen ,

I ran into the same idea while trying to complete all the testcases in the autobahn testsuite.

This caused some problems with fragmented byte frames as far as I remember.

Could you please provide an example code, when a specific message is not working any more?

Greetings
marci4

**Comment by marci4** [comment]
Could you please check if #570 is fixing this issue for you?

Greetings
marci4

**Comment by marci4** [comment]
This issue should be solved. If not feel free to open a new issue!

Greetings
marci4
