### ISSUE TITLE
I can't use WebSocketClient.send send message as (eg:client.emit("command", message);)

### ISSUE THREAD

**Issue by iokane** [TooTallNate/Java-WebSocket#428]

**Comment by rajathvsm** [comment]
I believe you have this confused with Socket.io. Could you check this?

**Comment by marci4** [comment]
hey @iokane,
do you still have an issue here?

Greetings
marci4

**Comment by marci4** [comment]
No feedback by issue creater and also unclear issue.
Closing
Greetings
marci4
