### ISSUE TITLE
under Linux throw  java.net.SocketException: Too many open files

### ISSUE THREAD

**Issue by Henryeung** [TooTallNate/Java-WebSocket#429]
Under Linux environment, throw "Too many open files" by looping  to start and stop WebSocketServer.

My Application need to start WebSocketServer on random port  when login and stop WebSocketServer  when logout.

How to solve this?

Environment :
Java 1.6
Linux Slackware 13

Testing code:

package test;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.java_websocket.WebSocket;
import org.java_websocket.handshake.ClientHandshake;
import org.java_websocket.server.WebSocketServer;

public class TestWebSocketServer extends WebSocketServer {
    public TestWebSocketServer(InetSocketAddress address) {
        super(address);
    }

    @Override
    public void onOpen(WebSocket conn, ClientHandshake handshake) {
        System.out.println("new connection to " + conn.getRemoteSocketAddress());
    }

    @Override
    public void onClose(WebSocket conn, int code, String reason, boolean remote) {
        System.out.println("closed  with exit code " + code + " additional info: " + reason);
    }

    @Override
    public void onMessage(WebSocket conn, String message) {
        System.out.println("received message from : " + message);
    }

    @Override
    public void onError(WebSocket conn, Exception ex) {
        System.err.println("an error occured on connection :" + ex);
    }

    public static void main(String[] args) {
        String host = "localhost";
        int port = 8887;
        int count = 1;
        while (true) {
            System.out.println(count++);
            WebSocketServer server = new TestWebSocketServer(new InetSocketAddress(host, port));
            server.start();
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(TestWebSocketServer.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                server.stop();
            } catch (IOException ex) {
                Logger.getLogger(TestWebSocketServer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(TestWebSocketServer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}

**Comment by bluechips23** [comment]
You are getting the exception because you have a `while(true)` loop. You don't need that at all. When you start your thread with server.start() - it stays open until you issue a shutdown (server.stop()) or something bad happens. When you put that under a while loop, it just opens infinite loop of creating new websocket connections - which is BAD! So, just remove your while loop.

**Comment by Henryeung** [comment]
while(true) is just a testing, my application need to start server when login and  stop server when logout, so will continue loop to start and stop server.

The question is why can't release open file after stop server until  quit application.

**Comment by Henryeung** [comment]
normal server socket loop to create and then close  not hold open file(number of open file will not be increased)

**Comment by marci4** [comment]
hey @Henryeung,
could you provide a complete stacktrace?

Also I think that the main problem is the small delay (100ms) combined with the while loop.

If you still having issues I would really like to help you!

Greetings
marci4

**Comment by marci4** [comment]
cannot reproduce this issue

Greetings
marci4
