### ISSUE TITLE
how to reconnect websocket ？？？ 

### ISSUE THREAD

**Issue by yin450561200** [TooTallNate/Java-WebSocket#431]
how to reconnect websocket for android app?

**Comment by marci4** [comment]
hello @yin450561200,

could you please describe your issue a bit more specific?

Greetings
marci4

**Comment by marci4** [comment]
Still no answer.
Closing

Greetings
marci4

**Comment by yin450561200** [comment]
I was in the development of my app, the use of your web socket framework, and sometimes the phone network is unstable, and then app web socket will be disconnected, and then in the app socket in the re connection.

**Comment by marci4** [comment]
Right now you cannot reuse your websocket connection instance!

Just call the constructor again and start the connection (like you do in your initial connection)

Greetings
marci4

**Comment by yin450561200** [comment]
ok，thank you.
