### ISSUE TITLE
Secure connection issue

### ISSUE THREAD

**Issue by GeminiLoal** [TooTallNate/Java-WebSocket#432]
Hi, I tried to create a secure connection between a server and client with a self signed certificate using the examples here in the repository. I created the .jks file and I use the same file both for the server and the client but when the client tries to connect the server says: 

Received fatal alert: certificate_unknown

How is it possible?

**Comment by marci4** [comment]
Hello @GeminiLoal,

have you tried to build the jar directly from the sources?

For me the example provided is currently working without any problems.

Greetings
marci4

**Comment by GeminiLoal** [comment]
Hi @marci4 , thanks for your reply. 

I cloned the project then I run mvn package. In the project I used the resulting .jar marked as Java-WebSocket-1.3.1-SNAPSHOT
Is this correct? 

I will run some other tests an see if I can fix the issue

Greetins

**Comment by marci4** [comment]
Hey @GeminiLoal,

I haven't changed any version-strings yet so I can't really tell if you have the right version.

If you still have the problem I will just send you my jar.

Greetings
marci4

**Comment by GeminiLoal** [comment]
That would be perfect @marci4, you can send it at my mail gemini.loal at gmail.com
Thanks

Greetings
L

**Comment by GeminiLoal** [comment]
Hi @marci4 , your .jar seems a bit more stable compared to the one I used. 
Anyway, on the client side now I see: 

write(156): {GET / HTTP/1.1
Connection: Upgrade
Host: xxxxx
Sec-WebSocket-Key: xxxxx
Sec-WebSocket-Version: 8
Upgrade: websocket

}

On the server side I see: 
!isHandShakeComplete

Still no connection :(

Thanks for the help so far
Greetings
L

**Comment by marci4** [comment]
hey @GeminiLoal,

it looks like you are using the wrong example.

You should use the example `SSLClientExample` and not `ExampleClient`

Greetings
marci4

**Comment by GeminiLoal** [comment]
Got my error... A very stupid one, not related to this specific project. 

Basically I wrote the loading of the .jsk in a wrong way...

Thank for everything, the .jar you sent me work really well!
Greetings
L

**Comment by marci4** [comment]
Issue solved :) closing

Greetings
