### ISSUE TITLE
Java-WebSocket new version not available for gradle 

### ISSUE THREAD

**Issue by 5hivams** [TooTallNate/Java-WebSocket#450]
Hello there
How we can implement latest java-websocket version 1.3.2 ?
old version 1.3.0 have bugs and You mentioned latest gradle implementation here: https://clojars.org/org.java-websocket/java-websocket 
but this latest version is not implementing in gradle.

**Comment by marci4** [comment]
Hello @5hivams ,

the way to resolve your issue is just to use a custom maven repository .

Add the following lines to your repositories list 
`maven {
        url "http://clojars.org/repo"
    }`

The result may look like this

`repositories {
    mavenCentral()
    maven {
        url "http://clojars.org/repo"
    }
}`

Then you can just use the clojars repository.

Greetings
marci4

**Comment by 5hivams** [comment]
Thanks @marci4 I tried same even tried with https://clojars.org/repo but nothing working.

**Comment by marci4** [comment]
Hey @5hivams 

you also added the compile dependency? 
`compile "org.java-websocket:java-websocket:1.3.2"`

Working for me :(

Greetings
marci4

**Comment by 5hivams** [comment]
Yes that's already added. But issues resolved by cleaning cache of android studio and restarted. Everything working fine now. 
Thanks for your response.
