### ISSUE TITLE
Unable to build using 'ant'

### ISSUE THREAD

**Issue by prithivraj** [TooTallNate/Java-WebSocket#456]
Socket-master/build/classes
    [javac] javac: target release 1.6 conflicts with default source release 1.8
BUILD FAILED
/Users/prithivraj-1942/Desktop/Java-WebSocket-master/build.xml:9: Compile failed; see the compiler error output for details.

**Comment by marci4** [comment]
Hello @prithivraj,

right now I cannot reproduce your issue.

I DO get a warning for the wrong source version which I am gonna fix, but other then that, my build succeeds.

Greetings
marci4

**Comment by marci4** [comment]
Fixed some warnings.

Closing issue.
Greetings
marci4
