### ISSUE TITLE
Support for  Compression Extensions for WebSocket

### ISSUE THREAD

**Issue by marci4** [TooTallNate/Java-WebSocket#463]
This feature is planned for the new release, or at least get the infrastructure ready for this.

https://tools.ietf.org/html/rfc7692

Greetings
marci4

**Comment by becast** [comment]
Uhm. I already written a permessage-deflate draft. If you're interested https://github.com/becast/Java-WebSocket/tree/Permessage-Deflate?files=1

**Comment by marci4** [comment]
Hello @becast,

thx for your input :)

I plan to support extensions in a more general way, so you don't have to copy changes for Draft_17 over to your other extensions.
But when the background stuff is done, I would like to take a look at your approach for the PerMessage-Deflate Extension.

Greetings
marci4

**Comment by marci4** [comment]
Current development status can be found [here](https://github.com/marci4/Java-WebSocket-Dev/tree/extensions)

**Comment by marci4** [comment]
infrastructure is done. Looking for a specific implementation for the per-message-deflate extension which is  not against any licence etc

**Comment by marci4** [comment]
Extension system in place. 
Implementation of different extensions for future release.
