### ISSUE TITLE
Send message to all connected clients

### ISSUE THREAD

**Issue by Gillardo** [TooTallNate/Java-WebSocket#467]
Is it possible to send a message to all connected clients?  I would like be able to force the server to spawn a message to each connected client, rather then having each client constantly spawning the server.

**Comment by marci4** [comment]
Hello @Gillardo,

yes it is.
Check out the example code in Chatserver.java

`/**
	 * Sends <var>text</var> to all currently connected WebSocket clients.
	 * 
	 * @param text
	 *            The String to send across the network.
	 * @throws InterruptedException
	 *             When socket related I/O errors occur.
	 */
	public void sendToAll( String text ) {
		Collection<WebSocket> con = connections();
		synchronized ( con ) {
			for( WebSocket c : con ) {
				c.send( text );
			}
		}
	}`


Greetings
marci4
