### ISSUE TITLE
Binary sendFragmentedFrame

### ISSUE THREAD

**Issue by bentzn** [TooTallNate/Java-WebSocket#468]
For performance I would like to be able to send two parts of a binary message. As I understand it this can be done with sendFragmentedFrame:

This is basically the setup:
`
                conn.sendFragmentedFrame(Opcode.BINARY, byteBuffer1, false);
                conn.sendFragmentedFrame(Opcode.BINARY, byteBuffer2, true);
`

As far as I understand the boolean is used to let the receiver know that the message is finished.
What am I doing wrong?

**Comment by marci4** [comment]
Hello @bentzn,

even though I tested it with a text fragment, that is the way to go.

So what is your current problem?

Greetings
marci4

**Comment by bentzn** [comment]
This is sent from the server. I can see in the debugger that the client receives both parts but onMessage(ByteBuffer buf) is never called.

**Comment by marci4** [comment]
Hello @bentzn,

there is no method onMessage(ByteBuffer buf) for the client, the method is `onFragment( Framedata fragment );`

Greetings
marci4

**Comment by bentzn** [comment]
It runs.
Thanks a lot!

**Comment by marci4** [comment]
Issue solved.

Closing issue.
Greetings
marci4
