### ISSUE TITLE
How can i know websocket connecting status?

### ISSUE THREAD

**Issue by maybea** [TooTallNate/Java-WebSocket#471]
client.isConnecting()  is also return false
client.isOpen is also return true;
but if phone out of network 
client.isOpen will return true
how can i get this websocket status?

**Comment by marci4** [comment]
Hello @maybea,

the best way to detect a lost connection is to ping the client and check if it succeeds.

E.g.
```java
public void sendAllPing() {
    FramedataImpl1 frame = new FramedataImpl1(Opcode.PING);
    frame.setFin(true);
    Collection<WebSocket> con = connections();
    synchronized ( con ) {
        for( WebSocket c : con ) {
            c.sendFrame( frame );
        }
    }
}
```

Even tough, yes I see the need to improve lost connection detection.

Greetings
marci4
