### ISSUE TITLE
How do I initiate with a JWT Authentication Header?

### ISSUE THREAD

**Issue by ao** [TooTallNate/Java-WebSocket#474]
I create a Map and add my Authentication:jwt string.

```
Map<String, String> _headers = new HashMap<String, String>();
_headers.put("Authorization:jwt","SOME_STRING_AS_A_JWT");
```
I then initiate the connection:

```
mWebSocketClient = new WebSocketClient(uri, new Draft_17(), _headers, 61) {
    //rest of the code snipped..
```

Is this the correct way of sending the JWT?

FYI: If I add in some debugging I get the following

```
NOT_YET_CONNECTED
process(1022): {too big to display}
onClose: -1 - draft org.java_websocket.drafts.Draft_17@712f6387 refuses handshake .
CLOSED
```

**Comment by marci4** [comment]
Hello @ao,

just a heads up, I don't know the specification for a JWT Authentication Header so you have to check for the correct header yourself please.

Apart from this, as far as I understand, what you need, you did it the right way!
You can add custom headers to your client handshake via this constructor.
The resulting handshake would be in this case:
```GET / HTTP/1.1
Authorization:jwt: SOME_STRING_AS_A_JWT
Connection: Upgrade
Host: localhost:8887
Sec-WebSocket-Key: AoKNz3DTFVjDKP8sI37/QQ==
Sec-WebSocket-Version: 13
Upgrade: websocket
```

Greetings
marci4

**Comment by ao** [comment]
For everyone who stumbles on this' information. The header should be set as follows:
```
Map<String, String> _headers = new HashMap<String, String>();
_headers.put("Authorization","jwt SOME_STRING_AS_A_JWT");
```
