### ISSUE TITLE
No Javadoc attached when using from Gradle

### ISSUE THREAD

**Issue by calvertdw** [TooTallNate/Java-WebSocket#481]
![image](https://cloud.githubusercontent.com/assets/1161586/26017001/08fd749c-372d-11e7-8084-bf3993f0cbfe.png)

Thanks :D

**Comment by marci4** [comment]
Not sure what I fu**ed up in the release. 
Gonna read up a bit more and hopefully fix it!

Greetings
marci4

**Comment by marci4** [comment]
Since I got access to the maven central repository, I hope that this issue solves itself with the next release!

Greetings
marci4

**Comment by marci4** [comment]
Snapshot for 1.3.4 is live with javadocs :)

Closing this issue!
Greetings
marci4

**Comment by calvertdw** [comment]
Awesome!
