### ISSUE TITLE
Chrome 15, can't send long messages?

### ISSUE THREAD

**Issue by runvnc** [TooTallNate/Java-WebSocket#49]
Hello, I'm on Chrome 15.. I believe it says it is using Draft 10 when I turn on Debug mode.  I am able to send short messages great, but anything more than 90? or 100? characters or so results in a message on the client "Could not decode a text frame as UTF-8." 

It seems like it could actually be the same issue as this other person was having on another implementation.  http://superwebsocket.codeplex.com/discussions/273222

Thanks for any ideas you have.

**Comment by khacdai37** [comment]
Hi @Davidiusdadi, please help me! I have a same issue on Android version when server send a too long message to the client and client not receive that message.
thanks.
