### ISSUE TITLE
Is the WebSocket .send() method thread-safe?

### ISSUE THREAD

**Issue by werner291** [TooTallNate/Java-WebSocket#491]
Hello,

suppose you implement a WebSocketServer that distributes WebSocket objects (received through onOpen) to diffferent worker threads, is it safe to call send(String...) on those from those other threads?

What about 2 threads sending in the same WebSocket?

~~WebSocketImpl does appear to use a BlockingQueue internally, so it should be safe, but is this safe to assume?~~

Also, if this is not the case, is it safe to synchronise on individual WebSocket instances, or do I have to do something special?

I tried finding something in the documentation about this, but couldn't.

**Comment by werner291** [comment]
Actually, I can already say for the 2 threads scenario that it is NOT thread-safe since sending multiple frames is not atomic.

**Comment by marci4** [comment]
Hello @werner291,

I am so sorry for not getting back to earlier.
I simply forgot to reply...

Getting to your question (disclaimer: I have not implemented it so I have to go through the code myself and understand it)
From my understanding yes this is not thread-safe.

I think the best way is to use an object to synchronize the 3 methods accessing the write method.

How high is your priority for this?

Greetings
marci4

**Comment by werner291** [comment]
Hi,
not very high at all, just checking. It's mostly a documentation issue for me, in that case I know what I'm up against.

**Comment by marci4** [comment]
For future me!
class WebSocketImpl
let everything use send( Collection<Framedata> frames ) instead of sendFrame( Framedata framedata ) and synchronize there!

**Comment by marci4** [comment]
Implementation with #500
