### ISSUE TITLE
WebSocketClient onMessage never called (android)

### ISSUE THREAD

**Issue by GregoryConrad** [TooTallNate/Java-WebSocket#496]
I'm currently working on making a chat application, except the onMessage method is never called on android (tested on a Nexus 6p running LineageOS with 7.1). I know data is getting sent from the server as a webpage is receiving the messages sent. I would love to post some sort of exception, except I'm not getting any. The method simply isn't getting called. Any further assistance with fixing this issue would be appreciated.

FYI, the application is going to be open source, so I would be happy to post some source code if desired.

Edit: I have also checked to make sure that the client was connected to the server.

**Comment by marci4** [comment]
Hello @GregoryConrad,

what is the version you are using?

Are you using ssl?

Is onOpen called at both ends?

Does your device lose connection? (A new feature to more easyly detect lost connection will be added with 1.3.4)

Greetings
marci4

**Comment by GregoryConrad** [comment]
I added the Gradle line to my project just a week ago, so presumably the latest version. I am not using ssl, and I'm pretty positive onOpen is called on both ends. I'll check to make sure later today.
And I'm not getting an onClose, so I don't think that's it either.

**Comment by marci4** [comment]
Hello @GregoryConrad,

thx for your fast feedback!
onClose is currently not correctly detected when a device looses internet connection (Java is not that smart in this case ;) )
With the upcoming release of 1.3.4 the lib will automatically send pings to the endpoints in a specific intervall and if no pong was recieved it assumes that the endpoint got disconnected!

Apart from this. Could you maybe activate the debug printouts with `WebSocketImpl.DEBUG = true;` and post the output?

Greetings
marci4

**Comment by GregoryConrad** [comment]
I tried again today, and there appeared to be no problems. Strange.

Sorry for using your time.

**Comment by tangze** [comment]
Meet the same question in 
OS: windows 10-1803
JRE: 1.8 
Server: websocket-sharp(https://github.com/sta/websocket-sharp) based

onMessage never called, & I'm sure the Server works fine.

**Comment by marci4** [comment]
Hello @GregoryConrad,

please open a new issue. Cannot keep track of old closed issues!
Best regards,
marci4
