### ISSUE TITLE
version 1.3.4 compilation error : FramedataImpl1 is abstract; cannot be instantiated

### ISSUE THREAD

**Issue by javierpineros** [TooTallNate/Java-WebSocket#505]
I have implemented **send ping** method on version 1.3.0, in this version this ping works fine, but when i change version to last 1.3.4 the code doesn´t compile, my code is:
   
public static void sendPing(){
        //Log.d(Constants.TAG, "SENDING PING");
        FramedataImpl1 frame = **new FramedataImpl1(Framedata.Opcode.PING);**
        frame.setFin(true);
        mWebSocketClient.getConnection().sendFrame(frame);
    }

Please helpme to resolve this compilation problem, or how to send ping with other way in version 1.3.4?

Thanks.

**Comment by javierpineros** [comment]
I resolve this issue temporarily extending FramedataImpl1 and implements isValid abstract method, but this implementation of this method its empty because i don´t know that is necessary to validate  in this method. 

My new implementation code is:

public class CithatFramedataImpl1 extends FramedataImpl1 {
    public CithatFramedataImpl1(Opcode op) {
        super(op);
    }

    @Override
    public void isValid() throws InvalidDataException {
        // i don´t know that make in this method
    }
}

And mi new send ping method is:

    public static void sendPing(){
        //Log.d(Constants.TAG, "SENDING PING PING PING PING");
        FramedataImpl1 frame = new CithatFramedataImpl1(Framedata.Opcode.PING);
        frame.setFin(true);
        mWebSocketClient.getConnection().sendFrame(frame);
    }

Please helpme to implements correctly isValid method

Thanks

**Comment by marci4** [comment]
Hello @javierpineros,

yeah I changed the implementation a bit to make it easier for you as a developer!

I created a class for every opcode, so you just have to use `new PingFrame()`

See https://static.javadoc.io/org.java-websocket/Java-WebSocket/1.3.4/index.html?org/java_websocket/framing/PingFrame.html

Hope this helps you!
Greetings
marci4

**Comment by marci4** [comment]
Issue is solved and no answer for over a month.

Closing issue!
Greetings
marci4
