### ISSUE TITLE
No jar files...

### ISSUE THREAD

**Issue by makedir** [TooTallNate/Java-WebSocket#507]
Why there are no compiled JAR files to download available on here? ... Ok found them somewhere else. Would be great though if they were linked on the page.

**Comment by marci4** [comment]
You can always directly download it from the maven repository.

This is way easier for me to maintain then everything else!

Link for the current version:
http://repo1.maven.org/maven2/org/java-websocket/Java-WebSocket/1.3.4/

Greetings
marci4

**Comment by makedir** [comment]
And why is it not linked here: https://github.com/TooTallNate/Java-WebSocket ?

**Comment by marci4** [comment]
Because most of the developer use building tools like maven or gradle and dont rely on the jar!

**Comment by makedir** [comment]
I see that nonsense and stubbornness a lot actually on so many projects on here, it is ridiculous. Why should I mess with Gradle... making things complicated and blown up, where there is just one jar file to include with a single line...

**Comment by Obsidiam** [comment]
Yea, totally, who to hell uses .jars nowadays? XD Maven or Gradle are best
option I believe.

**Comment by makedir** [comment]
Cool story.

**Comment by Obsidiam** [comment]
Yea, right now it is one file, but what will happen if there will be more
than one needed? For example 10 jars.
