### ISSUE TITLE
Ant fails due to missing `dist/` directory

### ISSUE THREAD

**Issue by tuetschek** [TooTallNate/Java-WebSocket#508]
The `dist/` directory is not created automatically during the build, and this makes `ant` fail when creating the jar:
```
jar:
      [jar] Building jar: /home/do8/madrigal/tools/Java-WebSocket/dist/java_websocket.jar

BUILD FAILED
/path/Java-WebSocket/build.xml:18: Problem creating jar: /path/Java-WebSocket/dist/java_websocket.jar (No such file or directory) (and the archive is probably corrupt but I could not delete it)
```

**Comment by marci4** [comment]
Hello @tuetschek,

thx for your bug report!
Looks like this is just an issue for linux.

Merged a fix!

Closing issue! 
Greetings
marci4

**Comment by tuetschek** [comment]
Thanks! And sorry I forgot to mention that it happened under Linux.

**Comment by marci4** [comment]
No problem. I know a linux path when I see it ;)
