### ISSUE TITLE
wss support for Android app

### ISSUE THREAD

**Issue by gomeskingsley** [TooTallNate/Java-WebSocket#513]
Hi I have to implement wss in my app and I have a public keystore file(.crt file) from the server.
How can I achieve wss implementation in the app, I went through https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLServerExample.java but I'm not able to understand it.

Can you provide a code snippet for this? 
Thanks in advance

**Comment by marci4** [comment]
Hello @gomeskingsley,

well I have a simple test application but I think this may help you :)

You need to have a bks keystore for android and put it in your res.raw folder.

Also don't just use this peace of code! It is just for testing purposes!

```java
ChatServer server = new ChatServer();
// load up the key store
String KEYPASSWORD = "PASSWORD";
try {
	KeyStore keystore = KeyStore.getInstance("BKS");
	InputStream in = getResources().openRawResource(R.raw.keystore);
	try {
		keystore.load(in, KEYPASSWORD.toCharArray());
	} finally {
		in.close();
	}
	KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance("X509");
	keyManagerFactory.init(keystore, KEYPASSWORD.toCharArray());
	TrustManagerFactory tmf = TrustManagerFactory.getInstance("X509");
	tmf.init(keystore);

	SSLContext sslContext = null;
	sslContext = SSLContext.getInstance("TLS");
	sslContext.init(keyManagerFactory.getKeyManagers(), tmf.getTrustManagers(), null);

	server.setWebSocketFactory(new DefaultSSLWebSocketServerFactory(sslContext));
} catch (Exception e) {
	Log.e("ChatServer", e.getMessage());
	throw new AssertionError(e);
}
server.start();
```

Greetings
marci4

**Comment by gomeskingsley** [comment]
Thanks for your prompt reply @marci4 !

Below is the piece of code which I use to open a web socket, 
can you tell where **setWebSocketFactory()** will be used over here?

private void openWebSocket(URI uri) {
        mWebSocket = new WebSocketClient(uri) {
            @Override
            public void onOpen(ServerHandshake serverHandshake) {
                Log.i(TAG, "onOpen: ");
            }

            @Override
            public void onMessage(String message) {
                Log.i(TAG, "onMessage: " + message);
            }

            @Override
            public void onClose(int code, String reason, boolean remote) {
                Log.i(TAG, "onClose: " + reason);
            }

            @Override
            public void onError(Exception ex) {
                Log.i(TAG, "onError: ");
            }
        };
          mWebSocket.connect()
    }

Thanks in advance!

**Comment by marci4** [comment]
Hello @gomeskingsley,

I am sorry. I thought you needed an example for a wss server not a wss client.

```java
ChatClient client = new ChatClient();
String KEYPASSWORD = "PASSWORD";
try {
	KeyStore keystore = KeyStore.getInstance("BKS");
	InputStream in = getResources().openRawResource(R.raw.keystore);
	try {
		keystore.load(in, KEYPASSWORD.toCharArray());
	} finally {
		in.close();
	}
	KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance("X509");
	keyManagerFactory.init(keystore, KEYPASSWORD.toCharArray());
	TrustManagerFactory tmf = TrustManagerFactory.getInstance("X509");
	tmf.init(keystore);

	SSLContext sslContext = null;
	sslContext = SSLContext.getInstance("TLS");
	sslContext.init(keyManagerFactory.getKeyManagers(), tmf.getTrustManagers(), null);
	//sslContext.init(null, null, null);
	SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();
	client.setSocket(sslSocketFactory.createSocket());
} catch (Exception e) {
	Log.e("ChatClient", e.getMessage());
	throw new AssertionError(e);
}
Log.i("ChatClient", "Trying to connect");
client.connect();
```

The important part is `client.setSocket(sslSocketFactory.createSocket());`

Greetings
marci4

**Comment by gomeskingsley** [comment]
Thanks @marci4! This is working fine!

**Comment by marci4** [comment]
Issue solved! 

Closing issue!
Greetings
marci4
