### ISSUE TITLE
ByteBuffer is empty when sent from the server

### ISSUE THREAD

**Issue by lvivtotoro** [TooTallNate/Java-WebSocket#515]
I sent some bytes from the server to a client, but the `ByteBuffer` on the client end is empty.
  
*I can confirm that the buffer is populated serverside*

**Comment by marci4** [comment]
Hello @lvivtotoro,

sorry I don't get what you are doing and what your issue is.

What exactly are you doing?
What type of websocket frame are you sending?
Are you sure you recieve the frame? 
Could you also provide the log you recieve by setting `WebSocketImpl.DEBUG = true;` before you open the connection?

Greetings
marci4

**Comment by lvivtotoro** [comment]
1. I am sending a byte array.  
2. Binary  
3. Yes  
4. I'll be back with that

**Comment by marci4** [comment]
Are you also overwriting the method `public void onMessage( ByteBuffer bytes );` ?

This is not abstract and that is why you dont have to implement it (most people dont need this use case)

Greetings
marci4

**Comment by lvivtotoro** [comment]
I'd rather implement it that the method with a `String` parameter if I'm sending a `ByteBuffer` not a `String`.  
The code would just be unreadable.

**Comment by marci4** [comment]
There are two different methods. 
The first one is `onMessage(String)` which is for receiving text frames.
The second one is  `onMessage(ByteBuffer)` which is for receiving byte frames.

The methods should be more clear. But there are in this project for years... Sorry!

Greetings
marci4

**Comment by lvivtotoro** [comment]
No, they're clear (at least to me).  
But the `ByteBuffer` is receiving an empty one

**Comment by marci4** [comment]
Ok. Just wanted to make sure!

Well. I just tried it (with a server and client) and it works for me!
Tested it also against the echo ws server from websocket.org

Sending a hello as binary to the server!
`opened connection
send frame: Framedata{ optcode:BINARY, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:5], payload:[72, 101, 108, 108, 111]}
write(11): {����~C��/�}
process(7): {�Hello}
matched frame: Framedata{ optcode:BINARY, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:5], payload:[72, 101, 108, 108, 111]}
Recieved ByteBuffer: Hello`

Greetings
marci4

**Comment by lvivtotoro** [comment]
Here's what I get serverside:
```

Connection lost timer started
process(154): {GET / HTTP/1.1
Connection: Upgrade
Host: localhost:25571
Sec-WebSocket-Key: **not sure if I should show**
Sec-WebSocket-Version: 13
Upgrade: websocket

}
write(212): {HTTP/1.1 101 Web Socket Protocol Handshake
Connection: Upgrade
Date: Thu, 29 Jun 2017 09:22:41 GMT
Sec-WebSocket-Accept: **not sure if I should show**
Server: TooTallNate Java-WebSocket
Upgrade: websocket

}
open using draft: Draft_6455
process(184): {��
send frame: Framedata{ optcode:BINARY, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:17, len:0], payload:[5, 76, 90, -17, -65, -67, -36, -70, -17, -65, -67, 8, 34, 6, -17, -65, -67, -17, -65, -67, 42, 82, 45, -17, -65, -67, 107]}
write(2): {�
```

**Comment by marci4** [comment]
Everything looks fine here!
What is your client doing then? And what is your client?

Greetings
marci4

**Comment by lvivtotoro** [comment]
`write(154): {GET / HTTP/1.1
Connection: Upgrade
Host: localhost:25571
Sec-WebSocket-Key: **not sure if I should show**
Sec-WebSocket-Version: 13
Upgrade: websocket

}
process(212): {HTTP/1.1 101 Web Socket Protocol Handshake
Connection: Upgrade
Date: Thu, 29 Jun 2017 09:55:59 GMT
Sec-WebSocket-Accept: **not sure if I should show**
Server: TooTallNate Java-WebSocket
Upgrade: websocket

}
open using draft: Draft_6455
Connection lost timer started
send frame: Framedata{ optcode:BINARY, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:176], payload:[0, 0, 0, 0, -17, -65, -67, 101, 121, 74, 104, 98, 71, 99, 105, 79, 105, 74, 73, 85, 122, 73, 49, 78, 105, 73, 115, 73, 110, 82, 53, 99, 67, 73, 54, 73, 107, 112, 88, 86, 67, 74, 57, 46, 101, 121, 74, 110, 97, 87, 81, 105, 79, 106, 69, 48, 78, 84, 103, 120, 77, 83, 119, 105, 99, 50, 78, 118, 99, 71, 86, 122, 73, 106, 112, 98, 73, 110, 66, 121, 98, 50, 90, 112, 98, 71, 85, 54, 98, 87, 85, 105, 88, 83, 119, 105, 100, 87, 108, 107, 73, 106, 111, 48, 78, 84, 73, 51, 79, 83, 119, 105, 90, 88, 104, 119, 73, 106, 111, 120, 78, 68, 107, 53, 77, 122, 77, 48, 79, 84, 85, 53, 102, 81, 46, 75, 85, 71, 106, 118, 118, 109, 103, 108, 89, 69, 54, 51, 89, 118, 118, 48, 73, 74, 86, 66, 82, 68, 107, 117, 84, 84, 97, 54, 85, 74, 84, 103, 74, 88, 120, 80, 111, 74, 84, 118, 78, 103]}
write(184): {��\00�����#�Q�Ax�oQ��|R��oR��hI��ER��mkВEQ��cbªgL٭Iq��HO�KH��e)Ʋe\޾Oq��Ouʽd)Ҵd\��dLݭ^H��bL�Oq��HO��IH��\C�Oq�H_��Ka��IO��`J��S\�pv�_^��_m��OQކT_�RO��SQܣLC�iQܲH|}
process(2): {�\00}
matched frame: Framedata{ optcode:BINARY, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:[]}`

**Comment by marci4** [comment]
As you can see, your other endpoint is not sending any data!
```
process(2): {�\00}
matched frame: Framedata{ optcode:BINARY, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:[]}
```

I am sorry but I cant help you if the other endpoint is not sending any payload back... 

Greetings
marci4

**Comment by lvivtotoro** [comment]
It is! Look at the server log!
The `send frame` shows the bytes

**Comment by marci4** [comment]
Yeah that is right but the OTHER endpoint is not sending any payload in the binary frame!

**Comment by lvivtotoro** [comment]
I don't understand, are you supposed to send a payload to get one?

**Comment by marci4** [comment]
Let me try to explain this for you:
You have a `client` and a `server`

If you send binary data from the client to the server, you probably do something like:
```java
client.send(new byte[]{0, 0, 0, 0, -17, -65, -67, 101, 121, 74, 104, 98, 71, 99, 105, 79, 105, 74, 73, 85, 122, 73, 49, 78, 105, 73, 115, 73, 110, 82, 53, 99, 67, 73, 54, 73, 107, 112, 88, 86, 67, 74, 57, 46, 101, 121, 74, 110, 97, 87, 81, 105, 79, 106, 69, 48, 78, 84, 103, 120, 77, 83, 119, 105, 99, 50, 78, 118, 99, 71, 86, 122, 73, 106, 112, 98, 73, 110, 66, 121, 98, 50, 90, 112, 98, 71, 85, 54, 98, 87, 85, 105, 88, 83, 119, 105, 100, 87, 108, 107, 73, 106, 111, 48, 78, 84, 73, 51, 79, 83, 119, 105, 90, 88, 104, 119, 73, 106, 111, 120, 78, 68, 107, 53, 77, 122, 77, 48, 79, 84, 85, 53, 102, 81, 46, 75, 85, 71, 106, 118, 118, 109, 103, 108, 89, 69, 54, 51, 89, 118, 118, 48, 73, 74, 86, 66, 82, 68, 107, 117, 84, 84, 97, 54, 85, 74, 84, 103, 74, 88, 120, 80, 111, 74, 84, 118, 78, 103});
```
This creates a binary frame with the provided payload!

You can also create the frame on your own doing something like:
```java
BinaryFrame frame = new BinaryFrame();
frame.setPayload(ByteBuffer.wrap(new byte[]{0, 0, 0, 0, -17, -65, -67, 101, 121, 74, 104, 98, 71, 99, 105, 79, 105, 74, 73, 85, 122, 73, 49, 78, 105, 73, 115, 73, 110, 82, 53, 99, 67, 73, 54, 73, 107, 112, 88, 86, 67, 74, 57, 46, 101, 121, 74, 110, 97, 87, 81, 105, 79, 106, 69, 48, 78, 84, 103, 120, 77, 83, 119, 105, 99, 50, 78, 118, 99, 71, 86, 122, 73, 106, 112, 98, 73, 110, 66, 121, 98, 50, 90, 112, 98, 71, 85, 54, 98, 87, 85, 105, 88, 83, 119, 105, 100, 87, 108, 107, 73, 106, 111, 48, 78, 84, 73, 51, 79, 83, 119, 105, 90, 88, 104, 119, 73, 106, 111, 120, 78, 68, 107, 53, 77, 122, 77, 48, 79, 84, 85, 53, 102, 81, 46, 75, 85, 71, 106, 118, 118, 109, 103, 108, 89, 69, 54, 51, 89, 118, 118, 48, 73, 74, 86, 66, 82, 68, 107, 117, 84, 84, 97, 54, 85, 74, 84, 103, 74, 88, 120, 80, 111, 74, 84, 118, 78, 103}))
c.sendFrame(frame);
```


To echo just the message back, you would do something like this on the server:
```java
@Override
public void onMessage( WebSocket conn, ByteBuffer message ) {
	conn.send(message);
}
```


What are you doing on your client and your server side?

Greetings
marci4

**Comment by lvivtotoro** [comment]
That's exactly what I am doing.  
The only difference is that I'm passing a `ByteBuffer`.

**Comment by marci4** [comment]
Could you please provide your code?

Greetings
marci4

**Comment by lvivtotoro** [comment]
Here's the gist:  
https://gist.github.com/lvivtotoro/d721c18b6bceb8cc09aefb32ed951d39

**Comment by marci4** [comment]
Just a few things.

- `ByteBuffer.array()` is _optional_ (see https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html#array()). You have to make sure that the underlying implementation actually implements it (Do this with `ByteBuffer.hasArray()`)

- Just use `this.send(buffer);` instead of `this.send(buffer.array());`

- `ByteBuffer.get()` is starting with the current position which may not be 0 (see https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html#get()). Set your position or use `ByteBuffer.get(<index>)` or  `ByteBuffer.array()` (if it has an array) instead

Greetings
marci4

**Comment by lvivtotoro** [comment]
I'm using `ByteBuffer.wrap` before sending it, so there's definitely an array there.  

When I passed the ByteBuffer instead of the `ByteBuffer.array`, the server wasn't receiving anything at all.  
Am I supposed to use `.position(0)` every single time?

**Comment by marci4** [comment]
`this.send(buffer.array())` is doing nothing more then` this.send(ByteBuffer.wrap(buffer.array()))`

I think the easiest is to just use `ByteBuffer.array()` (if it exists) if you want to have an array!

**Comment by lvivtotoro** [comment]
Something I noticed: When I pass a `ByteBuffer`, it is empty on the other side.  
So I'll just be using `.array()` from now on.
