### ISSUE TITLE
Can't stablish connection with Go server

### ISSUE THREAD

**Issue by UannaFF** [TooTallNate/Java-WebSocket#521]
Hi! I started using this library because I needed to stablish secure websockets connection, previously I was using autobahn and the connections were working without tls enabled. I have a local server that has a self signed certificate, I created a keystore to trust the certificate and the app started to communicate with the server. The problem is, it closes inmediatly and I get the following error on my server: http: TLS handshake error from 186.167.251.26:20625: tls: first record does not look like a TLS handshake

I'm trying to connect to the Websocket server written in Go: https://github.com/webrtc/apprtc/blob/master/src/collider/README.md

I haven't found anything that helps me figure out what's going on, maybe someone here could point me in the right direction to fix this. I want to know if there's something else I need to do from the client side.

**Comment by marci4** [comment]
Hello @UannaFF,

I assume you implemented something like the [SSLClientExample](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLClientExample.java) so the client uses your keystore ([BKS-keystore example](https://github.com/TooTallNate/Java-WebSocket/issues/513#issuecomment-311077668)).

To debug any ssl error, please use the vm option `-Djavax.net.debug=all` which can help to find out if there is a problem with the certificate.

Apart from this, can you tell me if there is any problem for a browser connecting to the server?

Greetings
marci4

**Comment by UannaFF** [comment]
Thank you for answering! Yes I implemented something like the BKS keystore example and it worked because previously I was getting another error: refused handshake.

I'm guessing my problem now has something to do with the handshake header? Because I tried connecting with my web app example and the server accepted the request.

I read the header has to have this form:

GET /chat HTTP/1.1
Host: server.example.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==
Sec-WebSocket-Protocol: chat, superchat
Sec-WebSocket-Version: 13
Origin: http://example.com

I know in the creation of the web socket client you can pass a Hash map as a header, so doing something like this should work, right?

    Map<String, String> cmap = new HashMap<String, String>();
    ....
    cmap.put("Upgrade", "websocket");
    cmap.put("Connection", "Upgrade"
    cmap.put("Origin", "wss://192.168.1.6:8089/ws");
    .....
    wss = new WebSocketSecureClient(uri, new Draft_6455(), cmap, TIMEOUT);
    ....

It has some special requirements I don't know if I have to put them explicitly: it has to have an empty line at the end, every line must end with \r\n and I don't know how would I put the first line.

I'm basing this in this question https://stackoverflow.com/questions/27332956/create-a-websocket-handshake-using-android-as-server-and-a-browser-as-client
But here instead of a Hashmap, they have a String to represent the header.

**Comment by marci4** [comment]
Hello @UannaFF,

well this Map is just for additional headers like cookies (will include something better when I have the time for it), so you don't have to do this! Also line breaks should be included automatically.

Could you please activate the debug printouts with` WebSocketImpl.DEBUG = true;` before connecting to the server. Then you can see the handshake which is send to the server.

Greetings
marci4

**Comment by TOTOROYang** [comment]
you can try this draft[https://github.com/TooTallNate/Java-WebSocket/commit/e30eb11a68a2e6733acfb330f2e031fb90d7d88d](url)

**Comment by marci4** [comment]
Is there any update on this issue?

**Comment by marci4** [comment]
Most likely related to https://github.com/TooTallNate/Java-WebSocket/pull/535#issuecomment-334198931
That would be an error in the webrtc websocket.

Closing issue!
Greetings
marci4
