### ISSUE TITLE
Version 1.3.4 seems to have fixed close-down problem with my project.

### ISSUE THREAD

**Issue by jpaulm** [TooTallNate/Java-WebSocket#522]
Using 1.3.0, my project didn't always come down cleanly - see https://github.com/jpaulm/javafbp-websockets/issues/2 and https://github.com/jpaulm/javafbp-websockets/issues/3 

Switching to 1.3.4 necessitated some changes to my code, but now it is working and coming down cleanly.

See also question for @Davidiusdadi and/or @TooTallNate  on https://github.com/jpaulm/javafbp-websockets/issues/3 .

Thanks for all your good work!

**PS Is it safe for me to use 1.3.+  in my build.gradle ?**

**Comment by marci4** [comment]
Hello @jpaulm,

right now I am the only active maintainer for this project!
With 1.3.4 I implemented a heartbeat check to detect lost connections( see #473 ).

Sorry for breaking your code! A lot changed since the 1.3.0 and there were no updates for over 2 years...

And sorry for the typo *facepalm*

Yeah it should be safe!
Trying to introduce a bit more of structure to the project. So any bade code is subject to change ;)

Greetings
marci4

**Comment by jpaulm** [comment]
Many thanks for the prompt feedback, Marcel!  

I am downloading Java-WebSocket from Maven in my build.gradle - so should I just run that periodically, or is there a way I can get notified about new versions, so I can do a regression test?  

Merci d'avance!

**Comment by marci4** [comment]
Hello @jpaulm,

I personally don't use maven or gradle.
There are plugins which notify you during the build process, if there is a new version (see https://stackoverflow.com/a/2687228 )

Greetings
marci4

**Comment by jpaulm** [comment]
Thanks @marci4 , that's a good technique.  However, I just realized that my keeping track of new releases doesn't help my _users_ much, as the build.gradle on my project currently downloads the _latest_ version of Java-WebSocket into their runtime library.   This means that, if they do a rebuild before I do one, they will be working with a version that I have not regression-tested against my project.  It seems safest, therefore, for me to hardcode the version number for Java-WebSocket, keep track myself of updates to Java-WebSocket, and just update build.gradle periodically after I have regression-tested the new version of Java-WebSocket.  Do I have this straight?  Or is there a general, cleaner solution?  TIA

**Comment by marci4** [comment]
Hello @jpaulm,

You can also use the maven repository to provide a compiled version of the lib, so you can also push updates to your users and you have control over the used java-websocket version!

Greetings
marci4

**Comment by marci4** [comment]
Hello @jpaulm,

I meant that you can compile the java-websocket lib with your project sources to one single lib. Sorry if this was not clear!

Greetings
marci4

**Comment by jpaulm** [comment]
Thanks, as always, for your prompt reply!  

GitHub allows me to store the `lib` directory on GitHub, and I have updated build.gradle to remove the copyJars function.  Would appreciate it if you could take a quick look at https://github.com/jpaulm/javafbp-websockets , to see if I did it right...?!   I haven't updated Readme yet, but I will publish an updated version after I hear from you!  

Merci d'avance,

Paul

**Comment by marci4** [comment]
Hello @jpaulm,

You need to include the the following line into your build.gradle
`from configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }`

Resulting to something like:
```
jar {
    manifest {
        attributes 'Implementation-Title': 'JavaFBP-WebSockets', 'Implementation-Version': version
    }
    from configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
}  
task javadocJar(type: Jar) {
    classifier = 'javadoc'
    from javadoc
    from configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
}
task sourcesJar(type: Jar) {
    classifier = 'sources'
    from sourceSets.main.allSource
    from configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
}
```

So with this lib you dont need the additional libs as arguments ( `java -cp "build/libs/javafbp-websockets-1.2.0.jar;`<del>`lib/javafbp-4.1.0.jar;lib/java-websocket-1.3.4.jar`</del>`" com.jpaulmorrison.fbp.examples.networks.TestWebSockets`)

Hope it is clear what I am trying to say!
Greetings
marci4

**Comment by jpaulm** [comment]
Hi @marci4,

Interesting!  I thought you might mean zipping - but doesn't this require the user to have a version of `zip` available?  Does everyone?  I know my wife doesn't as she has never needed it!  Or is there Git-related zip that all Git users have?!  Sorry to be dumb!

I also think I screwed up in a different way: please check out my logic:  I had been assuming all along that the user would have to do a `gradle build` to build the JavaFBP-WebSockets jar file - which then lands up in `build.libs`.  On the other hand, if we already have two jar files in the `lib` directory, why not include the JavaFBP-WebSockets jar file in the `lib` directory.  Then build.gradle can do a copy from `build\libs` into `lib`...?   (build/ is not currently included in the GitHub project online)  Or is there a standard GitHub-ish way of managing the primary jar file...?  TIA

**Comment by marci4** [comment]
Hello @jpaulm,

the idea behind the proposed approach is just so you not have to include the two additional libs on your own!
If you always just use gradle, then don't do this since gradle will do all the downloading etc.
If you wanna provide an easy to use lib, then you may think about the approach.

The GitHub-ish way is to use gradle/maven and let the build tool download any dependencies.

Greetings
marci4

**Comment by jpaulm** [comment]
Hi @marci4, got that, and it's a good idea!  But, just to clarify - new users should always do a `gradle build` at least once - right? That will also build javadoc, etc., so it makes sense!  I will update Readme accordingly!

Thanks a million for your patience!

Paul

**Comment by jpaulm** [comment]
Hi @marci4 , things are rolling, so that's great!  Mille remerciments!   

I think I now need to gitignore build.gradle - that's only for me to run now, right?

Merci d'avance!

**Comment by marci4** [comment]
Hello @jpaulm,

since there is no way for them to update the sources without downloading from github again, yeah one gradle build run is fine.

If you publish it up to maven, you can push a new version of your lib by just updating the Java-Websocket version your lib is depending on (e.g. see [here](https://mvnrepository.com/artifact/com.xeiam.xchange/xchange-core/3.1.0) under Compile Dependencies).

No worries, always trying to help :)

Greetings
marci4

**Comment by marci4** [comment]
Hello @jpaulm,

is it fine for you that I close this issue?

Greetings
marci4

**Comment by jpaulm** [comment]
Absolutely!  Many thanks for your help!

Best regards,

Paul
