### ISSUE TITLE
Session hang after 5min (approx) on Android devices

### ISSUE THREAD

**Issue by poly-sb** [TooTallNate/Java-WebSocket#523]
I have a server written in javaee with the session maxIdleTimeout() set to 0 so it remind open.

I run successfully an android client (using this library) on my emulator, as a simple java client on my local machine connecting to the websocket server. The TCP channel remind open until any of the two peers shut it down explicitly.

However the session hang after 5min (approx) as soon as the client run on a remote device.
Any idea about what's happening here?

**Comment by marci4** [comment]
Hello @poly-sb,

to be honest right now I have no idea what is happening there.

Could you provide me with some additional information:
- On what android version does this happen?
- On what device does this happen?
- Any other things which may help me understand this problem?

Greetings
marci4

**Comment by poly-sb** [comment]
Hi @marci4 

Thanks for your time. 
We can close this issue since it's not related to your library.
I realised lastly that the device I used was triggering the broadcast receiver "android.net.conn.CONNECTIVITY_CHANGE" service provided by android every 5 min, even on stable network connectivity. 
This was triggering some code which in turn reloaded the WebSocket.
