### ISSUE TITLE
how to get user's session message?

### ISSUE THREAD

**Issue by wang22123467469** [TooTallNate/Java-WebSocket#524]

**Comment by marci4** [comment]
Hello @wang22123467469,

first of all sorry for the delayed response. I was on holiday for a few days and normally don't read any emails.

Could you explain to me what you mean with session?
Right now for me it is not clear what you are trying to get.

Greetings
marci4

**Comment by marci4** [comment]
No response by the user for over a month and no description at all.

Closing issue!
Greetings
marci4
