### ISSUE TITLE
How to reuse a websocket client?

### ISSUE THREAD

**Issue by JamesChungZLL** [TooTallNate/Java-WebSocket#526]
How to reuse a websocket client when I want to re-try connect to websocket server?

**Comment by marci4** [comment]
Hello @JamesChungZLL,

first of all sorry for the delayed response. I was on holiday for a few days and normally don't read any emails.

Right now it is not possible to reuse the client or the server to reconnect.
The best way is just to create a new instance.
Apart from this, I may look into this a bit more if there is a growing interest!

Greetings
marci4

**Comment by Davevb** [comment]
I'm having the same issue. I try to reconnect by making a new instance every 10 sec. For example, when a connection is made after 2 minutes I see 12 connections on server side and only the last one is used...

**Comment by marci4** [comment]
@Davevb take a look at the new reocnnect method!

**Comment by marci4** [comment]
@Davevb open a separate issue please!
