### ISSUE TITLE
so_reuseaddr

### ISSUE THREAD

**Issue by robutil** [TooTallNate/Java-WebSocket#528]
Hello,

I am using your library to create an ad-hoc WebSocketServer in Android, and it works very well.

However, in some cases I need to restart the WebSocketServer. Unfortunately, this is impossible because the flag of SO_REUSEADDR is not set, thus causing a BindException. Currently, this is fixed by simply restarting the application, but this is not desirable.

Could you allow the created socket in WebSocketServer.java in run() to be public, thus allowing users to set the socket.setReuseAddress(true) flag?

Thanks in advance

**Comment by marci4** [comment]
Hello @robutil,

I will add such a feature to the next release. Default will still be false!

Greetings
marci4

**Comment by marci4** [comment]
I added this feature just now.

Thx again for your input!
Greetings
marci4
