### ISSUE TITLE
Do not support websocket 13?

### ISSUE THREAD

**Issue by zutuanwang** [TooTallNate/Java-WebSocket#543]
It seems that do not support websocket 13.

**Comment by marci4** [comment]
Hello @zutuanwang,

I have no clue what you mean with websocket 13 and why you think this is not supported.

Could you elaborate a bit more please?
Thank you!

Greetings
marci4

**Comment by marci4** [comment]
No answer for over a month and no clear question/issue.

Closing!
Greetings
marci4
