### ISSUE TITLE
Android client disconnects when working against SockJS server

### ISSUE THREAD

**Issue by atlithorn** [TooTallNate/Java-WebSocket#544]
Using latest version of Java-WebSocket vs latest version of SockJS.
We have browser and iOS websocket implementations maintaining connections to SockJS with no problems but Android disconnects after roughly a minute. Seems like it's server oriented - at least the call originates here:

https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/client/WebSocketClient.java#L280
And we receive `onClose(code== CloseFrame.ABNORMAL_CLOSE, reason == '', remote == true)`

Any ideas?

**Comment by marci4** [comment]
Hello @atlithorn,

this could be related to [lost connection detection]( https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection). 
The lib is sending a ping every 60 seconds (default value) to the other endpoint. If the other endpoint has not responded to this ping til the next ping is send, it assumes that the connection was lost.

So it is possible that the SockJS is not correctly implementing a response to a ping and causing the lib to think that the connection was lost.

You can see additional info if you activate the debug printouts with `WebSocketImpl.DEBUG = true;`

Greetings
marci4

**Comment by atlithorn** [comment]
Thanks for your response. I activated debug printout and received the following. Looks like the sockJS server is responding as expected? 
```
09-02 15:40:36.653 7975-8242/com.gangverk.sling I/System.out: write(163): {GET / HTTP/1.1
09-02 15:40:36.653 7975-8242/com.gangverk.sling I/System.out: Connection: Upgrade
09-02 15:40:36.653 7975-8242/com.gangverk.sling I/System.out: Host: test-socket.sling.is:443
09-02 15:40:36.653 7975-8242/com.gangverk.sling I/System.out: Sec-WebSocket-Key: BC4+qNvhgc4b6lfJhgxeAg==
09-02 15:40:36.653 7975-8242/com.gangverk.sling I/System.out: Sec-WebSocket-Version: 13
09-02 15:40:36.653 7975-8242/com.gangverk.sling I/System.out: Upgrade: websocket
09-02 15:40:36.653 7975-8242/com.gangverk.sling I/System.out: }
09-02 15:40:36.859 7975-8242/com.gangverk.sling I/System.out: process(188): {HTTP/1.1 101 Switching Protocols
09-02 15:40:36.859 7975-8242/com.gangverk.sling I/System.out: Server: nginx/1.10.1
09-02 15:40:36.859 7975-8242/com.gangverk.sling I/System.out: Date: Sat, 02 Sep 2017 15:39:54 GMT
09-02 15:40:36.859 7975-8242/com.gangverk.sling I/System.out: Connection: upgrade
09-02 15:40:36.859 7975-8242/com.gangverk.sling I/System.out: Upgrade: websocket
09-02 15:40:36.859 7975-8242/com.gangverk.sling I/System.out: Sec-WebSocket-Accept: I+1Ei30LItQxZ6o3TdmsPJujVJw=
09-02 15:40:36.859 7975-8242/com.gangverk.sling I/System.out: }
09-02 15:40:36.862 7975-8242/com.gangverk.sling I/System.out: open using draft: Draft_6455
09-02 15:40:36.862 7975-8242/com.gangverk.sling I/System.out: Connection lost timer started
09-02 15:41:36.868 7975-8259/com.gangverk.sling I/System.out: send frame: Framedata{ optcode:PING, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:[]}
09-02 15:41:36.868 7975-8259/com.gangverk.sling I/System.out: write(6): {��P���}
09-02 15:41:37.060 7975-8242/com.gangverk.sling I/System.out: process(2): {���}
09-02 15:41:37.061 7975-8242/com.gangverk.sling I/System.out: matched frame: Framedata{ optcode:PONG, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:[]}
09-02 15:42:36.865 7975-8259/com.gangverk.sling I/System.out: send frame: Framedata{ optcode:PING, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:[]}
09-02 15:42:36.865 7975-8259/com.gangverk.sling I/System.out: write(6): {���5j}
09-02 15:42:37.059 7975-8242/com.gangverk.sling I/System.out: process(2): {���}
09-02 15:42:37.059 7975-8242/com.gangverk.sling I/System.out: matched frame: Framedata{ optcode:PONG, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:[]}
09-02 15:43:36.865 7975-8259/com.gangverk.sling I/System.out: send frame: Framedata{ optcode:PING, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:[]}
09-02 15:43:36.866 7975-8259/com.gangverk.sling I/System.out: write(6): {��6Y�}
09-02 15:43:37.057 7975-8242/com.gangverk.sling I/System.out: Connection lost timer stoped
```

**Comment by atlithorn** [comment]
Debugging it some more and it appears not to be the client that is terminating the connection.
Seems weird that it always disconnects immediately after the ping however. 
I'll debug on the server and report back.

**Comment by marci4** [comment]
Hello @atlithorn,

yes that looks normal.

Could it be related to #523 ?

Greetings
marci4

**Comment by atlithorn** [comment]
I don't think so. We have an older version of the server which runs on https://github.com/websockets/ws which runs fine forever on exact same client code.
Unfortunately we had too many browser clients needing a fallback so we switched to https://github.com/sockjs/sockjs-node. That solved the browser problem but introduced a mobile app problem instead 😕.

I'm 99.9% sure this is not a java-websocket problem so feel free to close. I will report back here regardless.

**Comment by marci4** [comment]
Hello @atlithorn,

that is "good" to hear, at least for me.

We can also test the following.
Deactivate the lost connection detection by setting the value to 0 (method `setConnectionLostTimeout()`). This deactivates the feature. 
It could be that creating creating a response to a ping causes the sockjs-server to have problems.

Still gonna keep the issue opened just to get your feedback and for me to keep an eye on this issue.

Greetings
marci4

**Comment by atlithorn** [comment]
Tried it. Same result. Server kicks us after a couple of minutes. 

Time to dig into sockjs internals I guess.

**Comment by marci4** [comment]
Hello @atlithorn,

sorry to hear that :( 
Sad that I could not help you anyhow.

Good luck!

I will close this topic, if there is anything more, feel free to reopen it!

Greetings
marci4
