### ISSUE TITLE
Use nginx proxy,how to get real ip ?

### ISSUE THREAD

**Issue by ilahsa** [TooTallNate/Java-WebSocket#546]
nginx proxy for wss,how to get remote ip

**Comment by marci4** [comment]
Hello @ilahsa,

I have no idea how to get the remote ip for a nginx proxy since I am not using it.

Sorry!
Greetings
marci4

**Comment by AoEiuV020** [comment]
@marci4 there is a header key is "X-Real-IP", how to get it ?

**Comment by marci4** [comment]
@AoEiuV020, please check out the [FAQ](https://github.com/TooTallNate/Java-WebSocket/wiki/Frequently-asked-questions#how-can-i-get-a-specific-header-in-my-websocketclient)!
