### ISSUE TITLE
no PONG received from server

### ISSUE THREAD

**Issue by sww0825521xy** [TooTallNate/Java-WebSocket#547]
server side use spring boot default websocket, Android client use Java-WebSocket jar.
After 2 minutes,client will  receive close message.
09-05 00:18:20.148: I/System.out(3680): Closing connection due to no pong received: org.java_websocket.WebSocketImpl@107c96a
09-05 00:18:20.148: I/System.out(3680): Connection lost timer stopped

I don't know how to send PONG to the client from the server.
Can Java-WebSocket compatible with spring boot websocket?

**Comment by marci4** [comment]
Hello @sww0825521xy,

you can find a documentation for this feature [here](https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection).

This feature takes advantage of the [section 5.5.2](https://tools.ietf.org/html/rfc6455#section-5.5.2) in the rfc spec.
```
Upon receipt of a Ping frame, an endpoint MUST send a Pong frame in response, unless it already received a Close frame.  It SHOULD respond with Pong frame as soon as is practical.  Pong frames are discussed in Section 5.5.3.
```

If the spring boot websocket is implementing the spec correctly, then everything should be working fine!

Greetings
marci4

**Comment by marci4** [comment]
Issue answered. No feedback.
Closing issue!

Greetings
marci4
