### ISSUE TITLE
How to get url params? How to get client's unique id?

### ISSUE THREAD

**Issue by lifubang** [TooTallNate/Java-WebSocket#554]
1、for wss://ws.acmcoder.com:6262/roomid=123456
In Server side, how to get param roomid's value?

2、How to get client's cookie?

3、How to get client's unique id?
In server side, when administrator want to talk with a client, whose name is LFB, and id is DF38KFC in my database, how to find out his socket to run sock.send(text)?

**Comment by marci4** [comment]
Hello @lifubang,

When a new connection is opened and `onOpen()` is called, the `ClientHandshake` contains some of the information you are looking for.
`handshake.getResourceDescriptor()` will give you `/roomid=123456`
`handshake.getFieldValue("Cookie")` will give you the cookies.

3. I have no clue how the client gets this name... That is a application specific implementation which I have no clue of...

Greetings
marci4

**Comment by lifubang** [comment]
For the third question, I have no idea all. So I have to add a Dictionary in ChatServer, make a mapping from userid to websocket's unique id, but there are two problems:
1. I don't know this unique id is really one and only.
2. Although I remove the disconnected websocket from Dictionary in onClose event, but some disconnected websocket with some unknown errors will not be removed from the Dictionary for ever.

So I suggest the maintainer to add a clientid field in WebSocketImpl or WebSocket.

```java
    //The dic of websocket
    //todo: I suggest the maintainer to add a clientid field in WebSocketImpl or WebSocket
    private Dictionary<String, WebSocket> conns = new Hashtable<String, WebSocket>();

    //get a socket's unique key
    //todo: I suggest the maintainer to add a clientid field in WebSocketImpl or WebSocket
    private String key(WebSocketImpl sock) {
        StringBuilder s  = new StringBuilder();

        s.append(sock.toString().substring(33))
                .append(sock.key.toString().substring(28))
                .append(sock.hashCode())
                .append(sock.getRemoteSocketAddress().getAddress().getHostAddress().replaceAll("\\.", ""))
                .append(sock.getRemoteSocketAddress().getPort());
        String str = s.toString();

        return str;
    }

    @Override
    public void onOpen( WebSocket conn, ClientHandshake handshake ) {
        //this.sendToAll( "new connection: " + handshake.getResourceDescriptor() );
        WebSocketImpl sock = (WebSocketImpl)conn;

        //todo: I suggest the maintainer to add a clientid field in WebSocketImpl or WebSocket
        String key = this.key(sock);
        this.conns.put(key, conn);

        //get from cookie
        ......

        //add to db
        ChatUser chatUser = new ChatUser();
        chatUser.userid = json.getString("userid");
        chatUser.clientid = key;
        chatUser.role = json.getString("role");
        chatUser.in_date = new Date();
        ChatUser chatUserSaved = this.chatUserDAO.repository.insert(chatUser);
        //then there is a map from userid to websocket's key id
        if (WebSocketImpl.DEBUG)
            System.out.println(key + " entered the room!" );
    }
```

**Comment by marci4** [comment]
Hello @lifubang,

I think what you are looking for is something which is proposed on a different issue #485.

The hashcode of a websocket is currently not overridden so it is the default java object hashcode.

When is onClose not called? Do you have any example?

Greetings
marci4

**Comment by lifubang** [comment]
@marci4 in onOpen event, we can get ClientHandshake param, so we can get cookie value by handshake.getFieldValue("Cookie"). But in onMessage event, there are no ClientHandshake param, how to get cookie?

You may know, in web application, each controller may need cookie value to store the user's data. So I think in onMessage event, we may need cookie field.

**Comment by marci4** [comment]
Hello @lifubang, 
what you are describing is just a feature reqest which is #485. 
You are able to access these fields onOpen and if you need them later you may wanna save them in a separate map.

Closing issue since it is solved!
Greetings
marci4
