### ISSUE TITLE
no pong received from server 

### ISSUE THREAD

**Issue by wangdar** [TooTallNate/Java-WebSocket#555]
we develop a client app to receive maket info from server

we use ConnectionLostTimer for hearbeat communication with server
ConnectionLostTimer  ping pong sometime work ok, but after a while
we can not receive pong from the server,
the client report below error and close the connection.
how to fix the problem with client or there may be a bug in server side? 
> Closing connection due to no pong received

the code is 
`marketClient.setConnectionLostTimeout(5);`

**2017/09/10-18:17:36.765 [ConnectionLostTimeoutTimer] send ping to server: org.java_websocket.WebSocketImpl@3826822b**
2017/09/10-18:17:36.765 [ConnectionLostTimeoutTimer] send frame: Framedata{ optcode:PING, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:}
afterEnconding(0): {}
2017/09/10-18:17:36.765 [ConnectionLostTimeoutTimer] write(6): {���"�}
2017/09/10-18:17:36.765 [org.java_websocket.client.WebSocketClient$WebsocketWriteThread@20452100_WriteThread] write java.nio.HeapByteBuffer[pos=0 lim=6 cap=6]
2017/09/10-18:17:36.874 [com.huobi.api.market.WebSocketUtils@3070a602_ReaderThread] process(2): {��}
afterDecoding(0): {}
**2017/09/10-18:17:36.874 [com.huobi.api.market.WebSocketUtils@3070a602_ReaderThread] matched frame: Framedata{ optcode:PONG, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:}**
2017/09/10-18:17:36.874 [com.huobi.api.market.WebSocketUtils@3070a602_ReaderThread] onWebsocketPong:Framedata{ optcode:PONG, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:}
2017/09/10-18:17:37.868 [com.huobi.api.market.WebSocketUtils@3070a602_ReaderThread] process(42): {�(���������V*��KW�245050�fFƵ��j�H���}
afterDecoding(40): {���������V*��KW�245050�fFƵ��j�H���}
2017/09/10-18:17:37.869 [com.huobi.api.market.WebSocketUtils@3070a602_ReaderThread] matched frame: Framedata{ optcode:BINARY, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:40], payload:���������V*��KW�245050�fFƵ��j�H���}
2017/09/10-18:17:37.869 [com.huobi.api.market.WebSocketUtils@3070a602_ReaderThread] receive ping and send pong back to server {"pong":1505035057623}
2017/09/10-18:17:37.869 [com.huobi.api.market.WebSocketUtils@3070a602_ReaderThread] send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:22], payload:{"pong":1505035057623}}
afterEnconding(22): {{"pong":1505035057623}}
2017/09/10-18:17:37.869 [com.huobi.api.market.WebSocketUtils@3070a602_ReaderThread] write(28): {���F���d��!���s���u���q���;}
2017/09/10-18:17:37.869 [org.java_websocket.client.WebSocketClient$WebsocketWriteThread@20452100_WriteThread] write java.nio.HeapByteBuffer[pos=0 lim=28 cap=28]
**2017/09/10-18:17:41.761 [ConnectionLostTimeoutTimer] send ping to server: org.java_websocket.WebSocketImpl@3826822b**
2017/09/10-18:17:41.761 [ConnectionLostTimeoutTimer] send frame: Framedata{ optcode:PING, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:0], payload:}
afterEnconding(0): {}
2017/09/10-18:17:41.761 [ConnectionLostTimeoutTimer] write(6): {���h��}
2017/09/10-18:17:41.761 [org.java_websocket.client.WebSocketClient$WebsocketWriteThread@20452100_WriteThread] write java.nio.HeapByteBuffer[pos=0 lim=6 cap=6]
2017/09/10-18:17:46.761 [ConnectionLostTimeoutTimer] Closing connection due to no pong received: org.java_websocket.WebSocketImpl@3826822b
2017/09/10-18:17:46.761 [ConnectionLostTimeoutTimer] Connection lost timer stopped
2017/09/10-18:17:46.764 [ConnectionLostTimeoutTimer] 关流--Connection closed by us

**Comment by marci4** [comment]
Hello @wangdar,

this looks for me like a server side issue which may be caused by the low interval. 
Every client is sending every 5 seconds a ping to the server which the server then has to process and respond to. That could push the server to its limits.

Greetings
marci4

**Comment by wangdar** [comment]
Hi @marci4 
Thanks for you reply, this is may server side problem, I will report a issue my server side developer
also change my check interval to high value for sending ping to server.
