### ISSUE TITLE
send message like roomId in the connectionLostTimerTask

### ISSUE THREAD

**Issue by hattie0312** [TooTallNate/Java-WebSocket#557]
Hi,

Now Java-WebSocket just uses conn.sendPing() in the connectionLostTimerTask. I need to send message like roomId in the connectionLostTimerTask when it is timeout. Could you please tell me how can I do it?

Thanks!

    protected void startConnectionLostTimer() {
        if (this.connectionLostTimeout <= 0) {
            if (WebSocketImpl.DEBUG)
                System.out.println("Connection lost timer deactivated");
            return;
        }
        if (WebSocketImpl.DEBUG)
            System.out.println("Connection lost timer started");
        cancelConnectionLostTimer();
        connectionLostTimer = new Timer();
        connectionLostTimerTask = new TimerTask() {
            @Override
            public void run() {
                Collection<WebSocket> con = connections();
                synchronized ( con ) {
                    long current = (System.currentTimeMillis()-(connectionLostTimeout * 1500));
                    for( WebSocket conn : con ) {
                        if (conn instanceof WebSocketImpl) {
                            if( ((WebSocketImpl)conn).getLastPong() < current ) {
                                if (WebSocketImpl.DEBUG)
                                    System.out.println("Closing connection due to no pong received: " + conn.toString());
                                conn.close( CloseFrame.ABNORMAL_CLOSE );
                            } else {
                                **conn.sendPing();**
                            }
                        }
                    }
                }
            }
        };
        connectionLostTimer.scheduleAtFixedRate( connectionLostTimerTask,connectionLostTimeout * 1000, connectionLostTimeout * 1000 );
    }

**Comment by marci4** [comment]
Hello @hattie0312,

`sendPing()` does not support custom payloads write now.
So you have to implement the connectionLostTimerTask on your own.

Keep in mind that the specification does not specify what payload is allowed to be send in a ping.
If you are using a different implementation it could be the current time in milliseconds or stuff like that!

Apart from this, the other endpoint should now in which room this endpoint is and should not require a ping for this.

Greetings
marci4

**Comment by hattie0312** [comment]
Hello @marci4 ,

Thanks and I implemented the connectionLostTimerTask on my own.

Our server-side developer asked us to send a message every 5 seconds to keep the connection. If it is not received, they will close the connection from the server-side. But I think to send message such frequently is a waste of flow. 
Any Suggestions please？

Greetings
Hattie

**Comment by marci4** [comment]
Hello @hattie0312,

if that is the requirement, then you cannot do anything against it.
I am just sure that it will create a lot of load. You may wanna estimate how many ping/pong frames are send from and to the server with your planned user base.
Maybe this would change the requirement...

Greetings 
marci4

**Comment by marci4** [comment]
Closing issue since it is solved!

Greetings
marci4
