### ISSUE TITLE
websocket 在android 平台有大小限制8K 怎么办

### ISSUE THREAD

**Issue by hhhaiai** [TooTallNate/Java-WebSocket#559]
websocket 在android 平台有大小限制8K 怎么办

**Comment by marci4** [comment]
Hello @hhhaiai,

I do not understand Chinese. Could you please translate your issue to English ?

Thank you.
Greetings marci4

**Comment by TomWangTW** [comment]
This library has 8kb limitations on Android platform. What should i do?

**Comment by marci4** [comment]
Thx for translating @TomWangTW

could you please ask him the following:
when does he have this issue? (Text or Binary)
which version of android is he having this issue on?
Is he using ws or wss?
with which endpoints is he having this issue?
what is he exactly doing? (steps to reproduce)

thx a lot.
Greetings marci4

**Comment by forresthopkinsa** [comment]
I'll try Google Translate. @hhhaiai  :

我在用谷歌翻译

marci4想知道这些问题

首先，你有这个问题吗？

接下来，您正在使用什么版本的Android？

你使用ws还是wss？

哪些端点有问题？

什么步骤导致问题？  重现步骤

**Comment by marci4** [comment]
Could you please check if #570 is fixing this issue for you?

Greetings
marci4

**Comment by marci4** [comment]
Any update?

**Comment by oscarthecat** [comment]
He is asking about the 8KB receiving cache size limit, which can be set with custom values.
And forresthopkinsa's translation with google is read good in Chinese :)

**Comment by marci4** [comment]
I have no clue what he is taking about. Could you elaborate what he means with cache size limit and what the expected behaviour is ?

Greetings 
marci4

**Comment by marci4** [comment]
Any update?

**Comment by marci4** [comment]
Closing this dead issue.
Not sure what was meant with this issue in the first place.

Greetings
marci4
