### ISSUE TITLE
socket auto close with "code=1006 , reason ='' , remote=true" after one minute

### ISSUE THREAD

**Issue by KevinKmoo** [TooTallNate/Java-WebSocket#560]
I connect the socket , the server will send a 'ping' msg to me every 20 seconds , then after one minute ,the socket will auto close and the code is 1006 with no reason.
When i use the old version(1.3.3) , there is no error.I update it to version 1.3.4 , then i get the error.

**Comment by marci4** [comment]
Hello @KevinKmoo,

I introduced a feature called Lost connection detection in 1.3.4. (see [here](https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection))
It looks like the other endpoint is not correctly responding to pings and not answering them with pongs.
You can turn this feature off with `setConnectionLostTimeout(0)`

Greetings
marci4

**Comment by KevinKmoo** [comment]
Thanks , i try this way and it worked , i will close this issue.

**Comment by marci4** [comment]
Just to make it clear. Your endpoint is not responding correctly to the spec. You just turn the heart beat check off ...

**Comment by KevinKmoo** [comment]
Our server is written by PHP , i guess that the heart beat check is the server written with your code will do , i hadn't read your code , i just use that , maybe what i understand is wrong.

**Comment by marci4** [comment]
The specification requires an endpoint to respond to a ping with a pong! I use this requirement in my heart beat check. Since your endpoint is not correctly implementing the specification the heart beat check just fails and disconnects the client.

Greetings
marci4
