### ISSUE TITLE
messages sent （in outQueue）before do close() will always be sent?

### ISSUE THREAD

**Issue by hattie0312** [TooTallNate/Java-WebSocket#561]
Hello,

I sent a message and then closed the websocket. If the websocket is closed too fast, may the message is still in the waiting queue and will not be sent?

The following is your reply in other issue, it seems the messages sent （in outQueue）before do close() will always be sent. Could you please give me a confirm?

==================================================================
"Closing the socket is a process which is made up of a few steps:

1. Peer1 queues the asynchronous job to send the close handshake. After this it is not allowed to send more frames. (The output is logically closed)
2. The asynchronous job to send the close handshake executed and sends the close frame over the wire( which failed in your case ) after it completed other asynchronous operations like sending remaining frames( this will be guaranteed very soon ).
3. Peer2 continues to send more frames until it receives the close handshake. Then it echoes the close handshake.
4. Peer1 receives the frames( the data frames & the close frame ) sent by Peer2 and closes the socket completely."

Greeting
Hattie

**Comment by marci4** [comment]
Hello @hattie0312,

I am currently on holiday so I can not give you a definite answer.
Thow this statement was made a long time ago by a different maintainer.

I will give you a definite answer when I am back.

Greetings 
marci4

**Comment by marci4** [comment]
It looks like there could be an issue in the websocket client side.
I don't think there is an issue on the server side though.
Does this fit to your observations?

Greetings
marci4

**Comment by hattie0312** [comment]
Hi marci4,

Sorry for my poor English.
Suppose I sent a message then closed the connection immediately. If the message is received by the server?

**Comment by marci4** [comment]
Hello @hattie0312,

I think there could be an issue if you close the connection immediately.
I will fix this!

Greetings
marci4

**Comment by hattie0312** [comment]
thanks for your reply
