### ISSUE TITLE
Null pointer exception on Draft?

### ISSUE THREAD

**Issue by OmriSoudry** [TooTallNate/Java-WebSocket#565]
Running a websocket server, I started using Firefox as a web client in an old PC, and since then I'm getting this weird error spontaneously (it can be several minutes after establishing a connection and exchanging data):

> Oct  3 18:08:04 System root: Exception in thread "WebsocketSelector11" java.lang.ClassFormatError: LVTT entry for 'frames' in class file org/java_websocket/drafts/Draft_6455 does not match any LVT entry
Oct  3 18:08:04 System root:    at java.lang.ClassLoader.defineClass1(Native Method)
Oct  3 18:08:04 System root:    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
Oct  3 18:08:04 System root:    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
Oct  3 18:08:04 System root:    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
Oct  3 18:08:04 System root:    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
Oct  3 18:08:04 System root:    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
Oct  3 18:08:04 System root:    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
Oct  3 18:08:04 System root:    at java.security.AccessController.doPrivileged(Native Method)
Oct  3 18:08:04 System root:    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
Oct  3 18:08:04 System root:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Oct  3 18:08:04 System root:    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
Oct  3 18:08:04 System root:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Oct  3 18:08:04 System root:    at org.java_websocket.WebSocketImpl.<init>(WebSocketImpl.java:156)
Oct  3 18:08:04 System root:    at org.java_websocket.server.DefaultWebSocketServerFactory.createWebSocket$b85d923(DefaultWebSocketServerFactory.java:44)
Oct  3 18:08:04 System root:    at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:364)
Oct  3 18:08:04 System root:    at java.lang.Thread.run(Thread.java:745)

**Comment by marci4** [comment]
Hello @OmriSoudry,

thx for your bug report.

I got a few questions:
- Where is the NullPointerException? I just see a ClassFormatError
- What is your java version and what is your lib version?
- Are you using Java 8? If so, maybe update your java. There was a compiler error in a version (see [stackoverflow](https://stackoverflow.com/a/26240214))

Greetings
marci4

**Comment by marci4** [comment]
No feedback for over one month!

There is no NullPointer exception in the provided stacktrace!

Closing issue.
Greetings
marci4
