### ISSUE TITLE
1.3.5 is available!

### ISSUE THREAD

**Issue by marci4** [TooTallNate/Java-WebSocket#575]
A lot of bug fixes :) ENJOY!

_It may take some time til it is pushed to all servers!_

**Comment by yuripourre** [comment]
Awesome news! Thank you.

**Comment by tiagosantos1988** [comment]
There is a problem with sending ping. If there isn't network it throws an exception. It didn't happend in version 1.3.4.

**Comment by marci4** [comment]
Hello @tiagosantos1988,

please open a seperate issue for this!

Greetings
marci4
