### ISSUE TITLE
After onClose still receive message  and isOpen() returned true

### ISSUE THREAD

**Issue by hattie0312** [TooTallNate/Java-WebSocket#582]
## Expected Behavior
After onclose,not more received message, and isOpen() returned false.

## Current Behavior
onClose(int code, String reason, boolean remote) is called.Connection closed by us ,code: 1000,reason: 
After that,still received message, and isOpen() returned true.

## Your Environment

* Version used:1.3.4
* Java version:
* Operating System and version:
* Endpoint Name and version:
* Link to your project:

**Comment by marci4** [comment]
Hello @hattie0312,
there are still some information missing for me to understand your issue.
Are you talking about the client oder server side?
Please provide some steps to repeat...
The template is in place for a reason to help me to fix/develop more stuff in my limited time available...

Greetings
marci4

**Comment by marci4** [comment]
Any update?
