### ISSUE TITLE
Problem with WSS/HTTPS - ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Forsties08** [TooTallNate/Java-WebSocket#584]
## Current Behavior
I trying to regenerate my certificate with tihs #540 but it still doesn't work.

## Debug log (for bugs)
Server (when im trying to connect):
Removing connection which is not in the connections collection! Possible no handshake recieved! org.java_websocket.WebSocketImpl@369fa284
Connection closed because of javax.net.ssl.SSLHandshakeException: no cipher suites in common

Client:
WebSocket connection to 'wss://XXXXXXXXX:XXXX/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR

## Context
I create a mini game with J-WS, it work perfectly on localhost or http website, but when i moved him to my real website (https), the client cannot connect anymore.

## Your Environment

* Version used: 1.3.5
* Java version: 1.8.0_151
* Operating System and version: Debian 8

**Comment by Forsties08** [comment]
Oh, and my site / application WS are on different hosting

**Comment by marci4** [comment]
Hello @Forsties08,

what are you using as a client?
What kind of certificate are you using? Self Signed? Lets Encrypt? Other? And does the other endpoint trust it?

The message just says that both endpoints don't have any cipher suites in common.
The vm option `-Djavax.net.debug=all` can help to find out if there is a problem with the certificate.
This will activate additional debug printouts so you know which cipher suites are offered and so on.

We also have an example how to allow specific cipher suites [here](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLServerCustomWebsocketFactoryExample.java).

Hope this helps you!
Greetings
marci4

**Comment by Forsties08** [comment]
Hi ! thanks for your reply.

Debug with the option:
Removing connection which is not in the connections collection! Possible no handshake recieved! org.java_websocket.WebSocketImpl@426675d6
Connection closed because of javax.net.ssl.SSLHandshakeException: no cipher suites in common


I use this code
https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLServerCustomWebsocketFactoryExample.java

and the certificate in the header of the example:
keytool -genkey -validity 3650 -keystore "keystore.jks" -storepass "storepassword" -keypass "keypassword" -alias "default" -dname "CN=127.0.0.1, OU=MyOrgUnit, O=MyOrg, L=MyCity, S=MyRegion, C=MyCountry"

I trying to use Lets Encrypt but same probleme. 

My client is Google Chrome, this is my code for the connection :
conn = new WebSocket('wss:########:####');

How can i see if the other trust it ?

**Comment by marci4** [comment]
Hello @Forsties08,

It looks like you have not activated the vm option. You have to do something like `java -Djavax.net.debug=all -jar Server.jar` to activate the vpm option.

Well this will not work since you create the certificate for localhost/127.0.0.1 `CN=127.0.0.1`.

You can check it with https://########:#### using the same url/port as for wss.

Greetings
marci4

**Comment by Forsties08** [comment]
I regenerate the certificate with the adress.

Here is the debug from server when im trying to connect : https://hastebin.com/fehudavifo.txt

Do i need a domain or i can use directly my adress ?

When i go to the url (https://ipadress:port), i have this error on the developer tools, in the network tab :

The certificate for this site does not contain a Subject Alternative Name extension containing a domain name or IP address.

**Comment by marci4** [comment]
Hello @Forsties08,

if you use the ip address in your certificate, then you have to connect via ip address.
If you use a hostname in the certificate, use the hostname.

You have to add an exception for this certificate then! (Each browser allows this in a different way!)

Then you should be able to connect!

Greetings
marci4

**Comment by Forsties08** [comment]
OK thanks, i fixed the error with the SAN, but the https is always broken. How i can see what is missing ?

**Comment by marci4** [comment]
Hello @Forsties08,
there should always be a 404 Websocket Upgrade Failure since it is a different specification!

Greetings
marci4

**Comment by Forsties08** [comment]
What do you mean ? sorry i dont understand ?

I trying my url here https://www.sslshopper.com/ssl-checker.html

And he said all good except :

The certificate is self-signed. Users will receive a warning when accessing this site unless the certificate is manually added as a trusted certificate to their web browser. You can fix this error by

So, i think i can use my domain ? and use the Let's Encrypt SSL of him ? or i can use his SSL without the domain ? (the domain is link to the same hosting of the WS Application with Apache)

**Comment by marci4** [comment]
Hello @Forsties08,

well, you cannot use a self signed certificate for production. Of course you have to use a signed certificate...
Cheapest way is of course Let's Encrypt.

Maybe you should inform yourself about SSL a bit more before you start such a project!

Greetings
marci4

**Comment by Forsties08** [comment]
Sure, i found a solution with a proxy apache + Let's Encrypt, all works now ! thanks for your help

**Comment by Dayssam** [comment]
> 
> 
> Hello @Forsties08,
> there should always be a 404 Websocket Upgrade Failure since it is a different specification!
> 
> Greetings
> marci4

Hi @marci4 

What does mean 404 Websocket Upgrade Failure ?
I wanna customize the hello message if it's possible when i access https://XXXXXX:PORT

**Comment by wilddylan** [comment]
···
WebSocketConnectReadThread-33, received EOFException: error
WebSocketConnectReadThread-33, handling exception: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
WebSocketConnectReadThread-33, SEND TLSv1.2 ALERT:  fatal, description = handshake_failure
WebSocketConnectReadThread-33, WRITE: TLSv1.2 Alert, length = 2
[Raw write]: length = 7
0000: 15 03 03 00 02 02 28                               ......(
WebSocketConnectReadThread-33, called closeSocket()
WebSocketWriteThread-36, handling exception: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
···
