### ISSUE TITLE
WebsocketClient.close() does not call stopConnectionLostTimer()

### ISSUE THREAD

**Issue by meghneelgore** [TooTallNate/Java-WebSocket#587]
If connectionLostTimeout is not set to 0, results in a WebsocketNotConnectedException at WebsocketImpl.send() (around line number 606) after connectionLostTimeout number of seconds after WebsocketClient.close() is called.

This is basically because the WebSocket is closed but the connectionLostTimer tries to send a ping frame anyway.

## Expected Behavior

Should not throw WebsocketNotConnectedException after  WebsocketClient.close() is called

## Current Behavior

WebsocketNotConnectedException is thrown connectionLostTimeout seconds after WebsocketClient.close() is called.

## Steps to Reproduce (for bugs)

1. Start a websocket connection
2. Close the connection
3. Wait connectionLostTimeout number of seconds (default 60).
4.

## Your Environment

* Version used: 1.3.5
* Java version: 1.8
* Operating System and version: Android 8.0
* Endpoint Name and version: 
* Link to your project:

**Comment by meghneelgore** [comment]
One workaround is to call WebsocketClient.setConnectionLostTimeout(0);

**Comment by marci4** [comment]
Hello @meghneelgore,

thank you for your bug report. 
Will test it later when I am back home!

Could you maybe check if this issue is fixed already with #586 ?

Greetings
marci4

**Comment by marci4** [comment]
Hello @meghneelgore,

I can not reproduce this issue any more! 
Most likely fixed with #586.

Could you please confirm this?
Greetings
marci4

**Comment by szuwest** [comment]
I think this happens on the server have close but client not

**Comment by marci4** [comment]
Is this still an issue with 1.3.7?

Greetings
marci4

**Comment by meghneelgore** [comment]
@marci4 Apologies, I haven't been able to check this out because the workaround works ok for me.
