### ISSUE TITLE
Plan to support endpoint?

### ISSUE THREAD

**Issue by studenttwok** [TooTallNate/Java-WebSocket#595]
Hi all,

I would like to know if the library support multiple endpoints?
I read the server example and found that I can create the websocket server, but no place for me to specify the endpoint names.
So currently I can make ws://localhost:1234/ , but I am not able to make ws://localhost:1234/MyEndPoint1 and ws://localhost:1234/MyEndPoint2 at the same time.

Thanks.

**Comment by marci4** [comment]
Hello @studenttwok,

to my knowledge there is no way to have multiple SocketSever running on the same port.
It is technically not possible without some managing software, which redirects incoming request so the specific endpoint, to have multiple endpoints on one port.

Greetings
marci4
