### ISSUE TITLE
How to handle redirect

### ISSUE THREAD

**Issue by 836608061** [TooTallNate/Java-WebSocket#602]
Dear sir,
         per title, how to handle url redirect and where can do the operation?
Thanks.

**Comment by marci4** [comment]
Hello @836608061,

this client does not support HTTP redirect. 
Not even the chrome websocket does support this. Why do you need such a feature?

Greetings
marci4

**Comment by marci4** [comment]
Any update?

**Comment by SiKing** [comment]
I realize this question is closed (for a while now), but I just ran into the same problem.

Our entire environment, including the ws server, is hosted in OpenShift. There is some magic redirection based on the URI path.

I am using just the `ExampleClient` from your examples. When I try to connect to our server, the initial handshake fails with:

> Close connection, by: us, reason: Invalid status code received: 302 Status line: HTTP/1.1 302 Found, code: 1002

Anything I can do about this?
