### ISSUE TITLE
Sec-WebSocket-Protocol header not supported

### ISSUE THREAD

**Issue by nik17klika** [TooTallNate/Java-WebSocket#608]
## Expected Behavior

When client sends handshake it should be able to set "Sec-WebSocket-Protocol" header to establish connection, also Server should send "Sec-WebSocket-Protocol" header in handshake response

## Current Behavior

No "Sec-WebSocket-Protocol" supported

## Possible Solution

Update Draft_6455 class at least to return "Sec-WebSocket-Protocol" in  server response, and think how customize client request post processing to set "Sec-WebSocket-Protocol" header value.

**Comment by marci4** [comment]
Hello @nik17klika,

thank you for your feature request.

I will try to set something up tonight!
Can I then get some feedback from you?

Greetings
marci4

**Comment by marci4** [comment]
Hello @nik17klika,

I implemented some changes on [this](https://github.com/marci4/Java-WebSocket-Dev/tree/protocol) branch.
Could you please take a look at this and tell me if this is sufficient. Thank you!

To apply a protocol, you have to use call the constructor of the Draft_6455 the following way!
`new Draft_6455( Collections.<IExtension>emptyList(), Collections.<IProtocol>singletonList( new Protocol( "chat" )))`
This adds the Sec-WebSocket-Protocol "chat" to the handshake and the connection!

Greetings
marci4

**Comment by nik17klika** [comment]
Hello @marci4 ,
thanks for fast response, I guess your changes enough to use Sec-WebSocket-Protocol header
