### ISSUE TITLE
Retry send() automatically

### ISSUE THREAD

**Issue by Harlber** [TooTallNate/Java-WebSocket#611]
As title say , 
Is there any better way to implement retry `send()` action after exception automatically?
Thanks in advance!

Version used: `1.3.6`
Operating System and version: `Android`
Module: `Client`

**Comment by marci4** [comment]
Hello @Harlber,

You can always check with isOpen() if the connection is already open!

Greetings
marci4

**Comment by Harlber** [comment]
Got it，Thanks a lot！
