### ISSUE TITLE
onFragments methods

### ISSUE THREAD

**Issue by jebej** [TooTallNate/Java-WebSocket#616]
Hello, it seems that the `onFragment` methods have been deprecated recently, what is the suggested replacement?

Thanks for all the hard work!

**Comment by marci4** [comment]
Hello @jebej, 

the problem with onFragment was that it was not intuitive. A user expects a message send in Chrome to be received with` onMessage()`.
So I changed everything that all fragmented messages will get combined to a complete frame which will call the respective `onMessage()` method.

So to answer your message, just use` onMessage()`.

Greetings
marci4

**Comment by marci4** [comment]
Issue should be solved, if there are more questions feel free to open it again.

Greetings
marci4

**Comment by jebej** [comment]
Yes, it works with the latest version, thanks.
