### ISSUE TITLE
Modification of IP fields; DS field previously known as ToS

### ISSUE THREAD

**Issue by jasuade** [TooTallNate/Java-WebSocket#619]
Hello,
I write to ask if it is already implemented, or if it can be implemented with this library a method to
modify one of the fields if the IP header.
The field is the DS (previously known as  Type of Service: ToS) and is used to perform DiffServ.
This method is implemented in java.net.socket as setTrafficClass(int tc) and it "sets traffic class or type-of-service octet in the IP header for packets sent from this Socket. As the underlying network implementation may ignore this value applications should consider it a hint".

So there is a possibility to modify this IP field with this library?

**Description:**
Differentiated services or DiffServ is a computer networking architecture that specifies a simple and scalable mechanism for classifying and managing network traffic and providing quality of service (QoS) on modern IP networks. DiffServ uses a 6-bit differentiated services code point (DSCP) in the 8-bit differentiated services field (DS field) in the IP header for packet classification purposes. The DS field replaces the outdated IPv4 TOS field. This ID header determines the per-hop-behaviour (PHB) in the route.
Then, when you create a socket, normally, you can modify the configuration and some parameters. It if possible to set this parameter with this library?

Thanks in advance,
regards,

**Comment by marci4** [comment]
Hello @jasuade,

right now there is no way to modify this field.
I, of course, can add this, if it has any use.

Could you maybe elaborate why you need such a feature, especially since it is up to the underlying architecture to use it or not?

Greetings
marci4

**Comment by jasuade** [comment]
Hi @marci4,

Well, it's something complicated I will try to simplify. I am developing a system (gateway) with two main components that connect to each other through an SDN network, developed and managed by me also, in this SDN network you can manage the traffic attending to this DS field, so that I want to mark the traffic getting out from a component to be treated in a different way depending on the type of data if carries.

It was just as question or suggestion but if you do not see it interesting or necessary we can fork the repo and implement it so you can close the issue.

all the best, 
Jasuade

**Comment by marci4** [comment]
Hello @jasuade,

to be honest I don't think this is useful for other people.
Especially since it is not required that a gateway handels the trafific different.

So I would like you to fork and adjust it to your needs!

Greetings
marci4

**Comment by marci4** [comment]
Hello @jasuade,

Is this question answered for you? Can I close this issue or do you need more information?

Greetings
marci4

**Comment by jasuade** [comment]
Hi @marci4,

Yes, sure, you can close this issue. I will fork your code as suggested 👍 
Thank you.

regards,
Jara
