### ISSUE TITLE
sendHandshake on android may have a bad request

### ISSUE THREAD

**Issue by oscarthecat** [TooTallNate/Java-WebSocket#623]
**Android platform**
current master branch

`WebSocketClient.java`
```java
private void sendHandshake() throws InvalidHandshakeException {
		String path;
		String part1 = uri.getRawPath();
		String part2 = uri.getRawQuery();
		if( part1 == null || part1.length() == 0 )
			path = "/";
		else
			path = part1;
		if( part2 != null )
			path += '?' + part2;
```
in which `String part2 = uri.getRawQuery()`, which returns url decoded string in android

```java
    public String getQuery() {
        if ((decodedQuery == null) && (query != null))
            decodedQuery = decode(query);
        return decodedQuery;
    }
```
it's may cause a bad request.

**Comment by oscarthecat** [comment]
And I just check URI.java in java 1.8
```java
    public String getQuery() {
        if ((decodedQuery == null) && (query != null))
            decodedQuery = decode(query);
        return decodedQuery;
    }

```

**Comment by marci4** [comment]
Hello @oscarthecat,

I will not change this without any known issue. 
Why should this cause a bad request?
What is a bad request for you?

This code was changed due to this report here #247

Greetings
marci4

**Comment by marci4** [comment]
Any update?

**Comment by marci4** [comment]
Going to close this issue. 

No additional info by the author and we changed this due to issue #247.

If this is still an issue, feel free to reopen it!
Greetings
marci4
