### ISSUE TITLE
How to handle WebSocket messages inside an User

### ISSUE THREAD

**Issue by promatik** [TooTallNate/Java-WebSocket#625]
Hi!
I am migrating my java socket server to a **web** socket server with your library.

Previously I had a class `User` that handled the user messages because it was a thread always waiting on `inputStream.read()` it processed the message there, and depending on the message type (a kind of protocol I created), it would perform some operations in the object, like a login (saving that info in the `User` object), setting a status, requesting database data, or dispatch the message to a main system which would deal with the that in case the message couldn't be handle by the user (like sending a private message to other `User`).

While implementing this library, I faced the problem that I can't have a `User`, because all I got on `onOpen` is a `WebSocket` connection, with no information from the user. If I create a user with that connection `User(WebSocket connection)`, I would need to listen to an `onMessage()` event. To process the message there.

Is this possible?
Or should I opt for another approach?

I thought about creating an `HashMap<WebSocket, User> conns`, so when I receive an `onMessage(WebSocket conn, String message)` I could call and `onMessage()` inside my `User` like: `conns.get(conn).onMessage(String message)` and then handle the message inside that `User` object. But, isn't this HashMap a too heavy?

Can someone please guide me on the best approach?
Thank you!

**Comment by marci4** [comment]
Hello @promatik,

Right now it is not possible to assign a WebSocket additional values. 
There is however a an open discussion on such a new feature in issue #485 

So right now you have to use a map for assigning additional values to a websocket.

Gretings
marci4

**Comment by promatik** [comment]
Thank you @marci4, I'll close this issue and continue there.
