### ISSUE TITLE
Why callback webScoketclient's onClose() so immediately when close network by myself on Android phone 

### ISSUE THREAD

**Issue by VayneKaso** [TooTallNate/Java-WebSocket#626]
I finished my development tasks that dependency your lib in Android platform . but I have a question
: why callback onClose  immediately when close network by myself on Android phone? do you have some special implements about network listener on Android platform？

**Comment by VayneKaso** [comment]
sorry ，my English is not very well .I mean is the library can auto to callback  webScoketclient's onClose() and its so immediately when close network by myself on Android phone

**Comment by marci4** [comment]
Hello @VayneKaso,

this is most likely due to the underlying network layer directly indicating a disconnect.
There is nothing special this lib does on android, especially since it is mainly targeting Java.

Greetings
marci4

**Comment by VayneKaso** [comment]
thanks for your reply

I want to know in this lib . there are some frameworks or operates that likely loop pull to check the network state?

**Comment by marci4** [comment]
Hello @VayneKaso,

no, we are relying on the `InputStream.read()` method.

Greetings
marci4

**Comment by zhangshaobo87** [comment]
@marci4 请问你解决了这个断网socket立马断开的问题了么

**Comment by zhangshaobo87** [comment]
@VayneKaso 请问你解决了断网socket立马断开的问题了吗
