### ISSUE TITLE
Web app server interoperability

### ISSUE THREAD

**Issue by ericjs** [TooTallNate/Java-WebSocket#629]
How does one specify an endpoint? All the examples I find seem to assume that all you specify is the port when creating a WebSocketServer, and the path is the root address of the server. Is the assumption that  it is not be not running under a web application server? (My aim was to use it in a webapp running under Tomcat.)

**Comment by marci4** [comment]
Hello @ericjs,

this project was not designed to run under a web application server.
I personally haven't used Tomcat so I would need your input for the required changes.

Greetings
marci4

**Comment by ericjs** [comment]
Hi marci4,
Thanks for the reply. If you wanted to make this usable in a web app server I'm not sure I'd be the best person to listen to, as I'm not sure what I want is what most other web app devs want. Your project appealed to me because it was simple and not a "framework" like Atmosphere, and I was hoping to do something minimal, without using annotations, or relying on any automagic mechanisms that I don't understand. 

I can tell you that the main thing I got hung up on in trying to use this was that in a webapp one would want to map some specific path under the webapp path as the path to get the socket connect. For example suppose the webapp ran at /myapp on port 80. Also I assume there would need to be some way to have the app container redirect to your code on the http call that establishes the socket connection, perhaps via a class extending HttpServlet that was apped in web.xml.

**Comment by marci4** [comment]
Hello @ericjs,

well, still you have more experience then I do right now! :)

Everything we do cannot break the current system. I cannot enforce some annotations or stuff like that.

I will keep this in mind and when I got more time on my hands I will take a look at this!

Greetings
marci4

**Comment by ericjs** [comment]
Ok. I've already moved on using the websocket support that comes built into Tomcat (after trying a few other  libraries) for my task at hand. But if you ever come back to it, feel free to ping me again, I'll be happy to offer ideas and maybe try it out.

**Comment by marci4** [comment]
Hello everyone, 
I feel this is not possible right now.

To my knowledge it is not possible without breaking everything.

If anyone has a good idea, feel free to reopen/comment.

Greetings
marci4
