### ISSUE TITLE
Support error codes 1012 (Service Restart), 1013 (Try Again Later) and 1014 (Bad Gateway)

### ISSUE THREAD

**Issue by ebourg** [TooTallNate/Java-WebSocket#639]
Hi,

Using Java-WebSocket 1.3.7 as a client I encountered an InvalidDataException "Trying to send an illegal close code!" when the server sends an 1013 error code (Try Again Later). Looking at the CloseFrame.java
 class it seems the error codes 1012, 1013 and 1014 are not supported yet and trigger an exception on the client side.

**Comment by marci4** [comment]
Hello @ebourg,

thank you for your issue!

These close frames are not part of the official RFC and were added later.
Could you tell me which endpoints use these close codes?

Greetings
marci4

**Comment by ebourg** [comment]
The [Java WebSocket API 1.1](https://github.com/javaee/websocket-spec/blob/master/api/client/src/main/java/javax/websocket/CloseReason.java) has the codes 1012 and 1013 which are implemented in application servers such as Tomcat or Jetty. The code 1014 is described on the [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent).

**Comment by marci4** [comment]
Hello @ebourg,

thank you very much for your feedback.

Do you think you could submit a PR for this?
Thank you!

Greetings
marci4

**Comment by ebourg** [comment]
Thank you for the fix!
