### ISSUE TITLE
WebsocketNotConnectedException on send method

### ISSUE THREAD

**Issue by MukiA** [TooTallNate/Java-WebSocket#642]
I'm trying to create a simple client that connects to a public echoserver based on the examples that you provided but I get the following exception

```
Exception in thread "main" org.java_websocket.exceptions.WebsocketNotConnectedException
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585)
	at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:207)
	at Main.main(Main.java:16)
opened connection
```
with the following code:
```
ExampleClient c = new ExampleClient( new URI( "ws://localhost:8887" ));
c.connect();
c.send("test");
```

Am I missing something that should be in the code in order to successfully send data? Connection seems to be working but sending data through it isn't.

**Comment by marci4** [comment]
Hello @MukiA,

thank you for opening this issue!

The "problem" is the method `connect()`. This is a non blocking method, which is starting the connection/handshake etc.

If you wanna send a frame right after connecting, please use the method `connectBlocking()`.
This method blocks the thread till the connection is established (or failed).

Greetings
marci4

**Comment by MukiA** [comment]
Awesome thanks for clearing that up for me.

**Comment by supunUOM** [comment]
awesome my error resolved thank you
