### ISSUE TITLE
Android Websocket Server listener 

### ISSUE THREAD

**Issue by lavancfc** [TooTallNate/Java-WebSocket#646]
## Expected Behavior
I am trying to implement a basic websocket server listener on android listening on a specific port for handshakes from multiple clients by which

- The client devices should initiate a handshake everytime the android websocket server is listening.
- Connection should be open as long as the server is  listening.
-Websocket Server should store the client address (socket address or IP or URI etc) when it receives a handshake. These stored client  will be used to communicate with individual clients on demand by the android user.
-Android Server should be able to send control data (text,hex,int etc) when required.
-Get the updated status message back from the devices

## Current Behavior
Websocket Server is working fine with one client device using broadcast method. Handshake happening data can be send and received to and from single client device.

My code
```java
public class WebSocketActivity extends AppCompatActivity {

    public static TextView output;
    public String[] port ;
    public static Collection<WebSocket> client;
    //public static WebSocket i = 0;

    @Override
    protected void onCreate (Bundle savedInstanceState) {
        super.onCreate ( savedInstanceState );
        setContentView (R.layout.activity_websocket);


        int conn = 0;
        String message;
        int port = 8887; // 843 flash policy port
        try {
            final WSocServer socket = new WSocServer(port);
            socket.start();
            System.out.println( "WebSocket Server started on port: " + socket.getPort() );
            output = findViewById(R.id.tv_output);
            final EditText inputText = findViewById(R.id.et_input);
            Button SendMessage =  findViewById(R.id.btn_login);
            SendMessage.setOnClickListener(new View.OnClickListener () {
                @Override
                public void onClick ( View v ) {
                    Toast . makeText ( getApplicationContext (), "Sending data " ,
                            Toast . LENGTH_LONG ). show ();
                    client = socket.connections();
                    System.out.println("connections" + client);
                    socket.broadcast(inputText.getText().toString(), client);
                }
            });

        }catch ( Exception ex ) {
        }

    }

    public static class WSocServer extends WebSocketServer {

        public WSocServer( int port ) throws UnknownHostException {
            super( new InetSocketAddress( port ) );
        }

        public WSocServer( InetSocketAddress address ) {
            super( address );
        }

        @Override
        public void onOpen(WebSocket conn, ClientHandshake handshake ) {
           // broadcast( "new connection: " + handshake.getResourceDescriptor() );
            System.out.println( conn.getRemoteSocketAddress().getAddress().getHostAddress() + " entered the room!" );
            //client = conn;
          

        }

        @Override
        public void onClose( WebSocket conn, int code, String reason, boolean remote ) {
            //broadcast( conn + " has left the room!" );
            System.out.println( conn + " has left the room!" );
           // output.append(conn +  " has left the room!" + "/n");
        }

        @Override
        public void onMessage( WebSocket conn, String message ) {
            //broadcast( message );
            System.out.println( conn + ": " + message );
            //output.append(message + "Data received is" + "/n");

        }
        @Override
        public void onMessage( WebSocket conn, ByteBuffer message ) {
            //broadcast( message.array() );
            System.out.println( conn + ": " + message );

        }


        public static void main(String[] args ) throws InterruptedException , IOException {
            WebSocketImpl.DEBUG = true;
            int port = 8887; // 843 flash policy port
            try {
                port = Integer.parseInt( args[ 0 ] );
            } catch ( Exception ex ) {
            }
        }
        @Override
        public void onError( WebSocket conn, Exception ex ) {
            ex.printStackTrace();
            if( conn != null ) {
                // some errors like port binding failed may not be assignable to a specific websocket
            }
        }

        @Override
        public void onStart() {
            System.out.println("Server started!");
        }

    }
}
```

## Context
What am I trying to accomplish? 

1.Websocket server listening
2.Client handshake
3.Handshake success
4.Store the clients URI
5.Keep the connection open as long as server aapp is running on mobile
6.Use the stored client URI to send data to each client devices independently.

**Comment by marci4** [comment]
Hello @lavancfc,

thank you very much for opening this issue!

I think you are looking for the method `WebSocket.send(<yourMessage>);` to send a message only to the specific connection. For example  you may wanna great a user when he connected to the server.
(This replaces the use of the broadcast method).
This method may look like:
```java
        @Override
        public void onOpen(WebSocket conn, ClientHandshake handshake ) {
                conn.send("Welcome to the server");
                System.out.println( conn.getRemoteSocketAddress().getAddress().getHostAddress() + " entered the room!" );
        }
```

I am not sure why you need the client URI, so you may wanna clear this up for me!

If you wanna save some client-specific data, you could also you the attachment feature described [here](https://github.com/TooTallNate/Java-WebSocket/wiki/Attaching-data).

Greetings
marci4

**Comment by lavancfc** [comment]
hi @marci4 Thanks for your input. 

I have an issue with setting a Host address for the Websocket address

**Current Behavior**
My client devices(websocket clients)  are connecting to the Websocket server by using a hardcoded websocket address such as 192.168.0.X:8888 inside the local network.

**Expected Behavior**
The client devices should be able to connect to the websocket server without using a IP+port address.
More like a DNS method by using a hostname or something like that which I dont mind hardcoding to the client device.
Is it possible to achieve this using this library

Thanks in advance

**Comment by marci4** [comment]
Hello @lavancfc,

webSocket.begin() is no API of this project...

Of course, we do support a different URI. See https://github.com/TooTallNate/Java-WebSocket/wiki#client-example

Greetings
marci4

**Comment by lavancfc** [comment]
webSocket.begin("192.168.0.12", 8877);

This is the client part which is using a different WS client API.
These client devices should be able to connect to the websocket server without using a IP+port address

**Comment by marci4** [comment]
Hello @lavancfc,

I see you opened a separate issue on https://github.com/Links2004/arduinoWebSockets .

Closing this issue then!

Greetings
marci4

**Comment by lavancfc** [comment]
I am trying to:
1. Add the clients to an Array list inside onOpen
2. Display it on a listview
3.On user click on the list view send message to that particular client.

The below code does the job.

`@Override
        public void onOpen(WebSocket conn, ClientHandshake handshake ) {

            // conn.setAttachment(index++); //Set the attachment to the current index
            // index++;
            ip.add(getRemoteSocketAddress(conn));
            wsclientList.add(conn);
            System.out.println(wsclientList.size());

            runOnUiThread(new Runnable() {
                @Override
                public void run() {


                    ArrayAdapter myadapter;
                    myadapter = new ArrayAdapter<InetSocketAddress>(AndroidListViewActivity.this,R.layout.list_item, R.id.label, ip);
                    ListView lv = getListView();
                    lv.setAdapter(myadapter);

                    lv.setOnItemClickListener(new OnItemClickListener() {
                        @Override
                        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

                            final int device=position;

                            AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(AndroidListViewActivity.this);
                            alertDialogBuilder.setMessage("1.Toggle the light using ON and OFF \n 2.Check Visually for reversed Banks. \n 3.Swap the Banks if necessary");
                            alertDialogBuilder.setPositiveButton("ON",new DialogInterface.OnClickListener() {
                                @Override
                                public void onClick(DialogInterface arg0, int arg1) {

                                    broadcastData[0] = 4;
                                    broadcastData[1] = (byte) 255;
                                    wsclientList.get(device).send(broadcastData);

                                    Toast.makeText(AndroidListViewActivity.this,"You clicked yes button",Toast.LENGTH_LONG).show();
                                }
                            });

                            alertDialogBuilder.setNegativeButton("OFF",new DialogInterface.OnClickListener() {
                                @Override
                                public void onClick(DialogInterface arg0, int arg1) {

                                    broadcastData[0] = 4;
                                    broadcastData[1]=(byte) 0;
                                    wsclientList.get(device).send(broadcastData);
                                    //Toast.makeText(AndroidListViewActivity.this,"You clicked NO button",Toast.LENGTH_LONG).show();
                                }
                            });
                            alertDialogBuilder.setNeutralButton("SWAP",new DialogInterface.OnClickListener() {
                                @Override
                                public void onClick(DialogInterface arg0, int arg1) {

                                    broadcastData[0] = (byte) 5;
                                    broadcastData[1] = (byte) 0;

                                    wsclientList.get(device).send(broadcastData);

                                   // Toast.makeText(AndroidListViewActivity.this,"Check the Light Banks,if found reversed press swap button",Toast.LENGTH_LONG).show();
                                }
                            });


                            AlertDialog alertDialog = alertDialogBuilder.create();
                            alertDialog.show();
                        }
                    });
                }

            });
        }
`

Scenario and Problems:
1. How do I access the array lists ip, wsclientList outside onOpen.
2. Is there a API specific method to generate a collection of active websocket clients connected to the server which can be used to display a table view containing client id, Inetaddress, port?
3.Please provide some usage examples of the methods onOpen,onWebsocketOpen.

**Comment by lavancfc** [comment]
Sorted out using this

`        @Override
        public void onOpen(WebSocket conn, ClientHandshake handshake ) {

            conn.setAttachment( index); //Set the attachment to the current index
            index++;
            seriallist.add(index);
            iplist.add(getRemoteSocketAddress(conn));
            wsobjectlist.add(conn);
            System.out.println(seriallist);

            final String[] maintitle = new String[iplist.size()];
            for (int i = 0; i<iplist.size(); i++) {
                maintitle[i] = String.valueOf(iplist.get(i));
            }
            final String[] subtitle = new String[wsobjectlist.size()];
            for (int k = 0; k<wsobjectlist.size(); k++) {
                subtitle[k] = String.valueOf(wsobjectlist.get(k));
            }
            final String[] serial = new String[seriallist.size()];
            for (int j = 0; j<seriallist.size(); j++) {
                serial[j] = String.valueOf(seriallist.get(j));
            }

            System.out.println(Arrays.toString(serial));
            System.out.println(Arrays.toString(maintitle));
            System.out.println(Arrays.toString(subtitle));

           final ListView list;
            list =findViewById(R.id.list);



            runOnUiThread(new Runnable() {
                @Override
                public void run() {


                    MyListAdapter adapter=new MyListAdapter(FactoryActivity.this,serial,maintitle,subtitle);
                    list.setAdapter(adapter);
                    list.setOnItemClickListener(new OnItemClickListener() {
                        @Override
                        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                            final int device=position;
                            AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(FactoryActivity.this);
                            alertDialogBuilder.setMessage("1.Toggle the light using ON and OFF \n 2.Check Visually for reversed Banks. \n 3.Swap the Banks if necessary");
                            alertDialogBuilder.setPositiveButton("ON",new DialogInterface.OnClickListener() {
                                @Override
                                public void onClick(DialogInterface arg0, int arg1) {
                                    broadcastData[0] = 4;
                                    broadcastData[1] = (byte) 255;
                                    wsobjectlist.get(device).send(broadcastData);
                                }
                            });
                            alertDialogBuilder.setNegativeButton("OFF",new DialogInterface.OnClickListener() {
                                @Override
                                public void onClick(DialogInterface arg0, int arg1) {
                                    broadcastData[0] = 4;
                                    broadcastData[1]=(byte) 0;
                                    wsobjectlist.get(device).send(broadcastData);
                                }
                            });
                            alertDialogBuilder.setNeutralButton("SWAP",new DialogInterface.OnClickListener() {
                                @Override
                                public void onClick(DialogInterface arg0, int arg1) {
                                    broadcastData[0] = (byte) 5;
                                    broadcastData[1] = (byte) 0;
                                    wsobjectlist.get(device).send(broadcastData);
                                }
                            });
                            AlertDialog alertDialog = alertDialogBuilder.create();
                            alertDialog.show();
                        }
                    });
                }

            });
        }`

**Comment by HiddenMana** [comment]
![image](https://user-images.githubusercontent.com/47727787/83618096-2d3ead00-a5b4-11ea-96e1-2b72a06be079.png)
I tried to follow you. But the WebSocket and WSocServer objects do not seem to exist. Someone help me please

**Comment by PhilipRoman** [comment]
You should add more information about your issue.

**Comment by HiddenMana** [comment]
> You should add more information about your issue. Please upload all of the code you have and post a link to it here.
> 
> I'm not sure how this is related to the original issue; consider creating a new issue about your problem with more details.

I use Websocket and WSocServer objects but it seems to be missing a library or some class. It tells the class to create
:(

**Comment by HiddenMana** [comment]
> You should add more information about your issue. Please upload all of the code you have and post a link to it here.
> 
> I'm not sure how this is related to the original issue; consider creating a new issue about your problem with more details.

My problem is simply declaring WSocServer. But it seems that the library is missing something. For example, Websocket needs implementation 'com.squareup.okhttp3: okhttp: 3.6.0'. I don't know what WSocServer needs

**Comment by HiddenMana** [comment]
> You should add more information about your issue. Please upload all of the code you have and post a link to it here.
> 
> I'm not sure how this is related to the original issue; consider creating a new issue about your problem with more details.
My code:
![image](https://user-images.githubusercontent.com/47727787/83711174-b86b8180-a64c-11ea-84d1-7057b061d5e4.png)
![image](https://user-images.githubusercontent.com/47727787/83711194-c4efda00-a64c-11ea-9e22-ce000aa53d88.png)
![image](https://user-images.githubusercontent.com/47727787/83711207-ce794200-a64c-11ea-9bcf-213bd69c2989.png)
![image](https://user-images.githubusercontent.com/47727787/83711232-da650400-a64c-11ea-8799-a0dbcadad526.png)
![image](https://user-images.githubusercontent.com/47727787/83711244-e2bd3f00-a64c-11ea-9b52-ae19cdef0f4a.png)

**Comment by PhilipRoman** [comment]
Try adding `import org.java_websocket.server.WebSocketServer` (you might have to remove the 'okhttp' imports because they use the same class name). If the IDE doesn't recognize it, that means that you're missing a library.

Since you're developing for Android, I'm assuming that you have a file called `build.gradle`. You should add this line:
```gradle
compile group: 'org.java-websocket', name: 'Java-WebSocket', version: '1.5.1'
```
in the "dependencies" block.

**Comment by HiddenMana** [comment]
> Try adding `import org.java_websocket.server.WebSocketServer` (you might have to remove the 'okhttp' imports because they use the same class name). If the IDE doesn't recognize it, that means that you're missing a library.
> 
> Since you're developing for Android, I'm assuming that you have a file called `build.gradle`. You should add this line:
> 
> ```groovy-gradle
> compile group: 'org.java-websocket', name: 'Java-WebSocket', version: '1.5.1'
> ```
> 
> in the "dependencies" block.

Perfect! That's it. 
I changed everything to use 'org.java_websocket'. But there are still 2 errors. It seems that WSocServer doesn't have **connections ()**.
And **WebSocketImpl.DEBUG = true;** as shown.
![image](https://user-images.githubusercontent.com/47727787/83729686-28403300-a672-11ea-895a-c3751d8173ee.png)
![image](https://user-images.githubusercontent.com/47727787/83729695-30986e00-a672-11ea-884a-85dcc551ae9e.png)

**Comment by PhilipRoman** [comment]
The `connections()` method should be `getConnections()`.

The `DEBUG` field has been removed. You probably don't need it, but the same effect can be achieved by setting log level to `TRACE`

**Comment by HiddenMana** [comment]
> The `connections()` method should be `getConnections()`.
> 
> The `DEBUG` field has been removed. You probably don't need it, but the same effect can be achieved by setting log level to `TRACE`

Thank you very much.
I am trying to connect the browser to the application. But when clicking on the Button, it only shows "Sending data". On the browser side also did not see any reaction? I have tested the Browser with another application and found a response. Can you help me
My code:
![image](https://user-images.githubusercontent.com/47727787/83734505-4a897f00-a679-11ea-8671-d352b4e09d9d.png)
![image](https://user-images.githubusercontent.com/47727787/83734537-570dd780-a679-11ea-8005-3c136abc0f69.png)
![image](https://user-images.githubusercontent.com/47727787/83734569-61c86c80-a679-11ea-8838-a4be00fd0309.png)
![image](https://user-images.githubusercontent.com/47727787/83734608-70af1f00-a679-11ea-8797-5a43b8724efe.png)
![image](https://user-images.githubusercontent.com/47727787/83734641-7d337780-a679-11ea-97f2-d24deab57bfe.png)

**Comment by PhilipRoman** [comment]
Note: it is a good idea to upload your code as text, instead of images.

Your code has a bug: you use `getConnections()` once, when there are no clients connected yet and it returns an empty list. When you pass it to `broadcast(...)`, it doesn't send the message to anyone because the given list is empty.

To fix this, remove the second parameter from broadcast, and the server will send the message to all clients that are currently connected. See the documentation for more information: https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.1/org/java_websocket/server/WebSocketServer.html#broadcast-java.lang.String-

**Comment by HiddenMana** [comment]
> Note: it is a good idea to upload your code as text, instead of images.
> 
> Your code has a bug: you use `getConnections()` once, when there are no clients connected yet and it returns an empty list. When you pass it to `broadcast(...)`, it doesn't send the message to anyone because the given list is empty.
> 
> To fix this, remove the second parameter from broadcast, and the server will send the message to all clients that are currently connected. See the documentation for more information: https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.1/org/java_websocket/server/WebSocketServer.html#broadcast-java.lang.String-

Thank you! I tried **broadcast(String text)** but App và Browser have not yet interacted with each other.
Mycode: 
```
public void onClick ( View v ) {
                    Toast . makeText ( getApplicationContext (), "Sending data " ,
                            Toast . LENGTH_LONG ). show ();
                    client = socket.getConnections();
                    //System.out.println("connections" + client);
                    Toast.makeText(MainActivity.this, "connections" + client, Toast.LENGTH_LONG);

                    socket.broadcast(inputText.getText().toString());
                }
```

**Comment by PhilipRoman** [comment]
You should open a separate issue about this. Make sure to fill in all the required information and, if possible, include all of your code (or upload it somewhere and post a link to it).
