### ISSUE TITLE
WebSocket run() cause NullPointerException

### ISSUE THREAD

**Issue by LuigiCerone** [TooTallNate/Java-WebSocket#648]
Hi,

I'm trying to use your WebSocket Server, and I've a problem while starting it.
I get the following exception: 
```
Exception in thread "WebsocketSelector18" java.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:257)
	at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:263)
	at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:539)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
My code is pretty similar to the one in the [Wiki](https://github.com/TooTallNate/Java-WebSocket/wiki) but I will post it for completeness:

```
import org.java_websocket.WebSocket;
import org.java_websocket.handshake.ClientHandshake;
import org.java_websocket.server.WebSocketServer;

import java.net.InetSocketAddress;
import java.util.HashSet;

public class webSocket extends WebSocketServer {
    private HashSet<WebSocket> allClients;
    private String serializedData = null;

    public webSocket() {
        super(new InetSocketAddress("localhost", 9091));
        allClients = new HashSet<WebSocket>();
        System.out.println("Constructor");
    }

    public void setData(String serializedData) {
        this.serializedData = serializedData;
    }

    public boolean isSomeoneConnected() {
        if (allClients.size() > 0)
            return true;
        else return false;
    }

    @Override
    public void onOpen(WebSocket client, ClientHandshake handshake) {
        System.out.println("Address: " + client.getRemoteSocketAddress().getAddress().getHostAddress());
        System.out.println("Port: " + client.getRemoteSocketAddress().getPort());
        allClients.add(client);
        sendJSONToNew(client);
    }

    // Called when a client disconnects.
    @Override
    public void onClose(WebSocket client, int code, String reason, boolean remote) {
            System.out.println("closed " + client.getRemoteSocketAddress() + " with exit code " + code + " additional info: " + reason);
            allClients.remove(client);
    }

    @Override
    public void onMessage(WebSocket conn, String message) {
        System.out.println("received message from " + conn.getRemoteSocketAddress() + ": " + message);
    }

    @Override
    public void onError(WebSocket conn, Exception ex) {
//        System.err.println("an error occured on connection " + conn.getRemoteSocketAddress() + ":" + ex.getMessage());
    }

    @Override
    public void onStart() {
        System.out.println("server started successfully");
    }

    // Update stats.
    public void sendJSONToAll() {
        for (WebSocket client : allClients)
            client.send(serializedData);
    }

    private void sendJSONToNew(WebSocket client) {
        client.send(serializedData);
    }

}
```

And the webSocket object is created in a thread with:
```
 // Start the webSocket in debug mode.
WebSocketImpl.DEBUG = true;
  if (webSocket == null) {
            webSocket = new webSocket();
            webSocket.start();
        }
```
This exception doesn't show up every time I launch the WebSocket, but the problem occurs sporadically and I can't understand why. Thanks.

## Your Environment
* Java version: 9.0.1
* Operating System and version: Debian 9.0

**Comment by liuliuabc** [comment]
mee too.Have you solved this problem?

**Comment by KristinaBrak** [comment]
Problem is still relevant. Anyone knows a solution?

**Comment by PhilipRoman** [comment]
What version of this library are you using? Can you post a minimal example that reproduces this problem?

**Comment by KristinaBrak** [comment]
I am using 1.5.1 version.
My SocketServerImp class extends WebSocketServer.
I run server creating thread.
`       SocketServer server = new SocketServerImp(new InetSocketAddress("localhost", 32100));
        Thread serverThread = new Thread(server);
        serverThread.start();`
I start server and after client is connected I terminate server leaving Javascript client running.
But when I try to run server again, almost every time I get this exception :
`m22o.argfile com.Main 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "WebSocketSelector-27" java.lang.NullPointerException
        at com.server.socket.SocketServerImp.onError(SocketServerImp.java:27)
        at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:649)
        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:542)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341)
        at java.base/java.lang.Thread.run(Thread.java:834)`
But when I terminate Javascript client first and then terminate server, I still sometimes get this error.
What could cause this issue?

**Comment by PhilipRoman** [comment]
The stack trace shows that the error is thrown from your code, specifically, line 27 of SocketServerImp.java. Can you post the code here?

**Comment by KristinaBrak** [comment]
`package com.server.socket;

import java.net.InetSocketAddress;

import com.server.messenger.*;

import org.java_websocket.WebSocket;
import org.java_websocket.handshake.ClientHandshake;
import org.java_websocket.server.WebSocketServer;

public class SocketServerImp extends WebSocketServer implements SocketServer {

    Messenger messenger;

    public SocketServerImp(InetSocketAddress address) {
        super(address);
    }

    @Override
    public void onClose(WebSocket conn, int code, String reason, boolean remote) {
        System.out.println(
                "closed " + conn.getRemoteSocketAddress() + " with exit code " + code + " additional info: " + reason);
    }

    @Override
    public void onError(WebSocket conn, Exception ex) {
        System.err.println("an error occurred on connection " + conn.getRemoteSocketAddress() + ":" + ex);
    }

    @Override
    public void onMessage(WebSocket conn, String message) {
        System.out.println("received message from client " + conn.getRemoteSocketAddress() + ": " + message);
        messenger.append(message);
    }

    @Override
    public void onOpen(WebSocket conn, ClientHandshake handshake) {
        // conn.send("Welcome to the server!"); // This method sends a message to the
        // new client
        System.out.println("new connection to " + conn.getRemoteSocketAddress());
        this.messenger = new MessengerWSImp(conn);
        
        messenger.send("welcome");
        messenger.send("welcome2");

    }

    @Override
    public void onStart() {
        System.out.println("server started successfully");
    }
    @Override
    public Messenger getMessenger() {
        return this.messenger;
    }
}
`
Error onError function.

**Comment by PhilipRoman** [comment]
It seems like your problem might be caused by parameter `conn` of method `onError` being null. You can get more information here: https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.1/org/java_websocket/server/WebSocketServer.html#onError-org.java_websocket.WebSocket-java.lang.Exception-
