### ISSUE TITLE
In version 1.3.7 WebSocketServer implementation not receive onOpen(WebSocket conn, ClientHandshake handshake) event 

### ISSUE THREAD

**Issue by Salat-Cx65** [TooTallNate/Java-WebSocket#653]
We have an Android project, that implements WebSocketServer.
After upgrade from 1.3.6 to 1.3.7, we faced an issue when the WS client not able to connect to our WebSocketServer implementation. After research, we found that method `onOpen(WebSocket conn, ClientHandshake handshake)` never called for new connections.

As a hotfix, we revert back to  1.3.6

**Comment by marci4** [comment]
Hello @Salat-Cx65, 

could you please use [this issue template](https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md) for a bug report?

I have tests in place, which should report such an issue, so this is new for me!

Greetings
marci4

**Comment by marci4** [comment]
Cannot reproduce in emulator using API level 26.

**Comment by marci4** [comment]
Any update?
