### ISSUE TITLE
onclose with code=1006 and no reason

### ISSUE THREAD

**Issue by molaith** [TooTallNate/Java-WebSocket#663]
## Expected Behavior

	onClose whith code 1006 should not happened frequently.
	or tell me the reason about current closure.

## Current Behavior
	1、create a websocket connection.
	2、repeated calls the method send().
	3、received OnError:javax.net.ssl.SSLException: Write error: ssl=0xdca46f00: I/O error during system call, Broken pipe
	4、received onClose:code=1006;reason="";remote=true

## Steps to Reproduce (for bugs)
1.this is my demo : https://drive.google.com/file/d/1HRt-v_xjk2GOnsjP_V90ai2A7XM4dITo/view?usp=sharing
2.install in android phone or emulator and run, the minSdkVersion is 19
3.click button
4.waiting utill error occured.

## Debug log (for bugs)

02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket D/AOSHUO_WEBSOCKET_API: sendByte!!!!!1;isclose:false;isclosing:false;isopen:true;isconnecting:false
02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket I/System.out: send frame: Framedata{ optcode:BINARY, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:320], payload:����
02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ������������������������������������������������������������	����������
02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ��������������������������������������������������������������	����	��������������������������������������������������������	����	����������������������
02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ������������
02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ��
02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ������������������������������������
02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ����������������������������������������������������}
02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket I/System.out: afterEnconding(320): {����
02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ������������������������������������������������������������	����������
02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ��������������������������������������������������������������	����	��������������������������������������������������������	����	����������������������
02-08 11:38:48.189 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ������������
02-08 11:38:48.190 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ��
02-08 11:38:48.190 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ������������������������������������
02-08 11:38:48.190 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ����������������������������������������������������}
02-08 11:38:48.190 5756-5756/com.aoshuotec.testforwebsocket I/System.out: write(328): {��@'��0��-��"��*���B��B��B��B��B��B��B��B��B��B�'��)��&��%��-��%���B��B��B��B��B��B	��B��B�$��'��#��%�� ��.��.��$���B��B��B��B��B�"���B��B��B��B��B�!��.��.�� ���B�%���B�,��4��/��/��-��/���B�%��#���B��B�+��(��-��(��(��=��3��&���B��B��B��B��B��B��B�}
02-08 11:38:48.190 5756-5756/com.aoshuotec.testforwebsocket D/AOSHUO_WEBSOCKET_API: sendByte!!!!!1;isclose:false;isclosing:false;isopen:true;isconnecting:false
02-08 11:38:48.190 5756-5756/com.aoshuotec.testforwebsocket I/System.out: send frame: Framedata{ optcode:BINARY, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:320], payload:��������������������������������������������������������������������������������������������������������������������	��
02-08 11:38:48.190 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ��������������
02-08 11:38:48.190 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ��
02-08 11:38:48.190 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ����������������������������������������������������������������������������������	����������������������������������������������	������"����!����������&������������������������������������������}
02-08 11:38:48.190 5756-5802/com.aoshuotec.testforwebsocket D/AOSHUO_WEBSOCKET_API: onError:javax.net.ssl.SSLException: Write error: ssl=0xde11bb40: I/O error during system call, Broken pipe
02-08 11:38:48.190 5756-5756/com.aoshuotec.testforwebsocket I/System.out: afterEnconding(320): {��������������������������������������������������������������������������������������������������������������������	��
02-08 11:38:48.190 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ��������������
02-08 11:38:48.191 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ��
02-08 11:38:48.191 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ����������������������������������������������������������������������������������	����������������������������������������������	������"����!����������&�������������������������������������������}
02-08 11:38:48.191 5756-5756/com.aoshuotec.testforwebsocket I/System.out: write(328): {��@�P��PQ�J���P�PK�O�X� V�_�]���P��P��P��P��P��P��A���K�H�Z�W�G���G�C���P��P�P��P��P��P��P��P��P��@�	J�	E�E�F�M�U�!\� f�W�S�@���P��P��P��P��P��P��P��PG�F���PE�J���D���P@���P��P��P��P��P��P��P��P��P��P��P��PO�Z�\�g�%^�_�}
02-08 11:38:48.191 5756-5756/com.aoshuotec.testforwebsocket D/AOSHUO_WEBSOCKET_API: sendByte!!!!!0;isclose:false;isclosing:false;isopen:true;isconnecting:false
02-08 11:38:48.191 5756-5756/com.aoshuotec.testforwebsocket D/AOSHUO_WEBSOCKET_API: {"debug":"1"}
02-08 11:38:48.192 5756-5756/com.aoshuotec.testforwebsocket I/System.out: send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:13], payload:{"debug":"1"}}
02-08 11:38:48.192 5756-5756/com.aoshuotec.testforwebsocket I/System.out: afterEnconding(13): {{"debug":"1"}}
02-08 11:38:48.192 5756-5756/com.aoshuotec.testforwebsocket I/System.out: write(19): {���!wZ�?�Tx�Fx�}
02-08 11:38:48.192 5756-5756/com.aoshuotec.testforwebsocket I/System.out: send frame: Framedata{ optcode:BINARY, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:320], payload:��������������������������������������	����������������������������������������������������
02-08 11:38:48.192 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ����������������
02-08 11:38:48.192 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ����"������������������������������������������������������������������������������������	����
02-08 11:38:48.192 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ��������������������������������������������������������������������������������������������������������������������������}
02-08 11:38:48.192 5756-5756/com.aoshuotec.testforwebsocket I/System.out: afterEnconding(320): {��������������������������������������	����������������������������������������������������
02-08 11:38:48.192 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ����������������
02-08 11:38:48.192 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ����"������������������������������������������������������������������������������������	����
02-08 11:38:48.192 5756-5756/com.aoshuotec.testforwebsocket I/System.out: ��������������������������������������������������������������������������������������������������������������������������}
02-08 11:38:48.193 5756-5756/com.aoshuotec.testforwebsocket I/System.out: write(328): {��@����W]g�WEg�W@g�WIg�WGg�WBg�WJg�W���WNg�������������Og�WMg�WIg�Lg�Cg�WHg�W������������WOg�������������������Gg�WDg�WSg�WSg�W\g�WRg�W\g�WVg�W[g�W^g�WGg�WNg���������������������������������Ng�WOg�W���WAg����WAg�WLg�WIg�Hg����������������������Ng�W\g�Whg�Wgg�W`g�WPg�WYg�WRg�W_g�W_g�W_g�WFg}
02-08 11:38:48.193 5756-5756/com.aoshuotec.testforwebsocket D/AOSHUO_WEBSOCKET_API: sendByte!!!!!1;isclose:false;isclosing:true;isopen:false;isconnecting:false
02-08 11:38:48.193 5756-5756/com.aoshuotec.testforwebsocket D/AOSHUO_WEBSOCKET_API: WebsocketNotConnectedException:org.java_websocket.exceptions.WebsocketNotConnectedException
02-08 11:38:48.193 5756-5802/com.aoshuotec.testforwebsocket I/System.out: Connection lost timer stopped
02-08 11:38:48.194 5756-5802/com.aoshuotec.testforwebsocket D/AOSHUO_WEBSOCKET_API: onClose:1006;;true
02-08 11:38:48.198 5756-5756/com.aoshuotec.testforwebsocket E/EventBus: Could not dispatch event: class com.aoshuotec.testforwebsocket.ASREvent to subscribing class class com.aoshuotec.testforwebsocket.MainActivity
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.java_websocket.client.WebSocketClient.isClosed()' on a null object reference
                                                                            at com.aoshuotec.ascloudapi.websocket.ASROnline.sendByte(ASROnline.java:407)
                                                                            at com.aoshuotec.testforwebsocket.AoshuoASRManager.sendByte(AoshuoASRManager.java:91)
                                                                            at com.aoshuotec.testforwebsocket.MainActivity.startReadPcm(MainActivity.java:54)
                                                                            at com.aoshuotec.testforwebsocket.MainActivity.handleASRMessage(MainActivity.java:107)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                            at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
                                                                            at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:163)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6321)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
02-08 11:38:48.198 5756-5756/com.aoshuotec.testforwebsocket D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.SubscriberExceptionEvent
02-08 11:38:48.202 5756-5797/com.aoshuotec.testforwebsocket D/AOSHUO_WEBSOCKET_API: onError:java.lang.NullPointerException: Attempt to invoke interface method 'void com.aoshuotec.ascloudapi.websocket.ISocketConnectionListener.onMissionStart(java.lang.String)' on a null object reference
02-08 11:49:07.669 5756-5756/com.aoshuotec.testforwebsocket D/WAKEUP_JNI: Java_com_aoshuotec_voiceengine_OpusEncoder_destroy: Entry!
02-08 11:49:07.669 5756-5756/com.aoshuotec.testforwebsocket D/WAKEUP_JNI: Opus encoder get Java handle is Empty!

## Your Environment

* Version used:1.3.7
* Java version:1.8.0_144
* Operating System and version:android 7.0
* Endpoint Name and version:
* Link to your project:

**Comment by marci4** [comment]
Hello @molaith,

please use [this issue template](https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md) to help me understand the issue at hand.

This is the definition for close code 1006.
`1006 is a reserved value and MUST NOT be set as a status code in a Close control frame by an endpoint. It is designated for use in applications expecting a status code to indicate that the connection was closed abnormally, e.g. without sending or receiving a Close control frame.`

Greetings
marci4

**Comment by marci4** [comment]
Hello @molaith,

thank you for the updated issue!

I was not able to install your example apk in my emulator...
Never the less the exception you are describing is the cause for the disconnect and the resulting close with closecode 1006.

After a quick search on google, it is most likely related to the websocket server you are connecting to.

Could you give me a bit more insight on what you are using as your backend?

Greetings
marci4

**Comment by molaith** [comment]
hi，@marci4 ,
 i disabled SSL authentication in websocket server.
then，there is no SSLException. but it still disconnect with 1006.

there is the log below:
[onclose_1006.txt](https://github.com/TooTallNate/Java-WebSocket/files/1750776/onclose_1006.txt)

**Comment by oakkitten** [comment]
on android, the problem might be with the ping/pong mechanism of the library. android will freeze the application while it's idle, waking it up only from time to time. therefore you can't rely on `Timer`s to ping/pong, and `Timer` is what this library is using by default. you can do `setConnectionLostTimeout(0)` and implement your own pinging mechanism using `AlarmManager`

run the library in debug mode (set `WebSocketImpl.DEBUG` to `true`) to verify that you are getting 1006 because of this

**Comment by marci4** [comment]
Hello @oakkitten and @molaith ,

@molaith 
Please tell me more on what you are using as your websocket server you are connecting to!
Apart from this, you should also try the recommended setting by @oakkitten. 
This may be a problem since the other endpoint does not correctly implement the specification!

@oakkitten 
well it depends on how you use the library. If you use it in a service, it should still work fine!
I never developed any android app, so this may be not be correct but this is the best I understand it from the outside.

Greetings
marci4

**Comment by oakkitten** [comment]
@marci4 according to this [code](https://github.com/TooTallNate/Java-WebSocket/blob/02607c29d316df0fd5f43b64d3a1e5c4a26f1c80/src/main/java/org/java_websocket/AbstractWebSocket.java#L147), a timer that runs every 60 seconds will check for a pong event that is not older than 90 seconds. now if the threads are frozen for more than 30 seconds, the time between two calls can be more than 90 seconds according to the wall clock time, while the thread assumes it only slept 60 seconds. boom, abnormal close. you could perhaps use thread time instead of wall clock time (`time = 0; sleep(60 seconds); time += 60;`, but this sounds like a bad idea and doesn't help in detecting actual timeouts as the system can sleep for many minutes. this isn't a problem with the library but the system; perhaps there should be a note in the documentation somewhere

**Comment by marci4** [comment]
Hello @oakkitten,

I do see the problem and I think just implementing the WebSocketClient as a service should solve it.
When I got more time on my hands I wanna implement a service on my own to prove this and give the Android users a few tips on how to do it the right way.

Apart from this I opened a separate issue to include some more information in the onClose call to help users understand the issue at hand!

By the way I am really thankful for your continuous input :) 

Greetings
marci4

**Comment by molaith** [comment]
hi, @oakkitten,@marci4,
Thanks!
I implement pinging mechanism, and problem solved.

**Comment by marci4** [comment]
Problem solved. Closing issue!

**Comment by QiaoYang0923** [comment]
How did you solve it
