### ISSUE TITLE
android ssl via proxy

### ISSUE THREAD

**Issue by gjsbe** [TooTallNate/Java-WebSocket#672]
Hi,
I would like to know if it's possibile to use api to connect using ssl and behind a proxy.
Also If there's an option to pass proxy username and password.
Thank you very much

**Comment by marci4** [comment]
Hello @gjsbe,

maybe this helps you.
https://github.com/TooTallNate/Java-WebSocket/wiki/Using-the-WebSocket-through-a-http-proxy

Greetings
marci4

**Comment by gjsbe** [comment]
Hi,
thank you very much, but there's another problem: if I have a proxy pac url how can I use it?

**Comment by gjsbe** [comment]
Sorry... I found a solution but I have a big problem... It don't work:
`          SSLContext sslContext = SSLContext.getDefault();
                SSLSocketFactory sslFactory = sslContext.getSocketFactory();

                List<Proxy> proxies = ProxySelector.getDefault().select(new URI("wss://server.it:3333"));
                Proxy proxy;

                if(!proxies.isEmpty()) {

                    if(!proxies.get(0).type().equals(Proxy.Type.DIRECT)) {
                        proxy = proxies.get(0);
                    } else {
                        proxy = null;
                    }

                } else {
                    proxy = null;
                }

                if(proxy != null) {
                    Socket proxySocket = new Socket(proxy);
                    proxySocket.connect(new InetSocketAddress(host, port));
                    ws.setSocket(sslFactory.createSocket(proxySocket, host, port, true));
                } else {
                    ws.setSocket(sslFactory.createSocket());
                }`

select method of proxyselector returns DIRECT for wss and ws protocols.
If I use https uri inside proxyselector select method it returns me HTTP Type Proxy, but when I use it inside proxy Socket it gives me Invalid proxy, because Android works only with SOCKS proxy (for sockets).

**Comment by gjsbe** [comment]
Hi, the problem is that from latest android sdk version you cannot set http proxy for a Socket.
You need SOCKS Proxy, but for the ws we need http proxy connection.
So I writed my own proxy connection method (native).
Thank you anyway.

**Comment by marci4** [comment]
Hello @gjsbe,

Do you think you can share your solution to help other developers in the future?
Thank you!


Greetings
marci4

**Comment by gjsbe** [comment]
Sure:
`socket.connect(new InetSocketAddress(proxy.getHost(), proxy.getPort()));
socket.setKeepAlive(true);
socket.setTcpNoDelay(true);
socket.setReceiveBufferSize(8192);

String msg = "CONNECT " + dest.getHost() + ":" + dest.getPort() + " HTTP/1.0\r\n";

msg += "User-Agent: ProtoPro/2.0\r\n" +
                "Keep-Alive: 300\r\n" +
                "Proxy-Connection: keep-alive\r\n\r\n";

byte[] outData = msg.getBytes("ASCII");
socket.getOutputStream().write(outData);
socket.getOutputStream().flush();
int readed;

ByteArrayOutputStream responseStream = new ByteArrayOutputStream();
byte[] readBytes = new byte[8192];

while((readed = socket.getInputStream().read(readBytes)) > 0) {
               responseStream.write(readBytes, 0, readed);

                if(socket.getInputStream().available() == 0) {
                    break;
                }
}

String response = new String(responseStream.toByteArray(), "ASCII");

if(response.matches("^HTTP/[0-9]\\.[0-9] 407 .*(\r\n\r\n)?")) {
                socket.close();
                socket = null;
} else if(!response.matches("^HTTP/[0-9]\\.[0-9] 200 .*(\r\n\r\n)?")) {
                socket.close();
                socket = null;
}

`

then you can use proxy socket inside sslSocketFactory... 
There are some things that I don't like, for example the while with available() if... is not a good implementation in some case.
bye

**Comment by marci4** [comment]
It is a starting point for many! :)
Thank you!

Issue solved. Closing it!

Greetings
marci4
