### ISSUE TITLE
websocket server not response 

### ISSUE THREAD

**Issue by xmulxs** [TooTallNate/Java-WebSocket#673]
websocket server not response ,details describe in Steps to Reproduce, Any suggestions are welcome!
 
## Steps to Reproduce (for bugs)

1.
  I define a class  named websocketServer extended from WebSocketServer. 
in websocketServer I overide onOpen method as belows:
   @Override
    public void onOpen(WebSocket conn, ClientHandshake clientHandshake) {
                  sleep(4100);// 4.1seconds
                  conn.close();
    }
2. I new websocketServer(36669),and call start method;
3.In client,I send a websocket connection to server.
4.About 20% probability can not connect if sleep 4.1 seconds in onOpen, if sleep 200 seconds in onOpen， the next client 100% probability can not connect .
5.webserversocket version is java-websocket-1.3.7.jar

## Debug log (for bugs)

In server shell console,I find message as below:
shell@N10:/ $ netstat -tunlp | grep 36669
tcp6       2      0 :::36669               :::*                   LISTEN
tcp6     533      0 ::ffff:192.168.82.222:36669 ::ffff:192.168.74.191:50736 CLOSE_WAIT
tcp6       7      0 ::ffff:192.168.82.222:36669 ::ffff:192.168.82.163:44200 CLOSE_WAIT
tcp6     533      0 ::ffff:192.168.82.222:36669 ::ffff:192.168.74.191:51189 CLOSE_WAIT
tcp6       7      0 ::ffff:192.168.82.222:36669 ::ffff:192.168.82.163:43207 CLOSE_WAIT
tcp6       7      0 ::ffff:192.168.82.222:36669 ::ffff:192.168.82.163:43106 CLOSE_WAIT

## Your Environment

* Version used:
* Java version:
* Operating System and version:Android 5.1.1
* Endpoint Name and version:
* Link to your project:

**Comment by marci4** [comment]
Hello @xmulxs,

Please use the latest version 1.3.7!

Greetings
marci4

**Comment by xmulxs** [comment]
Hi,marci4,
    I test the issue with 1.3.7, and all is ok. but I  find a function named getMacFromIp may blocks callback onOpen as below:
@Override
    public void onOpen(WebSocket conn, ClientHandshake clientHandshake) {
       sleep(4100);// 4.1seconds
       getMacFromIp(szIp);
        conn.close();
} 
  When testing with 1.3.7,I make function getmacFromIp in "Not block". So The testing may not explain any problem.
  I think when getMacFromIp  blocks, It  cause the CLOSE_WAIT phenomenon. What I want to kown is  whether onOpen function blocks cause connect failure?

**Comment by xmulxs** [comment]
Hi,marci4,I think I find the problem, The  reason is " onOpen callback block for a long time cause the connection failure". When I sleep for 100 seconds in onOpen the next client indeed can't connect to server.

**Comment by xmulxs** [comment]
version 1.3.7 has the same problem, if sleep 200 seconds in onOpen， the next client 100% probability can not connect .

**Comment by marci4** [comment]
Is there any reason why you wanna sleep the connection?
Maybe use a separate timer for this?

Greetings
marci4

**Comment by xmulxs** [comment]
Hi,maric4 Thank you for your answer， Now I just new a thread in onOpen function  for doing blocking things  instead of  directly sleeping in onOpen that may block onOpen.
