### ISSUE TITLE
extends WebSocketServer VS Annotation

### ISSUE THREAD

**Issue by b3601993** [TooTallNate/Java-WebSocket#674]
extends WebSocketServer VS Annotation ？

This is my understanding: Annotation, it is not necessary to have a container, eg: tomcat, But extends WebSocketServer can not use tomcat。

Forgive me for being a rookie, in websocket, use Annotation Can not use container?

**Comment by marci4** [comment]
Hello @b3601993,

to my knowledge it is possible to use this library in a tomcat environment.
Some users reported that at least.

Greetings
marci4

**Comment by marci4** [comment]
Dead issue.

Closing!
Greetings
marci4
