### ISSUE TITLE
Connect error

### ISSUE THREAD

**Issue by bluekey630** [TooTallNate/Java-WebSocket#679]
I got exception like as "SSL handshake aborted: ssl=0x7829ac28: I/O error during system call, Connection reset by peer". So app can not connect to wss server. 
I using "org.java-websocket:Java-WebSocket:1.3.8" and tested Sumsung device.
Please let me know the way to solve this issue

**Comment by marci4** [comment]
Hello @bluekey630,

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md.

Without a full bug report this will be closed.

Greetings
marci4

**Comment by marci4** [comment]
Dead issue.

Closing it!

Greetings
marci4
