### ISSUE TITLE
Defining Port Configuration to be used by websocket

### ISSUE THREAD

**Issue by Patel32515** [TooTallNate/Java-WebSocket#680]
I am trying to start a websocket server within my already running web application on Tomcat7.
Application is running on port 8080 which is defined through  tomcat connector settings where as websocket is defined over 8088 port. (which is defined using constructor).

Problem:
How can I control max number of connection to the websocket? in tomcat server.xml, there is connector configuration for 8080 port but  if i am trying to defined configuration for 8080, it gives port already in use error when Websocket server is started.

If i dont limit websocket connections, its limiting my webpage user sessions. Please suggest a way to set limit of number of websocket connections.

**Comment by marci4** [comment]
Hello @Patel32515,

right now the lib does not directly have a connection limit.
You can however use the method `onWebsocketHandshakeReceivedAsServer()`, check for the limit and throw an InvalidDataException() if to many connections were made.

Check out [this](https://github.com/TooTallNate/Java-WebSocket/wiki/Rejecting-a-handshake) wiki article for more information.

Greetings
marci4

**Comment by Patel32515** [comment]
Hello @marci4 ,
Thanks for the suggestion, yes this could help.
Wondering if there is any option to make port configurable in server.xml as Connector port?

Thanks,
Priyank

**Comment by marci4** [comment]
Hello Priyank,

due to the reason that this lib does not require tomcat, we do not evaluate the server.xml.
To set the port, you have to call the WebSocketServer with a different constructor.

Greetings
marci4

**Comment by Patel32515** [comment]
No problem, will adapt my implementation accordingly, Thanks for the response..
