### ISSUE TITLE
Exclude default port from wss host

### ISSUE THREAD

**Issue by xcelder** [TooTallNate/Java-WebSocket#685]
I'm working with a server balanced by a proxy that redirect my request to the targeted server depends on the URL I requested.

One of these servers has a secure Websocket (I mean wss) and it works on the default port (443).

In your client (class WebSocketClient.java) you avoid to include the port in the host by: `port != WebSocket.DEFAULT_PORT ? ":" + port : ""`, but this works only for ws default port and not for wss that now is including ":443" at the end of the host. In my app, for example I want to connect to "wss://app.example.com" and without this check it's trying to connect to "wss://app.example.com:443" and the proxy cannot resolve this host.

## Possible Solution
Adding a check for DEFAULT_WSS_PORT as well as the check for DEFAULT_PORT it solves the problem.
```java
String host = uri.getHost() + ( 
			(port != WebSocket.DEFAULT_PORT && port != WbSocket.DEFAULT_WSS_PORT)
			? ":" + port : "" );
```

**Comment by marci4** [comment]
Hello @xcelder,

thanks for opening this issue!

Is this proxy available for testing? 

Greetings
marci4

**Comment by xcelder** [comment]
Unfortunately not, is a private server in the company 
I work on, but we've check the logs and the problem was that. Sorry if I cannot provide more clues... :(

**Comment by marci4** [comment]
Hello @xcelder,

thanks for the feedback.
No worries, I just like to check and make sure the changes really fix the issue ;) 

Anyway, after you fix the typo I found in your PR, I am really happy to merch it!

Greetings
marci4

**Comment by xcelder** [comment]
I fixed the typo, sorry I wrote it in the github editor and I didn't saw it.

**Comment by marci4** [comment]
No problem!

Thank you a lot for your changes!

Greetings
marci4

**Comment by xcelder** [comment]
thank you for answering so fast! 👍
