### ISSUE TITLE
 onMessage method perform time-consuming operations

### ISSUE THREAD

**Issue by ykbjson** [TooTallNate/Java-WebSocket#688]
In the onMessage method, if a blocking operation is performed, all subsequent requests will not enter the onMessage method. Do I have to reopen threads in the onMessage method to perform time-consuming operations?

` @Override
    public void onMessage(WebSocket webSocket, String message) {
        parseMessage(webSocket, message);
        System.out.println(webSocket + " : " + message);
    }

    @Override
    public void onError(WebSocket webSocket, Exception ex) {
        ex.printStackTrace();
        if (webSocket != null) {
            // some errors like port binding failed may not be assignable to a specific websocket
        }
    }

    @Override
    public void onStart() {
        System.out.println("the pokemon block chain server start");
    }

    private void parseMessage(WebSocket webSocket, String message) {
        JSONObject jsonObject = JSONObject.parseObject(message);
        if (null == jsonObject) {
            webSocket.send(JSONObject.toJSON("message error").toString());
            return;
        }
        switch (jsonObject.getString("type")) {
            case "ADD_BLOCK":
                blockService.save((Block) JSONObject.parse(jsonObject.getJSONObject("body").toString()));
                webSocket.send(JSONObject.toJSON("ADD_BLOCK success").toString());
                break;
            case "MINING_BLOCK":
                blockChain.minePendingTransactions(jsonObject.getJSONObject("body").getString("address"));
                webSocket.send("MINING_BLOCK success");
                break;

            case "BALANCE_OF_ADDRESS":
                float balance=blockChain.balanceOfAddress(jsonObject.getJSONObject("body").getString("address"));
                webSocket.send("BALANCE_OF_ADDRESS success,balance is : "+balance);
                break;

        }
    }`

`  public void minePendingTransactions(String address) {
        synchronized (chain) {
            final Block block = new Block(System.currentTimeMillis(), pendingTransactions);
            block.digBlock(difficulty);
            chain.addLast(block);
            synchronized (pendingTransactions) {
                pendingTransactions.clear();
                createTransaction(new Transaction("", address, miningReward));
            }
        }
    }`
`  public void digBlock(int difficulty) {
        final StringBuffer hashPreChar = new StringBuffer();
        for (int i = 0; i < difficulty; i++) {
            hashPreChar.append("0");
        }
        while (!StringUtils.pathEquals(hash.substring(0, difficulty)
                , hashPreChar.toString())) {
            nonce++;
            hash = calculateHash();
        }
        System.out.println("digBlock : " + hash);
    }`

onMessage->parseMessage->blockChain.minePendingTransactions->digBlock.

**Comment by marci4** [comment]
Hello @ykbjson,

that is intentional to make sure that you don't  have to manually synchronize messages.

If you however know that you have a non critical long running task to do, it is always the best to use an executor for such tasks!

Greetings
marci4

**Comment by marci4** [comment]
Hello @ykbjson,
is this issue solved for you?

**Comment by marci4** [comment]
No feedback. Closing issue!
