### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by Animaleante** [TooTallNate/Java-WebSocket#689]
I'm using the lib with a SSL cert, and it works nicely, but at least once a week I'm getting this error, and the whole WS Server crashes.

## Expected Behavior
No errors given, specially an error that crashes the whole server.

## Current Behavior
Don't know if this happens on a new connection, or on a message that the server receives.
But when it does, no other connection can be made, and current conenctions are not terminated, but don't work anymore. And the thread running the server is not interrupted.

## Steps to Reproduce (for bugs)
Don't know how to reproduce, it seems to happen at random.

## Debug log (for bugs)
I only have this stack trace as a log:
java.lang.IllegalArgumentException
    at java.nio.Buffer.position(Buffer.java:244)
    at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:343)
    at sun.nio.ch.IOUtil.write(IOUtil.java:60)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
    at org.java_websocket.SSLSocketChannel2.write(SSLSocketChannel2.java:243)
    at org.java_websocket.SocketChannelIOHelper.batch(SocketChannelIOHelper.java:87)
    at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:412)
    at java.lang.Thread.run(Thread.java:745)

## Your Environment
* Version used: 1.3.5
* Java version: 1.8.0_60
* Operating System and version: CentOS release 6.7 (Final)

**Comment by marci4** [comment]
Hello @Animaleante,

could you please update to the latest version 1.3.8 and see if this solves the issue?

Greetings
marci4

**Comment by Animaleante** [comment]
Hey there @marci4 
Will try that now, had not seen that a new version was released. Gonna test it for the rest of the week, and update you here if anything comes up. Thanks!

**Comment by Animaleante** [comment]
The error happened yesterday again, and I'm using the latest version now. Any ideas on how to better debug this?

**Comment by marci4** [comment]
Hello @Animaleante,

could you maybe enable the debug printouts with `WebSocketImpl.Debug = true;` and then post the log here? 

Greetings
marci4

**Comment by Animaleante** [comment]
All right @marci4, I will turn it on and will update here if it happens again and post the log. Thank you

**Comment by Animaleante** [comment]
This is 250 lines of log right before the moment that the error happened. It seems to happen always after there's a huge amount of clientes connecting and disconnecting rapidly (After around 9000 connections since the server started).

> open using draft: Draft_6455 extension: DefaultExtension
INFO server comment - CHTWSServer::onOpen >> instanceName: null, userId: -1, remoteSocketAddress: /190.123.207.20:20783, userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
process(21): {��*���B���^���^���_��}
afterDecoding(15): {heartbeatResult}
process(21): {��_5L�7P-�+W)�+g)�*Y8}
afterDecoding(15): {heartbeatResult}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:15], payload:heartbeatResult}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:15], payload:heartbeatResult}
INFO server comment - CHTWSServer::onOpen >> Application with instanceName: null doesn't exist.
process(21): {�����޴y�³}�}�ýl}
afterDecoding(15): {heartbeatResult}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:15], payload:heartbeatResult}
process(21): {��ԎM���,Ϡ�(ܠ�(Ρ�9}
afterDecoding(15): {heartbeatResult}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:15], payload:heartbeatResult}
process(21): {��2+��ZN��FI��Fy��GG�}
afterDecoding(15): {heartbeatResult}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:15], payload:heartbeatResult}
process(604): {GET /1352d0a0378e409aae43d0c9b94d2364/-1 HTTP/1.1
Host: streaming8.campremium.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: http://aovivo.camerahot.com
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: Cosj0P+B7aT/Th2poIJQxw==
DNT: 1
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
}
write(224): {HTTP/1.1 101 Web Socket Protocol Handshake
Connection: keep-alive, Upgrade
Date: Wed, 04 Apr 2018 19:09:45 GMT
Sec-WebSocket-Accept: vJhiizk8lybx3pl+v7PaWBbgldE=
Server: TooTallNate Java-WebSocket
Upgrade: websocket
}
open using draft: Draft_6455 extension: DefaultExtension
INFO server comment - CHTWSServer::onOpen >> instanceName: null, userId: -1, remoteSocketAddress: /179.113.26.65:50620, userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0
INFO server comment - CHTWSServer::onOpen >> Application with instanceName: null doesn't exist.
send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:22], payload:{"action":"heartbeat"}}
afterEnconding(22): {{"action":"heartbeat"}}
write(24): {�{"action":"heartbeat"}}
send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:22], payload:{"action":"heartbeat"}}
afterEnconding(22): {{"action":"heartbeat"}}
write(24): {�{"action":"heartbeat"}}
send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:22], payload:{"action":"heartbeat"}}
afterEnconding(22): {{"action":"heartbeat"}}
write(24): {�{"action":"heartbeat"}}
INFO stream play hlsStream -
send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:22], payload:{"action":"heartbeat"}}
afterEnconding(22): {{"action":"heartbeat"}}
write(24): {�{"action":"heartbeat"}}
process(599): {GET /1352d0a0378e409aae43d0c9b94d2364/-1 HTTP/1.1
Host: streaming8.campremium.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: http://aovivo.camerahot.com
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: MVu7Wh3EEvT7eNFbIiddhA==
DNT: 1
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
}
write(224): {HTTP/1.1 101 Web Socket Protocol Handshake
Connection: keep-alive, Upgrade
Date: Wed, 04 Apr 2018 19:09:45 GMT
Sec-WebSocket-Accept: OCkIj1dCZ7JBcwR+iysK92WCjb0=
Server: TooTallNate Java-WebSocket
Upgrade: websocket
}
open using draft: Draft_6455 extension: DefaultExtension
INFO server comment - CHTWSServer::onOpen >> instanceName: null, userId: -1, remoteSocketAddress: /179.208.247.211:51165, userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
INFO server comment - CHTWSServer::onOpen >> Application with instanceName: null doesn't exist.
send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:22], payload:{"action":"heartbeat"}}
afterEnconding(22): {{"action":"heartbeat"}}
write(24): {�{"action":"heartbeat"}}
process(21): {����'��cU��gF��gT��v}
afterDecoding(15): {heartbeatResult}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:15], payload:heartbeatResult}
send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:22], payload:{"action":"heartbeat"}}
afterEnconding(22): {{"action":"heartbeat"}}
write(24): {�{"action":"heartbeat"}}
INFO cupertino connect 1820616074 -
INFO stream create hlsStream -
INFO server comment - [32m 1360163 - CameraHotController::onHTTPCupertinoStreamingSessionCreate >> URI: camerahot_chat/1360163/hlsStream/playlist.m3u8?userid=-493, ipAddressClient: 177.7.126.139, queryStr: userid=-493, userAgent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
INFO server comment - [32m 1360163 - CameraHotController::onHTTPCupertinoStreamingSessionCreate >> HTTP Session accepted for userId: -493
send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:33], payload:{"action":"mobileVideoRequested"}}
afterEnconding(33): {{"action":"mobileVideoRequested"}}
write(35): {�!{"action":"mobileVideoRequested"}}
process(21): {��w��������������}
afterDecoding(15): {heartbeatResult}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:15], payload:heartbeatResult}
process(21): {���#qK�F9�A*�q8�O}
afterDecoding(15): {heartbeatResult}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:15], payload:heartbeatResult}
process(21): {��R�w7�}k0�nk

**Comment by Animaleante** [comment]
Seems like I hit a limit there

> send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:33], payload:{"action":"mobileVideoRequested"}}
afterEnconding(33): {{"action":"mobileVideoRequested"}}
write(35): {�!{"action":"mobileVideoRequested"}}
process(21): {��w��������������}
afterDecoding(15): {heartbeatResult}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:15], payload:heartbeatResult}
process(21): {���#qK�F9�A*�q8�O}
afterDecoding(15): {heartbeatResult}
matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:15], payload:heartbeatResult}
process(21): {��R�w7�}k0�nk

**Comment by Animaleante** [comment]
I noticed this only happens after several clients have been disconnected when trying to enter a non-existent room.

Inside onOpen, I check to see if the room they are trying to connect to is open, if not, I call 
`socket.closeConnection(CloseFrame.REFUSE, "Some message");`

Could this be causing the problem? Should I close the socket connection after the onOpen method has finished properly?

**Comment by marci4** [comment]
Hello @Animaleante,

thank you for the log!

Here are some things you may wanna change:
* Use a ping/pong frame instead of a custom text frame for the heartbeat. This should reduce the load for both client and server (since the payload of the frame does not have to be validated by each endpoint). For more on this, check out the [wiki](https://github.com/TooTallNate/Java-WebSocket/wiki/Framing#pingframe). This library uses this e.g. for the [lost connection detection](https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection).
* Try to use the normal `close()`, since it is initiating a normal closing handshake (no data will be lost, endpoint confirms closing etc). closeConnection() is a force method which ignores the spec and directly closes the connection (which could result in data not being send etc).

Other then that there is nothing in the log which suggests any bad client or stuff like that (like huge messages).

Greetings
marci4

**Comment by Animaleante** [comment]
Hey @marci4, thanks for the answer, and sorry for the delay.

Thank you for the tipo on using the PingFrame, I have implemented it. And changed from the closeConnection method to the close method, and will test it this afternoon, and will update this issue with the results, thank you!

**Comment by Animaleante** [comment]
Just to update you @marci4 

The modifications worked, and the server no longer crashes. Thank you very much!
