### ISSUE TITLE
how to listen client has disconnected and reconnect automically

### ISSUE THREAD

**Issue by a13707331174** [TooTallNate/Java-WebSocket#690]
I want the client reconnect when the connection is closed due to remote reason,
i call reconnectBlocking() in onClose(), but reconnectBlocking dose not work, 
so how i reconnect when the connection is closed? thx

**Comment by marci4** [comment]
Hello @a13707331174,

reconnect was never designed to use directly in the WebSocket-Thread!

To achieve what you are trying to do, just start a separate thread which then calls reconnect!

Greetings
marci4

**Comment by shufps** [comment]
In my project I used an extra Thread which acts as watchdog (e.g. connection alive but $x seconds no new data) and to reconnect if the socket is disconnected. It works great so far.

**Comment by a13707331174** [comment]
@shufps,@marci4,thanks for your help

**Comment by marci4** [comment]
@a13707331174 is this issue solved for you know ?

**Comment by marci4** [comment]
Issue seems to be solved!

Closing it!

Best regards,
marci4
