### ISSUE TITLE
Why open() called twice on android 

### ISSUE THREAD

**Issue by DarkSherlock** [TooTallNate/Java-WebSocket#692]
## Debug log (for bugs)
04-13 17:44:00.417 20147-20147/com.aikaola.www.doublestudents D/SocketClient: connectToServer: try to connectToServer :ws://47.96.31.242:7100
04-13 17:44:00.475 20147-20847/com.aikaola.www.doublestudents D/SocketClient: onOpen: ws://47.96.31.242:7100
04-13 17:44:00.476 20147-20848/com.aikaola.www.doublestudents D/SocketClient: onOpen: ws://47.96.31.242:7100

* version: jdk 8 ,android sdk 26

**Comment by marci4** [comment]
Hello @DarkSherlock 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md.

Without a full bug report this will be closed.

Greetings
marci4

**Comment by marci4** [comment]
No update for a week...

Closing issue!
Best regards,
marci4
