### ISSUE TITLE
Can someone explain an easy way to reconnect my client socket?

### ISSUE THREAD

**Issue by michaeldboyd** [TooTallNate/Java-WebSocket#696]
I don't understand the reconnect example. I have created a new thread 

```
public class Reconnector implements Runnable{
    boolean isClosed = SocketManager.socket.isClosed();
    boolean isConnecting = SocketManager.socket.isConnecting();
    @Override
    public void run() {
        while(isClosed || isConnecting) {
            try {
                WebsocketClient client = new SocketClient(new URI("ws://" + ip + ":8080/")
                client.connect();
            } catch (Exception e) {
                e.printStackTrace();
            }
            isClosed = SocketManager.socket.isClosed();
            isConnecting = SocketManager.socket.isConnecting();
            
        }

    }
}
```

**Comment by marci4** [comment]
Hello @michaeldboyd,
with 1.3.8 you don't have to recreate a WebSocket, you can reuse it!

Just keep in mind not to start the reconnect in the WebSocket itself and use a separate thread for this!

Apart from that I do not understand what you are trying to achieve with this code, I'm sorry!

Best regards,
marci4

**Comment by michaeldboyd** [comment]
Thanks for the quick response!  And apologies for the frantic late night post, haha. 

That makes much more sense.  I'm testing to see if I can reconnect to a server that dies and goes back online. It works really well, but the reconnect takes about a minute once the server is turned back on. Is there any way to lower this wait? I'd love to have it reconnect in < 10 seconds, but I understand if it can't

I read something about changing the timeout length, but I couldn't find where to do that.

**Comment by marci4** [comment]
Hello @michaeldboyd,

how do you trigger the reconnect? With the onClose() or different?
How does the server die? Does it shut down normally or is it killed hard, leaving all the connections open?

If the connections are left open, then it is harder to detect. Therefore we have a [lost connection detection](https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection), which just does a heart beat check every minute by default.
If no pong is received, the connection will be closed by the client and then onClose() is called.

Maybe you mean this with the timeout length, but keep in mind, lowering the interval in which frames are send will of course increase the load for your server!

Best regards,
marci4

**Comment by marci4** [comment]
@michaeldboyd is this issue solved for you?

Best regards,
marci4

**Comment by michaeldboyd** [comment]
yep, thank you!
