### ISSUE TITLE
how to keep alive between client and server ,use 1.3.8 ;

### ISSUE THREAD

**Issue by nysyzp** [TooTallNate/Java-WebSocket#700]
version: 

   <dependency>
      <groupId>org.java-websocket</groupId>
      <artifactId>Java-WebSocket</artifactId>
      <version>1.3.8</version>
    </dependency>

i hava read this wiki: https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection;

but this seems could not be used on this version(1.3.8); Yes?

i used this code ,but also was closed;pls help me solve this problem;

         
       WebSocketClient client = null;
        try {
            client = new WebSocketClient(
                    new URI("ws://"+strServer)

            ) {

                @Override
                public void onOpen(ServerHandshake arg0) {
                    logInfo.info("websocket open....");
                }

                @Override
                public void onMessage(String arg0) {
                    logInfo.info("websocket receive msg:"+arg0);

                }

                @Override
                public void onError(Exception arg0) {                    
                    logInfo.error("websocket has error:"+arg0);
                }

                @Override
                public void onClose(int arg0, String arg1, boolean arg2) {
                    logInfo.info("websocket was closed....");
                }

                @Override
                public void onMessage(ByteBuffer bytes) {
                    try {
                        System.out.println(new String(bytes.array(), "utf-8"));
                    } catch (UnsupportedEncodingException e) {
                        e.printStackTrace();
                    }
                }
            };
            client.setConnectionLostTimeout(120);
            client.connect();
            client.sendPing();

        }
        catch (Exception ex){
            Cat.logError(ex);
        }

**Comment by marci4** [comment]
Hello @nysyzp,

please read the [FAQ ](https://github.com/TooTallNate/Java-WebSocket/wiki/Frequently-asked-questions#im-getting-the-exception-websocketnotconnectedexception-what-should-i-do) on the WebSocketNotConnectedException!

Hope, this helps you!
Best regards, 
marci4

**Comment by nysyzp** [comment]
hi @marci4 ,
my question was how to keep alive between client and server ; not WebSocketNotConnectedException;

they can established, but auto closed after 120s;

pls help me ;thank you very much;

**Comment by nysyzp** [comment]
hi @marci4 ,
if i use client.setConnectionLostTimeout(0), it worked;it was not auto closed after 120s;

pls ignore it,thank you ;
