### ISSUE TITLE
Weird \0 bytes

### ISSUE THREAD

**Issue by stefan-reich** [TooTallNate/Java-WebSocket#705]
Hey, I'm seeing weird things with WebSockets. Basically, in onMessage(), I receive the correct string - but with additional superfluous null bytes attached (string displayed as hex in UTF8 format for illustrative purposes):

2b4d6f6e204d61792030372032333a34303a353620434553542032303138207c203630303538206d730a00000000

These can be fewer or more null bytes, depending on... the weather I guess. (?!!!)

I think I've seen the same with a JavaScript WebSocket client too, just with... fewer null bytes.

If I just drop these null bytes, the application works fine.

What's going on here?

[Simple example.](http://tinybrain.de/1014686)

**Comment by marci4** [comment]
Hello @stefan-reich ,

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md.

Without a full bug report this will be closed.

Best regards,
marci4

**Comment by stefan-reich** [comment]
You are trying to waste my time. I can provide a test program you can run if you like.

I'm using Java 1.8 on Peppermint Linux 64 bit. Standard stuff.

**Comment by marci4** [comment]
Missing template.

Closing issue!
Best regards,
marci4
