### ISSUE TITLE
GZIP support?

### ISSUE THREAD

**Issue by algiuxass** [TooTallNate/Java-WebSocket#707]
## Expected Behavior
GZIP compression.

## Current Behavior
No GZIP compression.

## Possible Solution
Add GZIP compression.

## Context
I want that sending data/receiving data would be faster, people with limited internet connection would save data.

**Comment by marci4** [comment]
Hello @algiuxass,

do you mean the per-message-deflate extension or GZIP on an application level.
If you mean the second one, you have to do this yourself!
If you mean the first one, there is already an open issue for that!

Best regards,
marci4

**Comment by algiuxass** [comment]
I meant the first one.
