### ISSUE TITLE
broadcasting a ByteBuffer

### ISSUE THREAD

**Issue by PhilipRoman** [TooTallNate/Java-WebSocket#711]
I would be very interested into an overload `broadcast(ByteBuffer)` for `WebSocketServer` like the one for byte arrays and strings. One could use `ByteBuffer.array()` but it is, in fact, sematically different, because variables like position and limit are not taken in account when sending. Are there any technical difficulties preventing such an overload and would there be any opportunities of optimization compared to  iterating clients and sending the buffer to each?

**Comment by marci4** [comment]
Hello @PhilipRoman,

thank you very much for the idea.
Yeah, for me it was never a use case so I thought, I just to the byte array.
But I see where you are coming from!

Feel free to open a PR for this. I am more than happy to merch it!

Best regards,
marci4

**Comment by marci4** [comment]
Merged #712 

Closing this issue!
