### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by wang0x32** [TooTallNate/Java-WebSocket#714]
AndroidRuntime: java.util.ConcurrentModificationException
 AndroidRuntime: 	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
 AndroidRuntime: 	at java.util.HashMap$KeyIterator.next(HashMap.java:814)
 AndroidRuntime: 	at java.util.AbstractCollection.toArrayList(AbstractCollection.java:349)
 AndroidRuntime: 	at java.util.AbstractCollection.toArray(AbstractCollection.java:339)
 AndroidRuntime: 	at java.util.ArrayList.<init>(ArrayList.java:97)
 AndroidRuntime: 	at org.java_websocket.server.WebSocketServer.getConnections(WebSocketServer.java:289)
 AndroidRuntime: 	at org.java_websocket.AbstractWebSocket$1.run(AbstractWebSocket.java:141)
 AndroidRuntime: 	at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by marci4** [comment]
Hello @wang0x32 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md.

Without a full bug report this will be closed.

Best regards,
marci4

**Comment by zebpaysagar** [comment]
We are facing the same issue and tried https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md. The link does not work.

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at io.deepstream.Connection.setState(Connection.java:331)
       at io.deepstream.JavaEndpointWebsocket$WebSocket.io.deepstream.Connection.onError(JavaEndpointWebsocket.java:6192)
       at org.java_websocket.client.WebSocketClient.onWebsocketError$6d401871(WebSocketClient.java:2521)
       at java.lang.Thread.run(Thread.java:764)
