### ISSUE TITLE
WebsocketNotConnectedException on SendPing

### ISSUE THREAD

**Issue by leokho** [TooTallNate/Java-WebSocket#715]
WebSocket pings without connections and causes to crash: WebsocketNotConnectedException

## Expected Behavior
Application using the websocket client is not supposed to crash while running on Android.

## Current Behavior
We have found in some Android phones the following error:

Fatal Exception: org.java_websocket.exceptions.WebsocketNotConnectedException
       at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
       at org.java_websocket.WebSocketImpl.sendFrame(WebSocketImpl.java:634)
       at org.java_websocket.WebSocketImpl.sendPing(WebSocketImpl.java:641)
       at org.java_websocket.AbstractWebSocket$1.run(AbstractWebSocket.java:153)
       at java.util.Timer$TimerImpl.run(Timer.java:284)

## Steps to Reproduce (for bugs)
Unfortunately I was still unable to reproduce the bug locally. As soon as I will, I will update the issue.

## Context
We implement the websocket client in an Android App.

## Your Environment
* Version used: 1.3.8
* Operating System and version: Android 6-8

**Comment by marci4** [comment]
Hello @leokho,

thank you for your bug report.

I think the best is to just catch this exception. Could be just a bad timing thing....
Does this happen a lot?

Best regards,
marci4

**Comment by leokho** [comment]
Hi @marci4 ,

Yes, it does happen quite a bit, around 10% of our users experience this bug. We are still trying to see if we find a way to replicate this on our side. 

The stack trace that I've posted, is the full one.

**Comment by marci4** [comment]
Hello @leokho,
that is actually a lot. I am sorry for the inconvenience!!

On what interval have you set the connection lost detection?
Have you run into the same issue described in #699 ?
Could you describe how you are using the library in your app?

Maybe this helps at least get to the source of the problem.

Best regards,
marci4

**Comment by JoanaDFerreira** [comment]
Hello @marci4,

Yes, we think our issue is the same as #699.
Could you please create a new version tag with the updates you did for this issue in master for us to test?

thank you,
Joana

**Comment by marci4** [comment]
Hello @JoanaDFerreira,

that would only be #708.

Best regards,
marci4

**Comment by beiCheNzero** [comment]
android10
Version used: 1.5.3
When I used version 1.5.3, the WebsocketNotConnectedException problem still occurred. Wasn't this problem solved in version 1.3.9? Why does it still occur?
