### ISSUE TITLE
Can I use this Library to connect to Unix Domain Socket.

### ISSUE THREAD

**Issue by princrai** [TooTallNate/Java-WebSocket#716]
Hello,

I am looking for some java library to connect to a process(daemon) which is listening on a unix domain socket. Not sure if this library can be used for that. Apart from that I am currently using JUnixSocket to write and read through the socket, but the read is causing the CPU spikes as it waits for the daemon to return the data back and at that that it keep blocked on the read() function.

**Comment by marci4** [comment]
Hello @princrai,

as far as I know this is not possible. 
This library implements [RFC 6455](https://tools.ietf.org/html/rfc6455) and to my knowledge there is now way to access a IPC socket using websockets. 

Best regards,
marci4

**Comment by PhilipRoman** [comment]
Apparently node.js supports this. See [this question on stackoverflow](https://stackoverflow.com/questions/23930293/websockets-listening-on-unix-domain-socket?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa). They are using a cool syntax for the url: `var client = new ws("ws+unix:///tmp/server.sock")`

**Comment by marci4** [comment]
Is this issue solved for you?

Best regards,
marci4

**Comment by princrai** [comment]
I am trying Netty library to connect to Unix Socket. And getting some good
result(latency,throughput).

Thanks,
Prince
