### ISSUE TITLE
可以实现重连吗？

### ISSUE THREAD

**Issue by yuliangC** [TooTallNate/Java-WebSocket#718]
非常感谢你的库给了我很大帮助。请问还可以实现断线重连吗？

**Comment by marci4** [comment]
Hello @yuliangC,

could you please ask your question in english? thanks!

Best regards,
marci4

**Comment by han361769045** [comment]
How can reconnect when the socket is closed ,the network is off ?

**Comment by yuliangC** [comment]
thanks for your library,it help me a lot ,while this is a question trouble me ,like the gay says above,How can reconnect when the socket is closed ,the network is off ?

**Comment by marci4** [comment]
Hello @yuliangC,

I added the reconnect() method with 1.3.8.

Check out the [JavaDocs](https://static.javadoc.io/org.java-websocket/Java-WebSocket/1.3.8/org/java_websocket/client/WebSocketClient.html) for more.

Best regards,
marci4

**Comment by marci4** [comment]
Hello @yuliangC ,

is this issue solved for you?

Best regards,
marci4

**Comment by marci4** [comment]
Hello @yuliangC,

no I cannot give you a time frame in which you wanna reconnect.
That is up to your application!

Best regards,
marci4

**Comment by marci4** [comment]
Is this issue solved for you now?

Best regards,
marci4
