### ISSUE TITLE
Spring Integration planned?

### ISSUE THREAD

**Issue by dersteve** [TooTallNate/Java-WebSocket#725]
I'm using Java-WebSocket in combination of https://github.com/ChargeTimeEU/Java-OCA-OCPP.

Java-WebSocket opens up a WebSocket listener on a specific port. My app runs inside a CloudFoundry container and I can only open up one port for the outside (limitation from the configured platform, which I can't change).

Everything works fine, but I'd also like to add REST-Endpoints to the Spring app, meaning I'd like to spin up the tomcat, but it can't start up, since the port is already in use; obviously.

Is there a way to somehow circumvent this? Down at the metal both (tomcat and web socket listener) try to bind on the same hostname + port and the second (tomcat in my case) fails. Is there a way to somehow integrate the Java-WebSocket listener into the Tomcat?

**Comment by marci4** [comment]
Hello @dersteve,

that would be of course an option, if it is possible to not break existing applications. 
I personally see this always as a benefit that we do not require any other framework. You can simple use a WebSocket.

I do not know how to achieve this, do you have any idea for that?

_I think that this also kind of matches issue #680._

Best regards,
marci4

**Comment by marci4** [comment]
No plans for now. Closing this issue!

Best regards,
Marcel
