### ISSUE TITLE
WebSocketClient can't recive message when WebSocket service message too large 

### ISSUE THREAD

**Issue by littleBoyGoing** [TooTallNate/Java-WebSocket#727]
websocketClinet can't recive message when  webSocket service message to large 

This tool have some setting about this  to recive large message

**Comment by marci4** [comment]
Hello @littleBoyGoing 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md.

Without a full bug report this will be closed.

Best regards,
marci4

**Comment by marci4** [comment]
No feedback!

Closing dead issue.
Best regards,
marci4
