### ISSUE TITLE
Please update the start command for example

### ISSUE THREAD

**Issue by marsend** [TooTallNate/Java-WebSocket#730]
## Expected Behavior

The websocket server will started by running command `java -cp build/examples:dist/WebSocket.jar ChatServer`. [where is command from](http://tootallnate.github.io/Java-WebSocket/)
## Current Behavior

Command result is `Error: Could not find or load main class ChatServer`
## Possible Solution

The correct command should be `java -cp build/examples:dist/java_websocket.jar ChatServer` in current version build
## Steps to Reproduce (for bugs)

nope

## Your Environment

* Version used:1.3.8
* Java version:1.8.0
* Operating System and version: mac OS 11.13.2
* Endpoint Name and version:
* Link to your project:

**Comment by marci4** [comment]
Hello @marsend,

thank you for your bug report!

Do you mind open a PR to fix this issue?
Love to give credit where credit is due!

Best regards,
marci4

**Comment by marci4** [comment]
Hello @marsend,

I changed everything!

Thank you again!

Best regards,
marci4
