### ISSUE TITLE
Android background disconnect

### ISSUE THREAD

**Issue by VyacheslavMartynenko** [TooTallNate/Java-WebSocket#731]
Getting "The connection was closed because the other endpoint did not respond with a pong in time." Full description of problem hear:
[https://stackoverflow.com/questions/51133783/socket-connection-in-background](https://stackoverflow.com/questions/51133783/socket-connection-in-background)

**Comment by PhilipRoman** [comment]
fixed the link

**Comment by VyacheslavMartynenko** [comment]
The link is fine, please check again.

**Comment by VyacheslavMartynenko** [comment]
Ah, aorry about this.

**Comment by oakkitten** [comment]
android suspends the cpu when it sleeps, which includes the library's ping-pong mechanism. you should implement your own pinging in such a way that it wakes up the cpu, and disable the built-in one. you may need to exclude your app from the doze, too

**Comment by VyacheslavMartynenko** [comment]
This app is excluded from battery optimization rules.
Possibly the only working way to wake up a device from service is to start an activity with window flags, but it doesn't look like an elegant option. And I'd like to try to find another solution.

**Comment by marci4** [comment]
Hello @VyacheslavMartynenko 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md.

Without a full bug report this will be closed.

I am also interested in your lib-version, since I added some additional info text for this dc to help enduser understand the issue!

Could you also provide a sample application, where I can test my changes?
I am not into Android and therefore have no knowledge how the doze and everything else works!

Thank you!
Best regards,
marci4

**Comment by VyacheslavMartynenko** [comment]
Hello @marci4 

I think, nevertheless, this problem is more relevant to Android than to the library. But you can see my answer to this problem by the same link to the StackOverflow. Perhaps it will be useful to you. 
And unfortunately, I can not provide the application in the near future.

Best regards,
Vyacheslav

**Comment by oakkitten** [comment]
> This app is excluded from battery optimization rules.

the system will still put cpu to sleep. this library uses the regular sleep method that does *not* take sleeping into account, so you need either to never sleep, which you are doing, or wake up the cpu using android's built-in things, which i am suggesting. this is a bit of (dated) code we are using using to schedule pings:

    alarmMgr = (AlarmManager) getSystemService(Context.ALARM_SERVICE);
    PING_ACTION = BuildConfig.APPLICATION_ID + ".PING_ACTION";

    public void onConnect() { 
        long triggerAt = SystemClock.elapsedRealtime() + pingTimeout; 
        schedulePing(triggerAt, new Bundle()); 
    } 

    ...

    @TargetApi(19) 
    void schedulePing(long triggerAt, Bundle extras) { 
        Intent intent = new Intent(PingActionReceiver.PING_ACTION); 
        intent.putExtras(extras); 
 
        PendingIntent alarmIntent = PendingIntent.getBroadcast( 
                this, 0, 
                intent, 
                PendingIntent.FLAG_CANCEL_CURRENT 
        ); 
 
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) { 
            alarmMgr.setExact(AlarmManager.ELAPSED_REALTIME_WAKEUP, triggerAt, alarmIntent); 
        } else { 
            alarmMgr.set(AlarmManager.ELAPSED_REALTIME_WAKEUP, triggerAt, alarmIntent); 
        } 
    }
    
    ...


    public void onReceive(Context context, Intent intent) { 
        if (!relayService.isConnection(RelayService.CONNECTED)) return; 
 
        long triggerAt; 
        Bundle extras = new Bundle(); 
 
        if (SystemClock.elapsedRealtime() - relayService.lastMessageReceivedAt > pingIdleTime) { 
            if (!intent.getBooleanExtra("sentPing", false)) { 
                logger.debug("last message too old, sending ping"); 
                relayService.connection.sendMsg("ping"); 
                triggerAt = SystemClock.elapsedRealtime() + pingTimeout; 
                extras.putBoolean("sentPing", true); 
            } else { 
                logger.debug("no message received, disconnecting"); 
                relayService.startThreadedDisconnect(false); 
                return; 
            } 
        } else { 
            triggerAt = relayService.lastMessageReceivedAt + pingIdleTime; 
        } 
 
        relayService.schedulePing(triggerAt, extras); 
    }

**Comment by marci4** [comment]
Any update on the template?

**Comment by marci4** [comment]
No template. Closing issue!

Best regards,
marci4
