### ISSUE TITLE
reconnect() method will block

### ISSUE THREAD

**Issue by sucaiji** [TooTallNate/Java-WebSocket#732]
my code: 

 ```
  @Override
    public void onClose(int code, String reason, boolean remote) {
        this.reconnect();
        System.out.println("123");
    }
```

by debug, I find program will block in LockSupport.java

```
public static void park(Object blocker) {
        Thread t = Thread.currentThread();
        setBlocker(t, blocker);
        UNSAFE.park(false, 0L);
        setBlocker(t, null);
    }
```

Did my usage is wrong?Or Bug?
My English is not good,Sorry.

**Comment by githubbugzz** [comment]
断线重连的问题解决了吗？

**Comment by sucaiji** [comment]
@githubbugzz 并不是这个框架的问题 只是reconnect()不能和WebSocketClient处在同一线程

**Comment by githubbugzz** [comment]
那样的话，是不是应该在onclose中先干掉这个websocketclient线程？您的解决思路是什么？能否看一下代码？

**Comment by sucaiji** [comment]
@githubbugzz  不用。。简单的做法在onclose里面开个线程就可以了呀

`@Override
    public void onClose(int code, String reason, boolean remote) {
        new Thread(() -> {
            this.reconnect();
        }).start();
    }` 比如这样

**Comment by marci4** [comment]
Any update on the template?

**Comment by sucaiji** [comment]
@marci4   No, sorry , It's not a bug, It's my using fault
