### ISSUE TITLE
ssl == null

### ISSUE THREAD

**Issue by 925941723** [TooTallNate/Java-WebSocket#735]
I got a error like this:

# Thread-13(5657)
java.lang.NullPointerException
ssl == null

1 com.android.org.conscrypt.NativeCrypto.SSL_set_timeout(Native Method)
--
2 com.android.org.conscrypt.SslWrapper.setTimeout(SslWrapper.java:101)
3 com.android.org.conscrypt.ActiveSession.invalidate(ActiveSession.java:147)
4 com.android.org.conscrypt.DelegatingExtendedSSLSession.invalidate(DelegatingExtendedSSLSession.java:120)
5 org.java_websocket.SSLSocketChannel2.close(SSLSocketChannel2.java:268)
6 org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:453)
7 org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:511)
8 org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:249)
9 org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
10 java.lang.Thread.run(Thread.java:764)

I even have no idea where is wrong.
Can anyone tell me how to fix it?The version is 1.3.0. Android 8.1.0
Thanks.

**Comment by marci4** [comment]
No template. Closing issue!

Best regards,
marci4
