### ISSUE TITLE
WSS Connection is refused after library update

### ISSUE THREAD

**Issue by schauersbergern** [TooTallNate/Java-WebSocket#740]
After updating from Java-WebSocket:1.3.6 to Java-WebSocket:1.3.8 I cannot
connect to a Secure Websocket any more.
I tried it with only updating the library, and then with code changes like 
described here:
https://stackoverflow.com/questions/39234517/java-websocket-draft-refuses-handshake

But no approach did work.

After downgrading to WebSocket:1.3.6 the connection worked again

## Expected Behavior

The Socket should connect and sending data should be possible

## Current Behavior

Websocket gets closed with following error:
Invalid status code received: 403 Status line: HTTP/1.1 403 Forbidden

Or it cannot connect, with following error:
org.java_websocket.drafts.Draft_6455 refuses handshake

## Debug log (for bugs)

1) Same Code as before, after library update:

/Websocket: %messageString%
07-24 16:29:30.049 5068-7203/at.vol.android I/System.out: Sec-WebSocket-Key: %key%
    Sec-WebSocket-Protocol: echo-protocol
    Sec-WebSocket-Version: 13
    Upgrade: websocket
    }
07-24 16:29:30.056 5068-7203/at.vol.android I/System.out: process(273): {HTTP/1.1 101 Switching Protocols
    Upgrade: websocket
    Connection: Upgrade
    Sec-WebSocket-Accept: %anotherKey%
    Sec-WebSocket-Protocol: echo-protocol
    Set-Cookie: %aCookie%
    }
07-24 16:29:30.061 5068-7203/at.vol.android I/Websocket: Closed draft Draft_6455 extension: DefaultExtension refuses handshake

2) After adding a Protocol:
like stated in following article I got
https://stackoverflow.com/questions/39234517/java-websocket-draft-refuses-handshake

07-24 15:56:45.367 23915-858/at.vol.android I/Websocket: Closed Invalid status code received: 403 Status line: HTTP/1.1 403 Forbidden

07-25 14:13:19.573 24000-25880/at.vol.android I/Websocket: Closed draft Draft_6455 extension: DefaultExtension refuses handshake
07-25 14:13:19.844 24000-24000/at.vol.android I/Websocket: Sending: %messageString%,
07-25 14:13:19.893 24000-25884/at.vol.android I/System.out: write(202): {GET / HTTP/1.1
    Connection: Upgrade
    Host: %host%
    Sec-WebSocket-Key: %key%
07-25 14:13:19.894 24000-25884/at.vol.android I/System.out: Sec-WebSocket-Protocol: echo-protocol
    Sec-WebSocket-Version: 13
    Upgrade: websocket
    }
07-25 14:13:19.901 24000-25884/at.vol.android I/System.out: process(273): {HTTP/1.1 101 Switching Protocols
    Upgrade: websocket
    Connection: Upgrade
    Sec-WebSocket-Accept: %key%
    Sec-WebSocket-Protocol: echo-protocol
    Set-Cookie: %someCookie%
    }
07-25 14:13:19.905 24000-25884/at.vol.android I/Websocket: Closed draft Draft_6455 extension: DefaultExtension refuses handshake

## Your Environment

* Version used:
1.3.8

* Java version:
Java 8

* Operating System and version:
* Endpoint Name and version:
* Link to your project:

**Comment by marci4** [comment]
Hallo @schauersbergern,

thank you for your bug report!

Could you tell me to which endpoint you are connecting?

Also an empty protocol is the default for the DefaultExtension, which represents the Draft_6455.

HTTP/1.1 403 Forbidden is not in our hand since it is coming from the other endpoint.
The refused handshake however should be made clearer why!

I pushed with #741 some changes which should help debug this issue more.
If you want, you can use the latest snapshot [(this one)](https://oss.sonatype.org/content/repositories/snapshots/org/java-websocket/Java-WebSocket/1.3.9-SNAPSHOT/Java-WebSocket-1.3.9-20180725.203211-6.jar) and test it with that!

Best regards,
marci4

**Comment by marci4** [comment]
@schauersbergern any update?

**Comment by schauersbergern** [comment]
Hello @marci4,

the debug Snapshot #741 didn't provide org.java_websocket.protocols.Protocol, so I couldn't instantiate the class. When using Draft_6455 without extensions and protocols, I got the same output like
I got with api 1.3.8 and debug flags.

I did another test now, with your new api 1.3.8 while the server administrator of our websocket
server was listening. He said that he didn't receive any single request.

The socket url of dev server is like wss://dev.ourservername.com

I did 3 Tests again, 

1) Draft_6455()  
2) new Draft_6455(knownExtensions, knownProtocols) 
with empty Protocol: knownProtocols.add(new org.java_websocket.protocols.Protocol(""));

On these tests I got the error:
Closed draft Draft_6455 extension: DefaultExtension refuses handshake

3) new Draft_6455(knownExtensions, knownProtocols) 
with wss Protocol: knownProtocols.add(new org.java_websocket.protocols.Protocol("wss"));

On this test I got the error:
Closed Invalid status code received: 403 Status line: HTTP/1.1 403 Forbidden

But also on this test the socket server did not receive any request.

Could it be, that the new api version 1.3.8 doesn't support echo protocol or TLS anymore?

How I instantiate the Websocket looks like this:

Map<String,String> headers = new HashMap<>();
headers.put("Sec-WebSocket-Protocol", "echo-protocol");

URI uri = new URI( "wss://dev.ourservername.com" );

WebSocketClient webSocketClient = new WebsocketClient(uri, new Draft_6455(), headers, connecttimeout);
SSLContext sslContext = SSLContext.getInstance( "TLS" );

TrustManager[] tm = new TrustManager[]{
        new X509TrustManager() {
            public java.security.cert.X509Certificate[] getAcceptedIssuers()
            {return null;}
            public void checkClientTrusted(java.security.cert.X509Certificate[] certs, String authType)
            {}
            public void checkServerTrusted(java.security.cert.X509Certificate[] certs, String authType)
            {}
        }
};

sslContext.init(null, tm, new java.security.SecureRandom() );
SSLSocketFactory factory = sslContext.getSocketFactory();
Socket socket = factory.createSocket();
webSocketClient.setSocket( socket );
webSocketClient.connect();

best regards,
schauersbergern

**Comment by marci4** [comment]
Hello @schauersbergern,

you are misunderstanding what the meaning of the protocol is, which is the [Sec-WebSocket-Protocol](https://tools.ietf.org/html/rfc6455#page-59). 
This is a way do define a different protocol on the application level!

If you e.g. only wanna allow the specific sec-websocket-protocol "echo-protocol", take a look at [this](https://github.com/TooTallNate/Java-WebSocket/wiki/Specifing-a-Sec-WebSocket-Protocol)!

If this is however still an issue, could you maybe mail me the address of your server so I can take a look at this? You can find it on my profile!

Best regards,
marci4

**Comment by marci4** [comment]
Hello @schauersbergern,

is there any update on your issue?

Best regards,
marci4

**Comment by schauersbergern** [comment]
Hello @marci4 

sorry for answering late, I just returned from vacation.

Thank you for your support, I could solve the issue with your Sec-WebSocket-Protocol example.

But as you stated, that it only works with "ocpp2.0" was not the case with our application.
When I changed it to "echo-protocol" it worked quite well, but I think that's the issue
with our wss server.

best regards,
schauersbergern

**Comment by marci4** [comment]
Hello @schauersbergern,

thank you for your feedback. 
I quess I can close this issue then!

Sorry if the example was not clear enough. I just meant that in this specific case, the only Sec-WebSocket-Protocol allowed would be "ocpp2.0". 
Maybe I need to rewrite it!

Best regards,
marci4
