### ISSUE TITLE
How to use the heartbeat mechanism to determine whether to disconnect?

### ISSUE THREAD

**Issue by 312353457** [TooTallNate/Java-WebSocket#742]
How to use the heartbeat mechanism to determine whether to disconnect?

**Comment by PhilipRoman** [comment]
Here is the relevant [wiki page](https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection). In short, when your other endpoint doesn't respond in time, the connection will automatically be closed. You can change the timeout (or disable it) using `setConnectionLostTimeout();`. Default timeout is 60 seconds.

**Comment by marci4** [comment]
No additional feedback and reference to the wiki

Closing issue!
Best regards,
marci4
