### ISSUE TITLE
Release of 1.3.9

### ISSUE THREAD

**Issue by leokho** [TooTallNate/Java-WebSocket#743]
Hi!

I've seen that the milestones for 1.3.9 have been all completed, is there a prediction data for it's release to maven repo? 

Thanks in advance!

**Comment by marci4** [comment]
Hello @leokho,

first of all thank you for your interest in this project!

So a few things:
- The milestone is mostly use to track changes which are part of this version. Never the less if there is an open issue with an active milestone, it will be part of this version (if no good reason come up)
- I currently plan to start my regression tests this week. This includes updating my private projects to a release candidate build and test, if there are any major bugs.
- After this regression tests succeeds, I would then push this release to maven!

If you however wanna use a snapshot version, feel free to test it (https://oss.sonatype.org/content/repositories/snapshots/org/java-websocket/Java-WebSocket/)

Best regards,
marci4

**Comment by marci4** [comment]
Hello @leokho,
the regression tests looks good. 

Releasing the new version to maven!

Best regards,
marci4
