### ISSUE TITLE
Reconnect fails on Android 5.1.1

### ISSUE THREAD

**Issue by Davevb** [TooTallNate/Java-WebSocket#744]
Is there any known issues using reconnect on Android 5.1. On Android 4.4.4 it works fine. On 5.1.1 it won't reconnect...
## Expected Behavior

When server side goes down and restarts, the clients should reconnect to te server side
## Current Behavior

On Android 4.4.4 the client reconnects. On Android 5.1.1 (API 22) it doesn't
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug log (for bugs)

08-01 13:11:41.879 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: process(12): {�
08-01 13:11:41.879 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: Echo: poll}
08-01 13:11:41.879 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: afterDecoding(10): {Echo: poll}
08-01 13:11:41.879 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:10], payload:Echo: poll}
08-01 13:11:46.967 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: process(641): {�~}{"Temp":{"Act":21.1,"Pre":16.7,"Max":44,"Min":0},"SunSouth":{"Act":26,"Pre":31,"Max":99,"Min":0},"SunEast":{"Act":19,"Pre":15,"Max":99,"Min":0},"SunWest":{"Act":17,"Pre":50,"Max":95,"Min":0},"DayLight":{"Act":658,"Pre":999,"Max":999,"Min":0},"Rain":false,"RainPre":false,"Twilight":true,"TwilightPre":false,"Wind":{"Act":0,"Pre":1.4,"Max":35,"Min":0},"GpsReport":true,"Elevation":-17,"Longitude":3.8,"Latitude":50.9,"Status":2,"ID":2,"Type":55,"Kind":0,"Description":"Weerstation","Group":{"ID":24,"Name":"Weerstation"},"IpAddress":"10.10.1.9","Port":30101,"Protocol":2,"Visible":false,"MobileVisible":false,"MobileIcon":0,"SubSystem":0}}
08-01 13:11:46.968 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: afterDecoding(637): {{"Temp":{"Act":21.1,"Pre":16.7,"Max":44,"Min":0},"SunSouth":{"Act":26,"Pre":31,"Max":99,"Min":0},"SunEast":{"Act":19,"Pre":15,"Max":99,"Min":0},"SunWest":{"Act":17,"Pre":50,"Max":95,"Min":0},"DayLight":{"Act":658,"Pre":999,"Max":999,"Min":0},"Rain":false,"RainPre":false,"Twilight":true,"TwilightPre":false,"Wind":{"Act":0,"Pre":1.4,"Max":35,"Min":0},"GpsReport":true,"Elevation":-17,"Longitude":3.8,"Latitude":50.9,"Status":2,"ID":2,"Type":55,"Kind":0,"Description":"Weerstation","Group":{"ID":24,"Name":"Weerstation"},"IpAddress":"10.10.1.9","Port":30101,"Protocol":2,"Visible":false,"MobileVisible":false,"MobileIcon":0,"SubSystem":0}}
08-01 13:11:46.969 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:637], payload:{"Temp":{"Act":21.1,"Pre":16.7,"Max":44,"Min":0},"SunSouth":{"Act":26,"Pre":31,"Max":99,"Min":0},"SunEast":{"Act":19,"Pre":15,"Max":99,"Min":0},"SunWest":{"Act":17,"Pre":50,"Max":95,"Min":0},"DayLight":{"Act":658,"Pre":999,"Max":999,"Min":0},"Rain":false,"RainPre":false,"Twilight":true,"TwilightPre":false,"Wind":{"Act":0,"Pre":1.4,"Max":35,"Min":0},"GpsReport":true,"Elevation":-17,"Longitude":3.8,"Latitude":50.9,"Status":2,"ID":2,"Type":55,"Kind":0,"Description":"Weerstation","Group":{"ID":24,"Name":"Weerstation"},"IpAddress":"10.10.1.9","Port":30101,"Protocol":2,"Visible":false,"MobileVisible":false,"MobileIcon":0,"SubSystem":0}}
08-01 13:11:47.730 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: process(250): {�~���{"Output":13,"Status":0,"Watt":0,"ID":569,"Type":1,"Kind":0,"Description":"Klep living (30.14)","Group":{"ID":8,"Name":"Kleppen"},"IpAddress":"10.10.60.30","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":2,"SubSystem":1}}
08-01 13:11:47.731 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: afterDecoding(246): {{"Output":13,"Status":0,"Watt":0,"ID":569,"Type":1,"Kind":0,"Description":"Klep living (30.14)","Group":{"ID":8,"Name":"Kleppen"},"IpAddress":"10.10.60.30","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":2,"SubSystem":1}}
08-01 13:11:47.731 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:246], payload:{"Output":13,"Status":0,"Watt":0,"ID":569,"Type":1,"Kind":0,"Description":"Klep living (30.14)","Group":{"ID":8,"Name":"Kleppen"},"IpAddress":"10.10.60.30","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":2,"SubSystem":1}}
08-01 13:11:51.875 4809-4809/com.ipbuilding.ipbtouchlayout I/System.out: send frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:4], payload:poll}
08-01 13:11:51.875 4809-4809/com.ipbuilding.ipbtouchlayout I/System.out: afterEnconding(4): {poll}
08-01 13:11:51.875 4809-4809/com.ipbuilding.ipbtouchlayout I/System.out: write(10): {��A/5�1@Y�}
08-01 13:11:51.879 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: process(12): {�
08-01 13:11:51.879 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: Echo: poll}
08-01 13:11:51.880 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: afterDecoding(10): {Echo: poll}
08-01 13:11:51.880 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:10], payload:Echo: poll}
08-01 13:11:52.399 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: process(605): {�~Y{"Mac":{"Code":70,"ID":"28CE9A8F02000094","Channel":5},"ActValue":{"Act":28.2,"Pre":28.2,"Max":0,"Min":0},"AskValue":{"Act":15,"Pre":15,"Max":0,"Min":0},"DeviationRun":false,"DeviationTime":{"Ticks":0,"Days":0,"Hours":0,"Milliseconds":0,"Minutes":0,"Seconds":0,"TotalDays":0,"TotalHours":0,"TotalMilliseconds":0,"TotalMinutes":0,"TotalSeconds":0},"Airco":false,"DualMode":false,"ID":976,"Type":51,"Kind":8,"Description":"Keuken (flat 0.1)","Group":{"ID":16,"Name":"Temperatuursensor"},"IpAddress":"10.10.60.50","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":0,"SubSystem":1}}
08-01 13:11:52.400 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: afterDecoding(601): {{"Mac":{"Code":70,"ID":"28CE9A8F02000094","Channel":5},"ActValue":{"Act":28.2,"Pre":28.2,"Max":0,"Min":0},"AskValue":{"Act":15,"Pre":15,"Max":0,"Min":0},"DeviationRun":false,"DeviationTime":{"Ticks":0,"Days":0,"Hours":0,"Milliseconds":0,"Minutes":0,"Seconds":0,"TotalDays":0,"TotalHours":0,"TotalMilliseconds":0,"TotalMinutes":0,"TotalSeconds":0},"Airco":false,"DualMode":false,"ID":976,"Type":51,"Kind":8,"Description":"Keuken (flat 0.1)","Group":{"ID":16,"Name":"Temperatuursensor"},"IpAddress":"10.10.60.50","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":0,"SubSystem":1}}
08-01 13:11:52.401 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:601], payload:{"Mac":{"Code":70,"ID":"28CE9A8F02000094","Channel":5},"ActValue":{"Act":28.2,"Pre":28.2,"Max":0,"Min":0},"AskValue":{"Act":15,"Pre":15,"Max":0,"Min":0},"DeviationRun":false,"DeviationTime":{"Ticks":0,"Days":0,"Hours":0,"Milliseconds":0,"Minutes":0,"Seconds":0,"TotalDays":0,"TotalHours":0,"TotalMilliseconds":0,"TotalMinutes":0,"TotalSeconds":0},"Airco":false,"DualMode":false,"ID":976,"Type":51,"Kind":8,"Description":"Keuken (flat 0.1)","Group":{"ID":16,"Name":"Temperatuursensor"},"IpAddress":"10.10.60.50","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":0,"SubSystem":1}}
08-01 13:11:52.415 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: process(605): {�~Y{"Mac":{"Code":70,"ID":"288936BA080000D5","Channel":7},"ActValue":{"Act":28.7,"Pre":28.6,"Max":0,"Min":0},"AskValue":{"Act":15,"Pre":15,"Max":0,"Min":0},"DeviationRun":false,"DeviationTime":{"Ticks":0,"Days":0,"Hours":0,"Milliseconds":0,"Minutes":0,"Seconds":0,"TotalDays":0,"TotalHours":0,"TotalMilliseconds":0,"TotalMinutes":0,"TotalSeconds":0},"Airco":false,"DualMode":false,"ID":977,"Type":51,"Kind":8,"Description":"Living (flat 0.2)","Group":{"ID":16,"Name":"Temperatuursensor"},"IpAddress":"10.10.60.50","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":0,"SubSystem":2}}
08-01 13:11:52.416 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: afterDecoding(601): {{"Mac":{"Code":70,"ID":"288936BA080000D5","Channel":7},"ActValue":{"Act":28.7,"Pre":28.6,"Max":0,"Min":0},"AskValue":{"Act":15,"Pre":15,"Max":0,"Min":0},"DeviationRun":false,"DeviationTime":{"Ticks":0,"Days":0,"Hours":0,"Milliseconds":0,"Minutes":0,"Seconds":0,"TotalDays":0,"TotalHours":0,"TotalMilliseconds":0,"TotalMinutes":0,"TotalSeconds":0},"Airco":false,"DualMode":false,"ID":977,"Type":51,"Kind":8,"Description":"Living (flat 0.2)","Group":{"ID":16,"Name":"Temperatuursensor"},"IpAddress":"10.10.60.50","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":0,"SubSystem":2}}
08-01 13:11:52.417 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:601], payload:{"Mac":{"Code":70,"ID":"288936BA080000D5","Channel":7},"ActValue":{"Act":28.7,"Pre":28.6,"Max":0,"Min":0},"AskValue":{"Act":15,"Pre":15,"Max":0,"Min":0},"DeviationRun":false,"DeviationTime":{"Ticks":0,"Days":0,"Hours":0,"Milliseconds":0,"Minutes":0,"Seconds":0,"TotalDays":0,"TotalHours":0,"TotalMilliseconds":0,"TotalMinutes":0,"TotalSeconds":0},"Airco":false,"DualMode":false,"ID":977,"Type":51,"Kind":8,"Description":"Living (flat 0.2)","Group":{"ID":16,"Name":"Temperatuursensor"},"IpAddress":"10.10.60.50","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":0,"SubSystem":2}}
08-01 13:11:52.754 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: process(248): {�~���{"Output":8,"Status":0,"Watt":0,"ID":956,"Type":1,"Kind":4,"Description":"Deurslot (35.9)","Group":{"ID":5,"Name":"Deursloten"},"IpAddress":"10.10.60.35","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":8,"SubSystem":2}}
08-01 13:11:52.755 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: afterDecoding(244): {{"Output":8,"Status":0,"Watt":0,"ID":956,"Type":1,"Kind":4,"Description":"Deurslot (35.9)","Group":{"ID":5,"Name":"Deursloten"},"IpAddress":"10.10.60.35","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":8,"SubSystem":2}}
08-01 13:11:52.755 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:244], payload:{"Output":8,"Status":0,"Watt":0,"ID":956,"Type":1,"Kind":4,"Description":"Deurslot (35.9)","Group":{"ID":5,"Name":"Deursloten"},"IpAddress":"10.10.60.35","Port":1001,"Protocol":0,"Visible":true,"MobileVisible":true,"MobileIcon":8,"SubSystem":2}}
08-01 13:11:56.982 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: process(641): {�~}{"Temp":{"Act":21.1,"Pre":16.7,"Max":44,"Min":0},"SunSouth":{"Act":26,"Pre":31,"Max":99,"Min":0},"SunEast":{"Act":19,"Pre":15,"Max":99,"Min":0},"SunWest":{"Act":17,"Pre":50,"Max":95,"Min":0},"DayLight":{"Act":658,"Pre":999,"Max":999,"Min":0},"Rain":false,"RainPre":false,"Twilight":true,"TwilightPre":false,"Wind":{"Act":0,"Pre":1.4,"Max":35,"Min":0},"GpsReport":true,"Elevation":-17,"Longitude":3.8,"Latitude":50.9,"Status":2,"ID":2,"Type":55,"Kind":0,"Description":"Weerstation","Group":{"ID":24,"Name":"Weerstation"},"IpAddress":"10.10.1.9","Port":30101,"Protocol":2,"Visible":false,"MobileVisible":false,"MobileIcon":0,"SubSystem":0}}
08-01 13:11:56.983 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: afterDecoding(637): {{"Temp":{"Act":21.1,"Pre":16.7,"Max":44,"Min":0},"SunSouth":{"Act":26,"Pre":31,"Max":99,"Min":0},"SunEast":{"Act":19,"Pre":15,"Max":99,"Min":0},"SunWest":{"Act":17,"Pre":50,"Max":95,"Min":0},"DayLight":{"Act":658,"Pre":999,"Max":999,"Min":0},"Rain":false,"RainPre":false,"Twilight":true,"TwilightPre":false,"Wind":{"Act":0,"Pre":1.4,"Max":35,"Min":0},"GpsReport":true,"Elevation":-17,"Longitude":3.8,"Latitude":50.9,"Status":2,"ID":2,"Type":55,"Kind":0,"Description":"Weerstation","Group":{"ID":24,"Name":"Weerstation"},"IpAddress":"10.10.1.9","Port":30101,"Protocol":2,"Visible":false,"MobileVisible":false,"MobileIcon":0,"SubSystem":0}}
08-01 13:11:56.983 4809-4859/com.ipbuilding.ipbtouchlayout I/System.out: matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:637], payload:{"Temp":{"Act":21.1,"Pre":16.7,"Max":44,"Min":0},"SunSouth":{"Act":26,"Pre":31,"Max":99,"Min":0},"SunEast":{"Act":19,"Pre":15,"Max":99,"Min":0},"SunWest":{"Act":17,"Pre":50,"Max":95,"Min":0},"DayLight":{"Act":658,"Pre":999,"Max":999,"Min":0},"Rain":false,"RainPre":false,"Twilight":true,"TwilightPre":false,"Wind":{"Act":0,"Pre":1.4,"Max":35,"Min":0},"GpsReport":true,"Elevation":-17,"Longitude":3.8,"Latitude":50.9,"Status":2,"ID":2,"Type":55,"Kind":0,"Description":"Weerstation","Group":{"ID":24,"Name":"Weerstation"},"IpAddress":"10.10.1.9","Port":30101,"Protocol":2,"Visible":false,"MobileVisible":false,"MobileIcon":0,"SubSystem":0}}
08-01 13:11:57.006 4809-4820/? W/art: Debugger told VM to exit with status -1
## Context

Our app is a solution for home automation. It makes a connection to the server to receive status update from lights etc. and receive emergency alerts for care solutions. So I have 2 instances of the websocket. One is connected, the other one not....
## Your Environment

* Version used: 1.3.8
* Java version: compileSdkVersion 27
* Operating System and version: Android 5.1.1
* Endpoint Name and version: 
* Link to your project:

**Comment by marci4** [comment]
Hello @Davevb,

sorry for the delayed response. I swear I already asked you these questions.... ;)

The debug log is not really helpful. 
Could you answer me the following questions?
- What server are you using as the other endpoint
- Are you using wss?
- Does this happen on all devices or special ones?
- Could you provide an example application?

Best regards,
marci4

**Comment by Davevb** [comment]
Hi, Sorry. I was on holiday.

- The server we are using is a small "black box" with Windows 10 IoT running on it.
-  No just ws
- I can only test on 1 device and that's our touchscreen (http://prodvx.com/products/integrated-android-displays/prodvx-appc-10-dskp-poe)
- This is hard. Because you will need a full home automation installation. The touchscreen connects locally to the instalation with the WIndows 10 Iot

Best regards

**Comment by marci4** [comment]
Hello @Davevb,

sorry if I don't understand you but why can you not just simple make an application on how you reconnect? Or does it only happen on this specific device with this specific server? Then you may wanna look into the specific hard/software.

Also by any change is this issue solved with 1.3.9? Just making sure we have the same version ;)


Apart from that I am not really sure how I am supposed to help without a specific example application.... 

Best regards,
marci4

**Comment by marci4** [comment]
Any update?

**Comment by marci4** [comment]
No feedback. Dead issue....

Closing it!

Best regards,
marci4
