### ISSUE TITLE
Improve code quality for 1.4.0

### ISSUE THREAD

**Issue by marci4** [TooTallNate/Java-WebSocket#749]
## Expected Behavior

SonarQube should not report to a lot of errors.

## Current Behavior

Currently SonarQube reports some errors. These should be fixed!

## Possible Solution

Fix errors found or disable rules!

## Context

Code quality

**Comment by PhilipRoman** [comment]
Glad to see I'm not the only one staring at SonarQube reports 😮!  On a more serious note, I think the first thing to do should be splitting up the large methods into smaller ones. This is guaranteed not to break anything and it could even help to achieve better performance. Reading some of the code currently is quite hard and improving code quality may help more people contribute in the future.

Again, thanks for bringing this up!

**Comment by marci4** [comment]
Yeah we really have to do this!
Helps us and everyone checking all the methods.
Especially the WebSocketServer is a beauty in itself ;)

**Comment by marci4** [comment]
@PhilipRoman could you send me an email please? I would like to get your input on a few things if it is fine with you !

**Comment by marci4** [comment]
We have a code close for 1.4.0.

Maybe opening another issue for 1.4.1.

Closing this issue as solved!
