### ISSUE TITLE
What add path in WebSocketServer for android ?

### ISSUE THREAD

**Issue by MrsCheng** [TooTallNate/Java-WebSocket#750]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Java version:
* Operating System and version:
* Endpoint Name and version:
* Link to your project:

**Comment by PhilipRoman** [comment]
Please add more information about your problem using the given issue template (issues without template may be closed). Currently the question is unclear.

**Comment by PhilipRoman** [comment]
I'm closing this because there is no template or other info provided.
