### ISSUE TITLE
onFragment() deprecated?

### ISSUE THREAD

**Issue by egueli** [TooTallNate/Java-WebSocket#751]
Hi all,

the application I'm maintaining overrides `WebSocketServer.onFragment(Websocket, Framedata)`. The IDE marks that method as deprecated, because of this annotation:
https://github.com/TooTallNate/Java-WebSocket/blob/8e9c82a138ff7b2f137e73a8b1df913aae317a17/src/main/java/org/java_websocket/client/WebSocketClient.java#L647

* why is `onFragment` deprecated?
* what should one do instead?

Thank you for any information!

**Comment by egueli** [comment]
I see this is related to https://github.com/TooTallNate/Java-WebSocket/pull/570/.

If I read correctly the changes, `WebsocketListener.onWebsocketMessageFragment()` will never be called anymore and neither will `WebsocketServer.onFragment()`?

**Comment by marci4** [comment]
Hello @egueli,

These changes where made since most of the users expected to receive all messages using OnMessage regardless of how the message was sent.
You're application should work without any problems by simply using OnMessage (string/bytebuffer)

Best regards,
marci4

**Comment by egueli** [comment]
Thank you. In my case, there wasn't much logic in `onFragment` so I could remove it altogether.
