### ISSUE TITLE
Use a SocketFactory to support reconnecting

### ISSUE THREAD

**Issue by VolodymyrSmolynets** [TooTallNate/Java-WebSocket#764]
https://github.com/TooTallNate/Java-WebSocket/blob/219f54e0f68a66b2cffab1a327e5cf57044deb4f/src/main/java/org/java_websocket/client/WebSocketClient.java#L227

please add

public void reconnect(Socket socket) {
        reset();
        setSocket(socket);
        connect();
    }

or make reset public

**Comment by marci4** [comment]
Hello @VolodymyrSmolynets 

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md.

Without a full bug report this will be closed.

Best regards,
marci4

**Comment by VolodymyrSmolynets** [comment]
It is not a defect, just cannot reconnect with with socket I want.

**Comment by marci4** [comment]
Please use the template to let me understand the use case, why you need such a method, some steps to repeat etc....

**Comment by VolodymyrSmolynets** [comment]
1. I create a ssl socket with my keystore
2. Set the socked - WebSocketClient.setSocket
3. Connect
4. Lose a connection
5. Try to reconect - WebSocketClient.reconect

On step 5 I lose my ssl socket because reset() make it null, than connect create a new usual socket.

**Comment by marci4** [comment]
So it would be better if you can set a `SocketFactory` instead of a `Socket`? 
So you do not have to take care for this?

**Comment by VolodymyrSmolynets** [comment]
Yes, it could be a solution.
