### ISSUE TITLE
Reload SSL Certificate

### ISSUE THREAD

**Issue by FlorentMasson** [TooTallNate/Java-WebSocket#765]
I just saw the Let's Encrypt example here:  [Java-WebSocket/src/main/example/SSLServerLetsEncryptExample.java ](https://github.com/TooTallNate/Java-WebSocket/blob/fa3909c391195178ccf5a92d4ac342a30ae247c8/src/main/example/SSLServerLetsEncryptExample.java)
Is the certificate updated automatically in the server when the file changes (letsencrypt certificates expire after 90 days), or is a reload needed? If the latter, is there a way to reload the certificate without restarting the websocket server and losing existing connections?

**Comment by marci4** [comment]
Hello @FlorentMasson,

no it does not automatically reload. It is an example just for the simple purpose to show how to get a SSLContext with a Let's Encrypt certificate and how to use it with this library...

Yes, simple update the `WebSocketFactory`.

Best regards,
marci4

**Comment by marci4** [comment]
Issue should be solved, since the question is answered!

Closing it.
Best regards,
marci4
