### ISSUE TITLE
Setup example servers

### ISSUE THREAD

**Issue by marci4** [TooTallNate/Java-WebSocket#766]
## Expected Behavior

This project should have some example servers with client examples!

## Current Behavior

This project does not have any example servers!

## Possible Solution

Example servers for:
- [x] [Echo](https://github.com/marci4/Java-WebSocket-Echo)
- [ ] Accept Handshake
- [ ] Protocols and protocol rejection

## Context

This would help people understand different behaviours!

**Comment by pellyadolfo** [comment]
I have been trying to understand some scenarios for a few days but many things are still are unclear to me, e.g.:
* how to transfer an object between client and server with ByteBuffer. Is this possible with serialization?
* how to transfer a map of values between client and server and back in a single message

I like the project, and would like to contribute new functionalities, but I need to find out how reliable is accessing a mobile phone by IP, specially when they are behind a firewall (and some ports are closed), or behind an intranet , an therefore with local IPs. I am still unclear about this. Great work anyway.

**Comment by marci4** [comment]
Hello @pellyadolfo,

please open a separate issue for these questions.

This issue is to track the progress of setting up running servers e.g. echoing a message back.

Apart from this, it looks like all of these messages are not directly linked on how to use the library but more standard java question. 

Best regards,
marci4
