### ISSUE TITLE
Android 8.0 (Oreo) : the server is not getting a client request through websockets

### ISSUE THREAD

**Issue by IlyaMyasoedov** [TooTallNate/Java-WebSocket#767]
## Summary
I use a Java-Websocket library for communication with server. The client sends a request through websockets and there are no exceptions on a client side but the server is not getting anything. Meanwhile the connection is established and when the server sends something to the client, the client is getting the data without errors.The issue is reproduced on Android 8+ only, on devices with Andorid 7.1 and below the behaviour is correct.

## Expected Behavior
The server is getting all the data the client is sending on devices with Android 8+ OS.

## Current Behavior
The server is not getting anything the client is sending on devices with Android 8+ OS.

## Note
I reproduced on devices: LG Nexus 5X, Xiaomi Redmi 6.; the issue is reproduced on 1.3.9 version

**Comment by marci4** [comment]
Hello @IlyaMyasoedov,

please provide an example application!

Best regards,
marci4

**Comment by IlyaMyasoedov** [comment]
I developed an example app that communcates with  3rd party server and all works without errors. That's why I suppose the issue is connected to our server.
