### ISSUE TITLE
Callbacks like onMessage, onClose, are sequential or not

### ISSUE THREAD

**Issue by chuntakung** [TooTallNate/Java-WebSocket#776]
A quick question: Callbacks like onMessage, onClose, are sequential or not 
More specifically, when onMessage is called and not finished yet, onClose can be called to interrupt the execution of onMessage? 

## Expected Behavior

I originally expect them to be sequentially executed

## Current Behavior

Looks it could be preempted. 

## Possible Solution

question and info only

## Steps to Reproduce (for bugs)

question and info only

## Debug log (for bugs)

question and info only

## Context

general 

## Your Environment

* Version used:
* Java version:
* Operating System and version:
* Endpoint Name and version:
* Link to your project:

Android 6

**Comment by marci4** [comment]
Hello @chuntakung,
are you talking about the server side or the client side?

Best regards,
marci4

**Comment by chuntakung** [comment]
Sorry, not elaborate. I am talking about server side.

**Comment by marci4** [comment]
Hello @chuntakung,
sorry for my delayed response. I am currently really busy....

Depending on the number of decoders defined in the constructor call of the WebSocketServer (default is the number of available processors using `Runtime.getRuntime().availableProcessors()`) we spawn a number of workers which decode the incoming message and call the respective method (like onOpen, onClose, onMessage).

Each connection does currently get one specific worker, which then does everything described above!

Therefore it is not possible what onMessage and onClose both are called the same time.

This could however be subject to change in the feature for a more free floating thread approach.

Apart from this the execution of onClose will not interrupt onMessage!

Best regards,
marci4

**Comment by marci4** [comment]
Issue should be answered. Closing it!

Best regards,
marci4
