### ISSUE TITLE
Can I get binary package message?

### ISSUE THREAD

**Issue by yangxsa** [TooTallNate/Java-WebSocket#777]
## Expected Behavior
I can get a binary package,and transform the package.

## Current Behavior
I can't get messages from the websocket server， I am sure websocket is connect success.
## Possible Solution

This is what I got from browsers.
![problem](https://user-images.githubusercontent.com/25025324/45795097-7198f500-bccc-11e8-9ed9-2d68d97068b8.png)
>
The onmessage method's param is type of String,By the way asked can i get binary package message?
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:1.3.9
* Java version:JDK 1.8
* Operating System and version:
* Endpoint Name and version:
* Link to your project:

**Comment by PhilipRoman** [comment]
There are two different `onMessage` methods that you can override - `onMessage(WebSocket, String)` and `onMessage(WebSocket, ByteBuffer)`. Overriding the last one will allow you to receive binary data. 

You can find more information on the [wiki](https://github.com/TooTallNate/Java-WebSocket/wiki).

**Comment by yangxsa** [comment]
Thanks a lot.
