### ISSUE TITLE
Websocket channel not close when network disconnect

### ISSUE THREAD

**Issue by zzhouag** [TooTallNate/Java-WebSocket#778]
## Expected Behavior

websocket client should be closed when I turn off network on client.

## Current Behavior

When I turn off network on Android device, the websocket connection is still established.

## Steps to Reproduce (for bugs)

1. create websocket client and establish a connection to server.
2. turn off network on client.
3. enter onClose callback on debug mode.
4. check server tcp port status, the connection is still established.

## Context

I will do reconnect in onClose callback, so if the previous connection is not be closed, then one more connection will be established.

## Your Environment

* Version used: 1.3.9
* Java version: 1.8
* Operating System and version: macOS 10.13.6, Android Studio 3+
* Endpoint Name and version: Android 8.0
* Link to your project:

**Comment by PhilipRoman** [comment]
Hello!
Thanks for your bug report.
Could you please add more information, such as versions, steps to reproduce and debug log? Issues without enough information may be closed.

**Comment by sepehr1014** [comment]
We have the same issue when calling reconnect. The tcp connection is never closed and the server quickly runs into port exhaustion.

**Comment by marci4** [comment]
Hello @zzhouag,

that is not a bug, this is simple because this is a Java library and not an Android library.
Therefore we cannot listen to such events and implemented a heart-beat check with the [lost connection detection feature](https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection).

@sepehr1014 please open a separate issue for that and include an example application!

Best regards,
marci4

**Comment by XJIOP** [comment]
Unfortunately on Android setconnectionlosttimeout does not work on websocket server.

**Comment by NoahAndrews** [comment]
@XJIOP It works fine in an Android app I work on.

**Comment by XJIOP** [comment]
> @XJIOP 
When disappears network or manually turn off Wi-Fi, there are no events about network loss. 
Should there be some kind of listener for network loss?

```
serverSocket = new ServerSocket(new InetSocketAddress(HOST, PORT));
serverSocket.setReuseAddr(true);
serverSocket.setTcpNoDelay(true);
serverSocket.setConnectionLostTimeout(5);
serverSocket.start();
```
