### ISSUE TITLE
Flushing the WebSocket / Limiting the buffer size

### ISSUE THREAD

**Issue by BaraHashesh** [TooTallNate/Java-WebSocket#779]
I'm trying to flush the data in the buffer of the WebSocket, is there any built in method that supports this operation?

I'm currently trying to move/send large amounts of data, however I noticed that the buffer for the WebSocket keeps getting bigger rather than waiting for old data to be sent, this may cause a problem if the device that is processing the data to be sent has a small limited RAM (which is the case in my use-case).

So is there any way to force flush the data or limit the size of the buffer?

I'm currently using java jdk8 and the 1.3.9 version of this library

**Comment by marci4** [comment]
Hello @BaraHashesh,

I think you may wanna take a look at the [fragmented example](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/FragmentedFramesExample.java) if you want to send a lot of data.
Of course we do not wait for data to be send, we send it whenever it is possible by the underlying socket. 
If that is really a problem, you may wanna think about not sending all the data at once!

No, based on your non existing bug report/detailed information, there is no reason for this behaviour....

Best regards,
marci4
