### ISSUE TITLE
Release Notes?

### ISSUE THREAD

**Issue by mikaelm12** [TooTallNate/Java-WebSocket#780]
I was just wondering if you could post a quick note about the changes in the `1.3.9` release. I'm not seeing any release notes about the new version. Any information would be appreciated!
Thanks!

**Comment by marci4** [comment]
Hello @mikaelm12,

you can find the release note and everything important [here](https://github.com/TooTallNate/Java-WebSocket/releases/tag/v1.3.9).

Best regards,
marci4
