### ISSUE TITLE
The Server wiki page should explain how to set the number of decoding threads

### ISSUE THREAD

**Issue by NoahAndrews** [TooTallNate/Java-WebSocket#782]
You can set the number of decoding threads by using one of the `WebSocketServer` constructors that takes a `decodercount` parameter. The last sentence of the [Server wiki page](https://github.com/TooTallNate/Java-WebSocket/wiki/Server) implies that this is not yet possible. I'd fix it myself, but I don't know the status of other ways to tweak performance that are mentioned there.

**Comment by marci4** [comment]
Hello @NoahAndrews,

thank you for spotting that!

Do you mind changing it? Thank you!

Best regards,
marci4

**Comment by NoahAndrews** [comment]
Done

**Comment by marci4** [comment]
Thank you very much !
