### ISSUE TITLE
Building with gradle fails

### ISSUE THREAD

**Issue by theAprel** [TooTallNate/Java-WebSocket#784]
**Describe the bug**
`./gradle build` fails immediately, with many errors similar to the following:
```
Java-WebSocket/src/main/java/org/java_websocket/server/WebSocketServer.java:56: error: package org.slf4j does not exist
import org.slf4j.Logger;
```

**To Reproduce**
Run `./gradle build`

**Expected behavior**
Java-WebSocket builds properly

**Additional context**
`build.gradle` hasn't been updated since the slf4j dependencies were introduced to the project. I have a PR for this. These dependencies were added only to maven (pom.xml).

**Comment by theAprel** [comment]
Fixed here: https://github.com/TooTallNate/Java-WebSocket/pull/785

**Comment by marci4** [comment]
Hello @theAprel,

thank you for your bug report and thank you for spotting this!

PR looks good, thank you again for your contribution.

Best regards,
marci4
