### ISSUE TITLE
How to properly stop the server

### ISSUE THREAD

**Issue by iamchathu** [TooTallNate/Java-WebSocket#786]
**Describe what you would like to know or do**
I'm running WebSocket server in Java SE Swing Application. I created a SwingWorker Thread and use `.run()` to start the server. When I need to stop the server How can I to it? I use .stop() method UI get freeze.

**Describe the solution you'd considered**
A proper way to stop the server.

**Additional context**

**Comment by marci4** [comment]
Hello @iamchathu,

please provide your source code.

Normally you just start the websocketserver with .start() and stop it with stop().

I do not thing there is something special needed for Swing.

Best regards,
marci4

**Comment by NoahAndrews** [comment]
Sounds like you might be attempting to stop the server by killing the SwingWorker? Make sure you call stop() on the websocket server instance itself.

**Comment by marci4** [comment]
Is this issue solved for you? @iamchathu

**Comment by iamchathu** [comment]
@marci4 No. This the code I have written.

This is the SwingWorker (To run on a sepate thread, since when I use run method it freezes the UI)

```
public class WSSWorker extends SwingWorker<Void, Void> {

    private String host = "192.168.1.4";
    private int port = 8887;

    private WSServer wss = null;

    public WSSWorker(WSListener listner) {
        wss = new WSServer(new InetSocketAddress(host, port), listner);
    }

    public void sendMessage(String message) {
        if (wss.getConnectedSocket() != null && wss.getConnectedSocket().isOpen()) {
            wss.getConnectedSocket().send(message);
        } else {
// throw error
        }
    }

    @Override
    protected Void doInBackground() {
        wss.setReuseAddr(true);
        wss.setTcpNoDelay(true);
        wss.run();
        return null;
    }

    @Override
    protected void done() {
        super.done();
        System.out.println("Stopping");
        try {
            wss.stop();
        } catch (IOException ex) {
            Logger.getLogger(WSSWorker.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(WSSWorker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
```

When I try to stop the Worker using

`wssw.cancel(false);`

It freeze the UI.

**Comment by marci4** [comment]
Hello @iamchathu,

I am sorry but I still does not get what you are trying to achieve and why you do not use the normal `.start()` and `.stop()` method for your swing application!

I also created a really simple application and to not see the need for a separate thread (see [here](https://github.com/marci4/Java-WebSocket-Stop)).

Best regards,
marci4

**Comment by marci4** [comment]
Is this issue solved?

**Comment by marci4** [comment]
Closing this issue since it should be solved and all questions answered.

Best regards,
marci4
