### ISSUE TITLE
How to provide http proxy server's username and password

### ISSUE THREAD

**Issue by defning** [TooTallNate/Java-WebSocket#787]
## How to provide http proxy server's username and password
My WebSocket client need to connect server via http proxy server and proxy server's username and password need to be provided. But there is only an Proxy class I can use (eg. client.setProxy(proxy)). How can I provide username and password? Thank you very much!

**Comment by marci4** [comment]
Hello @defning,

how you have to provide the username and password?
Is it done by using http headers? Then simply use the different constructor.

Best regards,
marci4

**Comment by marci4** [comment]
Dead issue.

Closing it .

Best regards,
Marcel
