### ISSUE TITLE
when do you plan to release version 40?

### ISSUE THREAD

**Issue by AlanVerne** [TooTallNate/Java-WebSocket#788]
Looks like reset() function removes socket
`this.socket = null;`

and ssl configuration becomes lost. and factory in 40th version should fix it.

**Comment by AlanVerne** [comment]
reset() is private so i don't know how to reconnect and set up socket now

**Comment by marci4** [comment]
Hello @AlanVerne,

No ETA, mostly since I am too busy with my normal work right now!

You can however use the snapshots (find the link in the readme) or build from master.

Best regards,
marci4
