### ISSUE TITLE
Is the order of onMessage calls guaranteed to be the same as when the messages were received?

### ISSUE THREAD

**Issue by NoahAndrews** [TooTallNate/Java-WebSocket#794]
I'm wondering if it's possible for WebSocket messages to be processed out of order. It seems like it could happen, since they're being processed by multiple decoder threads.

**Comment by marci4** [comment]
Hello @NoahAndrews,

for me this issue was already answered in #776 and therefore a duplicate.

Best regards,
marci4

**Comment by marci4** [comment]
Duplicate and therefore closing it!

Best regards,
marci4
