### ISSUE TITLE
Receive binary data on the server

### ISSUE THREAD

**Issue by nbtdev** [TooTallNate/Java-WebSocket#796]
The RFC does not prohibit servers receiving binary data. Is there a reason that Java-WebSocket only receives string data on the server? (the only `onMessage` method on `WebSocketServer` handles String data). 

I am trying to replace a `ServerSocket` implementation with `WebSocketServer` and the current system sends binary data in both directions. While I could use something like JSON in the client -> server direction, I am trying to be the least intrusive I can in this particular case. 

While it's true that the vast majority of use cases for WebSocket protocol are web-browser <--> web/app-server, there are times when a particular architecture is made easier if WebSocket were used. In my case, that is because I intend to use nginx to reverse-proxy some upstreams and I want each connection routed to a specific upstream based on a component of its URI (this allows me to use nginx without modification or unusually esoteric methods). 

If the answer to the top question is "because we haven't needed it before" I am fine with implementing it and submitting a PR, if there is interest in having this ability.

**Comment by nbtdev** [comment]
HAH! Never mind, it didn't occur to me to look through the *closed* issues, for example, #777...IntelliJ only implements one of the `onMessage` methods when you have it do it automatically...

**Comment by marci4** [comment]
Hello @nbtdev,

yeah we enforce the implementation of onMessage(String) but you can always overwride the onMessage(ByteBuffer).

Sorry for the confussion!

Best regards,
marci4
