### ISSUE TITLE
Missing api setSocketFactory

### ISSUE THREAD

**Issue by uncleleonfan** [TooTallNate/Java-WebSocket#802]
Cannot find setSocketFactory in version 1.3.9 at WebSocketClient.

**Comment by PhilipRoman** [comment]
This method was added after release 1.3.9 (#770). You can use [nexus](https://oss.sonatype.org/content/repositories/snapshots/org/java-websocket/Java-WebSocket/) (or [jitpack.io](jitpack.io)) to obtain latest versions of this project.

**Comment by uncleleonfan** [comment]
@PhilipRoman 
Thanks, setSocketFactory only found in v1.4.0 from nexus.
