### ISSUE TITLE
Server is not switching protocols

### ISSUE THREAD

**Issue by apexJCL** [TooTallNate/Java-WebSocket#812]
**Describe the bug**
Platform: Android (8.0, October patch)
Language: Java

Mounting the WebSocket Server works, the binding with the port succeeds and you can even use a client (tried with a Chrome's extension and a Python client) to connect and send/receive data.

Now, when trying to connect to the server using an ESP8266 (specifically a NodeMCU with the websocket module), the client cannot connect to the server.

The server does not sends logs nor seems to trigger events, and the client returns an error opcode `-17` that's listed as "Server is not switching protocols". The connection fails inmediately.

I even tested mounting a WebSocket server on my laptop and the ESP8266 could connect successfully. Also, my main project is running on Flutter, so mounted a WebSocket Server using Dart and the ESP8266 connected successfully also, so I think that there's an issue with the handshake or protocol upgrade.

**To Reproduce**
1. Mount WebSocket Server on Android
2. Try to connect with an ESP8266 (either with NodeMCU or using ESP8266 Arduino Core)
3. Connection fails inmediately

**Example application to reproduce the issue**
// TODO

**Expected behavior**
ESP8266 connecting successfully to the WebSocket server

**Debug log**
// TODO
The the debug log ('WebSocketImpl.DEBUG = true') to help explain your problem.

**Environment(please complete the following information):**
 - Version used: 1.3.9.
 - Java version: OpenJDK 8
 - Operating System and version: Arch Linux / Android 8.0.0 / NodeMCU 2.2.1-master_20180915
 - Endpoint Name and version: N/A
 - Link to your project: N/A

**Additional context**
N/A

**Comment by marci4** [comment]
Hello @apexJCL,

Could you please provide an example application as well as the debug log?

Could this issue be related to https://github.com/nodemcu/nodemcu-firmware/issues/2211 ?

Are you trying to connect over ws or wss?

Could you also provide the debug log of the NodeMCU  module?

Best regards,
Marcel

**Comment by marci4** [comment]
Could also be related since the nodemcu client may send a sec-websocket-protocol which is not enabled and therefore could result in a reject....
However the log would tell that as well.
https://github.com/nodemcu/nodemcu-firmware/blob/8181c3be7aed9f0a0ceb73ac8137c1a519e8a8e9/app/websocket/websocketclient.c#L76

**Comment by marci4** [comment]
Any update @apexJCL ?

**Comment by apexJCL** [comment]
Sorry, I've been very busy, I'll try to set things up these weekend and
notify on any updates.

**Comment by marci4** [comment]
Still no feedback!

Closing dead issue.
Best regards,
Marcel
