### ISSUE TITLE
java websocket library does not support "JKS" for WSS

### ISSUE THREAD

**Issue by testmayank013** [TooTallNate/Java-WebSocket#815]
**Describe the bug**
I am using java web socket library in android for connection on wss server. I m using Android api 5.1 and 8.0 for web socket client implementation. My issue is when i am trying the SSLClient example, Keystore doesn't support JKS.

The error is... 

java.security.KeyStoreException: java.security.NoSuchAlgorithmException: KeyStore JKS implementation not found

**Environment(please complete the following information):**
 - Java version: 1.7
 - Operating System and version: android 5.1 and 8.0

**Comment by marci4** [comment]
Hello @testmayank013,

check out https://github.com/TooTallNate/Java-WebSocket/wiki/FAQ:-Secure-WebSockets#wss-on-android for android ssl usage.

Best regards,
marci4
