### ISSUE TITLE
How do I send a ArrayBuffer over a WebSocket?

### ISSUE THREAD

**Issue by Pikachu920** [TooTallNate/Java-WebSocket#816]
**Describe what you would like to know or do**
I am working on custom server software for a web game. This web game reads in game packets as javascript `ArrayBuffer`s like so:
```javascript
this.ws.onmessage = function(e) {
                                for (var t = new u.MsgStream(e.data); ; ) {
```
where the constructor for MsgStream does this:
```javascript
            function e(t) {
                i(this, e);
                var a = t instanceof ArrayBuffer ? t : null;
                this.valid = null != a,
```

**Describe the solution you'd considered**
I have tried sending a `ByteBuffer` to the `WebSocket`, but this results in the client receiving a `Blob` instead of an `ArrayBuffer`.

**Additional context**
Unfortunately, I can't change the client code.

Thanks for your work on the project.

**Comment by NoahAndrews** [comment]
You have to specify in js which way you would like the data.

**Comment by PhilipRoman** [comment]
for the record, [binaryType](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/binaryType) is the property you're looking for.
Not sure what you mean by not being able to chage client, there is no way you can change that from the server side.

**Comment by Pikachu920** [comment]
ah shit, i forgot to set that in my debug environment.

what I meant with the not being able to change the client code is that I'm limited to doing things on the server side because I'm not the host/maintainer of the client.
