### ISSUE TITLE
How can I integrate the WebSocketClient with an event loop?

### ISSUE THREAD

**Issue by haelix888** [TooTallNate/Java-WebSocket#817]
I need to integrate the WebSocketClient with a different connection inside the same app. This would require the use of something like the java.nio.channels.SelectableChannel, which you poll using select(), possibly together with other pollables.

The documentation states "The underlying classes are implemented [using] java.nio, which allows for a non-blocking event-driven model", but this probably refers to the server-side WebSocket? It seems on the client-side one is expected to create a thread for the reading. This is not ideal.

**Describe the solution you'd considered**
Ideally the internals of the WebSocket should expose the event loop, or allow integration with an application-provided event loop.
The poorer alternative would be, for the application to create a reader thread which onMessage will push messages to a (pollable) blocking queue, which can in turn be used with select() or a similar non-blocking mechanism.

**Comment by PhilipRoman** [comment]
Personally, BlockingQueue has worked well for me. I don't really see why this is a "poor alternative". Do you mind elaborating on why you think it's bad?

**Comment by haelix888** [comment]
It's a poorer alternative in terms of performance of an application which is otherwise draught designed as single threaded (event driven), because it implies the additional thread switch and somewhat more code.

Can you please confirm my assumption above? "It seems on the client-side one is expected to create a thread for the reading.".  Is that how normally the WebSocket is integrated into apps? Thanks.

**Comment by PhilipRoman** [comment]
Well, I haven't used the client side but AFAIK on both sides this library runs in background, on a seperate thread (or you can just call "run" directly on any thread you want). As for performance penalty, in my experience BlockingQueue offers great throughput but not-so great latency (~20 microseconds unless you pin both threads on same cpu, not that it matters 99% of time). Honestly, if you are fine with 1 ms latency GC, you won't notice this at all. 

I've built a realtime game with WebSockets tons of blocking queues (~80 threads runing at the same time) where both latency and throughput are important and the bottleneck is either IO or physics engine. The cost of blocking queues is too small to be even considered.

Then again, if you find that a change to this library would yield a performance improvement for some users, I'd be interested in that.

**Comment by rahuls6** [comment]
Thanks for the implementation. However, I notice that when tested with 100 websocket clients there are 3x(300) odd threads created. So may be thats the reason as pointed by @haelix888 this implementaion doesnt use nio channel where we can have a single event loop by passing the selector. Honestly, this client choked when the number of client exceeded 1000 since it eats up lot of memory and I/O. It would be great if it was purely non-blocking one.

**Comment by haelix888** [comment]
That and the latency hit *although* I admit that is very rare to be latency sensitive at websocket level (you'd use a lower level protocol) AND if you're sensitive the rest of the code in the system would be super fast already

**Comment by PhilipRoman** [comment]
The server is purely non-blocking and number of threads will remain constant. 

The client, however, currently uses 3 threads per instance. Creating this many client instances in a single application (as opposed to receiving many connections in server) is not typical and I don't see a use case for this (apart from load testing maybe). 

What's your reason for creating so many clients?
