### ISSUE TITLE
There is  2 opening web client,when i refresh the web page, at server,the another one socket is closed.

### ISSUE THREAD

**Issue by bigyShot** [TooTallNate/Java-WebSocket#820]
**Describe what you would like to know or do**
Hi there,i want to get help from you.please.i just using webSockerServer to build a b/s  chat system.when i in 2 browsers to connect the server,let's call it a,b. when they started to connect,it's alright,but when i refresh a,i didn't receive the
reply of function onclose for a,i received the reply of function onclose for b.what happend,how can i solve it.

**Describe the solution you'd considered**
please!Emergency!

**Additional context**
My English is not well,may i didn't speak this to u clearly,so  i want to describe here again:   i have two connections of web to my server,when i close a,but the b is closed in server.it trigger  onClose function,the  server told me that a is closed when i refresh connection a's page.maybe the server mixed every connection from browser.

**Comment by PhilipRoman** [comment]
Hello!
Can you provide a simple example application (both client and server side) which reproduces the bug? 
Also, what browser are you using? Firefox and Chrome behave differently when refreshing a page with an active WebSocket connection.

**Comment by bigyShot** [comment]
Hello,@PhiliRoman,
sorry for so late to reply you,and thanks for your reply.these days i'm busy with another thing,I didn't see your reply,I used both chrome and firefox,and i tried other browsers,it's the same situation.
The client side just the very normal websocket function,In the server,i define a global variety userId to identify the user who connected.And i build a list to store the list that connect the server,on the close function.I let the current user's status changed,be offline,remove it from the onlineList.I think maybe the server mixed the userId,but i don't know how to fix it.maybe lock the userId?it should be no use and impossible.here is the onclose code:
@Override
    public void onClose(WebSocket webSocket, int code, String reason, boolean remote) {
        //this userId is defined in class,be a global variety
        User user = userService.getUser(Integer.valueOf(userId));
       //let this user be offline
        user.setIsOnline(0);
        userService.updateUser(user);
        onLineList.remove(userId);
    }

**Comment by bigyShot** [comment]
hi@PhiliRoman,
i missed something,I start the server class at springbootApplication start class.
Server server=new Server(20818);
server.run();
just like this,could it caused this problem?

**Comment by bigyShot** [comment]
I alredy solved this,thanks
