### ISSUE TITLE
ReconnectClientExample does not work with wss

### ISSUE THREAD

**Issue by AlexisBrito** [TooTallNate/Java-WebSocket#825]
If I merge the SSLClientExample.java and ReconnectClientExample.java, the program will end after it closes the connection with the server, not having a chance to do reconnectBlocking();

Starting from the SSLClientExample.java, after the c.connectBlocking();, if I copy and paste this:

c.send( "hi" );
Thread.sleep( 10 );
c.closeBlocking();
              
//Disconnect manually and reconnect blocking
c.reconnectBlocking();
c.send( "it's" );
Thread.sleep( 10000 );
c.closeBlocking();
//Disconnect manually and reconnect
c.reconnect();
Thread.sleep( 100 );
c.send( "me" );
Thread.sleep( 100 );
c.closeBlocking();

It will only display "hi", but it should display "hi it's me".

**Comment by marci4** [comment]
Hello @AlexisBrito,

can your issue be related to #764 ?

Best regards,
Marcel

**Comment by marci4** [comment]
Hey @AlexisBrito,

It simple does not work since there is a System.exit(0) when the client disconnects from the server (see https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLClientExample.java#L63).

Best regards,
marci4

**Comment by AlexisBrito** [comment]
Hey @marci4,

Thanks a lot! It's working :D

Best regards!
