### ISSUE TITLE
Is there anyway to add headers to the websocket?

### ISSUE THREAD

**Issue by jadefountain** [TooTallNate/Java-WebSocket#826]
^

**Comment by PhilipRoman** [comment]
I believe you're looking for the constructor `WebSocketClient(URI, Map<String, String>)` which accepts a Map containing additional headers you want to pass.

**Comment by jadefountain** [comment]
Map<String, String> httpHeaders = new HashMap<String, String>();
httpHeaders.put("Key","Value");
and then adding it to WebSocketCline(URI,httpHeaders);
isn't working for me

**Comment by jadefountain** [comment]
Nevermind, I fixed it!
