### ISSUE TITLE
Running server with IPv4 seems not working

### ISSUE THREAD

**Issue by tarasmytlovych** [TooTallNate/Java-WebSocket#828]
**Describe the bug**

socket.bind( address );  call in run() method throws Method threw 'java.net.BindException' exception.
detailedMessage = "Cannot assign requested address"

**To Reproduce**
1. I am trying to run server with following parameters  
 String host = "194.44.201.130";
  int port = 8887;

 WebSocketServer server = new SimpleServer(new InetSocketAddress(host, port));
2. socket.bind( address );
address = "/194.44.201.130:8887"

It seems that it is impossible to run server with IP provided

V:    compile "org.java-websocket:Java-WebSocket:1.3.9"

**Comment by marci4** [comment]
Hello @tarasmytlovych,

no, server is running fine with IPv4 without any problems in production...

What we do is use the provided InetSocketAddress and bind the server socket to it.

Best regards,
Marcel

**Comment by marci4** [comment]
Normally you are not required to provide an host name only if you have multiple ip addresses.

Check out stackoverflow for possible solutions. 
This is simple not related to this project.

Best regards,

**Comment by marci4** [comment]
Any update ?

**Comment by marci4** [comment]
Closing dead question.

Best regards,
Marcel
