### ISSUE TITLE
在什么情况下收到的消息会进onMessage(WebSocket conn, ByteBuffer blob)

### ISSUE THREAD

**Issue by xiexiangwei** [TooTallNate/Java-WebSocket#830]
这边用protobuf发送下次，服务器应该走onMessage(WebSocket conn, ByteBuffer blob)才对啊，实际上调用的确是 onMessage(WebSocket conn, String message) ，还要做一次ByteBuffer blob =ByteBuffer.wrap(message.getBytes());转换，觉得很奇怪，是不是我哪里做错了？

**Comment by PhilipRoman** [comment]
Hello!
Please use the provided issue template and translate your question to English.

**Comment by marci4** [comment]
No template. 

Closing issue!

Best regards,
Marcel
