### ISSUE TITLE
Workers should be daemon threads

### ISSUE THREAD

**Issue by BobVul** [TooTallNate/Java-WebSocket#835]
Related to #834 

Currently workers are normal threads, which means they can prevent the application from terminating as long as they are running.

Consider making workers daemon threads instead, which should allow the application to terminate even if workers are not cleaned up correctly.

The server itself should probably stay a non-daemon thread (by default?) so that it does block termination.

**Comment by marci4** [comment]
Not sure if we want to allow a shutdown when there would still be something in the pipe and cleanup should be doing everything fine to my knowledge.

Is there any issue?

**Comment by marci4** [comment]
Any update?

**Comment by BobVul** [comment]
I guess it's more of a design question whether workers should persist past the server lifetime. I can see your reasoning that (since the other bug is fixed) workers should stay alive until processing has finished.

**Comment by marci4** [comment]
Closing this issue.

Best regards,
Marcel
