### ISSUE TITLE
Can it be reconnected automatically?

### ISSUE THREAD

**Issue by zoubihai** [TooTallNate/Java-WebSocket#840]
When I switch the mobile phone network, the websocket will be disconnected, will not reconnect, and then I will be reconnected when I report SSL handshake aborted: ssl=0xe0022880: I/O error during system call, Software caused connection abort, can I  @automatically Reconnection

**Comment by marci4** [comment]
Hello @zoubihai,

Please use the issue template to clarify your problem.

Best regards,
Marcel

**Comment by PhilipRoman** [comment]
No update; closing this issue!
