### ISSUE TITLE
connectBlocking must run on main thread?

### ISSUE THREAD

**Issue by zoubihai** [TooTallNate/Java-WebSocket#842]
**Describe what you would like to know or do**
A clear and concise description of what the problem is.

**Describe the solution you'd considered**
A clear and concise description of any solutions you've considered.

**Additional context**
Add any other context or links about the question here.

**Comment by PhilipRoman** [comment]
Hello! Please use the given issue template and clarify your question. Issues without template may be closed.

**Comment by PhilipRoman** [comment]
No update; closing this issue!
