### ISSUE TITLE
java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by nalizadeh** [TooTallNate/Java-WebSocket#847]
Hello community,
I am not sure if this is a bug or a mistake of mine. I'm trying to upload images from an HTML page, it works quite well with small images (max size = 16kb), but with large images the server throws the exception java.nio.BufferUnderflowException. 

![grafik](https://user-images.githubusercontent.com/34987997/51798122-c36b0200-220d-11e9-9fb8-d760d8211d63.png)

Is there a way to increase the frame capacity here?
I use the Firefox Quantum as a browser.

**Comment by PhilipRoman** [comment]
Could you reproduce this with Chrome? Thanks!

**Comment by nalizadeh** [comment]
Yes I also get the same exception with Chrom (version 71.0.3578.98)

**Comment by PhilipRoman** [comment]
Hmm... I can't reproduce this behaviour. I can successfully upload & download images of size over 40 MB. Can you post the relevant server side code as well? And maybe a specific image file which causes it to fail?

**Comment by marci4** [comment]
Was able to reproduce this with 65.0-64 bit running against the ChatServer example using your avatar image @PhilipRoman  (https://avatars2.githubusercontent.com/u/33231208?s=400&v=4)

Worked best when trying to upload the same image multiple times

Only affects Firefox currently as it seems..

**Comment by PhilipRoman** [comment]
Very strange. I've tried on Java 8 and Java 11; on Chrome, Firefox Quantum 64.0.2 (64-bit), MS Edge with my avatar and loads of other files I could find, but none of them triggered the error.

**Comment by marci4** [comment]
Looks like the bug cause is #805, in detail my refactoring of translateSingleFramePayloadLength (call by value instead of reference for realpacketsize).

**Comment by marci4** [comment]
@nalizadeh could you confirm that this only affects 1.4.0?

Best regards,
Marcel

**Comment by PhilipRoman** [comment]
Looks like it happens only on 1.4.0 (I was previously testing on 1.3.9)! I tested on library version 1.4.0 and it happens both on chrome and firefox. From what I can tell, like after receiving an image larger than 16 kb, the server throws the error and any further messages (both text and binary) cause the same error. By the way, sending a 40 MB image file causes the server to emit the error repeatedly, which probably means that it is caused on every frame.

**Comment by nalizadeh** [comment]
specific image file which causes it to fail  
-> any large image causes the error

server side code
-> I just took the ChatServer example and changed each "broadcast(..)" with "conn.send(..)"

java version & Java-WebSocket library version
->jdk1.8.0_72, Eclipse Java EE IDE Neon.3 (4.6.3), this includes the latest javax.websocket library

could you confirm that this only affects 1.4.0?
-> yes. I use the latest repository.

Good luck with bug fixing! :)

**Comment by marci4** [comment]
Fixing this tonight!

**Comment by nalizadeh** [comment]
Now that's solved for me, many Thanks :)
