### ISSUE TITLE
Need to fix java_websocket.drafts.Draft_10refuses handshake error. 

### ISSUE THREAD

**Issue by L0ks** [TooTallNate/Java-WebSocket#857]
I have been working on creating a connection to a server, using WebSocketClient. My connection method looks like this.

`
private void establishConnection() {
    URI uri;
        try {
            uri = new URI("wss://webs.mylink.com:1234");
        } catch (URISyntaxException e) {
            Log.i("MyLog", "URI error: " + e.getMessage());
            return;
        }
        Log.i("MyLog", "Creating webSocket: ");
        myWebSocketClient = new WebSocketClient(uri) {
            @Override
            public void onOpen(ServerHandshake handshakedata) {
                Log.i("MyLog", "Connection opened");
                try {
                    myWebSocketClient.send("/connect 2");
                } catch (Exception err) {
                    Log.i("MyLog", "Error in onOpen: " + err.getMessage());
                }
            }

            @Override
            public void onMessage(String message) {
                // STUFF HAPPENS
            }

            @Override
            public void onClose(int code, String reason, boolean remote) {
                Log.i("MyLog", "Connection closed: " + reason);
            }

            @Override
            public void onError(Exception ex) {
                Log.i("MyLog", "Connection error: " + ex.getMessage());
                checkCurrentConnection();
            }
        };
        trustAllHosts(myWebSocketClient);
        myWebSocketClient.connect();
    }
`

In order to connecto to a wss uri I created a method trustAllHosts, that imports org.java_websocket.client.DefaultSSLWebSocketClientFactory in to setWebSocketFactory into my websocketclient 
`
public static void trustAllHosts(WebSocketClient chosenSocket) {
        // Create a trust manager that does not validate certificate chains
        TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
            public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                return new java.security.cert.X509Certificate[]{};
            }

            public void checkClientTrusted(X509Certificate[] chain,
                                           String authType) throws CertificateException {
            }

            public void checkServerTrusted(X509Certificate[] chain,
                                           String authType) throws CertificateException {
            }
        }};

        // Install the all-trusting trust manager
        try {
            SSLContext sc = SSLContext.getInstance("TLS");
            sc.init(null, trustAllCerts, new java.security.SecureRandom());
            chosenSocket.setWebSocketFactory(new DefaultSSLWebSocketClientFactory(sc));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

Everything worked well, untill the uri had to be changed and now, all I get are errors stating that
> draft org.java_websocket.drafts.Draft_10@4560b1d0 refuses handshake

In order to fix issue, I tried adding different drafts into when creating my websocketclient, but it prooved fruitless. What I know, is that when connectiong cloudflare checks the socket in order to prevent any DDOS attacks.

Does anyone know, how could this issue be fixed? Should I use newer versions of the websocker like 1.3.9 or 1.3.8 ?
Thank you in advance!

**Comment by PhilipRoman** [comment]
Hello! 

Can you verify that the problem still happens with version 1.3.9?

**Comment by L0ks** [comment]
> Hello!
> 
> Can you verify that the problem still happens with version 1.3.9?

I tried using 1.3.9, but found out that this versions package org.java_websocket.client doesn't have DefaultSSLWebSocketClientFactory class. Atempts to connect to the server without using trustAllHosts method, I made, resulted in the following error

> Invalid status code received: 503 Status line: HTTP/1.1 503 Service Temporarily Unavailable

**Comment by marci4** [comment]
@L0ks looks like your server is not correctly working ...

**Comment by L0ks** [comment]
> @L0ks looks like your server is not correctly working ...
> 
> By the way it is not recommended to trust all certificates...

Which certificates should be trusted for the wss connection to work ?

**Comment by marci4** [comment]
@L0ks if you have a self signed certificate, you should add it to a keystore and trust it this way.

If you have a public signed certificate, java should be able to verify it without a keystore
