### ISSUE TITLE
Hot wo specify a custom DNS Resolver

### ISSUE THREAD

**Issue by liukefeng2008** [TooTallNate/Java-WebSocket#859]
**Describe what you would like to know or do**
I want to specify a custome DNS resolver, like `apache http client`
```
/**
 * Users may implement this interface to override the normal DNS lookup offered
 * by the OS.
 *
 * @since 4.2
 */
public interface DnsResolver {

    /**
     * Returns the IP address for the specified host name, or null if the given
     * host is not recognized or the associated IP address cannot be used to
     * build an InetAddress instance.
     *
     * @see InetAddress
     *
     * @param host
     *            The host name to be resolved by this resolver.
     * @return The IP address associated to the given host name, or null if the
     *         host name is not known by the implementation class.
     */
    InetAddress[] resolve(String host) throws UnknownHostException;

}

```

**Comment by marci4** [comment]
Hello @liukefeng2008,

could you please describe your usecase and what you are trying to achieve?

Best regards,
Marcel

**Comment by liukefeng2008** [comment]
Hello, I want to access some websocket resources, eg: (wss://api.fcoin.com/v2/ws).
In some countries,The default dns parsing behavior will resolve the wrong ip address, So I want to specify a custom dns parser.

1. [how-to-configure-hostname-resolution-to-use-a-custom-dns-server-in-java](https://stackoverflow.com/questions/11647629/how-to-configure-hostname-resolution-to-use-a-custom-dns-server-in-java)
2. [how-to-override-dns-in-http-connections-in-java](https://stackoverflow.com/questions/24350150/how-to-override-dns-in-http-connections-in-java)

I want to use the second way, but this library(`Java-WebSocket`) does not support this method. Is it possible to add a custom dns resolver?

**Comment by marci4** [comment]
Hello @liukefeng2008 

Thank you for a feedback.
Do I understand you correctly, you just need an API to set a InetAddress instead of an URL?

Best regards,
Marcel

**Comment by liukefeng2008** [comment]
I can't set the IP directly. Because the server only respond by the host.
If url `wss://api.fcoin.com/v2/ws`, it's work for me.
If url `wss://x.x.x.x/v2/ws`, it's not work.

**Comment by marci4** [comment]
I am not really sure if there are reallife usecases for this.

If someone has the time, feel free to implement a solution and we discuss it on the PR.

Best regards,
Marcel
