### ISSUE TITLE
Issue resume websocket and exit websocket

### ISSUE THREAD

**Issue by RalryOng** [TooTallNate/Java-WebSocket#862]
**Issue 1**
**Describe the bug**
1) I create android project and then create android library module, 
2) in library module, add Service, and put websocket.
3) in library module, add activity, start websocket.
4) in android project, add button "btn" to startactivity to library module.
5) compile app to test
6) click button "btn", then will go to library module
7) click phone home button.
8) go back app.
9) the app exit library module, go back android project.

**To Reproduce**
1. Open app
2. click phone home button
3 go back app
4. will get same result

**Expected behavior**
after go back app, should resume library module, not exit library module. 

**Issue 2**
1) in library module, add Service, and put websocket.
2) in library module, add activity, after finish use, cant close socket in activity.

Does anyone know, how could this two issue be fixed?
Thank you.

**Comment by marci4** [comment]
Hello @RalryOng,
please provide an example application.

Keep in mind this library is designed for Java and not Android.

Best regards,
Marcel

**Comment by RalryOng** [comment]
Hi Marcel, 

thank you for your reply, i will think other way.
