### ISSUE TITLE
Making server silent

### ISSUE THREAD

**Issue by konrad-ch** [TooTallNate/Java-WebSocket#864]
Is there a way to make WebSocketServer 100% silent? As for now it gives a constant console output. Thanks!

**Comment by PhilipRoman** [comment]
Make sure WebSocketImpl.DEBUG is not set to true.

**Comment by konrad-ch** [comment]
Could you elaborate? I'm using this example: https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/ChatServer.java (with all broadcast and println functions commented out) and still having a lot of trace logs.

**Comment by PhilipRoman** [comment]
By default there should not be any logging. If you have added a logger implementation to your project, refer to the configuration format of that logging library. 

For example, if you are using Logback, you can configure the logging process of this library using 
```xml
<logger name="org.java_websocket" level="WARN"/>
```

**Comment by marci4** [comment]
Question should be solved and therefore this issue!

Best regards,
Marcel
