### ISSUE TITLE
Lost connection detection is sensitive to changes in system time

### ISSUE THREAD

**Issue by NoahAndrews** [TooTallNate/Java-WebSocket#869]
Because Lost Connection Detection uses the `java.util.Timer` API [instead of the `ScheduledThreadPoolExecutor` API](https://stackoverflow.com/a/409993/4651874), it is sensitive to changes in the system time. For example, if you set the system time to a point years in the future, the `connectionLostTimerTask` will be called constantly, frequently causing disconnects as the clients cannot respond before the task is called again. This is particularly an issue for embedded devices that must have their clock set at runtime.

The best solution would seem to be to use the `ScheduledThreadPoolExecutor` API. I plan to submit a PR.

**To Reproduce**
1. Start a WebSocket server using this library
2. Set the system time to a few years in the future

**Comment by marci4** [comment]
Hey @NoahAndrews,

how can we solve the problem of the last pong received.

I used `System.currentTimeMillis()` for detecting a missing response.

See https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/WebSocketImpl.java#L804

Best regards,
Marcel

**Comment by NoahAndrews** [comment]
@marci4 I just updated PR #878 to fix that.

**Comment by NoahAndrews** [comment]
Speaking of lost connection detection, I just made this modification to the wiki: https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection/_compare/de53ff89cd759a2517cdb36199ce4daf78dbdbe9...4d3b2372b9907c77a23a93f7cf8f132c0fba0537

Let me know if you don't like anything I changed.

**Comment by marci4** [comment]
Looks good!
