### ISSUE TITLE
Embeddind into Servlet API

### ISSUE THREAD

**Issue by davibaldin** [TooTallNate/Java-WebSocket#870]
Hi,

I would like to add Java-WebSocket server into OSGi's HTTP Service. The way todo that is:

httpService.registerServlet("/websocket", new WebSocketServer()), params, null);

However, WebSocketServer must be a javax.servlet.Servlet class. 

Do you provides an implementation of this or is there a way to wrap WebSocketServer into a servlet class?

Regards,

Davi

**Comment by marci4** [comment]
Hello @davibaldin,

no, we do not provide such an implementation.
Maybe take a look at the WebSocketServlet class of Jetty (https://github.com/eclipse/jetty.project/blob/master/jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/WebSocketServlet.java).

Best regards,
Marcel

**Comment by marci4** [comment]
Hello @davibaldin,

is this question answered for you?

Best regards,
Marcel

**Comment by davibaldin** [comment]
Hi Marcel, you’ve drived to Jetty, however I’ve no lucky yet. 

Davi
