### ISSUE TITLE
ExtCertPathValidatorException

### ISSUE THREAD

**Issue by simonchius** [TooTallNate/Java-WebSocket#872]
Marshmallow and below device, as soon as I connect to the socket I am getting the following exception.

com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate expired at Mon Feb 18 19:55:00 GMT+05:30 2019 (compared to Thu Mar 21 21:36:06 GMT+05:30 2019)

Can you please check this issue?

**Comment by marci4** [comment]
Hello,
Looks like TLS1.2 is not active by default.
Take a look at this answer on stackoverflow https://stackoverflow.com/a/48947188

Here is an example on how to change ciphers and protocols SSLServerCustomWebsocketFactoryExample.java

Best regards, 
Marcel

**Comment by simonchius** [comment]
Hi Marcel, 

Thanks for the quick reply, I have tried that, even but my issue is getting resolved. Here is my code

`URI lURI = new URI(Constants.WEB_SOCKET_CONNECTION_URL);

mWebSocketClient = new WebSocketClient(lURI) {
    @Override
    public void onOpen(ServerHandshake handshakedata) {
        
    }

    @Override
    public void onMessage(String message) {
       
    }

    @Override
    public void onClose(int code, String reason, boolean remote) {
       
    }

    @Override
    public void onError(Exception ex) {
       
    }
};

mWebSocketClient.setSocketFactory(new TLSSocketFactory());
mWebSocketClient.connect();`

And the TLSSocketFactory File
`package com.full.anywhereworks.websocket;

import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;

import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocket;
import javax.net.ssl.SSLSocketFactory;

/**
 * @author fkrauthan
 */
public class TLSSocketFactory extends SSLSocketFactory {

    private SSLSocketFactory internalSSLSocketFactory;

    public TLSSocketFactory() throws KeyManagementException, NoSuchAlgorithmException {
        SSLContext context = SSLContext.getInstance("TLS");
        context.init(null, null, null);
        internalSSLSocketFactory = context.getSocketFactory();
    }

    @Override
    public String[] getDefaultCipherSuites() {
        return internalSSLSocketFactory.getDefaultCipherSuites();
    }

    @Override
    public String[] getSupportedCipherSuites() {
        return internalSSLSocketFactory.getSupportedCipherSuites();
    }

    @Override
    public Socket createSocket() throws IOException {
        return enableTLSOnSocket(internalSSLSocketFactory.createSocket());
    }

    @Override
    public Socket createSocket(Socket s, String host, int port, boolean autoClose) throws IOException {
        return enableTLSOnSocket(internalSSLSocketFactory.createSocket(s, host, port, autoClose));
    }

    @Override
    public Socket createSocket(String host, int port) throws IOException, UnknownHostException {
        return enableTLSOnSocket(internalSSLSocketFactory.createSocket(host, port));
    }

    @Override
    public Socket createSocket(String host, int port, InetAddress localHost, int localPort) throws IOException, UnknownHostException {
        return enableTLSOnSocket(internalSSLSocketFactory.createSocket(host, port, localHost, localPort));
    }

    @Override
    public Socket createSocket(InetAddress host, int port) throws IOException {
        return enableTLSOnSocket(internalSSLSocketFactory.createSocket(host, port));
    }

    @Override
    public Socket createSocket(InetAddress address, int port, InetAddress localAddress, int localPort) throws IOException {
        return enableTLSOnSocket(internalSSLSocketFactory.createSocket(address, port, localAddress, localPort));
    }

    private Socket enableTLSOnSocket(Socket socket) {
        if(socket != null && (socket instanceof SSLSocket)) {
            ((SSLSocket)socket).setEnabledProtocols(new String[] {"TLSv1.1", "TLSv1.2"});
        }
        return socket;
    }
}`

Could you please check these

**Comment by marci4** [comment]
Could a `SSLContext.getInstance("TLSv1.2");` work as described [here](https://www.baeldung.com/java-7-tls-v12)?

**Comment by simonchius** [comment]
Hi @marci4, I have tried as it was described in [here]("https://www.baeldung.com/java-7-tls-v12") but it was not working, 

But this does work,
`SSLContext context = SSLContext.getInstance("TLS");
        context.init(null, new TrustManager[] {
                new X509TrustManager() {
                    public void checkClientTrusted(X509Certificate[] chain, String authType) {}
                    public void checkServerTrusted(X509Certificate[] chain, String authType) {}
                    public X509Certificate[] getAcceptedIssuers() { return new X509Certificate[]{}; }
                }
        }, null);`

**Comment by marci4** [comment]
*DO NOT* use this! You disable all the certificate checks....

AGAIN I ask you to provide an example application!

**Comment by simonchius** [comment]
Hello @marci4, Thanks for your reply. The example application is "AnywhereWorks".

`URI lURI = new URI(Constants.WEB_SOCKET_CONNECTION_URL);
            WebSocketClient mWebSocketClient = new WebSocketClient(lURI) {
                @Override
                public void onOpen(ServerHandshake handshakedata) {
                }

                @Override
                public void onMessage(String message) {
                }

                @Override
                public void onClose(int code, String reason, boolean remote) {
                    }
                }

                @Override
                public void onError(Exception ex) {
                }
            };
            SSLContext lSSLContext = SSLContext.getInstance("TLSv1.2");
            lSSLContext.init(null, null, null);
            mWebSocketClient.setSocketFactory(lSSLContext.getSocketFactory());
            mWebSocketClient.connect();`

This is my exact code, it is throwing this 
`com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate expired at Mon Feb 18 19:55:00 GMT+05:30 2019 (compared to Thu Apr 11 17:35:12 GMT+05:30 2019)`
Exception.

**Comment by marci4** [comment]
No, provide a full repository!

**Comment by simonchius** [comment]
I am really sorry @marci4 , It is a completely private repository and our company norms won't allow sharing this. As I mentioned previously, That is the exact part of my code, Could you please help me with this, and this issue won't happen android 7.0 and above devices, Please check it in the 6.0 or bellow.

Thanks,
Simon

**Comment by marci4** [comment]
Before I write here a long bad-tempered answer, how impudent I find such a behavior, I close this point.

Best regards,
Marcel
