### ISSUE TITLE
Bare socket implementation & proxy support

### ISSUE THREAD

**Issue by rmckay** [TooTallNate/Java-WebSocket#88]
This isn't really a 'bug' per-say, but it would be really nice to have this library implemented on top of the regular java Socket interface rather than the java nio one because the nio stuff doesn't work with proxy servers http://blog.tsunanet.net/2010/08/java-nio-and-overengineering.html

**Comment by privatejava** [comment]
I have a proxy server which have user and password but I am not sure how to add them in ExampleClient as it only accepts InetSocketAddress in setProxy. Please help

**Comment by BrushfireDigitalServices** [comment]
I'm going to close this due to changes in the codebase since 2012 and general inactivity in this thread. Feel free to open new issues about specific aspects of proxy support and mention this issue if relevant.

**Comment by daluu** [comment]
Is it sufficient to say that from https://github.com/TooTallNate/Java-WebSocket/wiki/Using-the-WebSocket-through-a-http-proxy, proxy support is there in this library with exception to (HTTP) proxy with (user + password) authentication?
