### ISSUE TITLE
Cannot connect to the server but no errors

### ISSUE THREAD

**Issue by SteMMo33** [TooTallNate/Java-WebSocket#882]
Hello everyone,
I imported the library in a simple Java Android app.
Version: "org.java-websocket:Java-WebSocket:1.4.0"

The server is a C Linux based server I wrote for other application, so it is working well (it is using libwebsockets library).

The app is notified by the onOpen() callback: the http code and description are 101 and 'Switching protocols'.
The server is still sleeping waiting for a connection. It is not using any protected protocol.
If I send a string nothing happens.

Please, how can I miss to start the connection?

Thanks, regards

**Comment by SteMMo33** [comment]
It seems that I need to send the **sec-weboscket-protocol** item: how can i do it?

**Comment by haruntuncay** [comment]
In the example directory, there is [SecWebSocketProtocolClientExample.java](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SecWebSocketProtocolClientExample.java). Which shows how you can achieve it.

**Comment by SteMMo33** [comment]
Yes, I saw the FAQ item and it resolved !!! 

Thanks!!

**Comment by nrohpos** [comment]
@SteMMo33 could you please drop the link of FAQ that it resolved?
