### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by hunanzjjhy** [TooTallNate/Java-WebSocket#883]
java.lang.NullPointerException
Attempt to invoke virtual method 'void java.net.Socket.close()' on a null object reference

org.b.a.a.o(WebSocketClient.java:654)

It should be multithreaded

**Comment by haruntuncay** [comment]
Could you share some context ? It is not possible to help with only this much information.

**Comment by hunanzjjhy** [comment]
I have multiple threads calling websocket, and I can't reproduce it, but there are many times such logs in exception statistics. I'm doing Android, and it should have no effect on users. I think it should be possible to add a null-pointer exception catch to this close try.

**Comment by haruntuncay** [comment]
Can you share the code that causes the exception and show how you are accessing the websocket from multiple threads ?

**Comment by hunanzjjhy** [comment]
I can't share it because it's bugly statistics. Now I've modified your code and added a null pointer exception capture when closing.

**Comment by marci4** [comment]
That is not really a good solution...

**Comment by marci4** [comment]
Closing dead issue!

Best regards,
Marcel
