### ISSUE TITLE
NullPointerException when socket close

### ISSUE THREAD

**Issue by whimaggot** [TooTallNate/Java-WebSocket#884]
My WebSocketClient's version is 1.3.8
dont know how to reproduce
and I had done this when I closed the WebSocketClient，but this crash still happened:
```
if(mSocket!=null){
     try {
           mSocket.close();
     }catch (Exception pE){
           pE.printStackTrace();
           Log.e(TAG,"socket close error");
     }
}
```

Here is some logs:
04-19 18:51:55.488 E/AndroidRuntime(24707): FATAL EXCEPTION: WebSocketWriteThread-801
04-19 18:51:55.488 E/AndroidRuntime(24707): Process: com.netease.gl, PID: 24707
04-19 18:51:55.488 E/AndroidRuntime(24707): java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.close()' on a null object reference
04-19 18:51:55.488 E/AndroidRuntime(24707): 	at org.java_websocket.a.a.closeSocket(WebSocketClient.java)
04-19 18:51:55.488 E/AndroidRuntime(24707): 	at org.java_websocket.a.a.access$400(WebSocketClient.java)
04-19 18:51:55.488 E/AndroidRuntime(24707): 	at org.java_websocket.a.a$a.run(WebSocketClient.java)
04-19 18:51:55.488 E/AndroidRuntime(24707): 	at java.lang.Thread.run(Thread.java:760)

**Comment by marci4** [comment]
Hello,

Please provide an example application and some steps to repeat otherwise this issue will be closed.

Best regards,
Marcel

**Comment by marci4** [comment]
Closing dead issue!

Best regards,
Marcel
