### ISSUE TITLE
JKS not found

### ISSUE THREAD

**Issue by nkchi** [TooTallNate/Java-WebSocket#885]
I am using Java-WebSocket:1.4.0 library in android for connection to wss server.
KeyStoreType: JKS
SSLProtocol: TLS
Algorithm: PKIX
But it return the error: java.lang.AssertionError: java.security.KeyStoreException: JKS not found
Caused by: java.security.NoSuchAlgorithmException: JKS KeyStore not available
How can I resolve this error.

**Comment by marci4** [comment]
Hello,

Please provide an example application and some steps to repeat otherwise this issue will be closed..

Best regards,
Marcel

**Comment by PhilipRoman** [comment]
Also, check out [wiki page for WSS on android](https://github.com/TooTallNate/Java-WebSocket/wiki/FAQ:-Secure-WebSockets#wss-on-android)

**Comment by nkchi** [comment]
My server used JKS, not used BKS, so I don't know how to access to server by BKS
 try {
            KeyStore keystore = KeyStore.getInstance("BKS");

            String path = Environment.getExternalStorageDirectory() + "/" + "wss/streamlock.net.bks";
           File kf = new File(path );
            InputStream in = new FileInputStream(kf);
            try {

                keystore.load(in, storePassword.toCharArray());
            } finally {
                in.close();
            }
            KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            keyManagerFactory.init(keystore, keyPassword .toCharArray());
            TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            tmf.init(keystore);

            sslContext = SSLContext.getInstance("TLS");
            sslContext.init(keyManagerFactory.getKeyManagers(), tmf.getTrustManagers(), null);
        } catch (KeyStoreException | IOException | CertificateException | NoSuchAlgorithmException | KeyManagementException | UnrecoverableKeyException e) {
            Log.e("ERROR", "MSG: "+e.getMessage());
            throw new IllegalArgumentException();
        }

**Comment by nkchi** [comment]
My Server used JKS
I don't know how to use BKS to connect to server
try {
            KeyStore keystore = KeyStore.getInstance("BKS");
            String path = Environment.getExternalStorageDirectory() + "/" + "wss/streamlock.net.bks";
            File f = new File(path);
            if(!f.exists()){
                f.mkdirs();
            }
            File kf = new File(path );
            InputStream in = new FileInputStream(kf);
            try {
                keystore.load(in, storePassword.toCharArray());
            } finally {
                in.close();
            }
            KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            keyManagerFactory.init(keystore, keyPassword .toCharArray());
            TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            tmf.init(keystore);
            sslContext = SSLContext.getInstance("TLS");
            sslContext.init(keyManagerFactory.getKeyManagers(), tmf.getTrustManagers(), null);
        } catch (KeyStoreException | IOException | CertificateException | NoSuchAlgorithmException | KeyManagementException | UnrecoverableKeyException e) {
            Log.e("ERROR", "MSG: "+e.getMessage());
            throw new IllegalArgumentException();
        }

**Comment by marci4** [comment]
Maybe try [this](http://lmgtfy.com/?q=How+to+create+a+BKS+(BouncyCastle)+from+JKS).

**Comment by marci4** [comment]
Issue should be solved!

Closing it.
Best regards,
Marcel

**Comment by dss-kenya** [comment]
Hi,
I seem to be getting this issue with the current version of this library. So then do we have to use BKS format vs JKS as you have it in the Sample Server file? Additionally, i tried it with BKS but then handshake doesnt happen between the client and server. Any idea what i should do? I keep getting "handshake cancelled" error message from the wss client (a web application), and android is my server. Please assist.

Thanks
