### ISSUE TITLE
Use user-supplied ThreadFactory to create internal Server/Client threads

### ISSUE THREAD

**Issue by offbynull** [TooTallNate/Java-WebSocket#888]
**Is your feature request related to a problem? Please describe.**
This library prevents the application from shutting down when the main application thread ends. The threads launched by the library are what prevent it from shutting down: if they aren't explicitly closed, the process doesn't end.

**Describe the solution you'd like**
Either allow the user to pass through a daemonize flag for threads spawned by the library or allow the user to supply a ThreadFactory that the library can use to spawn threads.

**Describe alternatives you've considered**
Using my own Thread to launch a server works fine...
```java
        Thread serverThread = new Thread(server);
        serverThread.setName("WebSocket Server Thread");
        serverThread.setDaemon(true);
        serverThread.start();
```

But there is no equivalent for clients...
```java
        WebSocketClient client = new Client(new URI("ws://localhost:8887"));
        Thread clientThread = new Thread(client);
        clientThread.setName("WebSocket Server Thread");
        clientThread.setDaemon(true);
        clientThread.start();
        client.sendPing();    // ERRORS OUT
        client.closeBlocking();
        clientThread.join(5000);
```

**Additional context**
N/A

**Comment by ViToni** [comment]
It might help to be able to provide at least the prefix for thread-names to be able to distinguish threads of different clients

**Comment by beiluonever** [comment]
It's still use new Thread to create Thread. We got a lot of threads in our stack becase of error usage. Do we have plan to improve this?
