### ISSUE TITLE
How to shut down the service safely?

### ISSUE THREAD

**Issue by dtboy1995** [TooTallNate/Java-WebSocket#889]
How to shut down the service safely?
thanks a lot!

**Comment by PhilipRoman** [comment]
For server side: `WebSocketServer.stop()`. For client side: `WebSocketClient.close()`. These methods also have variants where you can pass extra information like error code, message, timeout duration, etc.

If you're looking for something else, provide more details.

**Comment by dtboy1995** [comment]
@PhilipRoman Thanks for your reply.
I used it in Android and called the stop method in Service's onDestory, but it didn't stop. When I restarted, there was an error that the port had been occupied. I had to kill the app completely to restart it. thanks

**Comment by PhilipRoman** [comment]
Try using `server.setReuseAddr(true)` before launching server. If that doesn't help, create a minimal code example which reproduces the problem and post it here (or link to the repo).

**Comment by dtboy1995** [comment]
@PhilipRoman thanks a lot, I'll go to the company to try it tomorrow. The code is not on my own computer.

**Comment by yohiphopja** [comment]
server.stop ();
server.start ();
can only be started once.

**Comment by PhilipRoman** [comment]
@yohiphopja `WebSocketServer.start()` can only be used once per server. You can create and start another server on the same port instead.

**Comment by marci4** [comment]
Is this question answered?

Can we close this issue?

Best regards,
Marcel

**Comment by dtboy1995** [comment]
正在使用发音
There are too few scenarios for WS services on Android, so I think I can close this discussion. Thank you.
