### ISSUE TITLE
Performance different with Undertow?

### ISSUE THREAD

**Issue by soylomass** [TooTallNate/Java-WebSocket#891]
I'm using Undertow's WebSocket implementation for my web-browser based game, which uses XNIO, and it works fine (except for some unexplained RSV bit 4 errors with some users), but it's a big library when I only need WebSockets.

How does this library compare to Undertow/XNIO, speaking about performance? Were any benchmarks done?

Thanks

**Comment by marci4** [comment]
Hello,

No, there are now benchmarks done !

Best regards,
Marcel

**Comment by marci4** [comment]
Closing this issue since the question is answered. If someone has some benchmarks, feel free to share them!

Best regards,
Marcel
