### ISSUE TITLE
Hi,what IDE should I use to compile this project?

### ISSUE THREAD

**Issue by aigeek** [TooTallNate/Java-WebSocket#903]
What IDE should I use to compile this project? Thanks!

**Comment by marci4** [comment]
No need for a ide. you can simple use maven.

Best regards,
Marcel

**Comment by NoahAndrews** [comment]
If you're looking for a recommendation, IntelliJ community edition is an excellent choice.

**Comment by aigeek** [comment]
thanks,my friends😄
