### ISSUE TITLE
WebSocket send() OutOfMemoryError 

### ISSUE THREAD

**Issue by TBoyLi** [TooTallNate/Java-WebSocket#904]
**Describe the bug**
Read file transfer streaming on android device memory overflow problem，look at this：

![image](https://user-images.githubusercontent.com/14815341/59338954-e10cb400-8d35-11e9-99d3-0c80573a5fb5.png)

error logs：

![image](https://user-images.githubusercontent.com/14815341/59339006-f8e43800-8d35-11e9-8a8b-1bfd2cd6a7a5.png)

**Comment by marci4** [comment]
Please provide additional info as well as an example application.

Best regards,
Marcel

**Comment by TBoyLi** [comment]
@marci4 this is my  example application [Java-H5-WebSocket](https://github.com/TBoyLi/Java-H5-WebSocket), 本地存放1G的视频文件 /storage/emulated/0/Movies/alita-1G1.mp4,Provide file streams for h5 to use. thanks

**Comment by marci4** [comment]
Please provide an example for java not android.

Best regards,
Marcel

**Comment by marci4** [comment]
Closing dead issue.
Bes regards,
Marcel
