### ISSUE TITLE
数据long类型，自动转换成了科学计数法

### ISSUE THREAD

**Issue by moonstr** [TooTallNate/Java-WebSocket#910]
**Describe what you would like to know or do**
A clear and concise description of what the problem is.

**Describe the solution you'd considered**
A clear and concise description of any solutions you've considered.

**Additional context**
Add any other context or links about the question here.

**Comment by moonstr** [comment]
WebSocketLib: WebSocket 接收到消息：{"body":{"content":"{\"appKey\":\"19051484MSSX3P4K\",\"fromUserId\":\"444kkk\",\"toUserId\":\"555kkk\",\"msg\":\"\\\"sendTime\\\" -> \\\"1.561017601828E12\\\"

**Comment by PhilipRoman** [comment]
Please describe your issue in more detail. Issues which don't have enough information will be closed.

**Comment by marci4** [comment]
Closing dead issue!
