### ISSUE TITLE
Do I need a certificate for Android client for Websocket secure connection (WSS)

### ISSUE THREAD

**Issue by dajnz** [TooTallNate/Java-WebSocket#912]
**Describe what you would like to know or do**
I have node-based websocket server using Let's Encrypt cert, and I can connect to it over both WS and WSS using my browser-based and iOS-based clients, but my Android-based client can connect only using WS protocol, and I use your great library for that.

The error I got is:
```
WEBSOCKET error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. :: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:322)
        at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:623)
        at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:585)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:407)
        at java.lang.Thread.run(Thread.java:818)
```

So my question is: do I need to have self-signed certificate for my Android client for connecting to my server over WSS?

I checked some details about SSL/TLS connection establishing (I have not too much experience in SSL-related stuff, though), and it looks like a client don't need a certificate for handshaking phase, and for my non-Android clients I haven't specified anything but connection address (like `ws://mydomain.tld`) for proper connection.

Can you explain me if such certificate is needed, why we need it, and how can I add self-signed certificate to my Android app.

**Describe the solution you'd considered**
I tried approach described in [websocket SSL client example](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLClientExample.java), and here is my code snippet for connection address with WSS protocol:

```
        // Creating websocket client instance (named as "cli" below)
        ....

        if (wsAddrUri.getScheme() == "wss") {
            SSLContext sslContext = null;
            sslContext.init(null, null, null);
            SSLSocketFactory factory = (SSLSocketFactory) SSLSocketFactory.getDefault();
            cli.setSocketFactory(factory);
        }
     
        // Connecting ....
```

**Additional context**
none

Thank you forward!

**Comment by marci4** [comment]
Hello @dajnz,

no you don't need a self signed certificate, your server just needs to provide the chain of trust.

Best regards,
Marcel

**Comment by dajnz** [comment]
@marci4 thank you, can you also tell me please is SNI supported by the library?

**Comment by marci4** [comment]
Hello @dajnz,

take a look at the wiki. There should be a post for that (same for the first question).

Best regards,
Marcel

**Comment by marci4** [comment]
Question answered. Closing issue!
