### ISSUE TITLE
Does it support cluster?

### ISSUE THREAD

**Issue by YaoZhichao** [TooTallNate/Java-WebSocket#915]

**Comment by PhilipRoman** [comment]
Please describe your issue in more detail. Issues which don't have enough information will be closed.

**Comment by YaoZhichao** [comment]
The service should be high available. so I need more than one server to build web socket server. 
The question is the how to communication between servers.

Remark:
https://github.com/mrniko/netty-socketio
it use:
Supports client store (Memory, Redisson, Hazelcast)
Supports distributed broadcast across netty-socketio nodes (Redisson, Hazelcast)

**Comment by PhilipRoman** [comment]
Hello!
Is this issue still relevant to you?

**Comment by PhilipRoman** [comment]
Closing dead issue
