### ISSUE TITLE
Create a WebSocket Server in a service class android, but WebsocketNotConnectedException happened

### ISSUE THREAD

**Issue by Huiming37** [TooTallNate/Java-WebSocket#917]
Hi, sorry to bother you. My project requires me to have a Websocket server and Websocket client in one android app. So my plan is create the server in a service class, and create the client in another service class. However after I start the Websocket server and the client class also get the IP address of the server and then try to connect the server. I find that there is a WebsocketNotConnectedException exception. and I also try to log the socketClient.isOpen, the result is false. Is there anything wrong with my design patten. this project is very important for me, any help is appreciated. bellow is the Exception log information.

07-09 00:27:28.723 24005-24005/com.example.test5 W/System.err: org.java_websocket.exceptions.WebsocketNotConnectedException
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:630)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:607)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:344)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at com.example.test5.DirectiveFileListenerService.onStartCommand(DirectiveFileListenerService.java:48)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3061)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at android.app.ActivityThread.access$2100(ActivityThread.java:160)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at android.os.Looper.loop(Looper.java:135)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5597)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
07-09 00:27:28.724 24005-24005/com.example.test5 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by PhilipRoman** [comment]
Hello!
Could you post a minimal code example which reproduces the issue?

**Comment by Huiming37** [comment]
Thank you very much. In order to simplify my code, I put the WebSocket server on a service class, and put the client in the MainActivity.class.

**MainActivity.java file:**

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.ServiceConnection;
import android.os.IBinder;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;

import java.net.URI;

public class MainActivity extends AppCompatActivity {

    private static final String TAG = MainActivity.class.getSimpleName();

    WebSocketTransferService mService;
    private MySocketClient socketClient;
    boolean mBound = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Intent intent = new Intent(this, WebSocketTransferService.class);
        bindService(intent, connection, Context.BIND_AUTO_CREATE);
    }


    /** Defines callbacks for service binding, passed to bindService() */
    private ServiceConnection connection = new ServiceConnection() {

        @Override
        public void onServiceConnected(ComponentName className,
                IBinder service) {
            // We've bound to LocalService, cast the IBinder and get LocalService instance
            WebSocketTransferService.LocalBinder binder = (WebSocketTransferService.LocalBinder) service;
            mService = binder.getService();
            mBound = true;
            Log.i(TAG, mService.getServerAddr());
            try{
                //socketClient = new MySocketClient( new URI("ws:/" + mService.getServerAddr())); // more about drafts here: http://github.com/TooTallNate/Java-WebSocket/wiki/Drafts
                socketClient = new MySocketClient( new URI("ws:/" + mService.getServerAddr()));
                Log.e(TAG, "ws:/" + mService.getServerAddr());
                socketClient.connect();
                Log.e(TAG, socketClient.isOpen() + "");
                socketClient.send("I like here");
            }catch (Exception e){
                e.printStackTrace();
            }
        }

        @Override
        public void onServiceDisconnected(ComponentName arg0) {
            mBound = false;
        }
    };
}


**WebSocketTransferService.java file**

import android.app.Service;
import android.content.Intent;
import android.os.Binder;
import android.os.IBinder;
import android.util.Log;

import java.io.IOException;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.NetworkInterface;
import java.net.ServerSocket;
import java.net.SocketException;
import java.util.Enumeration;

public class WebSocketTransferService extends Service {
    private static final String TAG = WebSocketTransferService.class.getSimpleName();
    private static final int SERVER_PORT = findFreePort();

    private InetSocketAddress mInetSocketAddress;
    private MySocketServer mServer;

    // Binder given to clients
    private final IBinder binder = new LocalBinder();

    public class LocalBinder extends Binder {
        WebSocketTransferService getService() {
            // Return this instance of LocalService so clients can call public methods
            return WebSocketTransferService.this;
        }
    }


    @Override
    public IBinder onBind(Intent intent) {
        return binder;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        startServer();
    }

    private void startServer() {
        InetAddress inetAddress = getInetAddress();

        if (inetAddress == null) {
            Log.d(TAG, "Unable to lookup IP address");
            return;
        }

        mInetSocketAddress = new InetSocketAddress(inetAddress.getHostAddress(), SERVER_PORT);
        mServer = new MySocketServer(mInetSocketAddress);
        mServer.start();
        Log.d(TAG, mInetSocketAddress.toString());

    }

    private static InetAddress getInetAddress() {
        try {
            for (Enumeration en = NetworkInterface.getNetworkInterfaces(); en.hasMoreElements();) {
                NetworkInterface networkInterface = (NetworkInterface) en.nextElement();

                for (Enumeration enumIpAddr = networkInterface.getInetAddresses(); enumIpAddr.hasMoreElements();) {
                    InetAddress inetAddress = (InetAddress) enumIpAddr.nextElement();

                    if (!inetAddress.isLoopbackAddress() && inetAddress instanceof Inet4Address) {
                        System.out.println("connection test: " + inetAddress.getHostAddress());
                        return inetAddress;
                    }
                }
            }
        } catch (SocketException e) {
            e.printStackTrace();
            Log.d(TAG, "Error getting the network interface information");
        }
        return null;
    }


    private static int findFreePort() {
        ServerSocket socket = null;
        try {
            socket = new ServerSocket(0);
            socket.setReuseAddress(true);
            int port = socket.getLocalPort();
            try {
                socket.close();
            } catch (IOException e) {
                // Ignore IOException on close()
            }
            return port;
        } catch (IOException e) {
        } finally {
            if (socket != null) {
                try {
                    socket.close();
                } catch (IOException e) {
                }
            }
        }
        throw new IllegalStateException("Could not find a free TCP/IP port to start embedded Jetty HTTP Server on");
    }


    public String getServerAddr() {
        return mInetSocketAddress.toString();
    }

    public int getSERVER_PORT() {
        return SERVER_PORT;
    }
}

**MySocketServer.java file**

import android.util.Log;

import org.java_websocket.WebSocket;
import org.java_websocket.handshake.ClientHandshake;
import org.java_websocket.server.WebSocketServer;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.ServerSocket;


public class MySocketServer extends WebSocketServer {

    private static final String TAG = MySocketServer.class.getSimpleName();

    private WebSocket mSocket;

    public MySocketServer(InetSocketAddress address) {
        super(address);
    }

    @Override
    public void onOpen(WebSocket conn, ClientHandshake handshake) {
        mSocket = conn;
    }

    @Override
    public void onClose(WebSocket conn, int code, String reason, boolean remote) {

    }

    @Override
    public void onMessage(WebSocket conn, String message) {
        Log.i(TAG, message);
        broadcast( message );
    }

    @Override
    public void onError(WebSocket conn, Exception ex) {
    }

    public void sendMessage(String message) {
        mSocket.send(message);
    }


    @Override
    public void onStart() {
        System.out.println("connection test: Server started!");
        setConnectionLostTimeout(100);
    }

}


**MySocketClient.java file**

import android.util.Log;

import java.net.URI;

import org.java_websocket.client.WebSocketClient;
import org.java_websocket.drafts.Draft;
import org.java_websocket.handshake.ServerHandshake;

/** This example demonstrates how to create a websocket connection to a server. Only the most important callbacks are overloaded. */
public class MySocketClient extends WebSocketClient {

    public long receiveBrowsertime;
    public long sendTime;

    public MySocketClient( URI serverUri , Draft draft ) {
        super( serverUri, draft );
    }

    public MySocketClient( URI serverURI ) {
        super( serverURI );
    }

    @Override
    public void onOpen( ServerHandshake handshakedata ) {
        System.out.println( "opened connection" );
    }

    @Override
    public void onMessage( String message ) {

    }

    @Override
    public void onClose( int code, String reason, boolean remote ) {
        System.out.println( "Connection closed by " + ( remote ? "remote peer" : "us" ) + " Code: " + code + " Reason: " + reason );
    }

    @Override
    public void onError( Exception ex ) {
        ex.printStackTrace();
    }

}


**AndroidManifest.xml**

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.example.test6">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <service
            android:name=".WebSocketTransferService"
            android:enabled="true"
            android:exported="true">
        </service>

    </application>
</manifest>

Thank you very much. if you need more information, please let me know.

**Comment by marci4** [comment]
Try to use connectBlocking() when trying to directly send a message after connecting.

**Comment by Huiming37** [comment]
Thanks, It seems currently this problems have solved. Not sure whether there will be problems in the future. Thank you very much.
