### ISSUE TITLE
blocked where use reconnect

### ISSUE THREAD

**Issue by pipicoming** [TooTallNate/Java-WebSocket#920]
when i use this.reconnect() in the method onClose, my thread is block
i find the readyState is always CLOSING not closed, the line closeLatch.await() in the closeBlocking method blocked the thread, my code like this:

`new Thread(() -> {
                            this.reconnect();
                    }).start();`

what is the correct way to reconnect ?

**Comment by pipicoming** [comment]
please ignore

**Comment by lovingning** [comment]
@pipicoming  how to deal with this problem？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by lovingning** [comment]
@pipicoming Looking at the crash log, we found that the unsafe package was called at last, and the park method in it was blocked. How to deal with this problem at last?


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by lovingning** [comment]
@pipicoming Can I reconnect without starting a new thread?


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
