### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by AndMy** [TooTallNate/Java-WebSocket#924]
page not found
https://www.enterpriselab.ch/2010/10/22/android-trusting-ssl-certificates/

**Comment by PhilipRoman** [comment]
Hello!
Please add more information about your issue. Currently it's not clear what you're asking. Issues without enough information may be closed.

**Comment by AndMy** [comment]
This link cannot be opened
![image](https://user-images.githubusercontent.com/7222340/62353905-4616a600-b53e-11e9-94e7-e26ca7bda9db.png)

**Comment by PhilipRoman** [comment]
Where did you find this link? In the wiki?

**Comment by AndMy** [comment]
> Where did you find this link? In the wiki?

![image](https://user-images.githubusercontent.com/7222340/62354286-1320e200-b53f-11e9-856d-90f69dd1b093.png)

**Comment by PhilipRoman** [comment]
Thanks for the report! We should probably redirect to the relevant page in our wiki.

**Comment by PhilipRoman** [comment]
By the way, you can see the article here: https://web.archive.org/web/20180616102130/http://blog.antoine.li/2010/10/22/android-trusting-ssl-certificates/ but I have no idea if the information there is still accurate - it was added here more than 7 years ago!

**Comment by victoraugusto1** [comment]
I've created the #938 pull request with the desired fix.

**Comment by marci4** [comment]
Fixed with #938
