### ISSUE TITLE
WebSocket conn.close(int,string) does not return the int and string to client side

### ISSUE THREAD

**Issue by Cintrust** [TooTallNate/Java-WebSocket#925]
**Describe the bug**
WebSocket conn.close(int, string) function does not send the status code and the reason back to the client.
on the assumption that thats what the two variables are for.

**To Reproduce**
//server side code
import java.net.InetSocketAddress;
import java.nio.ByteBuffer;

import org.java_websocket.WebSocket;
import org.java_websocket.handshake.ClientHandshake;
import org.java_websocket.server.WebSocketServer;

public class SimpleServer extends WebSocketServer {
private  int members =0;

    private SimpleServer(InetSocketAddress address) {
        super(address);
    }

    @Override
    public void onOpen(WebSocket conn, ClientHandshake handshake)  {
        if(( members > 0)){
            conn.send("Sorry we have reached the max "); // does not reach the client before the connection closes

            conn.close(404," no allowed");//the supplied code and string doesn't appear client side

        }
        members++;
        conn.send("Welcome to the server!=> "+members); //This method sends a message to the new client

        broadcast( "new connection: " + handshake.getResourceDescriptor() ); //This method sends a message to all clients connected
        System.out.println("new connection to " + conn.getRemoteSocketAddress());
        System.out.println("total members "+members );

    }

    @Override
    public void onClose(WebSocket conn, int code, String reason, boolean remote) {
        --members;
        System.out.println("closed " + conn.getRemoteSocketAddress() + " with exit code " + code + " additional info: " + reason);
        System.out.println("total members "+members );

    }

    @Override
    public void onMessage(WebSocket conn, String message) {
        System.out.println("received message from "	+ conn.getRemoteSocketAddress() + ": " + message);
    }

    @Override
    public void onMessage( WebSocket conn, ByteBuffer message ) {
        System.out.println("received ByteBuffer from "	+ conn.getRemoteSocketAddress());
    }

    @Override
    public void onError(WebSocket conn, Exception ex) {
        System.err.println("an error occured on connection " + conn.getRemoteSocketAddress()  + ":" + ex);
    }

    @Override
    public void onStart() {
        System.out.println("server started successfully");
    }

    public static void main(String[] args) {
        String host = "localhost";
        int port = 8887;

        WebSocketServer server = new SimpleServer(new InetSocketAddress(host, port));
        server.run();
    }
}

//client side

<!DOCTYPE HTML>

<html>
<head>

    <script type = "text/javascript">
        function WebSocketTest() {
            var ws = null;
            if ("WebSocket" in window) {
                console.log("WebSocket is supported by your Browser!");

                // Let us open a web socket
                 ws = new WebSocket("ws://localhost:8887/echo");

                ws.onopen = function() {

                    // Web Socket is connected, send data using send()
                    ws.send("Message to send");
                    console.log("Message is sent...");
                };

                ws.onmessage = function (evt) {
                    var received_msg = evt.data;
                    console.log("Message is received...");
                    console.log("data => ",evt,received_msg);
                };

                ws.onclose = function() {

                    // websocket is closed.
                    console.log("Connection is closed...");
                    console.log(arguments,'dummy');
   // arguments[0].code should be 404 but it returns random interger
// arguments[0].reason should be " no allowed" but it returns empty string

                };
            } else {

                // The browser doesn't support WebSocket
                console.log("WebSocket NOT supported by your Browser!");
            }
            return ws;
        }
    </script>

</head>

<body>
<div id = "sse">
    <a href = "javascript:var wd = WebSocketTest();">Run WebSocket</a>
</div>

</body>
</html>

**Expected behavior**
the supplied code and reason should appear client side

![image](https://user-images.githubusercontent.com/35232573/62411574-e0cdbe00-b5ec-11e9-9f12-219dbe7f01fb.png)

but it dosen't

**Debug log**
The the debug log (set the log level to `TRACE`) to help explain your problem.

**Environment(please complete the following information):**
 - Version used: Java-WebSocket-1.4.0-with-dependencies.jar
 - Java version: ...
 - Operating System and version: windows 7
 

**Additional context**

**Comment by marci4** [comment]
Hello @Cintrust,

the close code is not a normal http code.
There are specific codes for ws/wss. Check out [this](https://static.javadoc.io/org.java-websocket/Java-WebSocket/1.4.0/org/java_websocket/framing/CloseFrame.html) page or the [offical specificiation](https://tools.ietf.org/html/rfc6455#section-7.4.1).

When I e.g. use close code 1001 and include a message, I recieve it in the browser (in my example chrome).

Best regards,
Marcel

**Comment by PhilipRoman** [comment]
Is this issue still relevant for you?
