### ISSUE TITLE
SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by a-sky** [TooTallNate/Java-WebSocket#930]
**Describe the bug**

**To Reproduce**
1. wss 
2. The server does not support SSLv3
3. ...
4. ....

**Example application to reproduce the issue**
A link to a github project/gist to reproduce the issue.

**Expected behavior**

**Debug log**
javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xabb012d0: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:765 0xedbdcbe1:0x00000000)
**Environment(please complete the following information):**
 - Version used:1.4.0
 - Java version:1.8
 - Operating System and version:android 5.0
 - Endpoint Name and version:
 - Link to your project:

**Additional context**

**Comment by PhilipRoman** [comment]
(I translated some parts of your issue)
This error most likely isn't related to this library, but happens at a lower level. SSLv3 is an outdated and vulnerable cryptographic protocol - this page contains helpful information on how to disable it: https://disablessl3.com/.

If you believe this issue is related specifically to this library, add more information.

**Comment by PhilipRoman** [comment]
Can you confirm that the issue is caused by this library?

**Comment by a-sky** [comment]
all of the library on github are not support,i have no idea.can you have a try under 5.0 ,this is the url:wss://user.ssrc.ml/_rpc




------------------ 原始邮件 ------------------
发件人: "Philip John Roman"<notifications@github.com>; 
发送时间: 2019年8月21日(星期三) 下午4:44
收件人: "TooTallNate/Java-WebSocket"<Java-WebSocket@noreply.github.com>; 
抄送: "风"<291468773@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TooTallNate/Java-WebSocket] SSL23_GET_SERVER_HELLO:sslv3 alerthandshake failure (#930)




Can you confirm that the issue is caused by this library?

**Comment by PhilipRoman** [comment]
By the way, I can connect to your server just fine using both https://www.websocket.org/echo.html and the `wscat` tool.

**Comment by marci4** [comment]
Closing dead issue!
