### ISSUE TITLE
Hi,About connection authentication

### ISSUE THREAD

**Issue by PandaChanV587** [TooTallNate/Java-WebSocket#932]
I want to do connection authentication in the onConnect(SelectionKey key) method, for example ws://127.0.0.1/abcdefg, how do I get abcdefg in the key?

**Comment by PandaChanV587** [comment]
Or do you have a better way to connect authentication?

**Comment by SnowRunescape** [comment]
hey, you can simply let the person connect normally, but to use WS functions, they have to authenticate themselves by sending packets

I recommend using JSON, when the person submits a request of type 0, is to authenticate the session, then you check the data in a database and see if everything is OK, and free access

**Comment by bliet** [comment]
> hey, you can simply let the person connect normally, but to use WS functions, they have to authenticate themselves by sending packets
> 
> I recommend using JSON, when the person submits a request of type 0, is to authenticate the session, then you check the data in a database and see if everything is OK, and free access

But the broadcast method will send messages to them? 
So we have to implement a new broadcast method just for the auth. Users?

**Comment by PhilipRoman** [comment]
> But the broadcast method will send messages to them?
> So we have to implement a new broadcast method just for the auth. Users?

There is a variant of `broadcast` which also accepts a Collection of clients which should receive the message. You can put all authenticated clients in a collection and pass it to this method.

**Comment by marci4** [comment]
The question is if you want to broadcast it or simply require a auth after onOpen.

**Comment by PandaChanV587** [comment]
I think I know what to do, use a variable to record whether a client has been verified, and this variable is judged each time.
think you，guys

**Comment by PandaChanV587** [comment]
And use the delay queue to disconnect the client that has not been verified after a period of time.

**Comment by bshawvt** [comment]
hello, you can use the getResourceDescriptor method to get /abcdefg 
specifically you can use the handshake from onOpen

**Comment by marci4** [comment]
Closing this issue as answered.

Best regards,
Marcel
