### ISSUE TITLE
Client Credential information in OnMessage

### ISSUE THREAD

**Issue by Jaganrao09** [TooTallNate/Java-WebSocket#934]
I was trying to use this websocket server and client with requirements that the application eventually will be running on docker as a separate Java application instances on same VM machine, each for a client. Does this API work properly on Docker? 

I was looking for a way to identify the client by user name with in onMessage which now has WebSocket connection as argument. Is it possible to attach http headers with WebSocket connection so that client can send its business identifier during the handshake and server knows the sender with in OnMessage calling some new method to get header details?

**Comment by PhilipRoman** [comment]
Each WebSocket can hold an "attachment" which can be any object you want. In the `onOpen` method of server you can access the handshake data. Set the attachment of the newly connected WebSocket to some object which contains the identification data you need. You can then access that object in the `onMessage` callback.

**Comment by Jaganrao09** [comment]
Thanks alot. Yes it works. Hope Web-socket api work on docker too.

**Comment by PhilipRoman** [comment]
I don't think there should be any trouble with Docker. So far no one has reported any Docker specific problems. 

I'm going to close this issue because the main problem has been solved. If you run into any problems, open a new, specific issue. Good luck!
