### ISSUE TITLE
How to export a file to the client through websocket?

### ISSUE THREAD

**Issue by WeLinkOn** [TooTallNate/Java-WebSocket#935]
I want to export to a file through web socket, but I don't know to make that.
Would I find some solutions here?
Thank you.

**Comment by PhilipRoman** [comment]
Hello!
You can use `WebSocket.send()` method to send a String, byte array or ByteBuffer with the contents of the file.

**Comment by PhilipRoman** [comment]
Has this issue been solved for you?

**Comment by WeLinkOn** [comment]
I am Sorry to reply you now. I am not good at English actually, hope you can understand me.
Yes, it worked. Thank you.
On the server side, I read a file from the local and write it to a ByteArrayOutputStream , then send the stream to the client with WebSocket.send(ByteArrayOutputStream.toByteArray()) .
And in the client's onMessage(ByteBuffer message) method, I get the byte array from ByteBuffer.array() and write to a new file, that's it.
I don't know whether it is a good way but it worked. Waiting for you reply.

**Comment by PhilipRoman** [comment]
Sounds good! If you want to simplify and speed up your code, read the file to a byte array directly using https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#readAllBytes(java.nio.file.Path)
