### ISSUE TITLE
WebSocket client read message from server.

### ISSUE THREAD

**Issue by kixiro** [TooTallNate/Java-WebSocket#936]
I need webSocket client. I'm find only send message method. How will i get message from server?

**Comment by PhilipRoman** [comment]
See the documentation: https://www.javadoc.io/doc/org.java-websocket/Java-WebSocket/1.4.0

You should create your own class that extends `WebSocketClient` and implements the `onMessage` method. This method will be called whenever the server sends something to you.

**Comment by kixiro** [comment]
Thanks!
