### ISSUE TITLE
 build.xml does not exist!

### ISSUE THREAD

**Issue by geekbanana** [TooTallNate/Java-WebSocket#937]
**Describe the bug**
`Java-WebSocket\src\main\example>ant`
`Buildfile: build.xml does not exist!`
`Build failed`

**To Reproduce**
1. cd into example directory
2. run ant

**Expected behavior**
build example correctly

**Environment(please complete the following information):**
 - Version used: Java-WebSocket 1.4.0
 - Java version: 1.8.0_221
 - Operating System and version: windows10
 - ant version: 1.10.7

**Additional context**
I found there is no build.xml in example directory

**Comment by PhilipRoman** [comment]
Support for building with Ant has been removed a while ago (commit de70cdc76f0bc9). I'm assuming this is because the project has external dependencies which are hard to manage with Ant.

You can either use other build tools, such as Maven and Gradle. If for some reason you have to use Ant, try to find a way to call Maven or Gradle from your ant script.

**Comment by geekbanana** [comment]
> Support for building with Ant has been removed a while ago (commit [de70cdc](https://github.com/TooTallNate/Java-WebSocket/commit/de70cdc76f0bc92e74f626a09a81d9f61582e503)). I'm assuming this is because the project has external dependencies which are hard to manage with Ant.
> 
> You can either use other build tools, such as Maven and Gradle. If for some reason you have to use Ant, try to find a way to call Maven or Gradle from your ant script.

thank you, if the [Tutorial](http://tootallnate.github.io/Java-WebSocket/) could be modifid will be better.

**Comment by PhilipRoman** [comment]
Oh, thanks for finding that! That page definitely needs an update.

**Comment by clankill3r** [comment]
Even removing the line from the doc would be better then having this false information.

**Comment by PhilipRoman** [comment]
I can have a look at it later today, but feel free to open a pull request.
