### ISSUE TITLE
How to send customized ping message on connectionLostTimeout interval

### ISSUE THREAD

**Issue by gharia** [TooTallNate/Java-WebSocket#941]
**Describe what you would like to know or do**
How to send a custom Ping message on `connectionLostTimeout`?

**Describe the solution you'd considered**
For creating a WS client, I am extending `WebSocketClient`. I did `setConnectionLostTimeout` to 30 seconds. and override the `sendPing()` method https://github.com/TooTallNate/Java-WebSocket/blob/a2c63db70cf33ff838acdfdedf34f50eb680eae7/src/main/java/org/java_websocket/client/WebSocketClient.java#L439 

```
@Override
  public void sendPing() {
    log.info("Sending ping");
    JsonObject pingObj = new JsonObject();
    pingObj.addProperty("id", "NGenerated guid id");
    pingObj.addProperty("type", "ping");
    this.send(pingObj.toString());
  }
```

I thought it would be simple, just to override `sendPing()`. But it is not the case. My overridden method never gets invoked. Rather it calls engine's `sendPing()` https://github.com/TooTallNate/Java-WebSocket/blob/a2c63db70cf33ff838acdfdedf34f50eb680eae7/src/main/java/org/java_websocket/WebSocketImpl.java#L661

**Additional context**
It's not causing any connection close issue, but I am just looking for a way o customize the send ping message.

**Comment by marci4** [comment]
Hello @gharia,

that is currently not possible!

Best regards,
Marcel

**Comment by haruntuncay** [comment]
Hello @marci4, I hope you are well and sorry that I wasn't active for a looong time. I would like to start helping again by giving this issue a go, if that's okay ?

**Comment by marci4** [comment]
Hello @haruntuncay,

doing well, hope you are doing good?
Please don't feel obligated. Just look at my activity currently ;)

Of course, feel free :)

Best regards,
Marcel

**Comment by haruntuncay** [comment]
@marci4, Can I ask for your on something via email ?

**Comment by marci4** [comment]
@haruntuncay always! :)

**Comment by haruntuncay** [comment]
Hello @gharia . Could you please clarify whether you want to send a ping frame "with data" or just want to be notified when a ping frame is sent ? Thanks in advance.

**Comment by gharia** [comment]
Thanks @haruntuncay for looking into it. If possible I would like to send the ping frame "with data" as described in the issue details. ould you point to me an example if any?

**Comment by haruntuncay** [comment]
@gharia, Currently, there isn't any way to set ping frame data, but I'm currently giving it a go. I would probably be able to submit a PR for review in 1-2 days.

**Comment by haruntuncay** [comment]
@marci4, @gharia, I am uncertain regarding the functionality here. Would support for String data would be enough, or should binary data also be supported for now ?

**Comment by gharia** [comment]
@haruntuncay  I think support for String data is good enough in case of ping, at least from my perspective. It would be rare if someone wants to send binary data frames along with PING.  

Re:  `sendPing` on `WebSocketClient` - Yes that is not being called on ping event. I am not sure what is the purpose of this method in `WebSocketClient`, because it always invokes the engine's `sendPing()` https://github.com/TooTallNate/Java-WebSocket/blob/a2c63db70cf33ff838acdfdedf34f50eb680eae7/src/main/java/org/java_websocket/WebSocketImpl.java#L661.

**Comment by haruntuncay** [comment]
`sendPing` is there because both `WebSocketImpl` and `WebSocketClient` implements `WebSocket` interface. But `WebSocketClient@sendPing` could be made `final` to avoid this confusion.

**Comment by marci4** [comment]
@haruntuncay I would not limit the data to Strings. 
I would simply provide method someone can overwrite, but by default returns new PingFrame().

Maybe extending the WebSocketListener/WebSocketAdapter and providing a default implementation for something like
onPreparePing(WebSocket conn)?

Then sendPing will call onPreparePing() (we have to remove the cached ping frame then).
