### ISSUE TITLE
an ByteBuffer help you to convert to string? It's not very good at using ByteBuffer

### ISSUE THREAD

**Issue by 18513578395** [TooTallNate/Java-WebSocket#942]
**Describe what you would like to know or do**
A clear and concise description of what the problem is.

**Describe the solution you'd considered**
A clear and concise description of any solutions you've considered.

**Additional context**
Add any other context or links about the question here.

**Comment by PhilipRoman** [comment]
Please clarify your issue, currently it's not possible to understand it.

If you want to convert a ByteBuffer to String,  use the following code:
```java
String s = StandardCharsets.UTF_8.decode(byteBuffer).toString();
```

**Comment by 18513578395** [comment]
This line of code is used, but it's still garbled

**Comment by 18513578395** [comment]
for example :`x���[k�0�����gO9G�,9o��l5���1�P�3�Rlg����I���a��s���<���u��hȒ\��_��A���L�VoM�{�7�S�%K��C�+Ww�!n}c(lۯ�Ur�v�lf�oK_��M�Ț��ɚza�c�ŉ޻��.;����m����T���2���\��56�)��xò�]?vPD����%���Oi�Rr>Do�u��s�.k��d�x�#��@�/��%iz7�	~�U^�G"T'�.�ѓ|4���1JAc~�i��H1�By�.�}W����pWI���e��U^��@����(Sn�<�TF��ݑ���.��.����M���}�69�����KeA�ҧ��g��D+%*��104O���fh�2CB�����a�Y�f�:ok_��Qcr
    ���Lũ%C;W�e_q�~Ⱦ3�s��H	o`

**Comment by 18513578395** [comment]
Thank you very much.can you help  me

**Comment by PhilipRoman** [comment]
Well that means the buffer contains binary data and not UTF-8 text. If you have questions about the received data format, ask whoever is maintaining the client/server that sends this data (or look at their documentation).

This issue has nothing to do with the library, so I'm closing it.

**Comment by 18513578395** [comment]
ok
