### ISSUE TITLE
Download link for jar files

### ISSUE THREAD

**Issue by clankill3r** [TooTallNate/Java-WebSocket#945]
Please make peoples life more easy and provide some jar files.

The documentation is outdated https://tootallnate.github.io/Java-WebSocket/ stating that you have to use ant.
Using maven, it does not pass the tests provided by the library.

**Comment by PhilipRoman** [comment]
There is a link in README: https://oss.sonatype.org/content/repositories/snapshots/org/java-websocket/Java-WebSocket/
