### ISSUE TITLE
Dynamic create room

### ISSUE THREAD

**Issue by joey-happy** [TooTallNate/Java-WebSocket#947]
I want to dynamic create a room just like wss://xxx.com/:roomid
The person in the same room can broadcast message to the person who in the same room.

**Comment by marci4** [comment]
Hello @joey-happy,

you can get the /:roomid during `onOpen` with `handshake.getResourceDescriptor()`.
You can see the usage here for example https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/ChatServer.java#L55 .

Best regards,
Marcel

**Comment by joey-happy** [comment]
How can I do when I want to broadcast the message to the room which I need

**Comment by joey-happy** [comment]
How can I listen the event(onOpen, onClose, onMessage) which from different room

**Comment by PhilipRoman** [comment]
This library doesn't know anything about "rooms", so you will need to store that information in your own data structures. For example, you could have a `Map<Integer, Collection<WebSocket>>` and also store the room id of each WebSocket using `webSocket.setAttachment()`. 

Now you can get the room of each WebSocket using `webSocket.getAttachment()` and broadcast a message to all clients of a room using `broadcast("Hello", map.get(roomId))`.

You can't listen for events from a specific room, but you can get the room of the websocket and then decide what to do with it.

Example code:
```java
Map<Integer, Collection<WebSocket>> map = new HashMap<>();

@Override
public void onMessage(WebSocket websocket, String message) {
    int roomId = <extract room ID using handshake.getResourceDescriptor()>
    // store the room id in websocket
    websocket.setAttachment(roomId);
    // update room map
    if(!map.containsKey(roomId))
        map.put(roomId, new ArrayList());
    map.get(roomId).add(websocket);
}

@Override
public void onMessage(WebSocket websocket, String message) {
    int roomId = websocket.getAttachment();
    // broadcast the message to all clients of this room
   broadcast(message, map.get(roomId));
}

@Override
public void onClose(WebSocket websocket, ...) {
    int roomId = websocket.getAttachment();
    // remove client from map
   map.get(roomId).remove(websocket);
}
```

**Comment by joey-happy** [comment]
Thanks

**Comment by marci4** [comment]
Question answered. Closing issue!
