### ISSUE TITLE
Is there an API or method to manage the heartbeat on server side? thanks!

### ISSUE THREAD

**Issue by liuqixing** [TooTallNate/Java-WebSocket#949]
Is there an API or method to manage the heartbeat on server side? thanks!

**Comment by marci4** [comment]
Hello @liuqixing,
check out the wiki https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection

Best regards,
Marcel

**Comment by liuqixing** [comment]
OK, thanks so much!
