### ISSUE TITLE
How to disable websocket logs ?

### ISSUE THREAD

**Issue by chaitanya1999** [TooTallNate/Java-WebSocket#951]
I want to disable the websockets logs but have no idea how to. I tried using SLF4J but I am new to it. Is there any way to disable the websocket logs or to redirect it to some other stream, maybe using SLF4J, just so that I can atleast see the logs of my application ?

**Comment by PhilipRoman** [comment]
Unless you have one of the SLF4J implementations on classpath, SLF4J should default to a no-op logger, so you should see something like this:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

If you don't see that warning when running your program, that means SLF4J has found an implementation to use and you'll need to configure it (or remove it from classpath to silence the logging).

If you want to redirect logs, check the documentation for the implementation that you're using.
