### ISSUE TITLE
How to check a WebSocket handle is live healthily?

### ISSUE THREAD

**Issue by liuqixing** [TooTallNate/Java-WebSocket#953]
How to check a WebSocket handle is live healthily?
Did I do the right thing with the code below?

if ( WebSocket.isOpen() &&
	! WebSocket.isClosing() &&
	! WebSocket.isFlushAndClose() &&
	! WebSocket.isClosed() )
{
	//	indicates that this socket connection is healthy
}

**Comment by PhilipRoman** [comment]
Each websocket can be in a single state (all possible states are listed here: https://www.javadoc.io/doc/org.java-websocket/Java-WebSocket/latest/org/java_websocket/enums/ReadyState.html).

Just use `isOpen()`, all other checks are unnecessary.

**Comment by marci4** [comment]
Question answered. Closing issue!
