### ISSUE TITLE
How does the client get a callback to the Ping message？

### ISSUE THREAD

**Issue by Followang** [TooTallNate/Java-WebSocket#955]
**Describe what you would like to know or do**
A clear and concise description of what the problem is.

**Describe the solution you'd considered**
A clear and concise description of any solutions you've considered.

**Additional context**
Add any other context or links about the question here.

**Comment by NoahAndrews** [comment]
If you mean a web browser client, it can't. The browser automatically responds to pings, without alerting the client JavaScript code. You'll have to send application-level "pings" if you want your webpage to be able to detect them.

**Comment by Followang** [comment]
thanks.Android Client ,Override method onWebsocketPong of class WebSocketClient.
