### ISSUE TITLE
Autoreconnect and timeout handling

### ISSUE THREAD

**Issue by hornta** [TooTallNate/Java-WebSocket#956]
**Describe what you would like to know or do**
I don't think it's clear whether or not this lib has support for auto reconnect when it looses connection to the websocket server(which in my case is written in nodejs using the https://github.com/websockets/ws). 
I have tried to use the async-http-client but it feels really basic and only has the neccessites and I don't want to have to implement all the stuff like auto reconnect and what not.

**Describe the solution you'd considered**
A clear and concise description of any solutions you've considered.

**Additional context**
Add any other context or links about the question here.

**Comment by marci4** [comment]
No, this lib does not support auto reconnect. 
We think that a developer has to react to the close codes and trigger specific actions!

Best regards,
Marcel
