### ISSUE TITLE
Improvements in socket connect to server

### ISSUE THREAD

**Issue by olivierayache** [TooTallNate/Java-WebSocket#962]
When you use a custom socketFactory this code can be buggy:

```
if (!socket.isBound()) {
  InetSocketAddress addr = new InetSocketAddress(dnsResolver.resolve(uri), this.getPort());
  socket.connect(addr, connectTimeout);
}
```

Indeed socket might already be bound by socketFactory and isBound() will return true. A better version could be

```
if (!socket.isConnected()) {
  InetSocketAddress addr = new InetSocketAddress(dnsResolver.resolve(uri), this.getPort());
  socket.connect(addr, connectTimeout);
}
```

This issue is linked to the solution I mentionned in issue #814

**Comment by marci4** [comment]
Hello,
Could you provide additional steps to repeat?
Can this issue be tested somehow?

And if you, would you be so kind an open a pull request?

Thx a lot
Marcel

**Comment by olivierayache** [comment]
Ok I will open a pull request.

Olivier
