### ISSUE TITLE
springboot websocket can't onMessage

### ISSUE THREAD

**Issue by dingyong666** [TooTallNate/Java-WebSocket#963]
server is use libs  org.springframework.boot:spring-boot-starter-websocket
client is java-websocket

Clients can receive messages from the server，However, if the client uses msocket.send ("text"), the server cannot receive it。

**Comment by marci4** [comment]
Please fill out the bug template and provide an example application with clear steps to repeat!

Thx,
Marcel

**Comment by dingyong666** [comment]
simple extends 
`public class NodeServer extends WebSocketClient`


`    public static void main(String[] args) {

        try {

            String nodeName = "node-001";
            URI uri = URI.create("ws://127.0.0.1:8080/webSocket/" + nodeName);
            NodeServer nodeServer = NodeServer.getInstance(uri);
            nodeServer.run();

            new Thread(new Runnable() {
                @Override
                public void run() {
                    while (true){
                        try {
                            Thread.sleep(2000);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        nodeServer.send("" + System.currentTimeMillis());
                    }
                }
            }).start();


        } catch (Exception e) {
        }`


server springboot
`
    @OnMessage
    public void onMessage(String message, Session session) {
        log.info(message);
    }
`
No message

**Comment by dingyong666** [comment]
No problem using desktop  tools for websocket

**Comment by marci4** [comment]
Please provide a complete repository .-.

**Comment by PhilipRoman** [comment]
`WebSocketClient.run()` runs synchronously, which means that it doesn't return until client shuts down. This means that your sending thread won't be started while the client is running.

You can fix it by starting the sending thread before running the client.

**Comment by dingyong666** [comment]
@PhilipRoman  Thank you. That's the question
