### ISSUE TITLE
Sometimes the connection of websocket is abnormal

### ISSUE THREAD

**Issue by welove312** [TooTallNate/Java-WebSocket#965]
Somebody can't connect to websocket. Checked out nginx access log. I got "HTTP/1.0 404"
Normal user requests HTTP1.1 , The exception user requested http1.0 
   I'm not sure if it's websocket jar sent "HTTP/1.0" Protocol.
   thanks,Best regards

**Comment by marci4** [comment]
404 will be sent if wrong handshake was received (e.g. you used https://websocket.url instead of wss://websocekt.url).

**Comment by marci4** [comment]
Question should be answered. Closing issue!

Best regards,
Marcel
