### ISSUE TITLE
When WebsocketServer started. If I start it again, the app will be crashed.

### ISSUE THREAD

**Issue by ngowangvinh** [TooTallNate/Java-WebSocket#968]
I start the websocketserver by call start().
after it start, the server work well.
If I call start() again, my android application will be crashed.
so, how can I check if the websocket server is started?

**Comment by PhilipRoman** [comment]
Each WebSocketServer should only be started once - you're not allowed to stop it and then start it again. If you need to do that, create a different WebSocketServer object and start it.

If you need to keep track of whether the server has been started or not, create a boolean flag in your subclass of WebSocketServer (`boolean started = false;`) and set that flag when the server starts:
```java
@Override
public void onStart() {
    started = true;
}
```

**Comment by marci4** [comment]
Question should be answered. Closing issue!
Best regards,
Marcel
