### ISSUE TITLE
Loggers should be declared non-static

### ISSUE THREAD

**Issue by ViToni** [TooTallNate/Java-WebSocket#969]
Loggers are declared as `private static final`. This can have impact when having the library deployed on "shared" classpaths. 
It is prefereable to have them `non-static`.
If you care about serialization Loggers could be changed to be also `transient`.

For reference see:
http://slf4j.org/faq.html#declared_static
https://cwiki.apache.org/confluence/display/COMMONS/Logging+StaticLog

Projects implementing such a policy:
https://www.eclipse.org/smarthome/documentation/development/guidelines.html#e-logging
https://www.openhab.org/docs/developer/guidelines.html#f-logging

(Have to admit these projetcs are closely related but both are supposed to support dynamic reloading of JARs/ bundles.)

**Comment by marci4** [comment]
@ViToni thx for pointing this out.
We do not plan serialize the logger.

Pull request welcome!

**Comment by ViToni** [comment]
Created PR https://github.com/TooTallNate/Java-WebSocket/pull/970.
