### ISSUE TITLE
Will it work over the network, internally which http server this library using for initial handshake and Can we setup this as server on any cloud?

### ISSUE THREAD

**Issue by sainath-everest** [TooTallNate/Java-WebSocket#972]
**Describe what you would like to know or do**
A clear and concise description of what the problem is.

**Describe the solution you'd considered**
A clear and concise description of any solutions you've considered.

**Additional context**
Add any other context or links about the question here.

**Comment by PhilipRoman** [comment]
1. Not sure what you're asking here. Yes, it will work over the network.
1. This library does not depend on any external HTTP libraries. You can see how the HTTP handshake is parsed here: https://github.com/TooTallNate/Java-WebSocket/blob/65300d44507e5a4ed942b92dd27873cb8b95c936/src/main/java/org/java_websocket/drafts/Draft.java
1. Yes, you can setup it on cloud. I run this library in a production cloud environment and it works well. The only thing you have to watch out for is firewalls or other processes blocking ports, etc.

**Comment by PhilipRoman** [comment]
Closing this because the questions have been answered and there is no other activity.
