### ISSUE TITLE
Can't compile on the Android

### ISSUE THREAD

**Issue by zbwxtex** [TooTallNate/Java-WebSocket#973]
**Describe the bug**
I'm using 'AIDE'
I'm using version 1.4.0
GRADLE:compile 'org.java-websocket:Java-WebSocket:1.4.1
compileSDKVer:29
minSDKVer:14
targetSDKVer:28
No pruguard

Build Error
Packaging error:
java.lang.RuntimeException: wn: unknown  tag byte: 13

**Environment(please complete the following information):**
 - Version used:1.4.0
 - Java version:ANDROID
 - Operating System and version:ANDROID6.0.1
 - Endpoint Name and version:??????
 - Link to your project:No opensource now

**Comment by marci4** [comment]
Hello @zbwxtex,
could you provide a simple repository for this issue?
Thx a lot.

Best regards,
Marcel

**Comment by zbwxtex** [comment]
...e, sorry, i can't
