### ISSUE TITLE
Reading custom server handshake headers

### ISSUE THREAD

**Issue by F0RIS** [TooTallNate/Java-WebSocket#974]
I am talkin about this limitation to 3 items
https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/drafts/Draft.java#L95

**Comment by marci4** [comment]
The comment is not correct any more.
This line is e.g. `GET / HTTP/1.1`

Best regards,
Marcel

**Comment by clickstan** [comment]
Is there a way to read http headers for the handshake http request? I need to read a cloudflare CF-Connecting-IP header to get the original ip of whoever connects.

**Comment by F0RIS** [comment]
@marci4 My concern is that we can't read more than 3 standart elements. I set custom headers in that packet on server side but I can't get them on client side because of that limit to just 3 elements. Is that limit necessary or can be removed?

**Comment by marci4** [comment]
@F0RIS how about you describe which headers you want to send and provide some steps to repeat.

**Comment by marci4** [comment]
Closing this issue as there is no additional information provided which header were not read correctly...

**Comment by F0RIS** [comment]
@marci4 any custom header field can't be read bcz of the limit to read only 3 standart header fileds

**Comment by F0RIS** [comment]
https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/drafts/Draft.java#L95

I'm asking to replace this
`String[] firstLineTokens = line.split( " ", 3 );`
To this
`String[] firstLineTokens = line.split( " ");`

**Comment by marci4** [comment]
@F0RIS please provide your complete HTTP request and then we can discuss if it is a valid http request and then how we can fix it!
