### ISSUE TITLE
How to read headers on the http request?

### ISSUE THREAD

**Issue by clickstan** [TooTallNate/Java-WebSocket#975]
Where are headers in the http handshake request headers readable for my Java-Websocket server? Or if they aren't readable, could someone hint at where they are at least parsed/stored so I can modify the lib to make them readable?

I need to read a header sent from the client (cloudflare's CF-Connecting-IP header), which would tell my server the original IP of the connecting client.

Thanks for any tips!

**Comment by marci4** [comment]
Check the argument `ClientHandshake` in `onOpen` [documentation here](https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.4.0/org/java_websocket/server/WebSocketServer.html#onOpen-org.java_websocket.WebSocket-org.java_websocket.handshake.ClientHandshake-)

Best regards,
Marcel

**Comment by clickstan** [comment]
Thanks!

**Comment by marci4** [comment]
Closing question as answered
