### ISSUE TITLE
Performance or pros or comparison with other languages?

### ISSUE THREAD

**Issue by fzyzcjy** [TooTallNate/Java-WebSocket#976]
**Describe what you would like to know or do**
Hi, thanks for the wonderful library! I am seeking for a WebSocket server library and found this one. It seems that people often talk about C++, Go, JS, etc when talking to WebSocket IMHO. Thus, I wonder the comparison between this library and other libs in other languages? For instance, what is the performance, what are the pros, etc. Thanks!

**Describe the solution you'd considered**
I have searched the issues and found that ~3 month ago there was no performance test. However, since time has passed and this repo is so actively developed I decided to ask again.

**Additional context**
N/A

**Comment by marci4** [comment]
Hey
To be honest I think it is really hard to compare libs across different languages in regard to performance.
Performance depends on a lot of factors and adding different languages to the mix is just bad in my opinion.
Apart from this I think people should use the language they need in the specific project with the specific requirements.

Best regards,
Marcel

**Comment by fzyzcjy** [comment]
I agree with you. However, when persuading people into using a library I have to provide some data... For instance, if this library is not 2x slower than a go/js library, I think it can be acceptable. Moreover, if this library is very fast, it can be a great thing to attract more potential users!

**Comment by marci4** [comment]
@fzyzcjy then you should provide the data specific to your usecase to persuade people into using a lib.
A general comparison is in most cases not helpful. 

I will not invest any time into this, sorry.

Best regards,
Marcel

**Comment by fzyzcjy** [comment]
@marci4 Ah OK I will try that.

Best regards,
Tom
