### ISSUE TITLE
Regarding WSS implementation on Internet explorer

### ISSUE THREAD

**Issue by sanshul26** [TooTallNate/Java-WebSocket#978]
I have a Websocket server written in java and a web client written in java script which connects to the server. 
The server runs locally as a java desktop application and the webclient runs on the browser of the same machine. The communication is happening via local host on a port.
The implementation is working completely fine on Chrome or firefox but not working on internet explorer or Edge.
Getting below error for the same:
SCRIPT12017: SCRIPT12017: WebSocket Error: SECURITY_ERR, Cross zone connection not allowed

Can you please suggest something.

**Comment by marci4** [comment]
Do a quick google for the error. 
This is not related to the lib, but simply IE and Edge not allowing localhost

**Comment by marci4** [comment]
Question answered. Closing issue!
