### ISSUE TITLE
wss 404

### ISSUE THREAD

**Issue by icecooly** [TooTallNate/Java-WebSocket#979]
firefox chrome
Request URL:wss://xxxxxx/
Request Method:GET
Status Code:
404  WebSocket Upgrade Failure
Version:HTTP/1.1

only safari is ok

**Comment by icecooly** [comment]
haproxy->Server | TooTallNate Java-WebSocket
80                                      9301

**Comment by PhilipRoman** [comment]
You need to add more information:
* a test case which reproduces your issue
* library version
* debug log from server side

**Comment by icecooly** [comment]
i found the reason
 
js client
when use protocols like this
var ws = new WebSocket('wss://xxxxxx/', ['event']);
result is 404  Provisional headers are shown

bug when no protocols 
var ws = new WebSocket('wss://xxxxxx/');
it is ok

https://javascript.info/websocket
Extensions and subprotocols 

but netty websocket it is ok
