### ISSUE TITLE
WS Client receives HTTP error 502

### ISSUE THREAD

**Issue by lvca** [TooTallNate/Java-WebSocket#984]
**Describe the bug**
Using as a client, can't connect to a WebSocket server. I'm using Cloudflare in front of my app. And the error I receive is: `Invalid status code received: 502 Status line: HTTP/1.1 502 Bad Gateway`. Tested with https://www.websocket.org/echo.html and works perfectly.

Any idea o special settings?

Thanks

**Environment(please complete the following information):**
 - Version used: 1.4.0
 - Java version: 11
 - Operating System and version: MaxOSX

**Comment by marci4** [comment]
Hello @lvca,
502 indicates a server error. Not much more I can say. 
Check your cloudflare settings

Best regards,
Marcel

**Comment by lvca** [comment]
I know, but the same test from the browser works perfectly. I wonder if there is some missing headers I should include.

**Comment by marci4** [comment]
Hello @lvca,

I have no clue which headers are required for the cloudflare integration.
Please ask their support on which headers are required.

Best regards,
Marcel
