### ISSUE TITLE
InvalidFrameException: bad rsv RSV1: true RSV2: false RSV3: false

### ISSUE THREAD

**Issue by hsxyhao** [TooTallNate/Java-WebSocket#990]
What should I do when this exception occurs？

This is my custom headers：
 Accept-Encoding：gzip, deflate, br
 Accept-Language：zh-CN,zh;q=0.9,en;q=0.8
 Cache-Control：no-cache
 Connection：Upgrade
 Pragma：no-cache
 Sec-WebSocket-Extensions：permessage-deflate; server_no_context_takeover; client_max_window_bits
 Sec-WebSocket-Protocol：zap-protocol-v1
 Sec-WebSocket-Version：13

**Comment by marci4** [comment]
Hello, 
you cannot send the websocket permessage-deflate extension.
This is currently not supported. This will be supported with 1.5.0

Best regards,
Marcel

**Comment by hsxyhao** [comment]
> Hello,
> you cannot send the websocket permessage-deflate extension.
> This is currently not supported. This will be supported with 1.5.0
> 
> Best regards,
> Marcel

Thanks for your answer and look forward to the next version.

**Comment by jercylew** [comment]
Can bu resolved by this
```
private static final Draft perMessageDeflateDraft = new Draft_6455(
      new PerMessageDeflateExtension());
WebSocketClient client = new WebSocketClient(new URI("ws://xxx.xxx.com:" + PORT), perMessageDeflateDraft);
```

Since you send the header permessagedeflate, you client should also accordingly use permessage deflat draft instead the default Draft `new Draft_6455()`
