### ISSUE TITLE
Add a new WebSocketServer constructor allowing  to specify the maximum number of pending connections 

### ISSUE THREAD

**Issue by dregueira** [TooTallNate/Java-WebSocket#991]
After running some load tests on our company's app, I found that is not possible to specify the maximum number of pending connections (backlog) for the WebSocketServer. 

I would be very interested in having a new WebSocketServer constructor that receives a new parameter in order to specify the backlog here `socket.bind( address )`.

Thanks

**Comment by marci4** [comment]
Hello @dregueira,

could you please describe your requirement a bit more?
What do you mean by pending connections?
When is a connection no longer pending?
Etc etc

Best regards,
Marcel

**Comment by dregueira** [comment]
Hello @marci4 ,

With "pending connections" I'm referring to incoming connections waiting to be accepted by the WebSocketServer `SocketChannel channel = server.accept();`. 

When the incoming connections can't be accepted fast enough by the WebScoketServer, the backlog queue gets full and new connections will be not accepted, causing a connection retry or a connection timeout (if the condition persists) at client side.

We are interested in customizing the backlog size according to our traffic characteristics, the WebSocketServer backlog size can be specified at the bind function `socket.bind( address )`.

You can find more info about the backlog here https://blog.cloudflare.com/syn-packet-handling-in-the-wild

Thanks!

**Comment by dregueira** [comment]
Hello @marci4 ,

Here you will find (at bind function, line 208) how the backlog parameter is used and his default value (50) http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/2a93ed39a4e9/src/share/classes/sun/nio/ch/ServerSocketChannelImpl.java

A backlog size of 50 is not allowing us the handle thousands of web socket clients try to connect to a web socket server at the same time, since the "backlog" gets full and start dropping connections, that's the reason why we are requesting a way to set this value.

Not sure if I was able to explain the problem correctly. If it was not the case, please let me know.

Thanks!

**Comment by marci4** [comment]
Hello @dregueira,
feel free to open a PR :)

Best regards,
Marcel
