### ISSUE TITLE
No message received after a period of time

### ISSUE THREAD

**Issue by lovewe** [TooTallNate/Java-WebSocket#992]
After the websocket establishes the connection, it can receive the message at first. After a period of time, it will not receive the message again（Probabilistic）. Through Wireshark packet capture, the message sent to the server appears win = 0, that is, the problem of TCP zerowindows.

I don't know if it is affected by sendping() (it is sent every minute, but the server will not return the pong frame). I don't know if anyone has encountered it. The version is 1.3.8

 - Version used:  1.3.8
 - Java version:  1.8.0_131
 - Operating System and version:  Windows Server 2008 R2 Standard

**Comment by marci4** [comment]
Hey @lovewe,
have you tried the latest version 1.4.1?

Could you include some steps to repeat?

Best regards
Marcel

**Comment by honglei92** [comment]
+1  cant receive message

**Comment by marci4** [comment]
Please provide some steps to repeat...

**Comment by marci4** [comment]
Closing this issue since no steps to repeat were provided!
