### ISSUE TITLE
Connection disconnected when communicating with other Websocket library servers. 

### ISSUE THREAD

**Issue by santoshJD** [TooTallNate/Java-WebSocket#993]
Scenario:
i am using websocket client :: tootallnate ,
                 websocket server :: uWebSockkets https://github.com/uNetworking/uWebSockets

problem is  when ping pong is enabled on uWebSocket server , after sending one message from webSocket client , 2nd time it gets disconnected 

"code=1006 and no reason" 

can think of any solution .  will appreciate any help.

**Comment by marci4** [comment]
Hello @santoshJD,
could you please provide a example implementation for the websocket server?

Thx a lot.

Best regards,
Marcel

**Comment by santoshJD** [comment]
https://github.com/uNetworking/uWebSockets/blob/master/examples/EchoServer.cpp

**Comment by marci4** [comment]
This issue can be reproduced with chrome and firefox.
Therefore it is most likely a server error and not caused by this project.

Closing issue.
Best regards,
Marcel
