### ISSUE TITLE
Annotation typing mistake inquiry

### ISSUE THREAD

**Issue by jayyhkwon** [TooTallNate/Java-WebSocket#994]
Hi there.
I appreciate your open source project.
It's helpful for me to study how to work connect socket networking.

when I read the annotaion in "WebSocketImpl.java" line 231,

	/**
	 * Returns whether the handshake phase has is completed.
	 * In case of a broken handshake this will be never the case.
	 **/

"Returns whether the handshake phase has is completed." is awkward.
as known as "Returns whether the handshake phase has completed." or 
"Returns whether the handshake phase is completed." is correct.

would you review my opinion?

thank you

**Comment by PhilipRoman** [comment]
You're correct, but this is a comment for an internal method and usually we don't bother fixing grammar as long as the meaning is clear.

I'm glad this project is helpful to you.
