### ISSUE TITLE
How to cancel "WS" during connection timeout

### ISSUE THREAD

**Issue by lovingning** [TooTallNate/Java-WebSocket#995]
**Describe what you would like to know or do**
A clear and concise description of what the problem is.

**Describe the solution you'd considered**
A clear and concise description of any solutions you've considered.

**Additional context**
Add any other context or links about the question here.

**Comment by lovingning** [comment]
I found that the timeout was set to 3 seconds, 
but I found that the connection succeeded after 6 seconds. 
This is bullshit ?????

```
Line 2289: 2020-03-27 10:50:51.611 6154-11756/<class> - prepare to connect wss... 
Line 2413: 2020-03-27 10:50:57.156 6154-11776/<class> >>> onWebsocketHandshakeReceivedAsClient...
Line 2414: 2020-03-27 10:50:57.156 6154-11776/<class> >>> onOpen
```

**Comment by lovingning** [comment]
What information is needed for this? We only know that the timeout is 3S, and then check the log and find that the connection is successful in 6S

Or, before "onOpen", is there any way I can terminate the connection process?
(at this time, the "close" method is invalid)

**Comment by marci4** [comment]
Please use the bug template and provide some steps to repeat including what you would expect!
And try to watch your language please. Everyone here tries to help others in their free time!

Best regards,
Marcel

**Comment by lovingning** [comment]
I'm sorry for the attitude,   ....ababababa
....

### Describe what you would like to know or do

It's like this. I met one situation, and it only happened once

I set the timeout to 3s. Normally, WS should connect successfully or fail within three seconds
But strangely, according to the log, we can see that WS was established in 6s

like this :

```
Line 2289: 2020-03-27 10:50:51.611 6154-11756/<class> - prepare to connect wss... 
Line 2413: 2020-03-27 10:50:57.156 6154-11776/<class> >>> onWebsocketHandshakeReceivedAsClient...
Line 2414: 2020-03-27 10:50:57.156 6154-11776/<class> >>> onOpen
```

I have tried to call "close" to close the WS connection being established in 3s,
However, "close" can only be called when the connection is successful

### Describe the solution you'd considered

In this case, I think of two aspects:

 1. Is it possible for ws to establish a connection after the timeout?
 2. For the close method, can we terminate the process of establishing WS connection, similar to "release"

### Additional context

Or do I have any other way to change that?

Dear Marcel

Best regards

**Comment by marci4** [comment]
Please provide some steps to to repeat...

**Comment by marci4** [comment]
No Steps to repeat provided.

Closing issue!
