### ISSUE TITLE
library "libMediaEncoder.so" not found

### ISSUE THREAD

**Issue by vigorlee** [TooTallNate/Java-WebSocket#996]
I take the liberty of disturbing you.
What I should be done if the missing so library file appears in the latest version of Android studio?
Thank you very much

`java.lang.UnsatisfiedLinkError: dlopen failed: library "libMediaEncoder.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1661)
        at teaonly.droideye.MainActivity.<clinit>(MainActivity.java:523)`

**Comment by marci4** [comment]
Hello @vigorlee,

we do not use any external lib.
This issue is therefore not related to this project!

Please check your dependencies.

Best regards,
Marcel

**Comment by vigorlee** [comment]
i'am sorry ,i check this project. This is the code's picture. If you know, could you give me some suggestions. I have no ideal to deal with it as a rookie. thank you very  very much.

![image](https://user-images.githubusercontent.com/57834665/77823930-a4317280-7139-11ea-93ed-1e2e218d5b14.png)

**Comment by marci4** [comment]
You should check the project NanoHttp for this ;)

**Comment by marci4** [comment]
Sorry but I do not have the time to answer general questions. Maybe ask on stackoverflow or other forums.

**Comment by vigorlee** [comment]
Thank you. I just keep to try it.
