### ISSUE TITLE
How to create multi-thread server

### ISSUE THREAD

**Issue by silent-coder-id** [TooTallNate/Java-WebSocket#998]
I want to build multi-thread chat server that handle hundreds clients.
Please give some example.

**Comment by marci4** [comment]
Hello @silent-coder-id,
why are the existing examples not sufficient for you?

Best regards,
Marcel

**Comment by silent-coder-id** [comment]
i want to build chat server app that handle hundred clients, how to handle all icoming message at same time? 
i mean without waiting one message proccess completed, assume per message need to be proccessed, sometimes it need long time to finish.

**Comment by marci4** [comment]
The best thing is to just push every recieved message into a queue and do all the heavy load processing of the message in a separate thread.

But it depends on your application if you require a strict order etc etc.

Best example is the chatserver to start your project, but it always depends on your use case what you want to do and have to do.

Best regards,
Marcel

**Comment by dOhx** [comment]
> The best thing is to just push every recieved message into a queue and do all the heavy load processing of the message in a separate thread.
> 
> But it depends on your application if you require a strict order etc etc.
> 
> Best example is the chatserver to start your project, but it always depends on your use case what you want to do and have to do.
> 
> Best regards,
> Marcel
I have do so, but on heavy load, new connections to WSS via Chrome 30 seconds or so when its possible. What iam doing wrong? In my ChatServer class only put messages in a Queue on a seperate class, its handle the messages in a separate thread. Its not possible to connect when use send or receive?

**Comment by marci4** [comment]
If you have a performance issue, open a separate bug with an example application etc etc.
