### ISSUE TITLE
code=1006, reason="" ,remote=true

### ISSUE THREAD

**Issue by QiaoYang0923** [TooTallNate/Java-WebSocket#999]
The connection will be closed after 1 minute or so. Do I need to send data to the server continuously to keep the connection

**Comment by marci4** [comment]
Hello @QiaoYang0923,

could you please provide some steps to repeat?
I am very interested what server you are using.

Best regards,
Marcel

**Comment by QiaoYang0923** [comment]
The client is Android, the server is written in PHP, and the workerman socket instant messaging framework is used

**Comment by QiaoYang0923** [comment]
workerman

**Comment by marci4** [comment]
Please provide a link to the server project. 

I think the server does not correctly implement the specification.

Best regards,
Marcel

**Comment by QiaoYang0923** [comment]
The LAN is used now. We guess that there is no heartbeat package. We will reply to you after we have the result.

**Comment by QiaoYang0923** [comment]
Thank you for your efforts.
This is the socket link address  ws:// 39.100.77.28:2346
You can try to access it,

**Comment by QiaoYang0923** [comment]
Does this library implement a heartbeat mechanism internally?Do I need to implement a heartbeat mechanism?

**Comment by PhilipRoman** [comment]
This library already provides a heartbeat mechanism to detect lost connections. See https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection for more information

**Comment by QiaoYang0923** [comment]
I will send a message to the server every 10 seconds, and the server will return to me that it has received, but it will still return code=1006. I am very confused, please help me to see what the reason may be.

**Comment by marci4** [comment]
Please read the documentation!
We are using the ping/pong frame for the heartbeat. If you server is implementing the specification (https://tools.ietf.org/html/rfc6455#section-5.5.2) there should be nothing you have to do.

**Comment by QiaoYang0923** [comment]
I set up  `  client.setConnectionLostTimeout(0); `  Then send the message to the server every once in a while, so far it looks good, and you won't lose the connection after a minute

**Comment by marci4** [comment]
Closing this issue as solved.

Never the less I want to stress that this issue is caused by the server and not this library. The server is not correctly implementing the specification!

Best regards,
Marcel
